-- lockin. — all migrations in order. Paste into Supabase → SQL Editor → Run.
-- Generated by `npm run db:bundle`; edit supabase/migrations/*.sql, not this file.

-- ==== 0001_core.sql ====
-- lockin. core: profiles, trusted XP ledger, dashboard stats.
-- Every table has RLS. XP can only be written by SECURITY DEFINER functions (never by clients).

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  name text not null default '' check (char_length(name) <= 60),
  branch text check (branch in ('CSE','CSE-DS','ECE','EE','ME','CE')),
  year smallint check (year = 1),
  semester smallint check (semester in (1, 2)),
  daily_goal_xp integer not null default 50 check (daily_goal_xp between 10 and 500),
  timezone text not null default 'Asia/Kolkata',
  language text not null default 'en' check (language in ('en','hi')),
  onboarded_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.profiles enable row level security;

create function public.validate_profile() returns trigger
language plpgsql set search_path = public, pg_catalog as $$
begin
  -- Accept IANA names including legacy aliases browsers still report (e.g. Asia/Calcutta), reject abbreviations like IST.
  if new.timezone <> 'UTC' and new.timezone !~ '^[A-Za-z_]+(/[A-Za-z0-9_+-]+){1,2}$' then
    raise exception 'invalid timezone';
  end if;
  begin
    perform now() at time zone new.timezone;
  exception when others then
    raise exception 'invalid timezone';
  end;
  new.name := btrim(new.name);
  if new.onboarded_at is not null and (char_length(new.name) < 1 or new.branch is null or new.year is null or new.semester is null) then
    raise exception 'onboarding needs name, branch, year and semester';
  end if;
  return new;
end $$;
create trigger profiles_validate before insert or update on public.profiles
  for each row execute function public.validate_profile();

create function public.handle_new_user() returns trigger
language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, email, name)
  values (new.id, new.email,
          left(coalesce(new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'name', ''), 60))
  on conflict (id) do nothing;
  return new;
end $$;
create trigger on_auth_user_created after insert on auth.users
  for each row execute function public.handle_new_user();

create policy profiles_select_own on public.profiles for select to authenticated using (id = auth.uid());
create policy profiles_update_own on public.profiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
revoke all on public.profiles from anon, authenticated;
grant select on public.profiles to authenticated;
grant update (name, branch, year, semester, daily_goal_xp, timezone, language, onboarded_at) on public.profiles to authenticated;

-- ------------------------------------------------------------------ XP ledger
create table public.xp_events (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  kind text not null check (kind in ('topic_completed','quiz_completed','practical_completed','mock_completed','daily_goal_completed')),
  ref text not null check (char_length(ref) between 1 and 120),
  xp integer not null check (xp between 1 and 200),
  created_at timestamptz not null default now(),
  unique (user_id, kind, ref)
);
create index xp_events_user_time on public.xp_events (user_id, created_at desc);
alter table public.xp_events enable row level security;
create policy xp_events_select_own on public.xp_events for select to authenticated using (user_id = auth.uid());
revoke all on public.xp_events from anon, authenticated;
grant select on public.xp_events to authenticated;

-- Internal only: called by other trusted functions after they verify the work. Not callable by clients.
-- Duplicate (user, kind, ref) is ignored, so refreshing or replaying never pays twice.
-- A per-day cap stops any single bug or exploit from inflating XP.
create function public.award_xp(p_user uuid, p_kind text, p_ref text, p_xp integer) returns integer
language plpgsql security definer set search_path = public, pg_catalog as $$
declare tz text; today_total integer; granted integer;
begin
  select timezone into tz from profiles where id = p_user;
  if tz is null then raise exception 'unknown user'; end if;
  select coalesce(sum(xp), 0) into today_total from xp_events
    where user_id = p_user and (created_at at time zone tz)::date = (now() at time zone tz)::date;
  granted := least(p_xp, greatest(0, 1500 - today_total));
  if granted <= 0 then return 0; end if;
  insert into xp_events (user_id, kind, ref, xp) values (p_user, p_kind, p_ref, granted)
    on conflict (user_id, kind, ref) do nothing;
  if not found then return 0; end if;
  return granted;
end $$;
revoke all on function public.award_xp(uuid, text, text, integer) from public, anon, authenticated;

-- ------------------------------------------------------------------ dashboard stats
-- security invoker: RLS applies, a caller only ever sees their own rows. Streak is computed here, in the
-- student's own timezone, never on the client.
create function public.dashboard_stats() returns jsonb
language plpgsql stable security invoker set search_path = public, pg_catalog as $$
declare uid uuid := auth.uid(); tz text; today date; total bigint; today_xp bigint; streak int := 0; cursor date; week jsonb;
begin
  if uid is null then raise exception 'not signed in'; end if;
  select timezone into tz from profiles where id = uid;
  if tz is null then raise exception 'no profile'; end if;
  today := (now() at time zone tz)::date;
  select coalesce(sum(xp), 0) into total from xp_events where user_id = uid;
  select coalesce(sum(xp), 0) into today_xp from xp_events where user_id = uid and (created_at at time zone tz)::date = today;
  cursor := today;
  if not exists (select 1 from xp_events where user_id = uid and (created_at at time zone tz)::date = today) then cursor := today - 1; end if;
  while exists (select 1 from xp_events where user_id = uid and (created_at at time zone tz)::date = cursor) loop
    streak := streak + 1; cursor := cursor - 1;
  end loop;
  select coalesce(jsonb_object_agg(d, s), '{}') into week from (
    select (created_at at time zone tz)::date d, sum(xp) s from xp_events
    where user_id = uid and (created_at at time zone tz)::date > today - 84 group by 1) t;
  return jsonb_build_object('total_xp', total, 'today_xp', today_xp, 'streak', streak, 'today', today, 'days', week);
end $$;
revoke all on function public.dashboard_stats() from public, anon;
grant execute on function public.dashboard_stats() to authenticated;

-- ------------------------------------------------------------------ consent records (DPDP)
create table public.consents (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  policy_version text not null check (char_length(policy_version) between 1 and 20),
  accepted_at timestamptz not null default now(),
  unique (user_id, policy_version)
);
alter table public.consents enable row level security;
create policy consents_select_own on public.consents for select to authenticated using (user_id = auth.uid());
revoke all on public.consents from anon, authenticated;
grant select on public.consents to authenticated;

create function public.record_consent(p_version text) returns void
language plpgsql security definer set search_path = public, pg_catalog as $$
begin
  if auth.uid() is null then raise exception 'not signed in'; end if;
  insert into consents (user_id, policy_version) values (auth.uid(), p_version) on conflict do nothing;
end $$;
revoke all on function public.record_consent(text) from public, anon;
grant execute on function public.record_consent(text) to authenticated;

-- ==== 0002_learning.sql ====
-- lockin. learning: topic progress and server-scored quiz sessions.
-- Clients can only READ their own rows. Every write goes through service_role functions that the Next.js server
-- calls after it has verified the signed-in user and graded the answer itself.

grant execute on function public.award_xp(uuid, text, text, integer) to service_role;

create table public.topic_progress (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  topic_key text not null check (topic_key ~ '^[A-Z]{2,3}-[0-9]{3}:[0-9]{1,2}:[0-9]{1,3}$'),
  best_score smallint not null check (best_score between 0 and 100),
  completed_at timestamptz not null default now(),
  unique (user_id, topic_key)
);
create index topic_progress_user on public.topic_progress (user_id);
alter table public.topic_progress enable row level security;
create policy topic_progress_select_own on public.topic_progress for select to authenticated using (user_id = auth.uid());
revoke all on public.topic_progress from anon, authenticated;
grant select on public.topic_progress to authenticated;

create table public.quiz_sessions (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  course text not null check (course ~ '^[A-Z]{2,3}-[0-9]{3}$'),
  unit smallint not null check (unit between 1 and 12),
  seed integer not null,
  kind text not null check (kind in ('practice', 'topic')),
  topic_key text check (topic_key is null or topic_key ~ '^[A-Z]{2,3}-[0-9]{3}:[0-9]{1,2}:[0-9]{1,3}$'),
  total smallint not null check (total between 1 and 20),
  answers jsonb not null default '{}',
  correct smallint check (correct >= 0),
  xp smallint check (xp >= 0),
  created_at timestamptz not null default now(),
  submitted_at timestamptz,
  check ((kind = 'topic') = (topic_key is not null))
);
create index quiz_sessions_user_time on public.quiz_sessions (user_id, created_at desc);
alter table public.quiz_sessions enable row level security;
create policy quiz_sessions_select_own on public.quiz_sessions for select to authenticated using (user_id = auth.uid());
revoke all on public.quiz_sessions from anon, authenticated;
-- the seed regenerates every question and answer, so it is never readable by the client
grant select (id, user_id, course, unit, kind, topic_key, total, correct, xp, created_at, submitted_at) on public.quiz_sessions to authenticated;

create function public.start_quiz_session(p_user uuid, p_course text, p_unit integer, p_seed integer, p_kind text, p_topic text, p_total integer)
returns uuid language plpgsql security definer set search_path = public, pg_catalog as $$
declare sid uuid;
begin
  if not exists (select 1 from profiles where id = p_user) then raise exception 'unknown user'; end if;
  if (select count(*) from quiz_sessions where user_id = p_user and created_at > now() - interval '24 hours') >= 120 then
    raise exception 'too many quizzes today';
  end if;
  insert into quiz_sessions (user_id, course, unit, seed, kind, topic_key, total)
    values (p_user, p_course, p_unit, p_seed, p_kind, p_topic, p_total) returning id into sid;
  return sid;
end $$;

-- The server has already graded the answer. The first answer for a question is final.
create function public.record_answer(p_user uuid, p_session uuid, p_index integer, p_answer jsonb, p_correct boolean)
returns boolean language plpgsql security definer set search_path = public, pg_catalog as $$
declare s quiz_sessions;
begin
  select * into s from quiz_sessions where id = p_session and user_id = p_user for update;
  if not found then raise exception 'unknown session'; end if;
  if s.submitted_at is not null then raise exception 'session already finished'; end if;
  if p_index < 0 or p_index >= s.total then raise exception 'bad question index'; end if;
  if s.answers ? p_index::text then return false; end if;
  update quiz_sessions set answers = answers || jsonb_build_object(p_index::text, jsonb_build_object('a', p_answer, 'ok', p_correct)) where id = p_session;
  return true;
end $$;

create function public.finish_quiz_session(p_user uuid, p_session uuid)
returns jsonb language plpgsql security definer set search_path = public, pg_catalog as $$
declare s quiz_sessions; n_ok integer; pct integer; gained integer := 0; topic_new boolean := false; topic_xp integer := 0;
begin
  select * into s from quiz_sessions where id = p_session and user_id = p_user for update;
  if not found then raise exception 'unknown session'; end if;
  if s.submitted_at is not null then
    return jsonb_build_object('correct', s.correct, 'total', s.total, 'xp', 0, 'topic_completed', false, 'replay', true);
  end if;
  if (select count(*) from jsonb_object_keys(s.answers)) < s.total then raise exception 'answer every question first'; end if;
  if now() - s.created_at < make_interval(secs => s.total * 2) then raise exception 'finished too fast'; end if;
  select count(*) into n_ok from jsonb_each(s.answers) e where (e.value->>'ok')::boolean;
  pct := (n_ok * 100) / s.total;
  gained := award_xp(p_user, 'quiz_completed', s.id::text, n_ok * 3 + case when n_ok = s.total then 10 else 0 end);
  if s.kind = 'topic' then
    if pct >= 60 then
      insert into topic_progress (user_id, topic_key, best_score) values (p_user, s.topic_key, pct)
        on conflict (user_id, topic_key) do update set best_score = greatest(topic_progress.best_score, excluded.best_score);
      topic_new := not exists (select 1 from xp_events where user_id = p_user and kind = 'topic_completed' and ref = s.topic_key);
      if topic_new then topic_xp := award_xp(p_user, 'topic_completed', s.topic_key, 20); topic_new := topic_xp > 0; end if;
    end if;
  end if;
  update quiz_sessions set submitted_at = now(), correct = n_ok, xp = gained + topic_xp where id = s.id;
  return jsonb_build_object('correct', n_ok, 'total', s.total, 'xp', gained + topic_xp, 'topic_completed', topic_new, 'passed', pct >= 60, 'replay', false);
end $$;

revoke all on function public.start_quiz_session(uuid, text, integer, integer, text, text, integer) from public, anon, authenticated;
revoke all on function public.record_answer(uuid, uuid, integer, jsonb, boolean) from public, anon, authenticated;
revoke all on function public.finish_quiz_session(uuid, uuid) from public, anon, authenticated;
grant execute on function public.start_quiz_session(uuid, text, integer, integer, text, text, integer) to service_role;
grant execute on function public.record_answer(uuid, uuid, integer, jsonb, boolean) to service_role;
grant execute on function public.finish_quiz_session(uuid, uuid) to service_role;

-- ==== 0003_planning.sql ====
-- lockin. planning: the student's own exam date and study hours (used by the study plan and countdown).
alter table public.profiles
  add column exam_date date check (exam_date is null or exam_date between date '2024-01-01' and date '2100-01-01'),
  add column study_hours smallint not null default 2 check (study_hours between 1 and 12);

grant update (exam_date, study_hours) on public.profiles to authenticated;

-- ------------------------------------------------------------------ mock tests
-- A mock is a 20-question timed session spread across every unit of one subject. It pays under its own XP kind.
alter table public.quiz_sessions drop constraint quiz_sessions_kind_check;
alter table public.quiz_sessions add constraint quiz_sessions_kind_check check (kind in ('practice', 'topic', 'mock'));

create or replace function public.finish_quiz_session(p_user uuid, p_session uuid)
returns jsonb language plpgsql security definer set search_path = public, pg_catalog as $$
declare s quiz_sessions; n_ok integer; pct integer; gained integer := 0; topic_new boolean := false; topic_xp integer := 0;
begin
  select * into s from quiz_sessions where id = p_session and user_id = p_user for update;
  if not found then raise exception 'unknown session'; end if;
  if s.submitted_at is not null then
    return jsonb_build_object('correct', s.correct, 'total', s.total, 'xp', 0, 'topic_completed', false, 'replay', true);
  end if;
  if (select count(*) from jsonb_object_keys(s.answers)) < s.total then raise exception 'answer every question first'; end if;
  if now() - s.created_at < make_interval(secs => s.total * 2) then raise exception 'finished too fast'; end if;
  select count(*) into n_ok from jsonb_each(s.answers) e where (e.value->>'ok')::boolean;
  pct := (n_ok * 100) / s.total;
  gained := award_xp(p_user, case when s.kind = 'mock' then 'mock_completed' else 'quiz_completed' end, s.id::text,
                     n_ok * 3 + case when n_ok = s.total then 10 else 0 end);
  if s.kind = 'topic' then
    if pct >= 60 then
      insert into topic_progress (user_id, topic_key, best_score) values (p_user, s.topic_key, pct)
        on conflict (user_id, topic_key) do update set best_score = greatest(topic_progress.best_score, excluded.best_score);
      topic_new := not exists (select 1 from xp_events where user_id = p_user and kind = 'topic_completed' and ref = s.topic_key);
      if topic_new then topic_xp := award_xp(p_user, 'topic_completed', s.topic_key, 20); topic_new := topic_xp > 0; end if;
    end if;
  end if;
  update quiz_sessions set submitted_at = now(), correct = n_ok, xp = gained + topic_xp where id = s.id;
  return jsonb_build_object('correct', n_ok, 'total', s.total, 'xp', gained + topic_xp, 'topic_completed', topic_new, 'passed', pct >= 60, 'replay', false);
end $$;

-- ==== 0004_labs_assignments.sql ====
-- lockin. saved lab setups and practice assignments.

-- ------------------------------------------------------------------ saved lab setups
-- A student's own named slider values for a lab. Values are re-validated and clamped by the lab on load.
create table public.lab_setups (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  lab text not null check (lab ~ '^[a-z0-9]{2,24}$'),
  name text not null check (char_length(btrim(name)) between 1 and 40),
  params jsonb not null check (jsonb_typeof(params) = 'object' and pg_column_size(params) <= 1500),
  created_at timestamptz not null default now()
);
create index lab_setups_user_lab on public.lab_setups (user_id, lab, created_at desc);
alter table public.lab_setups enable row level security;
create policy lab_setups_select_own on public.lab_setups for select to authenticated using (user_id = auth.uid());
create policy lab_setups_insert_own on public.lab_setups for insert to authenticated with check (user_id = auth.uid());
create policy lab_setups_delete_own on public.lab_setups for delete to authenticated using (user_id = auth.uid());
revoke all on public.lab_setups from anon, authenticated;
grant select, delete on public.lab_setups to authenticated;
grant insert (lab, name, params) on public.lab_setups to authenticated;

-- At most 100 saved setups per student, so the table cannot be used as free storage.
create function public.limit_lab_setups() returns trigger
language plpgsql security definer set search_path = public, pg_catalog as $$
begin
  new.name := btrim(new.name);
  if (select count(*) from lab_setups where user_id = new.user_id) >= 100 then
    raise exception 'too many saved setups';
  end if;
  return new;
end $$;
create trigger lab_setups_limit before insert on public.lab_setups for each row execute function public.limit_lab_setups();

-- ------------------------------------------------------------------ practice assignments
-- An assignment is a 10-question, untimed, resumable set for one unit. No verdicts until it is submitted.
-- It pays once per unit, ever (ref = course:unit), so retaking it never farms XP.
alter table public.quiz_sessions drop constraint quiz_sessions_kind_check;
alter table public.quiz_sessions add constraint quiz_sessions_kind_check check (kind in ('practice', 'topic', 'mock', 'assignment'));
alter table public.xp_events drop constraint xp_events_kind_check;
alter table public.xp_events add constraint xp_events_kind_check
  check (kind in ('topic_completed','quiz_completed','practical_completed','mock_completed','assignment_completed','daily_goal_completed'));

create or replace function public.finish_quiz_session(p_user uuid, p_session uuid)
returns jsonb language plpgsql security definer set search_path = public, pg_catalog as $$
declare s quiz_sessions; n_ok integer; pct integer; gained integer := 0; topic_new boolean := false; topic_xp integer := 0;
begin
  select * into s from quiz_sessions where id = p_session and user_id = p_user for update;
  if not found then raise exception 'unknown session'; end if;
  if s.submitted_at is not null then
    return jsonb_build_object('correct', s.correct, 'total', s.total, 'xp', 0, 'topic_completed', false, 'replay', true);
  end if;
  if (select count(*) from jsonb_object_keys(s.answers)) < s.total then raise exception 'answer every question first'; end if;
  if now() - s.created_at < make_interval(secs => s.total * 2) then raise exception 'finished too fast'; end if;
  select count(*) into n_ok from jsonb_each(s.answers) e where (e.value->>'ok')::boolean;
  pct := (n_ok * 100) / s.total;
  if s.kind = 'assignment' then
    gained := case when pct >= 40 then award_xp(p_user, 'assignment_completed', s.course || ':' || s.unit, n_ok * 4 + case when n_ok = s.total then 10 else 0 end) else 0 end;
  else
    gained := award_xp(p_user, case when s.kind = 'mock' then 'mock_completed' else 'quiz_completed' end, s.id::text,
                       n_ok * 3 + case when n_ok = s.total then 10 else 0 end);
  end if;
  if s.kind = 'topic' then
    if pct >= 60 then
      insert into topic_progress (user_id, topic_key, best_score) values (p_user, s.topic_key, pct)
        on conflict (user_id, topic_key) do update set best_score = greatest(topic_progress.best_score, excluded.best_score);
      topic_new := not exists (select 1 from xp_events where user_id = p_user and kind = 'topic_completed' and ref = s.topic_key);
      if topic_new then topic_xp := award_xp(p_user, 'topic_completed', s.topic_key, 20); topic_new := topic_xp > 0; end if;
    end if;
  end if;
  update quiz_sessions set submitted_at = now(), correct = n_ok, xp = gained + topic_xp where id = s.id;
  return jsonb_build_object('correct', n_ok, 'total', s.total, 'xp', gained + topic_xp, 'topic_completed', topic_new, 'passed', pct >= 60, 'replay', false);
end $$;
revoke all on function public.finish_quiz_session(uuid, uuid) from public, anon, authenticated;
grant execute on function public.finish_quiz_session(uuid, uuid) to service_role;

-- ==== 0005_lock_trigger_functions.sql ====
-- lockin. trigger functions are only ever run by their triggers; nobody needs to call them through the API.
revoke all on function public.handle_new_user() from public, anon, authenticated;
revoke all on function public.limit_lab_setups() from public, anon, authenticated;

-- ==== 0006_league_ai.sql ====
-- lockin. weekly league (opt-in, first name only) and a daily cap for the Ask Lochi AI helper.

-- ------------------------------------------------------------------ league
alter table public.profiles add column league_opt_in boolean not null default false;
grant update (league_opt_in) on public.profiles to authenticated;

-- The board for this week (Monday to Sunday, India time). Only students who chose to join appear, by first name and
-- weekly XP only. The caller always sees their own row. Never exposes ids, emails, branches or last names.
create function public.league_board(p_limit integer default 20) returns table (rank bigint, display text, xp bigint, me boolean)
language sql stable security definer set search_path = public, pg_catalog as $$
  with wk as (select date_trunc('week', now() at time zone 'Asia/Kolkata') as s),
  totals as (
    select p.id, p.name, sum(e.xp)::bigint as xp
    from profiles p join xp_events e on e.user_id = p.id, wk
    where p.league_opt_in and (e.created_at at time zone 'Asia/Kolkata') >= wk.s
    group by p.id, p.name
  ),
  ranked as (select t.*, rank() over (order by t.xp desc) as rk from totals t)
  select r.rk, coalesce(nullif(left(split_part(btrim(r.name), ' ', 1), 14), ''), 'Student'), r.xp, (r.id = auth.uid())
  from ranked r
  where (r.rk <= greatest(1, least(coalesce(p_limit, 20), 50)) or r.id = auth.uid()) and auth.uid() is not null
  order by r.rk, r.name;
$$;
revoke all on function public.league_board(integer) from public, anon;
grant execute on function public.league_board(integer) to authenticated;

-- ------------------------------------------------------------------ AI usage cap
create table public.ai_usage (
  user_id uuid not null references auth.users(id) on delete cascade,
  day date not null default ((now() at time zone 'Asia/Kolkata')::date),
  n integer not null default 0 check (n >= 0),
  primary key (user_id, day)
);
alter table public.ai_usage enable row level security;
revoke all on public.ai_usage from anon, authenticated;

-- Counts one request. Returns false (and counts nothing) once the student has used today's allowance.
create function public.bump_ai_usage(p_user uuid, p_limit integer) returns boolean
language plpgsql security definer set search_path = public, pg_catalog as $$
declare used integer;
begin
  insert into ai_usage (user_id, day, n) values (p_user, (now() at time zone 'Asia/Kolkata')::date, 1)
    on conflict (user_id, day) do update set n = ai_usage.n + 1 where ai_usage.n < p_limit
    returning n into used;
  return used is not null;
end $$;
revoke all on function public.bump_ai_usage(uuid, integer) from public, anon, authenticated;
grant execute on function public.bump_ai_usage(uuid, integer) to service_role;
