import type { LabMeta } from "../types";

/** BCA first-year labs: BCA-003 Digital Electronics, BCA-006 Data Structures, BCA-007 COA, BCA-008 Java. */
export const BCAX_LABS: LabMeta[] = [
  { id: "dlcodes", title: "Number codes and signed binary", where: [["BCA-003", 1], ["BCA-007", 1]], blurb: "See one number as sign-magnitude, 1's and 2's complement bit rows, as BCD, Excess-3, Gray and parity codes, or as a binary fraction with weight towers.", topics: ["Number systems and arithmetic", "signed binary representations", "binary codes (BCD, Excess-3, Gray code, parity)", "fixed-point and IEEE 754 floating-point representations"], animated: true,
    presets: [
      { name: "Q6.2 represent -25", note: "PYQ Q6.2: -25 in 8 bits. Sign-magnitude 10011001, 1's complement 11100110, 2's complement 11100111. Compare the three rows.", values: { view: "signed", n: -25 } },
      { name: "Q3.2 (1001.0010)2", note: "PYQ Q3.2: the fraction bits have weights 1/2, 1/4, 1/8, 1/16, so 1001.0010 = 8 + 1 + 1/8 = 9.125.", values: { view: "frac", fb: 146 } },
      { name: "Gray code of 9", note: "Digit 9 is 1001 in BCD, 1100 in Excess-3 and 1101 in Gray code. Step d up and down and count how many Gray bits change.", values: { view: "codes", d: 9 } },
    ] },
  { id: "dlqm", title: "Quine-McCluskey tabular minimiser", where: [["BCA-003", 1]], blurb: "Build the Quine-McCluskey table column by column: minterms grouped by number of 1s, merged into prime implicants, with essential primes and the minimal cover lit up.", topics: ["Quine-McCluskey (Tabular) minimization", "Don't Care conditions", "canonical SOP and POS forms", "K-maps up to 5 variables"], animated: false,
    presets: [
      { name: "Q3.4 Σm(0,1,5,7,10,14)", note: "PYQ Q3.4: four prime implicants; 000-, 01-1 and 1-10 are essential, so f = A'B'C' + A'BD + ACD'.", values: { fn: "q34", stage: 6 } },
      { name: "Q3.3 five variables", note: "PYQ Q3.3: the 17-minterm five-variable function. Step the stage slider to watch four merge passes shrink the table.", values: { fn: "q33", stage: 6 } },
      { name: "Cyclic cover", note: "No essential primes here: every minterm is covered twice, so you have to choose primes to finish the cover.", values: { fn: "cyc", stage: 6 } },
    ] },
  { id: "addsub", title: "Adders, subtractor and BCD adder", where: [["BCA-003", 2], ["BCA-007", 1]], blurb: "Four full adders with a gold carry packet: compare ripple and look-ahead carry delay, subtract by 2's complement and watch the BCD adder add 6 when the sum passes 9.", topics: ["Half adder", "full adder", "half subtractor", "full subtractor", "serial and parallel binary adders", "Look-Ahead Carry adder", "BCD adder", "computer arithmetic: signed addition", "subtraction"], animated: true,
    presets: [
      { name: "Ripple 15 + 1", note: "The carry must pass through all four stages (gold packet): the last sum is ready after 8 gate delays and Cout after 9.", values: { mode: "ripple", a: 15, b: 1, cin: false } },
      { name: "Look-ahead 15 + 1", note: "The look-ahead unit generates every carry at once from P and G: 4 gate delays for the sum, 3 for Cout, however long the word.", values: { mode: "lookahead", a: 15, b: 1, cin: false } },
      { name: "Q3.8 BCD 9 + 8", note: "PYQ Q3.8: 9 + 8 = 17 = 10001 in binary is above 9, so the orange +6 block adds 0110 and a carry goes to the tens digit: 1 7.", values: { mode: "bcd", a: 9, b: 8, cin: false } },
      { name: "Subtract 9 - 5", note: "A - B = A + B' + 1. Cout = 1 means there was no borrow (A at least B).", values: { mode: "sub", a: 9, b: 5, cin: false } },
    ] },
  { id: "muxdec", title: "Multiplexer, decoder and encoder bench", where: [["BCA-003", 2]], blurb: "Pick a select value and watch a gold packet take the one wire a multiplexer, demultiplexer, 3:8 decoder or priority encoder opens, including a 16:1 mux built from 4:1 muxes.", topics: ["multiplexers (MUX)", "demultiplexers (DEMUX)", "decoders (3:8, BCD-to-7 segment)", "encoders", "priority encoders"], animated: true,
    presets: [
      { name: "8:1 mux, select 4", note: "Data 10110010 with select 100: the multiplexer passes D4 = 1 to the output.", values: { mode: "mux", sel: 4, data: 178 } },
      { name: "Q3.7 3:8 decoder", note: "PYQ Q3.7: a 3:8 decoder with active-high enable. Untick the enable and every output goes to 0.", values: { mode: "decoder", sel: 5, en: true } },
      { name: "16:1 from 4:1 muxes", note: "Hint from the syllabus: four 4:1 muxes on S1S0 feed a fifth 4:1 mux on S3S2. Select 11 uses the third first-rank mux (orange) and its input 3.", values: { mode: "mux16", sel: 11, data: 42418 } },
      { name: "Priority encoder", note: "Inputs D2, D3 and D5 are high; the encoder outputs 101 because D5 has the highest priority.", values: { mode: "encoder", data: 44 } },
    ] },
  { id: "ffconv", title: "Flip-flop characteristics and conversion", where: [["BCA-003", 3]], blurb: "Clock SR, JK, D and T flip-flops through eight pulses and convert one type into another: see the inputs the real flip-flop needs on every pulse and Q after each clock edge.", topics: ["Latches (SR, D)", "flip-flops: SR", "JK", "Master-Slave JK", "characteristic tables", "characteristic equations", "excitation tables", "flip-flop conversions"], animated: true,
    presets: [
      { name: "Q3.11 SR as D", note: "PYQ Q3.11: convert an SR flip-flop to a D flip-flop. The orange S row copies D and the red R row is D': S = D, R = D'.", values: { base: "SR", tgt: "D", k: 8, xs: 90 } },
      { name: "JK as T", note: "A JK flip-flop with J = K = T toggles whenever T = 1 and holds when T = 0.", values: { base: "JK", tgt: "T", k: 8, xs: 117 } },
      { name: "Plain JK", note: "JK has no forbidden input: J = K = 1 toggles. Raise the pulse count and watch the toggles in the second input pattern.", values: { base: "JK", tgt: "same", k: 8, xs: 90, ys: 37 } },
    ] },
  { id: "counters", title: "Counters and shift registers", where: [["BCA-003", 3]], blurb: "Compare ripple and synchronous counters, ring and Johnson counters and a serial shift register while a gold clock pulse runs through the flip-flops, with the maximum clock frequency of each.", topics: ["shift registers (SISO, SIPO, PISO, PIPO, bi-directional)", "counters: asynchronous (ripple)", "synchronous", "Ring counter", "Johnson counter"], animated: true,
    presets: [
      { name: "Q3.9 ripple vs sync", note: "PYQ Q3.9: a 4-bit ripple counter needs 4 x 20 ns per clock (12.5 MHz); the synchronous counter needs only 20 + 10 ns (33.3 MHz).", values: { kind: "ripple", bits: 4, k: 10, tpd: 20, tg: 10 } },
      { name: "Q3.12 Johnson counter", note: "PYQ Q3.12: a 4-bit Johnson counter has 8 states: 0000, 1000, 1100, 1110, 1111, 0111, 0011, 0001. Step the pulse count from 0 to 8.", values: { kind: "johnson", bits: 4, k: 4 } },
      { name: "Ring counter", note: "A 4-bit ring counter circulates one 1 and has only 4 states.", values: { kind: "ring", bits: 4, k: 2 } },
      { name: "Serial shift register", note: "SISO: the serial input stream 10110001 is shifted in one bit per clock; after 4 pulses the register holds the first four bits.", values: { kind: "shift", bits: 4, k: 4, din: 177 } },
    ] },
  { id: "fsm", title: "Mealy, Moore and state reduction", where: [["BCA-003", 4]], blurb: "Run an overlapping sequence detector as a Mealy or Moore machine, and watch a 5-state machine collapse to 3 states by partition refinement.", topics: ["Synchronous clocked sequential circuits", "Mealy and Moore models", "state diagrams", "state tables", "state reduction methods (implication table)", "state assignment"], animated: true,
    presets: [
      { name: "1011 Mealy", note: "Mealy needs only 4 states; the output lamp lights on the arrow of the last matching bit. The stream 10110110 contains the overlapping match twice.", values: { view: "detect", model: "mealy", pat: "1011", inp: 182, step: 8 } },
      { name: "1011 Moore", note: "Moore needs 5 states: the extra green state outputs 1. Compare the number of states with the Mealy version.", values: { view: "detect", model: "moore", pat: "1011", inp: 182, step: 8 } },
      { name: "Q3.16 state reduction", note: "PYQ Q3.16: five states a-e. Round 0 splits by output, round 1 finds that a, c and e behave the same: 5 states reduce to 3.", values: { view: "reduce", step: 2 } },
    ] },
  { id: "hazard", title: "Static hazards and races", where: [["BCA-003", 4]], blurb: "Watch a static-1 glitch appear in F = AB + A'C when the inverter is slow, remove it with the consensus term, and see critical and non-critical races in an asynchronous circuit.", topics: ["hazards in combinational/sequential circuits (static-0, static-1, dynamic hazards)", "essential hazards", "race-free state assignment in asynchronous machines"], animated: true,
    presets: [
      { name: "Q3.14 static-1 hazard", note: "PYQ Q3.14: with B = C = 1, F = AB + A'C should stay 1 when A falls, but a 2 ns inverter delay makes a 2 ns glitch to 0.", values: { view: "hazard", dinv: 2, dand: 1, cons: false } },
      { name: "Consensus term fixes it", note: "Adding the redundant BC term keeps F at 1 the whole time: the glitch window disappears.", values: { view: "hazard", dinv: 2, dand: 1, cons: true } },
      { name: "Q3.13 critical race", note: "PYQ Q3.13: y1 is faster than y2, so the circuit passes through 10 and stops there. Swap the delays and it ends in 01: a critical race.", values: { view: "race", d1: 3, d2: 5, crit: true } },
    ] },
  { id: "logicfam", title: "Logic families: noise margin, fan-out, delay", where: [["BCA-003", 5]], blurb: "A voltage ladder shows VOH, VIH, VIL and VOL with the noise margins between them, while a row of load gates tests fan-out, delay and power for TTL, CMOS and ECL.", topics: ["Digital IC logic families: DTL, DCTL, TTL (totem-pole, open-collector, tri-state), ECL, CMOS", "operational metrics: Fan-in, Fan-out, Propagation Delay, Noise Margin, Power Dissipation"], animated: false,
    presets: [
      { name: "TTL noise margin", note: "74-series TTL: VOH 2.4 V, VIH 2.0 V, VIL 0.8 V, VOL 0.4 V give 0.4 V margins both ways.", values: { fam: "TTL", n: 4 } },
      { name: "TTL overloaded", note: "TTL fan-out is 10. Drive 14 gates and the extra loads turn red: the output level can no longer be guaranteed.", values: { fam: "TTL", n: 14 } },
      { name: "Q3.18 CMOS at 10 V", note: "PYQ Q3.18: CMOS noise margin is 30% of the supply (3 V at 10 V) and the power is dynamic, C V^2 f.", values: { fam: "CMOS", n: 4, vdd: 10, mhz: 10, cl: 15 } },
    ] },
  { id: "dsbigo", title: "Time complexity and Big-O", where: [["BCA-006", 1]], blurb: "Count how many times nested loops run and plot them against n log n and n squared, then test the formal definition f(n) at most c g(n) for n at least n0.", topics: ["asymptotic notations (O, Ω, Θ)", "time and space complexity", "space-time tradeoffs"], animated: true,
    presets: [
      { name: "Q5.4 nested loops", note: "PYQ Q5.4: two loops over n run n x n times: 64 for n = 8, so O(n^2).", values: { view: "count", prog: "nest", n: 8 } },
      { name: "Triangular loop", note: "The inner loop runs i times, so the body runs n(n-1)/2 = 28 times for n = 8: still O(n^2).", values: { view: "count", prog: "tri", n: 8 } },
      { name: "Q5.3 3n^2+2n+5", note: "PYQ Q5.3: 3n^2 + 2n + 5 is O(n^2) with c = 4 and n0 = 4.", values: { view: "bound", a: 3, b: 2, c: 5, k: 4, n: 10 } },
    ] },
  { id: "dsstack", title: "Stack, circular queue and expression evaluation", where: [["BCA-006", 2]], blurb: "Push and pop a physical tower of slabs with overflow and underflow flashes, wrap a circular queue round its ring, and evaluate or convert expressions with a stack.", topics: ["Stacks: push", "pop", "array implementation", "applications (recursion, infix to postfix conversion, postfix evaluation)", "Queues: enqueue", "dequeue", "circular queues"], animated: true,
    presets: [
      { name: "Q5.5 overflow at 4", note: "PYQ Q5.5: a stack of capacity 4. The fifth push flashes OVERFLOW (top = MAX-1) and the final pop shows UNDERFLOW.", values: { mode: "stack", cap: 4, step: 5 } },
      { name: "Q5.7 circular queue wrap", note: "PYQ Q5.7: with N = 5, rear = (rear + 1) mod 5 wraps to index 0 on the eighth operation although the array end was reached.", values: { mode: "cqueue", cap: 5, step: 8 } },
      { name: "Postfix 23+4*62/-", note: "Evaluate (2+3)*4-6/2: operands are pushed, each operator pops two and pushes the result; the answer is 17.", values: { mode: "postfix", ex: "e1", step: 9 } },
      { name: "Infix to postfix", note: "Convert (2+3)*4-6/2 with an operator stack: the output grows to 23+4*62/-.", values: { mode: "infix", ex: "e1", step: 11 } },
    ] },
  { id: "dslist", title: "Linked list pointer surgery", where: [["BCA-006", 2]], blurb: "Insert and delete in singly, doubly and circular linked lists one pointer assignment at a time, watching the arrows rewire and the new node drop into place.", topics: ["Linked Lists: singly", "doubly", "circular"], animated: true,
    presets: [
      { name: "Insert 25 after 20", note: "Singly list: first N.next = node20.next, only then node20.next = N. Reverse the order and the tail of the list is lost.", values: { mode: "singly", op: "mid", step: 3 } },
      { name: "Q5.6 doubly linked insert", note: "PYQ Q5.6: a doubly linked list needs four pointer changes for a middle insert (two on N, one on each neighbour) but gives O(1) delete and backward traversal.", values: { mode: "doubly", op: "mid", step: 4 } },
      { name: "Circular tail insert", note: "In a circular list the new tail must point back to the head; the arrow loops over the top.", values: { mode: "circular", op: "tail", step: 3 } },
    ] },
  { id: "dsarray", title: "Array address calculation", where: [["BCA-006", 2]], blurb: "Compute the memory address of A[i] in 1-D arrays and A[i][j] in 2-D arrays, row-major or column-major, with a packet walking memory in storage order.", topics: ["address calculation for 1D and 2D arrays"], animated: true,
    presets: [
      { name: "Q5.8 A[3] at base 1000", note: "PYQ Q5.8: A = [2,4,6,8,10], base 1000, 4 bytes per element: address of A[3] = 1000 + 3 x 4 = 1012.", values: { view: "1d", base: 1000, w: 4, i: 3 } },
      { name: "3x4 row-major", note: "A[1][2] of a 3 x 4 array: base + (1 x 4 + 2) x w. The numbers on the cells show storage order.", values: { view: "2d", base: 1000, w: 4, rows: 3, cols: 4, i: 1, j: 2, rm: true } },
      { name: "3x4 column-major", note: "The same element in column-major order sits at base + (2 x 3 + 1) x w: a different address.", values: { view: "2d", base: 1000, w: 4, rows: 3, cols: 4, i: 1, j: 2, rm: false } },
    ] },
  { id: "dsbst", title: "Binary search tree: insert, traverse, search, delete", where: [["BCA-006", 3]], blurb: "Grow a BST key by key, run inorder, preorder, postorder and level-order traversals, follow a search path and delete leaf, one-child and two-child nodes.", topics: ["binary trees", "tree traversals (inorder, preorder, postorder)", "Binary Search Trees (BST): insertion", "deletion", "searching", "Tree terminologies"], animated: true,
    presets: [
      { name: "Q5.12 insert 7 keys", note: "PYQ Q5.12: insert 15, 10, 20, 8, 12, 17, 25 into an empty BST. Drag the step slider and follow the gold node down each path.", values: { kset: "q512", view: "build", step: 7 } },
      { name: "Inorder is sorted", note: "Inorder on a BST visits the keys in ascending order: 8 10 12 15 17 20 25. Compare with preorder and postorder.", values: { kset: "q512", view: "traverse", trav: "in", step: 7 } },
      { name: "Delete the root", note: "Deleting 15 (two children): its inorder successor 17 takes its place and is removed from the right subtree.", values: { kset: "q512", view: "delete", key: 15, step: 3 } },
      { name: "Degenerate BST", note: "Sorted insertion makes a chain of height 5: search costs O(n). This is why AVL trees exist.", values: { kset: "skew", view: "build", step: 5 } },
    ] },
  { id: "dsavl", title: "AVL balance factors and rotations", where: [["BCA-006", 3]], blurb: "Insert keys into an AVL tree and watch balance factors turn red, then see LL, RR, LR and RL rotations glide the nodes back into balance.", topics: ["AVL trees", "balance factors", "rotations (LL, RR, LR, RL)"], animated: true,
    presets: [
      { name: "LL rotation 30,20,10", note: "Inserting 10 under 20 under 30 leaves 30 with balance +2: one right rotation makes 20 the root.", values: { seq: "ll", step: 3 } },
      { name: "Q5.11 LR rotation", note: "PYQ Q5.11: 30, 10, 20 is a left-right case: rotate 10 left, then 30 right. The middle key 20 becomes the root.", values: { seq: "lr", step: 3 } },
      { name: "Long sequence", note: "10,20,30,40,50,25 triggers an RR and later an RL rotation; the tree stays at height 3.", values: { seq: "long", step: 12 } },
    ] },
  { id: "dsgraph", title: "Graph search and spanning trees", where: [["BCA-006", 4]], blurb: "Run BFS with a queue, DFS with a stack, and Prim's and Kruskal's algorithms on a weighted graph; flip to the adjacency matrix to see the representation.", topics: ["graph traversals: Breadth-First Search (BFS)", "Depth-First Search (DFS)", "Spanning Trees", "Minimum Spanning Trees (Kruskal's, Prim's algorithms)", "representations: adjacency matrix", "adjacency list"], animated: true,
    presets: [
      { name: "Q5.16 BFS from A", note: "PYQ Q5.16: BFS uses a FIFO queue and visits A B D C E F G.", values: { alg: "bfs", s: 0, step: 7 } },
      { name: "DFS from A", note: "DFS uses a stack and dives deep first: A B C E D F G.", values: { alg: "dfs", s: 0, step: 7 } },
      { name: "Kruskal MST weight 39", note: "Sort the edges, accept those that join two components and reject cycle edges (red). Total weight 39.", values: { alg: "kruskal", step: 12 } },
      { name: "Prim MST weight 39", note: "Grow the tree from A by the cheapest edge leaving it. Prim and Kruskal give the same total weight 39.", values: { alg: "prim", s: 0, step: 6 } },
      { name: "Q5.15 adjacency matrix", note: "PYQ Q5.15: the matrix is symmetric for an undirected graph and costs O(V^2) memory; the adjacency list costs O(V + E).", values: { alg: "bfs", mat: true } },
    ] },
  { id: "dshash", title: "Hashing and collision resolution", where: [["BCA-006", 5]], blurb: "Insert keys into a hash table and watch a packet hop along the probe sequence of linear probing, quadratic probing and double hashing, or stack keys in chains.", topics: ["Hashing: hash functions", "collision resolution (chaining, open addressing: linear probing, quadratic probing, double hashing)"], animated: true,
    presets: [
      { name: "Q5.18 linear probing", note: "PYQ Q5.18: h(k) = k mod 7. Keys 85 and 92 collide with 50 at slot 1 and probe to the next free slots; the table ends full.", values: { scheme: "linear", m: 7, kset: "k1", step: 7 } },
      { name: "Separate chaining", note: "Same keys, no probing: slot 1 holds the chain 50, 85, 92. Chaining never overflows but chains slow search.", values: { scheme: "chain", m: 7, kset: "k1", step: 7 } },
      { name: "Double hashing", note: "The probe step comes from a second hash 1 + k mod (m-1), which avoids the clustering of linear probing.", values: { scheme: "double", m: 7, kset: "k1", step: 7 } },
    ] },
  { id: "dsmerge", title: "Merge sort and radix sort", where: [["BCA-006", 5]], blurb: "Watch merge sort split and merge runs with an exact comparison count, and radix sort drop numbers into digit buckets pass after pass.", topics: ["Sorting techniques: Bubble sort", "Merge sort", "Quick sort", "Radix sort"], animated: true,
    presets: [
      { name: "Q5.20 merge sort", note: "PYQ Q5.20: merge sort divides then merges in O(n log n) always; compare with quick sort's O(n^2) worst case.", values: { mode: "merge", arr: "m1", step: 18 } },
      { name: "Radix three passes", note: "Units, tens, hundreds: after the last pass the numbers are sorted without a single comparison.", values: { mode: "radix", step: 6 } },
    ] },
  { id: "coabooth", title: "Booth multiplication and restoring division", where: [["BCA-007", 1]], blurb: "Trace Booth's algorithm on signed 4-bit numbers register by register (add, subtract or just shift) and the restoring division algorithm.", topics: ["computer arithmetic: signed addition", "subtraction", "Booth's multiplication", "restoring/non-restoring division"], animated: true,
    presets: [
      { name: "Booth 7 x -3 = -21", note: "Unit hint: Booth's 2's complement multiplication trace on signed integers. 7 x -3 gives -21 = 11101011.", values: { mode: "booth", m: 7, q: -3, step: 8 } },
      { name: "Booth a run of ones", note: "Multiplier 0111 is a run of ones: only one subtraction at the start and one addition at the end are needed.", values: { mode: "booth", m: 3, q: 7, step: 8 } },
      { name: "Restoring 13 / 3", note: "13 / 3 gives quotient 4 and remainder 1; a restore step appears whenever A - M is negative.", values: { mode: "div", m: 3, q: 13, step: 12 } },
    ] },
  { id: "coacycle", title: "Instruction cycle on a common bus", where: [["BCA-007", 2], ["BCA-007", 3], ["BCA-007", 1]], blurb: "Step a tiny stored-program computer through fetch, decode, execute and interrupt, with every register transfer statement shown and a gold packet crossing the common bus.", topics: ["Instruction codes", "computer registers", "instruction cycle (Fetch, Decode, Execute, Interrupt)", "Register Transfer Language (RTL)", "bus and memory transfers", "Von Neumann architecture", "bus structures"], animated: true,
    presets: [
      { name: "Q6.5 fetch-decode-execute", note: "PYQ Q6.5: T0 AR <- PC, T1 IR <- M[AR] and PC <- PC + 1, then decode and execute. Run the program 5 + 3 to the end: AC = 8 stored in M[14].", values: { prog: "add", irq: false, step: 6 } },
      { name: "With an interrupt", note: "The interrupt cycle saves PC in M[0] and jumps to the service routine; it returns by jumping indirectly through M[0].", values: { prog: "add", irq: true, step: 10 } },
      { name: "Jump instruction", note: "JMP overwrites the PC, so the ADD at address 4 is skipped.", values: { prog: "jump", irq: false, step: 12 } },
    ] },
  { id: "coaddr", title: "Addressing modes", where: [["BCA-007", 2]], blurb: "Pick an addressing mode and follow the gold packet from the instruction through registers and memory to the operand, with the effective address calculated for you.", topics: ["instruction formats (zero, one, two, three-address)", "addressing modes"], animated: true,
    presets: [
      { name: "Q6.7 direct vs indirect", note: "PYQ Q6.7 set-up: address field 500, R1 = 400, XR = 100, PC = 202. Direct reaches M[500] = 800; switch to Indirect and it goes through M[500] to reach 300.", values: { mode: "ind", x: 500, r1: 400, xr: 100 } },
      { name: "Relative: PC + 500", note: "Relative mode adds the address field to the PC after the fetch: 202 + 500 = 702, operand 325.", values: { mode: "rel", x: 500, r1: 400, xr: 100 } },
      { name: "Indexed: 500 + XR", note: "Indexed mode adds the index register: 500 + 100 = 600, operand 900. Used for arrays.", values: { mode: "idx", x: 500, r1: 400, xr: 100 } },
    ] },
  { id: "coapipe", title: "Pipelining and hazards", where: [["BCA-007", 2]], blurb: "A 3D pipeline diagram of a RISC processor: see stalls from data hazards with and without forwarding, load-use delays and branch bubbles, with CPI and speed-up.", topics: ["RISC vs. CISC", "instruction cycle (Fetch, Decode, Execute, Interrupt)", "timing and control"], animated: false,
    presets: [
      { name: "RAW hazard, no forwarding", note: "Each instruction needs r1 from the first: without forwarding they wait 2 cycles for write-back (red bubbles).", values: { prog: "alu", fwd: false, cyc: 14 } },
      { name: "Forwarding fixes it", note: "With bypassing the ALU result goes straight to the next EX stage: no stalls.", values: { prog: "alu", fwd: true, cyc: 14 } },
      { name: "Load-use hazard", note: "Even with forwarding a load followed by its user loses 1 cycle: the data only exists after MEM.", values: { prog: "load", fwd: true, cyc: 14 } },
    ] },
  { id: "coacache", title: "Cache mapping and effective access time", where: [["BCA-007", 4]], blurb: "Send memory blocks into a direct-mapped, set-associative or fully associative cache and watch hits, misses and evictions, then compute the effective access time.", topics: ["cache memory: organization", "mapping techniques (Direct, Associative, Set-Associative)", "cache hit ratio", "Memory hierarchy"], animated: true,
    presets: [
      { name: "Q6.16 EMAT = 20 ns", note: "PYQ Q6.16: cache 10 ns, memory 100 ns, hit ratio 90%: EMAT = 0.9 x 10 + 0.1 x (10 + 100) = 20 ns (19 ns if memory is started in parallel).", values: { hr: 90, tc: 10, tm: 100, simul: false } },
      { name: "Direct-mapped conflicts", note: "Blocks 0 and 8 map to the same line of an 8-line direct cache and keep evicting each other: zero hits.", values: { map: "direct", seq: "conf", step: 10 } },
      { name: "2-way fixes the conflict", note: "The same accesses with 2-way sets: both blocks fit in set 0 and later accesses hit.", values: { map: "set2", seq: "conf", step: 10 } },
    ] },
  { id: "coavmem", title: "Paging and page replacement", where: [["BCA-007", 4]], blurb: "Process a page reference string with FIFO, LRU or optimal replacement and watch the frames fill, the page faults flash red and Belady's anomaly appear.", topics: ["virtual memory", "address mapping", "paging", "page replacement"], animated: true,
    presets: [
      { name: "FIFO 3 frames = 15 faults", note: "The classic 20-reference string 7 0 1 2 0 3 0 4 ... with 3 frames gives 15 faults under FIFO.", values: { alg: "fifo", nf: 3, seq: "classic", step: 20 } },
      { name: "LRU 3 frames = 12", note: "LRU keeps recently used pages: 12 faults on the same string. Optimal gets 9.", values: { alg: "lru", nf: 3, seq: "classic", step: 20 } },
      { name: "Belady's anomaly", note: "FIFO on 1 2 3 4 1 2 5 1 2 3 4 5: 3 frames give 9 faults but 4 frames give 10. Change the frame count and read the fault total.", values: { alg: "fifo", nf: 4, seq: "belady", step: 12 } },
    ] },
  { id: "coaio", title: "Programmed I/O, interrupts, DMA and daisy chain", where: [["BCA-007", 5]], blurb: "Compare how much CPU time programmed I/O, interrupt-driven I/O and DMA leave free for useful work, and watch a daisy chain grant the bus to the nearest requesting device.", topics: ["Programmed I/O", "Interrupt-driven I/O", "Direct Memory Access (DMA)", "priority interrupts", "inter-processor arbitration (daisy chaining, parallel arbitration)"], animated: true,
    presets: [
      { name: "Q6.19 100 words", note: "PYQ Q6.19: device time 50 us per word, interrupt overhead 10 us: programmed I/O leaves 0% CPU, interrupts 80%, DMA about 97%.", values: { view: "modes", words: 100, td: 50, ti: 10 } },
      { name: "Daisy chain: d1 and d3", note: "Devices 1 and 3 request together; the grant reaches d1 first and stops there. d3 must wait.", values: { view: "daisy", req: 10 } },
    ] },
  { id: "jvm", title: "JVM, bytecode and the operand stack", where: [["BCA-008", 1]], blurb: "See javac turn source into platform-independent bytecode and run it on the JVM's operand stack and local variables, step by step.", topics: ["JVM", "JDK", "JRE", "byte-code execution", "primitive data types", "operators"], animated: true,
    presets: [
      { name: "Q7.1 bytecode execution", note: "PYQ Q7.1: c = a + b * 2 with a = 3, b = 4. Watch the stack reach height 3 and the multiplication happen before the addition: c = 11.", values: { a: 3, b: 4, k: 2, step: 11 } },
      { name: "Bigger operands", note: "Change a, b and k and re-run: the bytecode is the same shape, only the constants differ.", values: { a: 10, b: 6, k: 5, step: 11 } },
    ] },
  { id: "jheap", title: "Objects, heap, garbage collection and Strings", where: [["BCA-008", 2]], blurb: "Watch references on the stack point at objects on the heap, an unreachable object get collected, and compare string-pool literals, new String and StringBuffer.", topics: ["object instantiation", "garbage collection", "String and StringBuffer", "Class definitions"], animated: true,
    presets: [
      { name: "Garbage appears", note: "After b = c nothing refers to the Asha object: it turns red and the next step collects it.", values: { mode: "gc", step: 5 } },
      { name: "Q7.2 String vs StringBuffer", note: "PYQ Q7.2: s1.concat creates a new immutable String, while sb.append changes the same StringBuffer in place.", values: { mode: "str", step: 6 } },
    ] },
  { id: "jdispatch", title: "Inheritance and dynamic method dispatch", where: [["BCA-008", 3]], blurb: "Build Animal a = new Dog() in blocks: the compiler checks the reference type, then a packet climbs the inheritance chain from the real object's class to find the method that runs.", topics: ["Inheritance basics", "method overriding", "dynamic method dispatch", "abstract classes", "interfaces"], animated: true,
    presets: [
      { name: "Q7.3 Animal a = new Dog()", note: "PYQ Q7.3: a.speak() runs Dog's overridden version because dispatch uses the run-time class: output Woof.", values: { ref: "Animal", obj: "Dog", mi: 0 } },
      { name: "Inherited method", note: "Puppy does not override speak(), so the search climbs to Dog and runs Dog.speak().", values: { ref: "Animal", obj: "Puppy", mi: 0 } },
      { name: "Compile-time error", note: "fetch() exists only in Dog; through an Animal reference the compiler refuses, whatever the object is.", values: { ref: "Animal", obj: "Dog", mi: 2 } },
    ] },
  { id: "jexc", title: "Exception handling flow", where: [["BCA-008", 6]], blurb: "Follow the control flow of try, catch and finally for normal runs, built-in exceptions and a custom checked exception, including return inside try.", topics: ["exception handling (try-catch-finally-throw-throws)"], animated: true,
    presets: [
      { name: "Q7.6 ArithmeticException", note: "PYQ Q7.6: the divide throws, stmt2 is skipped, the matching catch runs, then finally and the code after the try.", values: { kind: "arith", all: false, step: 9 } },
      { name: "Custom exception propagates", note: "A checked custom exception with no matching catch runs finally and then propagates to the caller. Tick the catch-all box to handle it.", values: { kind: "custom", all: false, step: 9 } },
      { name: "return and finally", note: "Even a return inside try runs the finally block first.", values: { kind: "none", early: true, step: 9 } },
    ] },
  { id: "jthread", title: "Thread life cycle and synchronization", where: [["BCA-008", 6]], blurb: "Step a thread through NEW, RUNNABLE, RUNNING, WAITING and TERMINATED, and run two threads on a shared counter to see lost updates vanish with synchronized.", topics: ["Java thread model", "Thread lifecycle", "Thread class and Runnable interface", "inter-thread communication (wait(), notify())", "synchronization"], animated: true,
    presets: [
      { name: "Q7.5 full life cycle", note: "PYQ Q7.5: from new Thread through start, sleep, a blocked monitor, wait/notify to termination.", values: { view: "life", step: 11 } },
      { name: "Race: lost updates", note: "Switching threads every 2 micro-steps breaks counter++ (load, add, store): the total is below the expected 20.", values: { view: "race", q: 2, n: 10, sync: false } },
      { name: "Synchronized fix", note: "With synchronized the three steps are indivisible and the total is exactly 20.", values: { view: "race", q: 2, n: 10, sync: true } },
    ] },
];
