import { flag, num, opt, type ParamSpec } from "../params-core";

/** Adjustable values of the BCA labs (Digital Electronics, Data Structures, Computer Organization, Java). */
export const BCAX_SPECS = {
  dlcodes: { view: opt("signed", ["signed", "codes", "frac"] as const), n: num(-25, -127, 127), d: num(7, 0, 9), fb: num(146, 0, 255) },
  dlqm: { fn: opt("q34", ["q34", "cyc", "q33"] as const), stage: num(0, 0, 6) },
  addsub: { mode: opt("ripple", ["ripple", "lookahead", "sub", "bcd"] as const), a: num(11, 0, 15), b: num(6, 0, 15), cin: flag(false) },
  muxdec: { mode: opt("mux", ["mux", "mux16", "demux", "decoder", "encoder"] as const), sel: num(3, 0, 15), data: num(178, 0, 65535), en: flag(true), din: flag(true) },
  ffconv: { base: opt("SR", ["SR", "JK", "D", "T"] as const), tgt: opt("D", ["same", "D", "T", "JK", "SR"] as const), k: num(0, 0, 8), xs: num(90, 0, 255), ys: num(37, 0, 255) },
  counters: { kind: opt("ripple", ["ripple", "sync", "ring", "johnson", "shift"] as const), bits: num(4, 2, 6), k: num(5, 0, 40), tpd: num(20, 5, 50), tg: num(10, 2, 30), din: num(177, 0, 255) },
  fsm: { view: opt("detect", ["detect", "reduce"] as const), model: opt("mealy", ["mealy", "moore"] as const), pat: opt("1011", ["101", "110", "1011"] as const), inp: num(182, 0, 255), step: num(0, 0, 8) },
  hazard: { view: opt("hazard", ["hazard", "race"] as const), dinv: num(2, 0, 5), dand: num(1, 0, 3), cons: flag(false), d1: num(3, 1, 9), d2: num(5, 1, 9), crit: flag(true) },
  logicfam: { fam: opt("TTL", ["TTL", "CMOS", "ECL"] as const), n: num(4, 1, 40), vdd: num(5, 3, 15), mhz: num(10, 0.1, 100), cl: num(15, 1, 100) },
  dsbigo: { view: opt("count", ["count", "bound"] as const), prog: opt("nest", ["lin", "nest", "tri", "log", "nlogn"] as const), n: num(8, 1, 64), a: num(3, 1, 10), b: num(2, 0, 20), c: num(5, 0, 50), k: num(4, 1, 20) },
  dsstack: { mode: opt("stack", ["stack", "cqueue", "postfix", "infix"] as const), cap: num(5, 3, 8), ex: opt("e1", ["e1", "e2"] as const), step: num(0, 0, 14) },
  dslist: { mode: opt("singly", ["singly", "doubly", "circular"] as const), op: opt("mid", ["head", "mid", "tail", "del"] as const), step: num(0, 0, 5) },
  dsarray: { view: opt("1d", ["1d", "2d"] as const), base: num(1000, 0, 5000), w: num(4, 1, 8), rows: num(3, 2, 6), cols: num(4, 2, 6), i: num(3, 0, 5), j: num(2, 0, 5), rm: flag(true) },
  dsbst: { kset: opt("q512", ["q512", "mix", "skew"] as const), view: opt("build", ["build", "traverse", "search", "delete"] as const), trav: opt("in", ["in", "pre", "post", "level"] as const), key: num(17, 1, 99), step: num(0, 0, 8) },
  dsavl: { seq: opt("lr", ["ll", "rr", "lr", "rl", "long"] as const), step: num(0, 0, 12) },
  dsgraph: { alg: opt("bfs", ["bfs", "dfs", "prim", "kruskal"] as const), s: num(0, 0, 6), step: num(0, 0, 12), mat: flag(false) },
  dshash: { scheme: opt("linear", ["chain", "linear", "quad", "double"] as const), m: num(7, 5, 13), kset: opt("k1", ["k1", "k2"] as const), step: num(0, 0, 8) },
  dsmerge: { mode: opt("merge", ["merge", "radix"] as const), arr: opt("m1", ["m1", "m2", "m3"] as const), step: num(0, 0, 30) },
  coabooth: { mode: opt("booth", ["booth", "div"] as const), m: num(7, -7, 7), q: num(-3, -8, 15), step: num(0, 0, 12) },
  coacycle: { prog: opt("add", ["add", "jump"] as const), irq: flag(false), step: num(0, 0, 45) },
  coaddr: { mode: opt("dir", ["imm", "dir", "ind", "reg", "regind", "autodec", "rel", "idx"] as const), x: num(500, 0, 999), r1: num(400, 0, 999), xr: num(100, 0, 999) },
  coapipe: { prog: opt("alu", ["free", "alu", "load", "branch"] as const), fwd: flag(false), bp: num(0, 0, 3), cyc: num(6, 0, 14) },
  coacache: { map: opt("direct", ["direct", "set2", "set4", "full"] as const), seq: opt("conf", ["conf", "loc", "mix"] as const), step: num(0, 0, 12), hr: num(90, 0, 100), tc: num(10, 1, 50), tm: num(100, 20, 300), simul: flag(false) },
  coavmem: { alg: opt("fifo", ["fifo", "lru", "opt"] as const), nf: num(3, 1, 7), seq: opt("classic", ["classic", "belady"] as const), step: num(0, 0, 20) },
  coaio: { view: opt("modes", ["modes", "daisy"] as const), words: num(100, 10, 1000), td: num(50, 10, 200), ti: num(10, 2, 40), req: num(10, 0, 15) },
  jvm: { a: num(3, 1, 20), b: num(4, 1, 20), k: num(2, 1, 9), step: num(0, 0, 11) },
  jheap: { mode: opt("gc", ["gc", "str"] as const), step: num(0, 0, 7) },
  jdispatch: { ref: opt("Animal", ["Animal", "Dog", "Puppy", "Cat"] as const), obj: opt("Dog", ["Animal", "Dog", "Puppy", "Cat"] as const), mi: num(0, 0, 2) },
  jexc: { kind: opt("arith", ["none", "arith", "index", "custom"] as const), all: flag(false), early: flag(false), step: num(0, 0, 9) },
  jthread: { view: opt("life", ["life", "race"] as const), step: num(0, 0, 11), q: num(2, 1, 6), n: num(10, 5, 40), sync: flag(false) },
} satisfies Record<string, ParamSpec>;
