import type { LabMeta } from "../types";

/** Round-3 labs (group mechy): fills every unit of the core subjects to at least five labs. */
export const MECHY_LABS: LabMeta[] = [
  { id: "elastic", title: "Elastic constants E, G, K and ν", where: [["MET-001", 2]], blurb: "Pull, shear or squeeze a cube and watch it stretch and narrow, skew or shrink; see why only two of E, G, K and Poisson's ratio are independent.", topics: ["Elastic constants and their relationship", "Hooke's law", "Normal and shear stresses", "Poisson's ratio", "Bulk modulus"], animated: true,
    presets: [
      { name: "Steel: E = 200 GPa, ν = 0.3", note: "The classic numerical: G = E/2(1 + ν) = 76.9 GPa and K = E/3(1 − 2ν) = 166.7 GPa. A 100 MPa pull stretches a 100 mm cube by 50 µm and narrows it by 15 µm.", values: { E: 200, nu: 0.3, s: 100, a: 100, mode: "normal" } },
      { name: "Exam type: E = 200 GPa, G = 80 GPa", note: "Given E and G, ν = E/2G − 1 = 0.25 and then K = E/3(1 − 2ν) = 133.3 GPa. Here the cube is in pure shear: it skews but its volume does not change.", values: { E: 200, nu: 0.25, s: 100, a: 100, mode: "shear" } },
      { name: "Nearly incompressible (ν → 0.5)", note: "As ν approaches 0.5 the bulk modulus soars (here 17 times E): rubber-like materials change shape easily but hardly change volume under all-round pressure.", values: { E: 10, nu: 0.49, s: 50, a: 100, mode: "volume" } },
    ] },
  { id: "steppedbar", title: "Stepped bar under axial loads (ΔL = PL/AE)", where: [["MET-001", 2]], blurb: "Load a three-step bar at its joints, find the missing load for equilibrium, then the force, stress and change in length of every segment and of the whole bar.", topics: ["Introduction to stress and strain", "Hooke's law", "Normal and shear stresses", "Axial deformation of stepped bars"], animated: true,
    presets: [
      { name: "PYQ: member LMNP (E = 210 GPa)", note: "50 kN pulls L to the left, 500 kN pulls N to the left and 200 kN pulls P to the right (the usual figure). Equilibrium needs P = 350 kN at M; LM is in tension, MN in compression, NP in tension, and the total change is +0.278 mm.", values: { FA: -50, FC: -500, FD: 200, A1: 600, A2: 2400, A3: 1200, L1: 1000, L2: 1000, L3: 600, E: 210 } },
      { name: "PYQ: rod 2 cm × 2 cm × 100 cm, 1000 kgf", note: "1000 kgf = 9.81 kN, 400 mm² and E = 2 × 10⁶ kgf/cm² = 196.2 GPa: δ = PL/AE = 0.0125 cm = 0.125 mm. (One uniform bar, drawn as three equal-area pieces.)", values: { FA: -9.81, FC: 0, FD: 9.81, A1: 400, A2: 400, A3: 400, L1: 400, L2: 300, L3: 300, E: 196.2 } },
      { name: "Squeezed, with a thin middle", note: "120 kN pushes on both ends: every segment is in compression, the bar shortens by 1.2 mm, and the thin middle piece carries twice the stress of the ends.", values: { FA: 120, FC: 0, FD: -120, A1: 1000, A2: 500, A3: 1000, L1: 500, L2: 500, L3: 500, E: 200 } },
    ] },
  { id: "carbonsteel", title: "Carbon steels, cast iron & alloy steels", where: [["MET-001", 2]], blurb: "Slide the carbon content from mild steel to cast iron (or switch to alloy steel) and watch strength, hardness, toughness, ductility, the stress–strain curve and the microstructure change.", topics: ["Cast iron", "Carbon steels (low, medium, high)", "Alloy steels and their applications", "Mechanical properties: strength, hardness, toughness, ductility, brittleness", "Stress-strain diagrams for ductile and brittle materials"], animated: true,
    presets: [
      { name: "Mild steel (0.15 % C)", note: "Low-carbon steel: mostly soft ferrite, about 380 MPa UTS and 33 % elongation. Ductile and tough, easy to weld, bend and press: sheet, wire, structural sections.", values: { c: 0.15, kind: "plain" } },
      { name: "Alloy steel (0.4 % C, Cr–Ni–Mo)", note: "Hardened and tempered alloy steel reaches more than 900 MPa while keeping about 13 % elongation, far stronger than plain 0.4 % carbon steel: crankshafts, gears, axles.", values: { c: 0.4, kind: "alloy" } },
      { name: "Grey cast iron (3.2 % C)", note: "Graphite flakes make it brittle: no yield point, fracture at about 0.6 % strain and very low toughness, yet it is hard, cheap to cast and damps vibration: machine beds and engine blocks.", values: { c: 3.2, kind: "plain" } },
    ] },
  { id: "manometer", title: "U-tube manometer & Bourdon gauge", where: [["MET-001", 3]], blurb: "Read the pressure in a pipe from the deflection of a U-tube manometer and from a Bourdon-tube dial; switch between gauge and absolute pressure and between mercury, water and oil.", topics: ["Introduction to measuring instruments for pressure (manometer, Bourdon gauge)", "Pressure at depth p = ρgh", "Absolute and gauge pressure", "Specific gravity"], animated: true,
    presets: [
      { name: "PYQ: 250 cm of mercury on a gas tank", note: "p = ρgh = 13 600 × 9.81 × 2.5 = 333.5 kPa gauge; adding 101 kPa of atmosphere gives 434.5 kPa = 0.4345 MPa absolute.", values: { h: 250, s2: 13.6, s1: 0, y: 0, patm: 101 } },
      { name: "PYQ: oil SG 0.95, 150 cm deep", note: "A column of oil works like a piezometer: p = 0.95 × 1000 × 9.81 × 1.5 = 13.98 kN/m² gauge.", values: { h: 150, s2: 0.95, s1: 0, y: 0, patm: 101.3 } },
      { name: "Water pipe, mercury U-tube", note: "With water in the pipe the column of water above the left meniscus pushes down too: p = ρg(13.6 × 0.20 − 1 × 0.30) = 23.7 kPa.", values: { h: 20, s2: 13.6, s1: 1, y: 30, patm: 101.3 } },
    ] },
  { id: "hydrolift", title: "Pascal's law: hydraulic lift", where: [["MET-001", 3]], blurb: "A small plunger pumps oil under a big ram that lifts a car: see the pressure, the force multiplication A₂/A₁ and why the plunger must travel so much further.", topics: ["Pascal's law", "Hydraulic press and lift", "Fluid properties (compressibility)"], animated: true,
    presets: [
      { name: "PYQ: car on a 0.90 m² ram", note: "A 1.2 × 10⁴ N car on a 0.90 m² ram with a 0.20 m² plunger: F₁ = W·A₁/A₂ = 2667 N, at an oil pressure of 13.3 kPa.", values: { W: 12, A1: 0.2, A2: 0.9, lift: 10, eta: 100 } },
      { name: "Workshop jack (area ratio 100)", note: "A tiny plunger lifts 50 kN with only 556 N of effort (90 % efficient), but it has to travel 20 m in many short strokes to raise the load 20 cm.", values: { W: 50, A1: 0.005, A2: 0.5, lift: 20, eta: 90 } },
      { name: "Equal pistons: no gain", note: "With equal areas the pressure is the same but the force is not multiplied: the effort equals the load and both pistons move equally.", values: { W: 5, A1: 0.5, A2: 0.5, lift: 10, eta: 100 } },
    ] },
  { id: "viscosity", title: "Newton's law of viscosity", where: [["MET-001", 3]], blurb: "Drag a plate over a thin fluid film: layers slide over each other with a straight-line velocity profile. Compare Newtonian, shear-thinning, shear-thickening and Bingham fluids on a τ–du/dy graph.", topics: ["Newton's law of viscosity", "Types of fluids (ideal, real, Newtonian, non-Newtonian)", "Fluid properties (viscosity)", "Kinematic viscosity"], animated: true,
    presets: [
      { name: "Textbook: plate on an oil film", note: "R.K. Bansal: an 0.8 m × 0.8 m plate slides at 0.3 m/s on a 1.5 mm oil film. τ = μu/y = 234 Pa needs 150 N, so μ ≈ 1.17 Pa·s (11.7 poise).", values: { u: 0.3, y: 1.5, mu: 1.172, A: 0.64, rho: 900, kind: "newtonian" } },
      { name: "Water in a 1 mm gap", note: "Water (μ = 0.001 Pa·s) sheared at 1000 s⁻¹ resists with just 1 Pa: a 1 m² plate needs only 1 N. Its kinematic viscosity is 0.01 stokes.", values: { u: 1, y: 1, mu: 0.001, A: 1, rho: 1000, kind: "newtonian" } },
      { name: "Toothpaste (Bingham plastic)", note: "A Bingham plastic needs its 20 Pa yield stress before it moves at all, then behaves like a viscous fluid: τ = τ_y + μ du/dy = 70 Pa here.", values: { u: 0.2, y: 2, mu: 0.5, A: 0.1, rho: 1300, kind: "bingham" } },
    ] },
  { id: "sfee", title: "Steady flow energy equation: nozzle, turbine, compressor, boiler", where: [["MET-001", 4]], blurb: "Pick a steady-flow device, set enthalpies, velocities and heights, and let the SFEE find the exit velocity, shaft work or heat, with a bar for every energy term.", topics: ["Steady flow energy equation", "Control volume", "Flow work and non-flow work", "Processes: flow and non-flow", "First law of thermodynamics"], animated: true,
    presets: [
      { name: "Textbook nozzle (P.K. Nag)", note: "Steam enters at 3000 kJ/kg and 60 m/s and leaves at 2762 kJ/kg: with q = w = 0, V₂ = √(60² + 2 × 238 000) = 692 m/s.", values: { dev: "nozzle", h1: 3000, h2: 2762, V1: 60, V2: 100, dz: 0, q: 0, mdot: 1 } },
      { name: "Steam turbine, 2 kg/s", note: "600 kJ/kg of enthalpy drop, minus 3.75 kJ/kg of extra kinetic energy and 5 kJ/kg of heat loss, gives w = 591 kJ/kg, about 1.18 MW.", values: { dev: "turbine", h1: 3200, h2: 2600, V1: 50, V2: 100, dz: 0, q: -5, mdot: 2 } },
      { name: "Boiler, 10 kg/s", note: "Feed water at 420 kJ/kg leaves as steam at 2800 kJ/kg: q = h₂ − h₁ = 2380 kJ/kg (the kinetic energy term is only 0.2 kJ/kg), 23.8 MW of heat.", values: { dev: "boiler", h1: 420, h2: 2800, V1: 2, V2: 20, dz: 0, q: 0, mdot: 10 } },
    ] },
  { id: "secondlaw", title: "Kelvin–Planck vs Clausius: why they are equivalent", where: [["MET-001", 4]], blurb: "Combine an engine and a refrigerator between two reservoirs; suppose one statement of the second law fails and watch the composite device break the other.", topics: ["Statements of second law (Kelvin-Planck and Clausius) and their equivalence", "Thermal reservoir", "Heat engines", "COP of heat pump and refrigerator", "Perpetual motion machine of the second kind"], animated: true,
    presets: [
      { name: "Clausius broken ⇒ a PMM2", note: "The engine makes 30 kJ of work and rejects 70 kJ; a free heat pump puts the 70 kJ straight back. Net: 30 kJ from one reservoir turned entirely into work, violating Kelvin–Planck (ΔS < 0).", values: { mode: "clausius", Q1: 100, TH: 600, TC: 300, frac: 0.6 } },
      { name: "Kelvin–Planck broken ⇒ heat flows uphill", note: "A 100 % engine drives a Carnot refrigerator. Net: 100 kJ moves from the cold to the hot reservoir with no work from outside, violating Clausius.", values: { mode: "kp", Q1: 100, TH: 600, TC: 300, frac: 1 } },
      { name: "Real engine drives a real fridge", note: "Both machines reach 60 % of their Carnot limit: more heat goes down than comes up and the reservoirs' entropy rises (ΔS > 0), as the second law demands.", values: { mode: "legal", Q1: 100, TH: 600, TC: 300, frac: 0.6 } },
    ] },
  { id: "zerothlaw", title: "Zeroth law & thermometers (RTD, thermocouple)", where: [["MET-001", 4], ["MET-001", 3]], blurb: "A thermometer compares two blocks that never touch; put them in contact and they settle at one temperature. Read it as RTD resistance, thermocouple EMF or a mercury column.", topics: ["Zeroth law of thermodynamics", "Introduction to measuring instruments for temperature (thermometers, thermocouple, RTD)", "Thermal equilibrium"], animated: true,
    presets: [
      { name: "Hot copper into water", note: "1 kg of copper at 200 °C dropped into 2 kg of water at 20 °C: water's heat capacity is 22 times larger, so they settle at only 27.9 °C. The thermocouple then reads 1.14 mV in both.", values: { TA: 200, TB: 20, mA: 1, mB: 2, matA: "cu", matB: "water", sensor: "tc", contact: true } },
      { name: "Not in equilibrium", note: "Apart, A and B give different RTD readings (130.8 Ω and 107.7 Ω): they are not in thermal equilibrium, and heat would flow if they touched.", values: { TA: 80, TB: 20, mA: 1, mB: 2, matA: "cu", matB: "water", sensor: "rtd", contact: false } },
      { name: "Equal water masses", note: "Equal masses of water at 80 °C and 20 °C settle at exactly the average, 50 °C; the mercury thermometer reads the same in both, so by the zeroth law they are in equilibrium.", values: { TA: 80, TB: 20, mA: 1, mB: 1, matA: "water", matB: "water", sensor: "hg", contact: true } },
    ] },
  { id: "twostroke", title: "Two-stroke engine: ports & scavenging", where: [["MET-001", 5]], blurb: "A valve-less crankcase-scavenged two-stroke: the piston opens the exhaust and transfer ports, fresh charge sweeps out the exhaust, and one power stroke comes every revolution.", topics: ["Two stroke S.I. engine and its working", "Two stroke C.I. engine and its working", "Introduction to I.C. engines (classification, parts)", "Indicated power", "Port timing and scavenging"], animated: true,
    presets: [
      { name: "Scooter-type petrol two-stroke", note: "A 57 × 57 mm, 145 cc engine at 5000 rpm makes 83 power strokes per second; with p_m = 5 bar the indicated power is 6.1 kW, twice a four-stroke of the same size.", values: { rpm: 5000, bore: 57, stroke: 57, pm: 5, ex: 30, tr: 20, crank: 150, fuel: "si" } },
      { name: "Textbook IP: 100 × 150 mm, 6 bar, 1000 rpm", note: "IP = p_m L A n/60 = 6 × 10⁵ × 0.15 × 0.007854 × 1000/60 = 11.8 kW with n = N for a two-stroke (a four-stroke would give 5.9 kW). Paused at BDC: both ports wide open.", values: { rpm: 1000, bore: 100, stroke: 150, pm: 6, ex: 30, tr: 20, crank: 180, fuel: "ci" } },
      { name: "Racing tune: tall exhaust port", note: "A higher exhaust port opens earlier (about 92° after TDC) and stays open for 176°: more time for breathing at high rpm, but a shorter useful power stroke and more charge lost.", values: { rpm: 6000, bore: 54, stroke: 54, pm: 7, ex: 42, tr: 28, crank: 120, fuel: "si" } },
    ] },
  { id: "centripump", title: "Centrifugal pump & velocity triangles", where: [["MET-001", 3]], blurb: "Spin an impeller with backward-curved vanes inside a volute; read the outlet velocity triangle, the Euler head, the discharge and the power given to the water.", topics: ["Working principle of centrifugal pumps", "Velocity triangles", "Hydraulic turbines and pumps", "Pump power P = ρgQH"], animated: true,
    presets: [
      { name: "Textbook: 44.1 N·m per newton", note: "R.K. Bansal: D₁ = 200 mm, D₂ = 400 mm, 1200 rpm, vane angles 20° and 30°, radial entry: u₂ = 25.1 m/s, V_w2 = 17.2 m/s, work = V_w2·u₂/g = 44.1 N·m per N (44.1 kN·m per kN).", values: { N: 1200, D2: 400, D1: 200, b2: 20, beta1: 20, beta2: 30 } },
      { name: "Radial vanes (β₂ = 90°)", note: "With radial outlet vanes the whirl equals the blade speed, V_w2 = u₂, and the head is simply u₂²/g.", values: { N: 1450, D2: 300, D1: 150, b2: 20, beta1: 20, beta2: 90 } },
      { name: "Double the speed", note: "At 2400 rpm the same pump gives 4 times the head (H ∝ N²), twice the flow (Q ∝ N) and 8 times the power.", values: { N: 2400, D2: 400, D1: 200, b2: 20, beta1: 20, beta2: 30 } },
    ] },
];
