import type { Lesson } from "./types";

const truthTables: Lesson = {
  intro: "A truth table lists every possible combination of true and false for the variables of a formula and the value the formula takes in each row. It is the most reliable tool in logic: you can prove two formulas equivalent, show a formula is a tautology, or catch a contradiction by pure bookkeeping. Expect to prove a De Morgan law or classify a formula, so learn the connective tables and the row-by-row method.",
  sections: [
    { h: "The connectives", p: ["A statement is a sentence that is either true or false. The connectives build compound statements from simple ones: negation ¬p (not p), conjunction p ∧ q (and), disjunction p ∨ q (or, inclusive), conditional p → q (if p then q) and biconditional p ↔ q (p if and only if q).", "Memorise the cases that fail. p ∧ q is true only when both are true. p ∨ q is false only when both are false. p → q is false only when p is true and q is false (a true promise cannot lead to a false result; a false p makes the conditional true automatically). p ↔ q is true when p and q have the same value."], formula: ["¬p flips the value", "p ∧ q = T only for (T, T)", "p ∨ q = F only for (F, F)", "p → q = F only for (T, F)", "p ↔ q = T when p and q agree"] },
    { h: "Building a table", p: ["With n variables there are 2<sup>n</sup> rows. List the rows in the standard order (TT, TF, FT, FF for two variables) so that none is missed. Then add one column for every sub-formula, working from the inside out, and finish with the column for the whole formula. Showing every intermediate column is what earns the marks."], formula: ["Number of rows = 2^n  (2 variables: 4 rows, 3 variables: 8 rows)", "Add a column per sub-formula, innermost first"] },
    { h: "Tautology, contradiction, contingency, equivalence", p: ["A tautology is true in every row (p ∨ ¬p). A contradiction is false in every row (p ∧ ¬p). A formula that is sometimes true and sometimes false is a contingency.", "Two formulas A and B are logically equivalent, A ≡ B, when their columns are identical, which is the same as saying A ↔ B is a tautology. The laws you should know by heart: De Morgan ¬(p ∨ q) ≡ ¬p ∧ ¬q and ¬(p ∧ q) ≡ ¬p ∨ ¬q; conditional p → q ≡ ¬p ∨ q; contrapositive p → q ≡ ¬q → ¬p; double negation ¬¬p ≡ p."], formula: ["Tautology: all T;  Contradiction: all F", "A ≡ B  if and only if  A ↔ B is a tautology", "p → q ≡ ¬p ∨ q ≡ ¬q → ¬p", "¬(p → q) ≡ p ∧ ¬q"] },
  ],
  examples: [
    { q: "Prove ¬(p ∨ q) ≡ ¬p ∧ ¬q using a complete truth table.", steps: ["Rows (p, q): TT, TF, FT, FF.", "p ∨ q column: T, T, T, F.", "¬(p ∨ q) column: F, F, F, T.", "¬p column: F, F, T, T; ¬q column: F, T, F, T.", "¬p ∧ ¬q column: F, F, F, T.", "The two final columns are identical in all four rows."], ans: "The columns match, so ¬(p ∨ q) ≡ ¬p ∧ ¬q" },
    { q: "Show that (p ∧ (p → q)) → q is a tautology.", steps: ["Rows (p, q): TT, TF, FT, FF.", "p → q: T, F, T, T.", "p ∧ (p → q): T, F, F, F.", "Now (p ∧ (p → q)) → q: row TT: T → T = T; row TF: F → F = T; row FT: F → T = T; row FF: F → F = T."], ans: "All four rows are true, so it is a tautology (modus ponens)" },
    { q: "Classify (p → q) ∧ (p ∧ ¬q).", steps: ["p → q is false only at (T, F).", "p ∧ ¬q is true only at (T, F).", "At (T, F): p → q is F and p ∧ ¬q is T, so the AND is F.", "At every other row p ∧ ¬q is F, so the AND is F."], ans: "False in every row: a contradiction" },
  ],
  mistakes: ["Making the conditional true when p is true and q is false. That is the only row where p → q is false.", "Skipping the intermediate columns and writing only the final column. Marks are given for the working.", "Missing a row, for instance listing only 3 rows for two variables.", "Treating ∨ as exclusive or. In logic p ∨ q is true when both are true.", "Calling a formula a tautology after checking only a couple of rows. Every row must be true."],
  check: [
    { q: "How many rows does the truth table of a formula with 4 variables have?", o: ["8", "12", "16", "4"], a: 2, why: "2 to the power 4 equals 16." },
    { q: "p → q is false exactly when", o: ["p is false and q is true", "p is true and q is false", "both are false", "both are true"], a: 1, why: "A true hypothesis with a false conclusion breaks the implication." },
    { q: "p ∧ ¬p is a", o: ["tautology", "contradiction", "contingency", "equivalence"], a: 1, why: "It is false for both values of p." },
    { q: "Which formula is equivalent to p → q?", o: ["p ∨ ¬q", "¬p ∨ q", "¬p ∧ q", "q → p"], a: 1, why: "A conditional is false only at (T, F), exactly like ¬p ∨ q." },
  ],
};

const normalForms: Lesson = {
  intro: "A normal form is a standard way to write a logical formula, so that two formulas can be compared by looking at them. The principal disjunctive normal form (PDNF) is a sum of full products and the principal conjunctive normal form (PCNF) is a product of full sums. Exam questions give a formula and ask for both. You will learn minterms and maxterms, how to read PDNF and PCNF straight from the truth table, and how to convert one into the other.",
  sections: [
    { h: "Minterms and maxterms", p: ["For n variables, a minterm is a product (AND) in which every variable appears exactly once, either plain or negated. A maxterm is a sum (OR) in which every variable appears exactly once. For p, q: the minterms are p∧q, p∧¬q, ¬p∧q, ¬p∧¬q and the maxterms are p∨q, p∨¬q, ¬p∨q, ¬p∨¬q.", "Each minterm is true in exactly one row: the row where it is built to be true. Each maxterm is false in exactly one row. Number the rows with T as 1 and F as 0 read as a binary number, with the first variable as the highest bit; the minterm for that row is m<sub>i</sub> and the maxterm is M<sub>i</sub>."], formula: ["Minterm m: variable written plain if its value in that row is T, negated if F", "Maxterm M: variable written negated if its value in that row is T, plain if F", "Row of all T has index 2^n − 1;  all F has index 0"] },
    { h: "Reading the normal forms from the truth table", p: ["PDNF: take every row where the formula is TRUE, write its minterm and join them with ∨. PCNF: take every row where the formula is FALSE, write its maxterm and join them with ∧.", "Because each row is either true or false, the indices used by the PDNF and those used by the PCNF are complementary: together they make up all 2<sup>n</sup> rows. If you have one you can write the other by listing the missing indices."], formula: ["PDNF = Σ m(rows where formula is T)  (OR of minterms)", "PCNF = Π M(rows where formula is F)  (AND of maxterms)", "Indices of PDNF and PCNF together = {0, 1, ..., 2^n − 1}"] },
    { h: "Algebraic method and special cases", p: ["Without a table: remove → and ↔, push negations in with De Morgan, distribute to reach a sum of products, then expand each product by multiplying with (x ∨ ¬x) for every missing variable x. A tautology has all minterms and no PCNF terms; a contradiction has no PDNF terms.", "The truth table method is slower for many variables but is less error prone and is the safe choice in an exam."] },
  ],
  examples: [
    { q: "Find the PDNF and PCNF of p → q.", steps: ["Rows (p, q): TT, TF, FT, FF. p → q is T, F, T, T.", "True rows: TT (m3), FT (m1), FF (m0). PDNF = (p ∧ q) ∨ (¬p ∧ q) ∨ (¬p ∧ ¬q).", "False row: TF (index 2). Its maxterm negates the T variable p and keeps the F variable q plain: (¬p ∨ q).", "PCNF = (¬p ∨ q)."], ans: "PDNF = (p∧q) ∨ (¬p∧q) ∨ (¬p∧¬q);  PCNF = ¬p ∨ q" },
    { q: "Obtain the PDNF and PCNF of (p ∧ q) ∨ (¬p ∧ r).", steps: ["Rows (p, q, r) with TTT = index 7 down to FFF = index 0.", "p ∧ q is true for TTT (7) and TTF (6). ¬p ∧ r is true for FTT (3) and FFT (1).", "True indices: 1, 3, 6, 7. PDNF = Σ m(1, 3, 6, 7) = (¬p∧¬q∧r) ∨ (¬p∧q∧r) ∨ (p∧q∧¬r) ∨ (p∧q∧r).", "False indices are the rest: 0, 2, 4, 5. Maxterms: 000 gives (p∨q∨r); 010 gives (p∨¬q∨r); 100 gives (¬p∨q∨r); 101 gives (¬p∨q∨¬r).", "PCNF = (p∨q∨r) ∧ (p∨¬q∨r) ∧ (¬p∨q∨r) ∧ (¬p∨q∨¬r)."], ans: "PDNF = Σ m(1, 3, 6, 7);  PCNF = Π M(0, 2, 4, 5)" },
    { q: "A formula in three variables has PDNF Σ m(0, 2, 5). Write its PCNF indices.", steps: ["There are 2<sup>3</sup> = 8 rows, indices 0 to 7.", "Remove 0, 2 and 5 from the full set.", "What remains is 1, 3, 4, 6, 7."], ans: "PCNF = Π M(1, 3, 4, 6, 7)" },
  ],
  mistakes: ["Using the minterm rule for a maxterm. In a maxterm the variable is negated where the row value is T.", "Writing the PDNF from the false rows (and the PCNF from the true rows). It is the other way round.", "Writing a term without all the variables. A principal form must contain every variable in every term.", "Joining minterms with ∧ or maxterms with ∨. PDNF is an OR of ANDs; PCNF is an AND of ORs.", "Getting the row index wrong by reading T as 0. T is 1 and the first variable is the most significant bit."],
  check: [
    { q: "The PDNF is built from the rows in which the formula is", o: ["true", "false", "both", "undefined"], a: 0, why: "A sum of minterms, one for each true row." },
    { q: "PDNF of a three-variable formula is Σ m(1, 4). Its PCNF has how many maxterms?", o: ["2", "4", "6", "8"], a: 2, why: "8 rows minus 2 true rows leaves 6 false rows." },
    { q: "The maxterm for the row (p, q) = (T, F) is", o: ["p ∨ ¬q", "¬p ∨ q", "p ∧ ¬q", "¬p ∧ q"], a: 1, why: "Variables with value T are negated and those with F stay plain in a maxterm." },
    { q: "A contradiction has", o: ["a PDNF with all minterms", "no minterms in its PDNF", "no maxterms in its PCNF", "equal PDNF and PCNF"], a: 1, why: "It is never true, so there are no true rows." },
  ],
};

const relations: Lesson = {
  intro: "A relation from a set A to a set B is a set of ordered pairs, and the exam asks you to test the properties of a given relation: reflexive, symmetric, antisymmetric and transitive. Passing the test for the right combination makes the relation an equivalence relation or a partial order. You will learn each definition as a check you can run on the pairs, the two named relations, and how an equivalence relation splits a set into classes.",
  sections: [
    { h: "Relations and how to test them", p: ["A relation R on a set A is any subset of A × A. If (a, b) is in R we write a R b. You will normally be given R as a list of pairs, so you test each property by scanning the list.", "Reflexive: (a, a) is in R for EVERY element a of A. Symmetric: whenever (a, b) is in R, so is (b, a). Antisymmetric: if both (a, b) and (b, a) are in R then a = b (so no two different elements are related both ways). Transitive: whenever (a, b) and (b, c) are in R, then (a, c) is in R."], formula: ["Reflexive:  for all a,  (a, a) ∈ R", "Symmetric:  (a, b) ∈ R  implies  (b, a) ∈ R", "Antisymmetric:  (a, b) ∈ R and (b, a) ∈ R  implies  a = b", "Transitive:  (a, b) ∈ R and (b, c) ∈ R  implies  (a, c) ∈ R"] },
    { h: "Two relations that matter", p: ["An equivalence relation is reflexive, symmetric and transitive. It behaves like equality: congruence modulo n, same remainder, same size, same birthday are all examples. A partial order is reflexive, antisymmetric and transitive: ≤ on numbers, divisibility on positive integers and subset ⊆ on sets are examples.", "Symmetric and antisymmetric are not opposites. A relation like {(1,1), (2,2)} is both, and one like {(1,2), (2,1), (2,3)} can be neither. Always test both separately."], formula: ["Equivalence relation = Reflexive + Symmetric + Transitive", "Partial order = Reflexive + Antisymmetric + Transitive", "Reflexive relations on an n-element set: 2^(n² − n)"] },
    { h: "Equivalence classes and partitions", p: ["For an equivalence relation, the equivalence class of a is the set of all elements related to a. Two classes are either identical or disjoint, and together they cover the set. So an equivalence relation on A is the same thing as a partition of A into non-empty disjoint blocks, and each partition defines an equivalence relation 'in the same block'.", "For congruence modulo 3 on the integers, there are exactly three classes: the multiples of 3, the numbers leaving remainder 1, and the numbers leaving remainder 2."], formula: ["[a] = { x : x R a }", "Classes are disjoint and their union is A", "Number of classes of congruence mod n = n"] },
  ],
  examples: [
    { q: "Let A = {a, b, c} and R = {(a,a), (a,b), (b,c), (c,c), (b,b), (a,c)}. Find which properties R has.", steps: ["Reflexive: (a,a), (b,b), (c,c) are all present. Yes.", "Symmetric: (a,b) is present but (b,a) is not. No.", "Antisymmetric: no pair of different elements appears both ways. Yes.", "Transitive: (a,b),(b,c) give (a,c) present; (a,c),(c,c) give (a,c); (b,b),(b,c) give (b,c); (a,a),(a,b) give (a,b). Yes.", "It is reflexive, antisymmetric and transitive."], ans: "Reflexive, antisymmetric, transitive: a partial order, not an equivalence relation" },
    { q: "Show that R = {(x, y) : x − y is divisible by 3} on the integers is an equivalence relation and describe the classes.", steps: ["Reflexive: x − x = 0 is divisible by 3.", "Symmetric: if 3 divides x − y then it divides y − x = −(x − y).", "Transitive: if 3 divides x − y and y − z then it divides their sum x − z.", "x R y means x and y leave the same remainder when divided by 3, so the classes are remainders 0, 1 and 2."], ans: "Equivalence relation with 3 classes: [0], [1], [2]" },
    { q: "On A = {1, 2, 3} the relation R = {(1,1), (2,2), (1,2), (2,1)} is given. Is it an equivalence relation?", steps: ["Reflexive needs (3,3), which is missing. So R is not reflexive.", "It is symmetric, since (1,2) and (2,1) are both present.", "It is transitive.", "One property fails, so it is not an equivalence relation. Adding (3,3) would fix it."], ans: "Not an equivalence relation (not reflexive); R ∪ {(3,3)} is one" },
  ],
  mistakes: ["Checking reflexivity only for the elements that appear in R. Every element of the set A must have its loop (a, a).", "Declaring a relation antisymmetric because it is not symmetric. Check the definition, they are independent.", "Missing a transitivity case with a loop such as (a,a),(a,b). Write down every chain.", "Calling ≤ an equivalence relation. It is a partial order since it is not symmetric.", "Forgetting that a partition's blocks must be non-empty, disjoint and cover the whole set."],
  check: [
    { q: "Which property set defines an equivalence relation?", o: ["reflexive, antisymmetric, transitive", "reflexive, symmetric, transitive", "symmetric, antisymmetric, transitive", "reflexive, symmetric, antisymmetric"], a: 1, why: "That is the definition; the first option is a partial order." },
    { q: "Divisibility on the positive integers is", o: ["an equivalence relation", "a partial order", "symmetric", "neither reflexive nor transitive"], a: 1, why: "It is reflexive, antisymmetric and transitive." },
    { q: "An equivalence relation on a set gives", o: ["a lattice", "a partition into classes", "a total order", "a function"], a: 1, why: "Equivalence classes are disjoint and cover the set." },
    { q: "How many reflexive relations are there on a 3-element set?", o: ["8", "64", "512", "6"], a: 1, why: "2^(n² − n) = 2^(9 − 3) = 2^6 = 64." },
  ],
};

const hasse: Lesson = {
  intro: "A Hasse diagram is the picture of a partial order with all unnecessary lines removed. It is a standard 5 to 8 mark question, usually for divisibility on a set of numbers, followed by the maximal and minimal elements, upper bounds and whether the poset is a lattice. You will learn the drawing rules, the vocabulary and the covering test that stops you drawing too many lines.",
  sections: [
    { h: "Posets and the covering relation", p: ["A partially ordered set (poset) is a set with a partial order ≤ (reflexive, antisymmetric, transitive). For divisibility, a ≤ b means a divides b. Not every two elements need to be comparable: 2 and 3 do not divide each other.", "b covers a if a is below b and there is no element c with a below c and c below b. The Hasse diagram draws a line only for covering pairs. The rules: put smaller elements lower; draw no loops (reflexivity is understood); draw no line that is implied by transitivity; draw no arrows (upward is the direction)."], formula: ["b covers a  if  a ≤ b, a ≠ b and no c with a ≤ c ≤ b, c ≠ a, b", "Draw an edge only for each covering pair, with b above a"] },
    { h: "Vocabulary", p: ["Maximal element: nothing above it. Minimal element: nothing below it. Greatest element: above every element (it is unique if it exists). Least element: below every element. Upper bound of a subset: an element above all of them; the least upper bound (lub or join) is the lowest of these. Lower bound and greatest lower bound (glb or meet) are the mirror images.", "A chain is a subset in which any two elements are comparable. An antichain is a subset in which no two are comparable. A poset is a lattice if every pair of elements has both a lub and a glb. A divisibility poset is a lattice, with lub = LCM and glb = GCD when the set is closed under them."], formula: ["lub(a, b) = LCM(a, b),  glb(a, b) = GCD(a, b)  (for divisibility)", "Maximal/minimal: look at the top/bottom of the diagram", "Greatest/least exist only if one element is above/below all others"] },
    { h: "Drawing method that does not fail", p: ["Step 1: list the elements. Step 2: find the minimal elements and put them on the bottom row. Step 3: for each other element, find the elements it covers (the largest elements below it) and connect. Step 4: place each element one level above the highest element it covers. Step 5: check that you never drew a line between a and c when a path a to b to c exists."] },
  ],
  examples: [
    { q: "Construct the Hasse diagram of (A, |) for A = {1, 2, 3, 4, 8, 16, 28, 32, 64} and list its maximal and minimal elements.", steps: ["Powers of 2 form a chain: 1 | 2 | 4 | 8 | 16 | 32 | 64. Covering pairs: 1-2, 2-4, 4-8, 8-16, 16-32, 32-64.", "3 divides no other element and is divisible only by 1, so it covers 1. Edge 1-3.", "28 = 4 × 7. Elements dividing 28 in A are 1, 2, 4, so the highest is 4: 28 covers 4. Edge 4-28 (no 2-28 or 1-28, those follow by transitivity).", "Nothing above 64, 28 or 3, so they are maximal. Only 1 has nothing below."], ans: "Edges: 1-2, 1-3, 2-4, 4-8, 4-28, 8-16, 16-32, 32-64. Maximal: 3, 28, 64. Minimal (and least): 1. No greatest element." },
    { q: "Draw the Hasse diagram of divisors of 12 and decide if it is a lattice.", steps: ["Elements {1, 2, 3, 4, 6, 12}.", "Covering pairs: 1-2, 1-3, 2-4, 2-6, 3-6, 4-12, 6-12.", "Least = 1, greatest = 12.", "Check pairs: lub(4, 6) = LCM = 12 and glb(4, 6) = GCD = 2; lub(2, 3) = 6 and glb(2, 3) = 1. All pairs have both."], ans: "Edges as listed; it is a lattice with least 1 and greatest 12" },
    { q: "For the poset in the previous example, find the upper bounds and lub of {2, 3}.", steps: ["Upper bounds must be divisible by both 2 and 3: 6 and 12.", "The lowest of these is 6, since 6 divides 12."], ans: "Upper bounds 6 and 12; lub = 6" },
  ],
  mistakes: ["Drawing a line from 1 to 4 as well as 1-2 and 2-4. That edge is implied by transitivity.", "Drawing arrows or self loops. Hasse diagrams have neither.", "Calling an element 'greatest' when it is only maximal. Greatest must be above all elements.", "Placing 3 above 2 or on a line with it. Incomparable elements have no line between them.", "Assuming every poset is a lattice. Check that every pair has both a lub and a glb."],
  check: [
    { q: "In a Hasse diagram the edge a-c is omitted if", o: ["a and c are equal", "there is b with a ≤ b ≤ c", "c is maximal", "a is minimal"], a: 1, why: "Then c does not cover a; the relation follows by transitivity." },
    { q: "In (divisors of 30, |), lub(6, 10) is", o: ["2", "30", "15", "60"], a: 1, why: "LCM(6, 10) = 30." },
    { q: "A poset with a unique maximal element always has", o: ["a greatest element in a finite poset", "no minimal element", "a chain structure", "no lattice"], a: 0, why: "In a finite poset a unique maximal element is above everything, so it is greatest." },
    { q: "In the divisibility poset of A = {2, 3, 4, 6}, the minimal elements are", o: ["2 and 3", "4 and 6", "only 2", "only 6"], a: 0, why: "Nothing in A divides 2 or 3 (1 is not in the set)." },
  ],
};

const functions: Lesson = {
  intro: "A function sends each element of one set to exactly one element of another, and the questions ask you to decide whether it is one-to-one, onto or both. The three words, injective, surjective and bijective, decide whether a function can be reversed. You will learn the definitions as tests, how to prove or disprove each with a counter-example, and how to compose functions and find an inverse.",
  sections: [
    { h: "Function, domain, codomain, range", p: ["A function f: A → B assigns to every element x of A exactly one element f(x) of B. A is the domain, B is the codomain, and the set of values f actually takes is the range, which is a subset of B.", "Every input has one output, but different inputs may share an output. Whether that sharing is allowed, and whether every element of B is used, give the three types."] },
    { h: "Injective, surjective, bijective", p: ["Injective (one-to-one): different inputs give different outputs. To prove it, assume f(x<sub>1</sub>) = f(x<sub>2</sub>) and show x<sub>1</sub> = x<sub>2</sub>. To disprove, give two different inputs with the same output.", "Surjective (onto): every element of the codomain is hit. To prove it, take any y in B and solve y = f(x) for x, checking that x lies in the domain. To disprove, give a y that is never reached.", "Bijective: both injective and surjective. Only bijective functions have an inverse function."], formula: ["Injective:  f(x₁) = f(x₂)  implies  x₁ = x₂", "Surjective:  for every y in B there is x in A with f(x) = y", "Bijective = injective + surjective", "|A| = m, |B| = n:  all functions n^m;  injective n!/(n − m)!;  bijective n! (when m = n)"] },
    { h: "Composition and inverse", p: ["The composition g∘f means: apply f first, then g, so (g∘f)(x) = g(f(x)). It is defined when the range of f lies in the domain of g. Composition is associative but usually not commutative. If f and g are both injective, so is g∘f; if both surjective, so is g∘f.", "The inverse f<sup>−1</sup> exists only when f is bijective. To find it, write y = f(x), solve for x in terms of y, and then rename. It satisfies f<sup>−1</sup>(f(x)) = x and f(f<sup>−1</sup>(y)) = y."], formula: ["(g∘f)(x) = g(f(x))", "(g∘f)⁻¹ = f⁻¹ ∘ g⁻¹", "y = f(x)  gives  x = f⁻¹(y)"] },
  ],
  examples: [
    { q: "Determine whether f: R → R, f(x) = 2x + 3 is injective, surjective, bijective. Find f<sup>−1</sup>.", steps: ["Injective: f(x₁) = f(x₂) gives 2x₁ + 3 = 2x₂ + 3, so x₁ = x₂.", "Surjective: for any real y, solve y = 2x + 3 to get x = (y − 3)/2, a real number in the domain.", "Both hold, so f is bijective.", "Inverse: x = (y − 3)/2, so f<sup>−1</sup>(x) = (x − 3)/2."], ans: "Bijective; f⁻¹(x) = (x − 3)/2" },
    { q: "Show that f: R → R, f(x) = x² is neither injective nor surjective. Which restriction makes it bijective?", steps: ["Not injective: f(2) = 4 = f(−2) although 2 ≠ −2.", "Not surjective: y = −1 would need x² = −1, which has no real solution.", "Restrict both the domain and the codomain to [0, ∞): then each non-negative y has exactly one non-negative square root."], ans: "Neither; f: [0, ∞) → [0, ∞) is bijective" },
    { q: "Let f(x) = x + 2 and g(x) = x² on R. Find g∘f and f∘g and compare.", steps: ["(g∘f)(x) = g(f(x)) = g(x + 2) = (x + 2)².", "(f∘g)(x) = f(g(x)) = f(x²) = x² + 2.", "At x = 1: (g∘f)(1) = 9 but (f∘g)(1) = 3."], ans: "g∘f = (x + 2)², f∘g = x² + 2; composition is not commutative" },
  ],
  mistakes: ["Disproving injectivity by showing the function is not onto. The two tests are independent.", "Forgetting the codomain: the same formula can be onto for one codomain and not for another.", "Reading g∘f as 'g first'. It means f is applied first.", "Taking an inverse of a function that is not bijective, for example f(x) = x² on R.", "Computing the inverse of g∘f as g⁻¹∘f⁻¹. The order reverses: f⁻¹∘g⁻¹."],
  check: [
    { q: "A function is injective when", o: ["every output is used", "different inputs give different outputs", "it has an inverse", "domain equals codomain"], a: 1, why: "That is the definition of one-to-one." },
    { q: "How many bijections exist from a 4-element set to a 4-element set?", o: ["4", "16", "24", "256"], a: 2, why: "4! = 24." },
    { q: "For f(x) = x + 2 and g(x) = 3x, (g∘f)(1) =", o: ["5", "9", "3", "11"], a: 1, why: "f(1) = 3, then g(3) = 9." },
    { q: "f: R → R, f(x) = x³ is", o: ["injective only", "surjective only", "bijective", "neither"], a: 2, why: "Every real has exactly one real cube root." },
  ],
};

const groups: Lesson = {
  intro: "A group is the basic structure of algebra: a set with one operation that can always be undone. Group questions are typically proofs that a given set under a given operation is a group or a subgroup, so the skill is to run the four axioms and the subgroup test without missing a step. You will learn the axioms, the one-step subgroup test, Lagrange's theorem and two full worked proofs.",
  sections: [
    { h: "Algebraic structures in a ladder", p: ["An algebraic system (G, *) is a non-empty set with a binary operation. Adding properties builds up a ladder. A semigroup is closed and associative. A monoid is a semigroup with an identity. A group is a monoid in which every element has an inverse. An abelian group is a group whose operation is also commutative."], formula: ["Semigroup: closure + associativity", "Monoid: semigroup + identity", "Group: monoid + inverses", "Abelian group: group + commutativity"] },
    { h: "The four axioms", p: ["Closure: a * b is in G for all a, b in G. Associativity: (a * b) * c = a * (b * c). Identity: there is e in G with a * e = e * a = a for all a. Inverse: for every a there is a⁻¹ in G with a * a⁻¹ = a⁻¹ * e = e.", "To show it is a group you must verify all four, in order, writing down the identity and the inverse explicitly. To show it is not a group, one failure with a concrete example is enough."], formula: ["a * b ∈ G", "(a * b) * c = a * (b * c)", "a * e = e * a = a", "a * a⁻¹ = a⁻¹ * a = e"] },
    { h: "Subgroups and Lagrange's theorem", p: ["A subset H of a group G is a subgroup if it is itself a group under the same operation. The shortcut test: H is non-empty and for all a, b in H, a * b⁻¹ is in H. For a finite subset it is enough to show closure and non-empty (inverses then follow).", "Lagrange's theorem: for a finite group G, the order (number of elements) of every subgroup H divides the order of G. So a group of order 6 can only have subgroups of order 1, 2, 3 or 6. It does not say every divisor occurs. The group (Z<sub>n</sub>, +<sub>n</sub>) is cyclic, generated by 1."], formula: ["Subgroup test: H ≠ empty and a, b ∈ H  implies  a * b⁻¹ ∈ H", "Lagrange: |H| divides |G|", "(Z<sub>n</sub>, +<sub>n</sub>): identity 0, inverse of a is n − a"] },
  ],
  examples: [
    { q: "Prove that H = {0, 2, 4} is a subgroup of the cyclic group (Z<sub>6</sub>, +<sub>6</sub>).", steps: ["H is non-empty and a subset of Z<sub>6</sub> = {0, 1, 2, 3, 4, 5}.", "Closure table mod 6: 2 + 2 = 4, 2 + 4 = 6 ≡ 0, 4 + 4 = 8 ≡ 2, and sums with 0 are unchanged. All results lie in H.", "Identity 0 is in H.", "Inverses: 2 + 4 ≡ 0 so 2⁻¹ = 4 and 4⁻¹ = 2; 0⁻¹ = 0. Both are in H.", "Check with Lagrange: |H| = 3 divides |G| = 6."], ans: "H is closed with identity and inverses, so it is a subgroup of order 3" },
    { q: "Let G = R − {0} and a * b = ab/2. Show that (G, *) is an abelian group.", steps: ["Closure: a, b non-zero gives ab/2 non-zero.", "Associativity: (a * b) * c = (ab/2)c/2 = abc/4 and a * (b * c) = a(bc/2)/2 = abc/4.", "Identity: a * e = ae/2 = a gives e = 2, and 2 is in G.", "Inverse: a * a′ = aa′/2 = 2 gives a′ = 4/a, which is non-zero.", "Commutative: a * b = ab/2 = ba/2 = b * a."], ans: "All axioms hold with e = 2 and inverse 4/a; it is an abelian group" },
    { q: "Is (N, +), the natural numbers 1, 2, 3, ... under addition, a group?", steps: ["Closure holds and addition is associative.", "Identity would be 0, which is not in N.", "Without an identity there can be no inverses, so the set is a semigroup only."], ans: "No: it is a semigroup (no identity)" },
  ],
  mistakes: ["Proving only closure and associativity and calling it a group. The identity and inverse must be shown.", "Assuming the identity is always 0 or 1. Solve a * e = a for the given operation, as in the e = 2 example.", "Forgetting to check that the inverse lies inside the set (for example 4/a is non-zero).", "Using the subgroup test on an empty set. H must be non-empty.", "Reading Lagrange's theorem backwards: a divisor of |G| need not be the order of a subgroup in every group."],
  check: [
    { q: "A group differs from a monoid in that every element has", o: ["an identity", "an inverse", "a square", "a commutative partner"], a: 1, why: "A monoid has an identity; a group also has inverses." },
    { q: "The inverse of 4 in (Z<sub>6</sub>, +<sub>6</sub>) is", o: ["2", "4", "0", "1"], a: 0, why: "4 + 2 = 6 ≡ 0." },
    { q: "By Lagrange's theorem, which cannot be the order of a subgroup of a group of order 10?", o: ["2", "5", "4", "10"], a: 2, why: "4 does not divide 10." },
    { q: "(Z, −) integers under subtraction is not a group because", o: ["it is not closed", "it is not associative", "it has no inverses", "it is not commutative only"], a: 1, why: "(5 − 3) − 1 = 1 but 5 − (3 − 1) = 3." },
  ],
};

const combinations: Lesson = {
  intro: "A combination is a way to choose objects when the order does not matter. Most counting questions in the exam turn on one decision: does order matter? If not, you use nCr. This lesson covers the formula, the symmetry rule, restricted selections with conditions, handshake and committee problems, and the stars and bars method for counting solutions of an equation.",
  sections: [
    { h: "Choosing without order", p: ["Choosing r objects from n distinct objects, order ignored, can be done in nCr ways. Each unordered choice corresponds to r! orderings, so nCr = nPr / r! = n! / (r! (n − r)!).", "Choosing r objects to take is the same as choosing n − r to leave, so nCr = nC(n − r). Use this to shorten the work: 50C48 is 50C2. Pascal's rule nCr + nC(r − 1) = (n + 1)Cr builds the triangle of binomial coefficients."], formula: ["nCr = n! / (r! (n − r)!)", "nCr = nC(n − r);  nC0 = nCn = 1", "nCr + nC(r − 1) = (n + 1)Cr", "Number of subsets of an n-set = 2^n"] },
    { h: "Conditions and restricted selections", p: ["Combine independent choices by the product rule: choose 2 from group A AND 3 from group B gives ACa × BCb. Alternatives (OR) add. 'At least one' is easiest by complement: total minus the cases with none. If two particular people must be together, treat them as already chosen; if two must not be together, subtract the cases where they are both chosen."], formula: ["Group A and group B:  ACa × BCb", "At least one = total − none", "Particular k included:  (n − k)C(r − k);  particular k excluded:  (n − k)Cr"] },
    { h: "Handshakes and stars and bars", p: ["If everyone in a group of n shakes hands exactly once with every other person, the number of handshakes is the number of pairs: nC2 = n(n − 1)/2. If two separate groups shake hands only across the groups, it is a product, m × n.", "To count non-negative integer solutions of x<sub>1</sub> + x<sub>2</sub> + ... + x<sub>k</sub> = n, picture n identical stars to be divided by k − 1 bars into k boxes. There are n + k − 1 positions and we choose where the k − 1 bars go. If every x must be at least 1, first give each a 1 and distribute the rest."], formula: ["Handshakes among n people = nC2 = n(n − 1)/2", "Non-negative solutions of x₁ + ... + x_k = n:  C(n + k − 1, k − 1)", "Positive solutions (each ≥ 1):  C(n − 1, k − 1)"] },
  ],
  examples: [
    { q: "Find the number of non-negative integer solutions to x₁ + x₂ + x₃ = 20 using stars and bars.", steps: ["n = 20 stars, k = 3 boxes, so k − 1 = 2 bars.", "Total positions = 20 + 2 = 22; choose 2 for the bars.", "C(22, 2) = 22 × 21 / 2 = 231."], ans: "231 solutions" },
    { q: "There are 35 students and 4 teachers. How many handshakes occur if everyone shakes hands once with everyone else? How many if only students shake hands with teachers?", steps: ["Everyone with everyone: 39 people, so 39C2 = 39 × 38 / 2 = 741.", "Only students with teachers: each of the 35 students meets each of the 4 teachers, so 35 × 4 = 140."], ans: "741 handshakes; 140 if only across the two groups" },
    { q: "A committee of 5 is chosen from 6 men and 4 women with at least 2 women. In how many ways?", steps: ["Total ways = 10C5 = 252.", "Subtract fewer than 2 women. 0 women: 6C5 = 6. 1 woman: 4C1 × 6C4 = 4 × 15 = 60.", "252 − 6 − 60 = 186. Check by direct count: 2 women 4C2 × 6C3 = 120, 3 women 4C3 × 6C2 = 60, 4 women 4C4 × 6C1 = 6, total 186."], ans: "186 ways" },
  ],
  mistakes: ["Using nPr when the order does not matter, and so overcounting by r!.", "Adding instead of multiplying for 'and' choices from separate groups.", "Using n − 1 choose k − 1 for non-negative solutions. That formula is for positive solutions.", "Double counting in 'at least' problems by choosing the required items first and then the rest freely. Use the complement.", "Treating handshakes as ordered pairs (n(n − 1)) instead of unordered pairs."],
  check: [
    { q: "The value of 8C3 is", o: ["24", "56", "336", "40320"], a: 1, why: "8 × 7 × 6 / 6 = 56." },
    { q: "Handshakes among 10 people if each pair shakes hands once", o: ["90", "45", "100", "20"], a: 1, why: "10C2 = 45." },
    { q: "Non-negative solutions of x + y + z = 5", o: ["10", "21", "15", "35"], a: 1, why: "C(5 + 2, 2) = C(7, 2) = 21." },
    { q: "nCr equals", o: ["nC(r + 1)", "nC(n − r)", "(n − r)Cr", "rCn"], a: 1, why: "Choosing r to take is the same as choosing n − r to leave." },
  ],
};

const multinomial: Lesson = {
  intro: "The binomial theorem expands (x + y) to a power, and the multinomial theorem does the same for three or more terms. The exam asks for the coefficient of a particular term, which is a counting formula with factorials, and often with numbers other than 1 in front of the variables. You will learn the coefficient formula, the number of terms, and the trick for coefficients that carry their own multipliers.",
  sections: [
    { h: "The binomial theorem", p: ["Expanding (x + y)<sup>n</sup> picks x or y from each of n brackets. The term with y chosen k times and x chosen n − k times can be formed in nCk ways, so the coefficient is nCk. The general term is T<sub>k+1</sub> = nCk x<sup>n−k</sup> y<sup>k</sup>. The coefficients add up to 2<sup>n</sup> and the expansion has n + 1 terms."], formula: ["(x + y)^n = sum over k of nCk x^(n−k) y^k", "General term T(k+1) = nCk x^(n−k) y^k", "Sum of coefficients = 2^n"] },
    { h: "The multinomial theorem", p: ["For (x<sub>1</sub> + x<sub>2</sub> + ... + x<sub>m</sub>)<sup>n</sup>, choose which brackets give which variable. The number of ways to get x<sub>1</sub> exactly a<sub>1</sub> times, x<sub>2</sub> exactly a<sub>2</sub> times and so on (with a<sub>1</sub> + ... + a<sub>m</sub> = n) is the multinomial coefficient n! / (a<sub>1</sub>! a<sub>2</sub>! ... a<sub>m</sub>!).", "The number of different terms in the expansion equals the number of non-negative solutions of a<sub>1</sub> + ... + a<sub>m</sub> = n, which is C(n + m − 1, m − 1) by stars and bars."], formula: ["Coefficient of x₁^a₁ x₂^a₂ ... x_m^a_m  is  n! / (a₁! a₂! ... a_m!)", "Number of terms = C(n + m − 1, m − 1)", "Sum of all coefficients: put every variable equal to 1"] },
    { h: "When the terms carry coefficients", p: ["If the expression is (x − 2y + 3z)<sup>7</sup>, treat −2y and 3z as the terms. The coefficient of x<sup>a</sup> y<sup>b</sup> z<sup>c</sup> is the multinomial coefficient multiplied by (1)<sup>a</sup> (−2)<sup>b</sup> (3)<sup>c</sup>. Keep the sign: an odd power of a negative number is negative.", "The same factorial formula counts rearrangements of a word with repeated letters. MISSISSIPPI has 11 letters with I four times, S four times, P twice, so the arrangements number 11! / (4! 4! 2!)."], formula: ["Coefficient = n!/(a!b!c!) × (c₁)^a × (c₂)^b × (c₃)^c", "Arrangements of n objects with repeats = n! / (n₁! n₂! ...)"] },
  ],
  examples: [
    { q: "Find the coefficient of x²y³z² in the expansion of (x − 2y + 3z)<sup>7</sup>.", steps: ["The exponents add up: 2 + 3 + 2 = 7, so the term exists.", "Multinomial coefficient: 7! / (2! 3! 2!) = 5040 / 24 = 210.", "Multiply by the factors: (1)² × (−2)³ × (3)² = −8 × 9 = −72.", "210 × (−72) = −15120."], ans: "−15120" },
    { q: "Find the coefficient of x<sup>5</sup> in the expansion of (x + 2)<sup>8</sup> and the sum of all its coefficients.", steps: ["x⁵ means the 2 is chosen k = 3 times, so the term is 8C3 x⁵ 2³.", "8C3 = 56 and 2³ = 8, so the coefficient is 448.", "Put x = 1: (1 + 2)⁸ = 3⁸ = 6561."], ans: "448; sum of coefficients = 6561" },
    { q: "How many distinct terms are in (x + y + z)<sup>7</sup> and how many arrangements does the word MISSISSIPPI have?", steps: ["Terms: non-negative solutions of a + b + c = 7: C(7 + 2, 2) = C(9, 2) = 36.", "MISSISSIPPI: 11 letters, I × 4, S × 4, P × 2, M × 1.", "11! / (4! 4! 2! 1!) = 39916800 / 1152 = 34650."], ans: "36 terms; 34650 arrangements" },
  ],
  mistakes: ["Forgetting the numeric factors in the terms. The coefficient of (x − 2y + 3z) terms must include (−2)ᵇ and 3ᶜ.", "Dropping the sign when the power of the negative term is odd.", "Choosing exponents that do not add up to the total power n; then the term does not exist (coefficient 0).", "Using nCk when there are three or more different terms. Use the factorial formula with all exponents.", "Confusing the number of terms C(n + m − 1, m − 1) with the sum of the coefficients."],
  check: [
    { q: "The coefficient of x²y²z in the plain expansion of (x + y + z)<sup>5</sup> is", o: ["30", "60", "120", "10"], a: 0, why: "5! / (2! 2! 1!) = 120 / 4 = 30." },
    { q: "The number of terms in (a + b + c + d)<sup>3</sup> is", o: ["4", "16", "20", "64"], a: 2, why: "C(3 + 3, 3) = 20." },
    { q: "The sum of the coefficients of (2x + 3y)<sup>4</sup> is", o: ["16", "81", "625", "256"], a: 2, why: "Put x = y = 1: 5⁴ = 625." },
    { q: "Arrangements of the letters of BANANA", o: ["720", "60", "120", "30"], a: 1, why: "6! / (3! 2!) = 720 / 12 = 60." },
  ],
};

const euclid: Lesson = {
  intro: "The Euclidean algorithm finds the greatest common divisor of two integers using only division with remainder, and the extended version also finds integers x and y with ax + by = gcd. This is the engine behind modular inverses and linear congruences, and exam questions ask you to carry out the back-substitution neatly. You will learn the division algorithm, the repeated-division table, the back-substitution method and how to get an inverse from it.",
  sections: [
    { h: "Division algorithm and gcd", p: ["For integers a and b with b greater than 0 there are unique integers q (quotient) and r (remainder) with a = bq + r and 0 ≤ r less than b. The key fact: gcd(a, b) = gcd(b, r), because any common divisor of a and b also divides r = a − bq and vice versa.", "The gcd is the largest integer dividing both. Two numbers are coprime when gcd = 1. The LCM follows from the gcd: gcd(a, b) × lcm(a, b) = a × b."], formula: ["a = bq + r,  0 ≤ r < b", "gcd(a, b) = gcd(b, r)", "gcd(a, b) × lcm(a, b) = a × b"] },
    { h: "The Euclidean algorithm", p: ["Divide a by b to get remainder r<sub>1</sub>. Divide b by r<sub>1</sub> to get r<sub>2</sub>. Keep dividing the last divisor by the last remainder. The last non-zero remainder is the gcd. The remainders strictly decrease, so it always stops, in a number of steps proportional to the number of digits."], formula: ["gcd(512, 320):  512 = 1 × 320 + 192", "320 = 1 × 192 + 128;   192 = 1 × 128 + 64;   128 = 2 × 64 + 0", "Last non-zero remainder 64, so gcd = 64"] },
    { h: "Extended Euclidean algorithm", p: ["Bézout's identity says gcd(a, b) = ax + by for some integers x and y. To find them, write each remainder as a combination of the two original numbers by working backwards through the table: start from the line that gave the gcd and substitute each earlier remainder in turn.", "A very useful consequence: if gcd(a, m) = 1 then ax + my = 1, so ax ≡ 1 (mod m) and x is the multiplicative inverse of a modulo m. This is how you solve ax ≡ b (mod m)."], formula: ["gcd(a, b) = a x + b y   (Bézout)", "If gcd(a, m) = 1:  a x ≡ 1 (mod m),  so x = a⁻¹ mod m", "x and y are not unique; adding b/g to x and subtracting a/g from y gives another pair"] },
  ],
  examples: [
    { q: "Using the Extended Euclidean Algorithm, calculate gcd(512, 320) and find integers x and y with 512x + 320y = gcd.", steps: ["Forward: 512 = 1·320 + 192;  320 = 1·192 + 128;  192 = 1·128 + 64;  128 = 2·64.  gcd = 64.", "Back: 64 = 192 − 1·128.", "Replace 128 = 320 − 192: 64 = 192 − (320 − 192) = 2·192 − 320.", "Replace 192 = 512 − 320: 64 = 2(512 − 320) − 320 = 2·512 − 3·320.", "Check: 1024 − 960 = 64."], ans: "gcd = 64 with x = 2, y = −3" },
    { q: "Find the multiplicative inverse of 7 modulo 40.", steps: ["40 = 5·7 + 5;  7 = 1·5 + 2;  5 = 2·2 + 1.  gcd = 1, so an inverse exists.", "1 = 5 − 2·2 = 5 − 2(7 − 5) = 3·5 − 2·7.", "5 = 40 − 5·7, so 1 = 3(40 − 5·7) − 2·7 = 3·40 − 17·7.", "So 7·(−17) ≡ 1 (mod 40); −17 + 40 = 23.", "Check: 7 × 23 = 161 = 4 × 40 + 1."], ans: "7⁻¹ ≡ 23 (mod 40)" },
    { q: "Find gcd(240, 46) and write it as 240x + 46y. Also find lcm(240, 46).", steps: ["240 = 5·46 + 10;  46 = 4·10 + 6;  10 = 1·6 + 4;  6 = 1·4 + 2;  4 = 2·2.  gcd = 2.", "2 = 6 − 4 = 6 − (10 − 6) = 2·6 − 10.", "6 = 46 − 4·10: 2 = 2·46 − 9·10.", "10 = 240 − 5·46: 2 = 47·46 − 9·240.", "lcm = 240 × 46 / 2 = 5520."], ans: "gcd = 2 = −9·240 + 47·46; lcm = 5520" },
  ],
  mistakes: ["Stopping when the remainder is 0 and giving 0 as the gcd. The gcd is the previous remainder.", "Making an arithmetic slip in back-substitution. Always verify with ax + by at the end.", "Substituting a quotient instead of a remainder in the back-substitution.", "Expecting x and y to be positive or unique. Negative values and other pairs are fine.", "Trying to find an inverse when gcd is not 1. It does not exist."],
  check: [
    { q: "gcd(48, 18) is", o: ["3", "6", "9", "12"], a: 1, why: "48 = 2·18 + 12, 18 = 1·12 + 6, 12 = 2·6, so 6." },
    { q: "If gcd(a, b) = 1 then lcm(a, b) is", o: ["a + b", "a − b", "a b", "1"], a: 2, why: "gcd × lcm = a b." },
    { q: "Bézout's identity states that gcd(a, b) can be written as", o: ["a x + b y with integers x, y", "a / b", "a mod b", "a x y b"], a: 0, why: "It is an integer linear combination of a and b." },
    { q: "The inverse of 3 modulo 7 is", o: ["2", "4", "5", "6"], a: 2, why: "3 × 5 = 15 ≡ 1 (mod 7)." },
  ],
};

const congruence: Lesson = {
  intro: "A linear congruence ax ≡ b (mod m) is an equation in modular arithmetic, and solving it is the use for the Euclidean algorithm. The exam asks you to decide whether a solution exists, to find all solutions in the range, and sometimes to use Fermat's little theorem. You will learn the existence test, the inverse method, what to do when gcd is bigger than 1, and Fermat's theorem as a calculation shortcut.",
  sections: [
    { h: "Congruence arithmetic", p: ["a ≡ b (mod m) means m divides a − b, that is, a and b leave the same remainder when divided by m. Congruences can be added, subtracted and multiplied like equations: if a ≡ b and c ≡ d then a + c ≡ b + d and ac ≡ bd.", "Division is the exception. You may cancel a common factor c from ac ≡ bc (mod m) only when gcd(c, m) = 1, otherwise the modulus must also be divided by gcd(c, m)."], formula: ["a ≡ b (mod m)  if and only if  m | (a − b)", "a ≡ b, c ≡ d  implies  a + c ≡ b + d  and  a c ≡ b d", "ac ≡ bc (mod m) and gcd(c, m) = g  implies  a ≡ b (mod m/g)"] },
    { h: "When is ax ≡ b (mod m) solvable?", p: ["Let d = gcd(a, m). The congruence has a solution if and only if d divides b. If it does, there are exactly d solutions modulo m, spaced m/d apart.", "If d = 1 there is exactly one solution modulo m, found by multiplying by the inverse of a: x ≡ a⁻¹ b (mod m). The inverse comes from the Extended Euclidean Algorithm or by inspection for small m."], formula: ["d = gcd(a, m);  solvable  if and only if  d | b", "Number of solutions mod m = d", "d = 1:  x ≡ a⁻¹ b (mod m)", "d > 1:  divide a, b, m by d, solve, then x₀ + k (m/d), k = 0, ..., d − 1"] },
    { h: "Fermat's little theorem", p: ["If p is prime and p does not divide a, then a<sup>p−1</sup> ≡ 1 (mod p). Equivalently a<sup>p</sup> ≡ a (mod p) for every a. It reduces huge powers: reduce the exponent modulo p − 1.", "It also gives an inverse for prime moduli: a⁻¹ ≡ a<sup>p−2</sup> (mod p). Euler's theorem generalises it: a<sup>φ(n)</sup> ≡ 1 (mod n) when gcd(a, n) = 1."], formula: ["p prime, p ∤ a:  a^(p − 1) ≡ 1 (mod p)", "a^p ≡ a (mod p) for all a", "a⁻¹ ≡ a^(p − 2) (mod p)", "Euler: a^φ(n) ≡ 1 (mod n),  gcd(a, n) = 1"] },
  ],
  examples: [
    { q: "Solve 3x ≡ 2 (mod 7).", steps: ["gcd(3, 7) = 1, so there is exactly one solution mod 7.", "The inverse of 3 mod 7 is 5, since 3 × 5 = 15 ≡ 1.", "x ≡ 5 × 2 = 10 ≡ 3 (mod 7).", "Check: 3 × 3 = 9 ≡ 2 (mod 7)."], ans: "x ≡ 3 (mod 7)" },
    { q: "Solve 6x ≡ 9 (mod 15).", steps: ["d = gcd(6, 15) = 3 and 3 divides 9, so there are 3 solutions mod 15.", "Divide everything by 3: 2x ≡ 3 (mod 5).", "The inverse of 2 mod 5 is 3, so x ≡ 9 ≡ 4 (mod 5).", "Solutions mod 15: 4, 4 + 5, 4 + 10 = 4, 9, 14.", "Check: 6 × 4 = 24 ≡ 9, 6 × 9 = 54 ≡ 9, 6 × 14 = 84 ≡ 9 (mod 15)."], ans: "x ≡ 4, 9, 14 (mod 15)" },
    { q: "Does 4x ≡ 3 (mod 8) have a solution? Find 2<sup>100</sup> mod 7 using Fermat.", steps: ["gcd(4, 8) = 4 does not divide 3, so no solution.", "7 is prime and 7 does not divide 2, so 2⁶ ≡ 1 (mod 7).", "100 = 6 × 16 + 4, so 2¹⁰⁰ ≡ 2⁴ = 16 ≡ 2 (mod 7)."], ans: "No solution; 2¹⁰⁰ ≡ 2 (mod 7)" },
  ],
  mistakes: ["Dividing both sides by a number that shares a factor with the modulus without also dividing the modulus.", "Giving only one solution when gcd(a, m) = d is greater than 1. There are d of them.", "Skipping the divisibility test d | b and 'solving' an impossible congruence.", "Using Fermat when the modulus is not prime or when p divides a.", "Not reducing the final answer into the range 0 to m − 1."],
  check: [
    { q: "ax ≡ b (mod m) has a solution if and only if", o: ["gcd(a, m) divides b", "a divides m", "b divides m", "m is prime"], a: 0, why: "That is the existence criterion." },
    { q: "How many solutions mod 12 does 4x ≡ 8 (mod 12) have?", o: ["1", "2", "4", "0"], a: 2, why: "gcd(4, 12) = 4 divides 8, so there are 4 solutions." },
    { q: "By Fermat, 3<sup>12</sup> mod 13 is", o: ["0", "1", "3", "12"], a: 1, why: "13 is prime, so 3¹² ≡ 1." },
    { q: "The inverse of 4 mod 9 is", o: ["2", "5", "7", "8"], a: 2, why: "4 × 7 = 28 ≡ 1 (mod 9)." },
  ],
};

export const L_BCA002: Record<string, Lesson> = {
  "BCA-002:1:5": truthTables,
  "BCA-002:1:11": normalForms,
  "BCA-002:2:3": relations,
  "BCA-002:2:12": hasse,
  "BCA-002:3:3": functions,
  "BCA-002:3:9": groups,
  "BCA-002:4:5": combinations,
  "BCA-002:4:8": multinomial,
  "BCA-002:5:6": euclid,
  "BCA-002:5:11": congruence,
};
