import type { Lesson } from "./types";

// Code lines are written with &lt; &gt; &amp; entities: the lesson renderer decodes them and nothing is parsed as markup.

const dataTypes: Lesson = {
  intro: "Every variable in C has a data type, and the type decides how many bytes it takes, which values it can hold and how arithmetic on it behaves. Questions ask you to describe char, int, float and double with size and range, and to name derived and user-defined types. You will learn the sizes, the range formula, the type families, and the integer-division trap that costs marks in output questions.",
  sections: [
    { h: "Three families of types", p: ["Primary (basic) types are built into the language: char, int, float, double and void. Derived types are made from them: arrays, pointers, functions. User-defined types are the ones you declare yourself: struct, union, enum and typedef.", "A type is a promise to the compiler about size and meaning. The same 32 bits can be an int, a float or four chars, and only the declared type tells the compiler how to read them."] },
    { h: "Size and range of the primary types", p: ["The C standard fixes only minimum sizes. On a typical modern 32-bit or 64-bit compiler the values below hold (older Turbo C used a 2-byte int, so always say which compiler you assume). Always use sizeof(type) to be sure.", "With n bits a signed integer (stored in 2's complement) holds −2<sup>n−1</sup> to 2<sup>n−1</sup> − 1, and an unsigned integer holds 0 to 2<sup>n</sup> − 1. The modifiers short, long, signed and unsigned change the size or the sign."], formula: ["char: 1 byte, 8 bits, −128 to 127 (unsigned: 0 to 255), format %c", "int: 4 bytes, −2147483648 to 2147483647, format %d", "float: 4 bytes, about 6 decimal digits of precision, format %f", "double: 8 bytes, about 15 decimal digits of precision, format %lf", "Signed n-bit range: −2^(n−1) to 2^(n−1) − 1;  unsigned: 0 to 2^n − 1"] },
    { h: "Conversions and the division trap", p: ["When an expression mixes types, the smaller type is promoted: char to int to float to double. The result of int divided by int is an int, and the fraction is thrown away, even if you store it in a float afterwards.", "To get a real quotient, make at least one operand floating point, by a cast such as (float)a / b or by writing 2.0 instead of 2. Assigning a float to an int truncates, it does not round."], formula: ["int / int gives int: 7 / 2 = 3", "(float)7 / 2 = 3.5", "int x = 3.99;   /* x becomes 3 */"] },
    { h: "User-defined types in one glance", p: ["struct groups different types under one name, union overlays them in the same memory, enum names a set of integer constants, and typedef gives a new name to an existing type."], formula: ["struct point { int x; int y; };", "enum day { MON, TUE, WED };   /* MON = 0, TUE = 1, WED = 2 */", "typedef unsigned long ulong;"] },
  ],
  examples: [
    { q: "Find the range of a signed char and of an unsigned char, and say what unsigned char x = 255; x++; leaves in x.", steps: ["char has 8 bits, so n = 8.", "Signed range: −2<sup>7</sup> to 2<sup>7</sup> − 1 = −128 to 127.", "Unsigned range: 0 to 2<sup>8</sup> − 1 = 0 to 255.", "255 + 1 = 256 does not fit in 8 bits. It wraps modulo 256, giving 0."], ans: "−128 to 127; 0 to 255; x becomes 0" },
    { q: "What does this print?  int a = 7, b = 2;  float c = a / b;  printf(\"%f %f\", c, (float)a / b);", steps: ["a / b is int divided by int, so the result is the int 3.", "c = 3 becomes the float 3.000000.", "(float)a / b converts a first, so 7.0 / 2 = 3.5.", "printf with %f shows six decimals."], ans: "3.000000 3.500000" },
    { q: "Declare a variable for a student's roll number, percentage and grade letter, and print each with the right format specifier.", steps: ["Roll number is whole: int roll = 21;", "Percentage has a fraction: float per = 78.5;", "Grade is a single character: char g = 'A';", "Print them using %d, %f and %c respectively."], ans: `printf("%d %.1f %c", roll, per, g);  prints  21 78.5 A` },
  ],
  mistakes: ["Quoting one fixed size for int. Say 2 bytes in 16-bit compilers and 4 bytes in modern ones, or give sizeof.", "Expecting 7 / 2 to give 3.5 because the target variable is float. The division is done on ints first.", "Using %d to print a float or %f to print an int. The output is garbage, not an error.", "Writing char grade = \"A\"; with double quotes. Double quotes make a string, single quotes make a char.", "Forgetting that unsigned values never go negative; they wrap around instead."],
  check: [
    { q: "On a 32-bit compiler, the range of a signed int is", o: ["−32768 to 32767", "−2147483648 to 2147483647", "0 to 4294967295", "−255 to 255"], a: 1, why: "n = 32 bits gives −2^31 to 2^31 − 1." },
    { q: "Which of these is a user-defined type?", o: ["float", "pointer", "enum", "void"], a: 2, why: "enum, struct, union and typedef are user-defined. Pointer is a derived type." },
    { q: "int a = 9, b = 4; printf(\"%d\", a / b); prints", o: ["2.25", "2", "3", "2.0"], a: 1, why: "Integer division truncates 2.25 to 2." },
    { q: "The format specifier for a double in printf is conventionally", o: ["%d", "%c", "%lf", "%s"], a: 2, why: "%lf (or %f in printf) is used for double; %d is for int." },
  ],
};

const logicalOps: Lesson = {
  intro: "Relational and logical operators build the conditions that drive every if, while and for. The exam favourites are the value of a mixed expression, short-circuit evaluation and operator precedence. You will learn that true is 1 and false is 0, how && and || stop early, and how to read a long expression with the precedence table.",
  sections: [
    { h: "Relational and logical operators", p: ["Relational operators compare two values: less than, greater than, less or equal, greater or equal, equal to and not equal to. Logical operators combine conditions: && (AND), || (OR) and ! (NOT).", "C has no separate boolean in the classic syntax. Any non-zero value counts as true and zero counts as false, but the result of a comparison or logical operator is always exactly 1 or 0."], formula: ["a &lt; b,  a &gt; b,  a &lt;= b,  a &gt;= b,  a == b,  a != b   (result is 1 or 0)", "a &amp;&amp; b is 1 only if both are non-zero;  a || b is 0 only if both are zero", "!a is 1 if a is 0, else 0"] },
    { h: "Short-circuit evaluation", p: ["C evaluates && and || from left to right and stops as soon as the answer is known. In A &amp;&amp; B, if A is false then B is never evaluated. In A || B, if A is true then B is never evaluated.", "This is a feature you can use for safety, as in (d != 0 &amp;&amp; n / d &gt; 2) where the division can never run with d = 0. It is also a trap when B has a side effect like i++."], formula: [`if (d != 0 && n / d > 2)   /* division skipped when d is 0 */`, `x = 5; (x < 3) && (x++);   /* x stays 5, x++ never runs */`] },
    { h: "Precedence and associativity", p: ["When an expression has several operators, the one higher in this list binds first. Use brackets whenever you are unsure, because the examiner will test the order.", "Order from high to low: ! and unary operators, then * / %, then + -, then relational (&lt; &lt;= &gt; &gt;=), then equality (== !=), then &amp;&amp;, then ||, then ?:, then assignment (=, +=, ...), then comma. Most binary operators associate left to right; assignment and unary associate right to left."], formula: ["! , ++ , -- , unary -   (highest)", "* / %   then   + -", "&lt; &lt;= &gt; &gt;=   then   == !=", "&amp;&amp;   then   ||   then   ?:   then   =   (lowest, apart from comma)"] },
    { h: "Demonstration program", p: ["Trace the program below by hand first, then compare. It shows precedence, chained comparison and short-circuit together."], formula: ["int a = 5, b = 0, c;", "c = a &gt; 3 &gt; 1;                       /* (a&gt;3) is 1, then 1&gt;1 is 0, so c = 0 */", "c = a + 2 * 3 == 11 &amp;&amp; !b;     /* 5+6==11 is 1, !b is 1, so c = 1 */", `c = (b != 0) && (a++ > 0);         /* a++ never runs, a stays 5 */`] },
  ],
  examples: [
    { q: "Find x, y and z.  int x = 2, y = 3, z;  z = x++ || y++;", steps: ["|| evaluates its left side first: x++ gives the old value 2 (non-zero, true) and then x becomes 3.", "The left side is true, so || stops. y++ never runs.", "z receives the value of the whole expression, which is 1."], ans: "x = 3, y = 3, z = 1" },
    { q: "Evaluate  int a = 4, b = 2, c = 0;  r = a &gt; b &amp;&amp; b &gt; c || c;", steps: ["&amp;&amp; has higher precedence than ||, so group as (a &gt; b &amp;&amp; b &gt; c) || c.", "a &gt; b is 1 and b &gt; c is 1, so the AND gives 1.", "1 || c is 1 and c is never even looked at."], ans: "r = 1" },
    { q: "What does this print?  int i = 0;  if (i = 5) printf(\"yes\"); else printf(\"no\");", steps: ["The condition is i = 5, an assignment, not the comparison i == 5.", "The assignment stores 5 in i and the value of the expression is 5.", "5 is non-zero, so the condition is true."], ans: "yes (and i is now 5)" },
  ],
  mistakes: ["Writing = where == was meant inside an if. It compiles and silently assigns.", "Chaining comparisons like 0 &lt; x &lt; 10 as in maths. It is evaluated as (0 &lt; x) &lt; 10 and is always true.", "Putting a side effect like i++ on the right of &amp;&amp; or || and assuming it always runs.", "Mixing up the bitwise &amp; and | with the logical &amp;&amp; and ||. They give different results and do not short-circuit.", "Believing the result of a true condition can be any non-zero number. Comparisons always give exactly 1 or 0."],
  check: [
    { q: "In (a &amp;&amp; b), when is b not evaluated?", o: ["when a is true", "when a is false", "never", "when b is a variable"], a: 1, why: "If a is false the whole AND is false already, so evaluation stops." },
    { q: "What is the value of  5 &gt; 3 &gt; 1 ?", o: ["1", "0", "5", "error"], a: 1, why: "(5 &gt; 3) is 1, then 1 &gt; 1 is 0." },
    { q: "Which has the highest precedence?", o: ["||", "&amp;&amp;", "==", "!"], a: 3, why: "The unary ! binds tighter than relational, equality and logical operators." },
    { q: "int x = 0; if (x = 0) printf(\"A\"); else printf(\"B\"); prints", o: ["A", "B", "AB", "nothing"], a: 1, why: "x = 0 assigns 0, which is false, so the else branch runs." },
  ],
};

const forLoop: Lesson = {
  intro: "Loops repeat a block until a condition fails, and the exam asks you to compare the three kinds and to trace how many times a loop body runs. The key idea is entry-controlled versus exit-controlled. You will learn the exact execution order of for, while and do-while, how to count iterations, and how to write the standard sum and pattern programs.",
  sections: [
    { h: "The for loop and its execution order", p: ["The for loop packs initialisation, condition and update into one line. The order is always: initialisation (once), then test the condition, then run the body, then update, then test again.", "If the condition is false the very first time, the body never runs. Any of the three parts may be left empty, and for (;;) is an infinite loop that you leave with break."], formula: ["for (init; condition; update) { body }", "Order: init -> test -> body -> update -> test -> body -> update -> ... -> test fails -> exit"] },
    { h: "Entry-controlled and exit-controlled loops", p: ["for and while are entry-controlled: the condition is tested before each pass, so the body can run zero times. do-while is exit-controlled: the body runs first and the condition is tested at the end, so the body runs at least once and the statement ends with a semicolon.", "Use for when the count is known, while when you loop until something happens, and do-while for menus and input validation where you must ask at least once."], formula: ["while (cond) { body }            /* 0 or more times */", "do { body } while (cond);        /* 1 or more times */", "for (i = 1; i &lt;= n; i++) { body }   /* n times */"] },
    { h: "Counting iterations", p: ["For a loop that steps by a constant, the count is about (last − first) / step + 1. For a loop that doubles, count the doublings: i = 1, 2, 4, 8 ... runs while i stays within the limit, which is about log<sub>2</sub> of the limit plus one.", "Always find the final value of the loop variable. After for (i = 0; i &lt; 5; i++) finishes, i is 5, not 4."], formula: ["Iterations of for (i = a; i &lt;= b; i += s) = floor((b − a) / s) + 1", "Doubling loop for (i = 1; i &lt;= N; i *= 2) runs floor(log<sub>2</sub> N) + 1 times"] },
    { h: "Standard programs", p: ["Sum of the first n numbers and a right-angle star pattern using nested loops: the outer loop counts rows and the inner loop counts columns in each row."], formula: ["int i, n = 5, sum = 0;", "for (i = 1; i &lt;= n; i++) sum += i;", `printf("%d", sum);   /* 15 */`, "for (i = 1; i &lt;= 3; i++) {", `   for (j = 1; j <= i; j++) printf("*");`.replace("<=", "&lt;="), `   printf("\\n");`, "}"] },
  ],
  examples: [
    { q: "How many times does the body run, and what is i at the end?  for (i = 1; i &lt;= 100; i *= 2) printf(\"%d \", i);", steps: ["Values of i that pass the test: 1, 2, 4, 8, 16, 32, 64.", "Next value 128 is greater than 100, so the loop stops.", "Seven values were printed, so the body ran 7 times.", "i is 128 when the loop exits."], ans: "7 iterations, prints 1 2 4 8 16 32 64, final i = 128" },
    { q: "Differentiate with output.  int i = 10;  while (i &lt; 5) printf(\"A\");   do { printf(\"B\"); } while (i &lt; 5);", steps: ["The while tests i &lt; 5 first. 10 &lt; 5 is false, so A is never printed.", "The do-while runs its body once before testing, so B is printed once.", "Then 10 &lt; 5 is false and the loop ends."], ans: "Output: B (the while body runs 0 times, do-while runs once)" },
    { q: "Write a program to print the sum of the digits of a number n using a loop.", steps: ["Take n = 482 and sum = 0.", "While n is not 0: add n % 10 to sum, then n = n / 10.", "Pass 1: sum = 2, n = 48. Pass 2: sum = 10, n = 4. Pass 3: sum = 14, n = 0.", "n is 0, so the loop stops."], ans: "sum = 14; code: while (n != 0) { sum += n % 10; n /= 10; }" },
  ],
  mistakes: ["Putting a semicolon right after for (...) or while (...). The loop body becomes empty and the next block runs once.", "Forgetting the semicolon after while (cond) in a do-while.", "Using &lt;= n where &lt; n was meant, giving one iteration too many, especially with arrays.", "Never changing the loop variable inside a while, which makes an infinite loop.", "Saying do-while is entry-controlled. It is exit-controlled."],
  check: [
    { q: "Which loop always executes its body at least once?", o: ["for", "while", "do-while", "none"], a: 2, why: "do-while tests the condition after the body." },
    { q: "for (i = 0; i &lt; 5; i++); after this statement i equals", o: ["4", "5", "0", "6"], a: 1, why: "The loop ends when i becomes 5 and the test fails." },
    { q: "for (i = 2; i &lt;= 20; i += 3) runs how many times?", o: ["6", "7", "8", "18"], a: 1, why: "floor((20 − 2) / 3) + 1 = 7 (values 2, 5, 8, 11, 14, 17, 20)." },
    { q: "The loop for (;;) is", o: ["a syntax error", "an infinite loop", "a loop that runs once", "a loop that never runs"], a: 1, why: "An empty condition is treated as true, so it only ends on break or return." },
  ],
  lab: { id: "ctrlflow", label: "Open the control-flow railway lab" },
};

const array2d: Lesson = {
  intro: "A two-dimensional array stores a table of values in rows and columns, and it is the C way to handle matrices. The exam asks for the declaration and initialisation rules, for a matrix program, and for the address of an element in row-major order. You will learn all three, plus the dimension rule for matrix multiplication.",
  sections: [
    { h: "Declaration and initialisation", p: ["type name[rows][cols]; reserves rows × cols elements of one type, and indices start at 0. A 3 × 4 int array has 12 elements and the last one is a[2][3].", "You can initialise it row by row with inner braces. When you give the initial values, the row count may be left out but the column count may not, because the compiler needs it to find where each row starts. Elements you leave out become 0."], formula: ["int a[3][4];", "int m[2][3] = { {1, 2, 3}, {4, 5, 6} };", "int t[][2] = { {1, 2}, {3, 4}, {5, 6} };   /* rows deduced = 3 */"] },
    { h: "How it sits in memory: row-major address", p: ["Memory is a single line, so the rows are laid end to end. C uses row-major order: all of row 0, then all of row 1, and so on. To reach a[i][j] you skip i complete rows of C elements each and then j more elements.", "Column-major order (used by Fortran) does the opposite and stores column after column. The exam often asks both, so learn both formulas. B is the base address, w the size of one element, R rows, C columns, with indices from 0."], formula: ["Row-major: address of a[i][j] = B + (i × C + j) × w", "Column-major: address of a[i][j] = B + (j × R + i) × w", "With lower bounds L<sub>r</sub>, L<sub>c</sub>: use (i − L<sub>r</sub>) and (j − L<sub>c</sub>)"] },
    { h: "Reading and summing a 3 × 3 matrix", p: ["Nested loops visit every element: the outer loop over rows, the inner loop over columns. The same pattern gives the sum, the trace (sum where i equals j) and the transpose."], formula: ["int a[3][3], i, j, sum = 0;", "for (i = 0; i &lt; 3; i++)", "   for (j = 0; j &lt; 3; j++) {", `      scanf("%d", &a[i][j]);`.replace("&a", "&amp;a"), "      sum += a[i][j];", "   }", `printf("Sum = %d", sum);`] },
    { h: "Matrix multiplication rule", p: ["A (m × k) times B (k × n) is possible only if the number of columns of A equals the number of rows of B. The product C is m × n and each element is a sum of k products. If the check fails the program must print an error instead of multiplying."], formula: ["C[i][j] = sum over x of A[i][x] × B[x][j]", "Valid only if cols(A) == rows(B);  result size = rows(A) × cols(B)", "for (i...) for (j...) { c[i][j] = 0; for (x = 0; x &lt; k; x++) c[i][j] += a[i][x] * b[x][j]; }"] },
  ],
  examples: [
    { q: "An int array int A[3][4] has base address 1000 and an int takes 4 bytes. Find the address of A[2][1] in row-major and in column-major order.", steps: ["R = 3, C = 4, w = 4, i = 2, j = 1, B = 1000.", "Row-major: 1000 + (2 × 4 + 1) × 4 = 1000 + 36 = 1036.", "Column-major: 1000 + (1 × 3 + 2) × 4 = 1000 + 20 = 1020."], ans: "1036 (row-major), 1020 (column-major)" },
    { q: "Write a C program to input a 3 × 3 matrix and print the sum of its diagonal elements.", steps: ["Declare int a[3][3], i, j, d = 0.", "Read with two nested loops.", "The diagonal elements are those with i == j, so add a[i][i] in a single loop.", "Print d."], ans: `for (i = 0; i < 3; i++) d += a[i][i];  printf("%d", d);`.replace("<", "&lt;") },
    { q: "Can a 2 × 3 matrix be multiplied by another 2 × 3 matrix? What is the size of the product of a 2 × 3 by a 3 × 4?", steps: ["Columns of the first = 3 but rows of the second = 2, so the first pair is not allowed.", "For 2 × 3 times 3 × 4, the inner dimensions 3 and 3 match.", "The product takes the outer dimensions: 2 × 4."], ans: "Not possible; the valid product is 2 × 4" },
  ],
  mistakes: ["Starting indices at 1. The valid indices of a[3][4] are 0 to 2 and 0 to 3.", "Leaving out the column size in a declaration such as int a[][]; only the first dimension can be omitted.", "Using the row count where the column count belongs in the row-major formula (i × C, not i × R).", "Writing a[i,j] instead of a[i][j]. The comma expression compiles but is wrong.", "Forgetting to set c[i][j] = 0 before accumulating in matrix multiplication."],
  check: [
    { q: "int a[3][4] has how many elements and which is the last?", o: ["12, a[3][4]", "12, a[2][3]", "7, a[2][3]", "12, a[3][3]"], a: 1, why: "3 × 4 = 12 elements, indices run to 2 and 3." },
    { q: "In row-major order the address of a[i][j] with C columns is", o: ["B + (j × R + i) × w", "B + (i × C + j) × w", "B + (i + j) × w", "B + i × j × w"], a: 1, why: "Skip i full rows of C elements, then j more." },
    { q: "Which declaration is legal?", o: ["int a[][];", "int a[][3] = {{1,2,3},{4,5,6}};", "int a[3][] = {{1,2,3}};", "int a[,3];"], a: 1, why: "Only the first dimension may be left out when initialising." },
    { q: "A (4 × 2) times B (2 × 5) gives a matrix of size", o: ["4 × 5", "2 × 2", "4 × 2", "not possible"], a: 0, why: "Inner dimensions match; the result takes the outer ones." },
  ],
};

const callByValue: Lesson = {
  intro: "When you call a function, C must decide whether the function works on the caller's variable or on a copy. This is the classic call by value versus call by reference question, always with the swap function. You will learn what is actually copied, why a plain swap fails, and how passing addresses fixes it.",
  sections: [
    { h: "Call by value", p: ["In call by value the value of each actual argument is copied into the formal parameter. The function works on its own copy inside its own stack frame, so whatever it does to the parameter is lost when the function returns. This is how C passes every ordinary argument.", "It is safe, because the caller's data cannot be damaged, but the function cannot return more than one result through its parameters."], formula: [`void swap(int a, int b) { int t = a; a = b; b = t; }`, `swap(x, y);   /* x and y are unchanged */`] },
    { h: "Call by reference using pointers", p: ["C has no true reference parameters, but you get the same effect by passing addresses. The address is itself copied (so strictly this is call by value of a pointer), but the function uses it to reach the original variable with the * operator.", "At the call you send &amp;x and &amp;y. In the function the formal parameters are pointers, and you write *a and *b to read and change the caller's variables."], formula: [`void swap(int *a, int *b) { int t = *a; *a = *b; *b = t; }`, `swap(&amp;x, &amp;y);   /* x and y are exchanged */`] },
    { h: "Side-by-side comparison", p: ["What is passed: value passes a copy of the data, reference passes the address. Effect: the first leaves the caller's variables alone, the second can change them. Memory: the first copies the whole value (costly for large data), the second copies only an address. Use: reference is the way to return several values or to avoid copying big structures.", "Arrays are special. An array name decays to the address of its first element, so passing an array already behaves like passing by reference: changes made inside the function show up in the caller."], formula: [`void fill(int arr[], int n) { arr[0] = 99; }   /* changes the caller's array */`] },
  ],
  examples: [
    { q: "Trace the output.  void f(int n) { n = n + 10; }  int main() { int x = 5; f(x); printf(\"%d\", x); }", steps: ["f(x) copies 5 into n.", "Inside f, n becomes 15, but only the copy changes.", "On return the copy disappears. x is still 5."], ans: "5" },
    { q: "Write a function that swaps two integers using call by reference and show the trace for x = 3, y = 8.", steps: ["Prototype: void swap(int *a, int *b). Call: swap(&amp;x, &amp;y).", "t = *a stores 3. *a = *b writes 8 into x. *b = t writes 3 into y.", "Back in main, x = 8 and y = 3."], ans: "x = 8, y = 3" },
    { q: "Write a function that returns both the sum and the product of two numbers.", steps: ["A function returns one value, so pass two result addresses.", "void calc(int a, int b, int *s, int *p) { *s = a + b; *p = a * b; }", "Call calc(4, 5, &amp;sum, &amp;prod);", "After the call sum = 9 and prod = 20."], ans: "sum = 9, prod = 20" },
  ],
  mistakes: ["Writing a swap with plain int parameters and expecting the caller to change.", "Calling swap(x, y) when the function wants pointers. You must pass &amp;x and &amp;y.", "Forgetting the * when using the pointer in the body (a = b swaps the local pointers, not the data).", "Saying C supports call by reference as a language feature. It simulates it with pointers.", "Thinking an array is copied when passed. Only the address of its first element is passed."],
  check: [
    { q: "In call by value, the function receives", o: ["the address of the argument", "a copy of the argument", "the argument itself", "nothing"], a: 1, why: "The actual value is copied into the formal parameter." },
    { q: "To change the caller's int inside a function the parameter must be declared as", o: ["int", "int *", "int &amp;&amp;", "const int"], a: 1, why: "A pointer lets the function reach the caller's variable." },
    { q: "How do you call void swap(int *a, int *b) for x and y?", o: ["swap(x, y);", "swap(*x, *y);", "swap(&amp;x, &amp;y);", "swap(x&amp;, y&amp;);"], a: 2, why: "Pass the addresses with the address-of operator." },
    { q: "When an array is passed to a function, changes made to its elements inside the function", o: ["are lost", "affect the original array", "cause a compile error", "affect only the first element"], a: 1, why: "The array name decays to a pointer, so the function works on the original." },
  ],
};

const recursion: Lesson = {
  intro: "A recursive function is one that calls itself on a smaller version of the same problem. Factorial is the question you must be able to write without thinking, and you should also be ready to trace Fibonacci and explain what happens on the stack. You will learn the two parts every recursion needs, a full trace, and how recursion compares with a loop.",
  sections: [
    { h: "The two parts of every recursion", p: ["A base case is the smallest input where the answer is known directly, so the function returns without calling itself. The recursive case reduces the problem toward the base case and calls the function again.", "If the base case is missing or never reached, the calls pile up until the stack overflows and the program crashes."], formula: ["n! = n × (n − 1)!  for n ≥ 1,   0! = 1  (base case)", `long fact(int n) { if (n <= 1) return 1; return n * fact(n - 1); }`.replace("<=", "&lt;=")] },
    { h: "What happens on the stack", p: ["Each call creates a new stack frame holding its own n and its return address. Calls go down until the base case returns, then each frame returns its answer to the one below and is removed, so the multiplications happen on the way back up.", "Depth equals the number of pending calls, so fact(1000) needs 1000 frames. This memory cost is the main disadvantage against a loop."], formula: ["fact(4) -> 4 * fact(3) -> 4 * 3 * fact(2) -> 4 * 3 * 2 * fact(1)", "fact(1) returns 1, then fact(2) = 2, fact(3) = 6, fact(4) = 24"] },
    { h: "Fibonacci and the cost of repeated work", p: ["fib(n) = fib(n − 1) + fib(n − 2), with fib(0) = 0 and fib(1) = 1. The function calls itself twice per level, so the same values are recomputed again and again and the number of calls grows roughly as 2<sup>n</sup>.", "The loop version keeps the last two values and needs only n steps. Recursion is clearer for naturally recursive things such as trees, towers of Hanoi and divide-and-conquer sorting."], formula: [`int fib(int n) { if (n == 0) return 0; if (n == 1) return 1; return fib(n - 1) + fib(n - 2); }`, "fib(5) makes 15 calls, fib(6) makes 25 calls"] },
    { h: "Recursion versus iteration", p: ["Recursion: short code, uses stack memory, slower because of call overhead, fits recursive structures. Iteration: uses a loop, constant extra memory, faster, can be harder to write for trees. Any recursion can be rewritten as a loop, sometimes with an explicit stack."] },
  ],
  examples: [
    { q: "Write a recursive function to find the factorial of a positive integer and trace it for n = 4.", steps: ["Base case: if n is 0 or 1, return 1.", "Recursive case: return n * fact(n − 1).", "Calls: fact(4), fact(3), fact(2), fact(1). fact(1) returns 1.", "Unwind: fact(2) = 2 × 1 = 2; fact(3) = 3 × 2 = 6; fact(4) = 4 × 6 = 24."], ans: "4! = 24" },
    { q: "Write a recursive function for the sum of the first n natural numbers and find sum(4).", steps: ["Base: sum(0) = 0.", "Recursive: sum(n) = n + sum(n − 1).", "sum(4) = 4 + sum(3) = 4 + 3 + sum(2) = 4 + 3 + 2 + 1 + sum(0).", "Add up: 4 + 3 + 2 + 1 + 0."], ans: "10" },
    { q: "How many calls does fib(4) make in total, counting the first call?", steps: ["fib(4) calls fib(3) and fib(2).", "fib(3) calls fib(2) and fib(1); fib(2) calls fib(1) and fib(0).", "Count: fib(4)=1, fib(3)=1, fib(2) appears twice, fib(1) appears three times, fib(0) appears twice.", "Total = 1 + 1 + 2 + 3 + 2 = 9."], ans: "9 calls" },
  ],
  mistakes: ["Leaving out the base case, or writing one that is never reached (such as calling fact(n) instead of fact(n − 1)).", "Using an int for factorial and overflowing at 13!. Use long or unsigned long long for bigger values.", "Assuming the multiplication happens on the way down. It happens as the calls return.", "Forgetting the return in front of the recursive call, so the value is lost.", "Claiming recursion is always faster. It usually costs more time and stack than a loop."],
  check: [
    { q: "Every correct recursive function must have", o: ["a loop", "a base case", "global variables", "a pointer parameter"], a: 1, why: "Without a base case the calls never stop." },
    { q: "What is the value of fact(5) for the standard recursive factorial?", o: ["24", "60", "120", "720"], a: 2, why: "5 × 4 × 3 × 2 × 1 = 120." },
    { q: "Infinite recursion normally ends with", o: ["output of 0", "stack overflow", "a compile error", "a warning only"], a: 1, why: "Frames keep piling up until the stack is exhausted." },
    { q: "Naive recursive Fibonacci is slow because", o: ["it uses loops", "it recomputes the same values", "it uses pointers", "it has no base case"], a: 1, why: "Two recursive calls per level repeat the same sub-problems, growing about as 2^n." },
  ],
  lab: { id: "sortstack", label: "Open the recursion stack lab" },
};

const pointers: Lesson = {
  intro: "A pointer is a variable that stores the address of another variable. Pointer questions in the exam ask for a definition, the two operators & and *, pointer arithmetic and pointer to pointer, usually with an output to trace. By the end you will read every pointer expression as an address or a value, and know why adding 1 to an int pointer moves 4 bytes.",
  sections: [
    { h: "Declaring and using a pointer", p: ["Every variable lives at an address. A pointer variable holds such an address. Declare it with a * and the type of the thing it points to: int *p; means p can hold the address of an int. Always initialise it, either with an address or with NULL.", "Two operators do the work. The address-of operator &amp; gives the address of a variable. The dereference operator * follows a pointer to the variable it points to, so *p can be read or assigned."], formula: ["int x = 10;  int *p = &amp;x;", "p holds the address of x;  *p means the value at that address, which is 10", "*p = 25;   /* x is now 25 */"] },
    { h: "Pointer arithmetic", p: ["Adding a number n to a pointer moves it by n elements, not n bytes: the address changes by n × sizeof(type). So p + 1 on an int pointer advances 4 bytes, on a char pointer 1 byte, on a double pointer 8 bytes.", "Subtracting two pointers into the same array gives the number of elements between them. Allowed operations are pointer ± integer, pointer − pointer and comparisons. Adding two pointers or multiplying a pointer is illegal.", "For an array a, the name a is the address of a[0], so a[i] is exactly *(a + i)."], formula: ["new address = old address + n × sizeof(type)", "a[i]  is the same as  *(a + i)", "ptr2 − ptr1 = (address difference) / sizeof(type)"] },
    { h: "Pointer to pointer", p: ["A pointer can itself have an address, and a pointer that holds it is a pointer to pointer, declared with two stars. Then *pp is the first-level pointer and **pp is the final value.", "Use it when a function must change a pointer, for dynamic arrays of strings, and for tables of rows."], formula: ["int x = 7;  int *p = &amp;x;  int **pp = &amp;p;", "pp -> p -> x:   *pp is p,   **pp is 7", "**pp = 9;   /* x becomes 9 */"] },
    { h: "Array name versus pointer variable", p: ["An array name is a constant address: you cannot assign to it or increment it (a++ is an error), and sizeof(a) gives the whole array. A pointer variable can be reassigned and incremented, and sizeof(p) is just the pointer size, such as 8 bytes on a 64-bit system."] },
  ],
  examples: [
    { q: "Trace the output.  int a = 5, b = 8;  int *p = &amp;a, *q = &amp;b;  *p = *q + 1;  q = p;  *q = *q * 2;  printf(\"%d %d\", a, b);", steps: ["*p = *q + 1 sets a = 8 + 1 = 9.", "q = p makes q point to a as well.", "*q = *q * 2 doubles the value at a: a = 18.", "b was never changed."], ans: "18 8" },
    { q: "An int array a[5] = {10, 20, 30, 40, 50} starts at address 2000 and p = a. Find p + 3, *(p + 3) and the effect of p++.", steps: ["p + 3 = 2000 + 3 × 4 = 2012.", "*(p + 3) is a[3] = 40.", "p++ moves p to 2004, so *p becomes 20."], ans: "2012, 40, p now points to a[1]" },
    { q: "Using a pointer to pointer, write a program that changes x from 7 to 9.", steps: ["Declare int x = 7, *p = &amp;x, **pp = &amp;p;", "**pp = 9; follows pp to p and p to x, and stores 9.", "printf(\"%d\", x) now prints 9."], ans: "9" },
  ],
  mistakes: ["Using a pointer before giving it an address (a wild pointer). Initialise it or set it to NULL.", "Believing p + 1 adds one byte. It adds sizeof(type) bytes.", "Mixing p (the address) with *p (the value), for example scanf(\"%d\", x) instead of the address of x.", "Declaring int *a, b; and thinking both are pointers. Only a is.", "Trying to increment an array name such as a++."],
  check: [
    { q: "If p is an int pointer holding 1000, then p + 2 holds (int = 4 bytes)", o: ["1002", "1004", "1008", "1016"], a: 2, why: "1000 + 2 × 4 = 1008." },
    { q: "Given int x = 4; int *p = &amp;x;, *p equals", o: ["the address of x", "4", "the address of p", "garbage"], a: 1, why: "* dereferences the pointer and gives the value stored at that address." },
    { q: "In int **pp, the expression **pp denotes", o: ["the address of pp", "the pointer p", "the final int value", "a compile error"], a: 2, why: "*pp is the pointer, **pp is the variable it points to." },
    { q: "a[i] is equivalent to", o: ["*(a + i)", "*a + i", "&amp;(a + i)", "a + i"], a: 0, why: "Array indexing is pointer arithmetic followed by dereference." },
  ],
  lab: { id: "ptrheap", label: "Open the pointer arithmetic lab" },
};

const strings: Lesson = {
  intro: "A string in C is just a character array that ends with a null character. Almost every string question reduces to understanding that terminator and walking along the array, whether it is finding the length, copying, comparing or checking a palindrome. You will learn the library functions, how to do the same by hand, and the standard two-pointer palindrome program.",
  sections: [
    { h: "Strings are null-terminated character arrays", p: ["A string constant such as \"HELLO\" is stored as the six characters H E L L O followed by the null character, written '\\0' (value 0). So char s[6] holds a 5-letter word; an array that is too short loses the terminator and the functions run past the end.", "You can initialise with char s[] = \"HELLO\"; (size is deduced as 6) or with a brace list that includes '\\0' by hand. Read a word with scanf(\"%s\", s) (no &amp; needed, it stops at whitespace) and a line with fgets(s, size, stdin). Avoid gets, which cannot check the length."], formula: [`char s[] = "HELLO";   /* H E L L O \\0 : 6 bytes */`, `printf("%s", s);   scanf("%s", s);   fgets(s, 20, stdin);`] },
    { h: "Library functions (string.h)", p: ["strlen(s) returns the length without counting the null. strcpy(dest, src) copies src including the null. strcat(dest, src) appends src to the end of dest. strcmp(a, b) returns 0 if equal, a negative number if a comes before b, a positive number if after. strrev is not standard C.", "You cannot compare strings with == (that compares addresses) or copy them with = (arrays are not assignable). Always use strcmp and strcpy."], formula: ["strlen(\"abc\") = 3", "strcmp(\"apple\", \"apply\") &lt; 0", "strcpy(d, s);   strcat(d, s);"] },
    { h: "Doing it by hand: length and the two-pointer idea", p: ["Length is the index where the null is found. For a palindrome, place one index at the first character and another at the last character, compare, and move them toward each other. If any pair differs it is not a palindrome. This needs only n/2 comparisons and no extra array."], formula: ["int len = 0;  while (s[len] != '\\0') len++;", "int i = 0, j = len - 1, ok = 1;", "while (i &lt; j) { if (s[i] != s[j]) { ok = 0; break; } i++; j--; }", `printf(ok ? "Palindrome" : "Not palindrome");`] },
  ],
  examples: [
    { q: "Write a C program to check whether a given string is a palindrome using two indices.", steps: ["Read the string into char s[100].", "Find len by scanning to '\\0'.", "Set i = 0 and j = len − 1. While i &lt; j compare s[i] and s[j]; on a mismatch set flag = 0 and stop.", "Move i forward and j backward each pass.", "Print the result from the flag. For \"madam\": m=m, a=a, then i meets j in the middle, so it is a palindrome."], ans: "Palindrome check in n/2 comparisons; \"madam\" gives Palindrome" },
    { q: "What does this print?  char s[] = \"CODE\"; printf(\"%d %d\", strlen(s), sizeof(s));", steps: ["strlen counts C, O, D, E = 4 and stops at the null.", "sizeof(s) counts the array bytes including the null: 5."], ans: "4 5" },
    { q: "Write the code to count the vowels in a string without any library function.", steps: ["Loop i from 0 while s[i] != '\\0'.", "Test each character against a, e, i, o, u in both cases (or convert with tolower).", "Increase the counter when it matches.", "For \"Education\" the vowels are E, u, a, i, o so the count is 5."], ans: "count = 5 for \"Education\"" },
  ],
  mistakes: ["Giving the array no room for the terminating null, so char s[5] = \"HELLO\" is wrong.", "Using == to compare two strings. Use strcmp, which returns 0 when they are equal.", "Using scanf(\"%s\") for a sentence. It stops at the first space; use fgets.", "Forgetting that strlen does not count the null but sizeof does.", "Treating 'a' and \"a\" as the same. One is a char, the other a two-byte string."],
  check: [
    { q: "A string in C ends with", o: ["a newline", "a space", "the null character '\\0'", "an EOF"], a: 2, why: "The null character marks the end and is how every string function stops." },
    { q: "strcmp(\"abc\", \"abc\") returns", o: ["1", "0", "−1", "3"], a: 1, why: "It returns 0 for equal strings." },
    { q: "char s[] = \"HI\"; sizeof(s) is", o: ["2", "3", "4", "1"], a: 1, why: "H, I and the null make 3 bytes." },
    { q: "The two-pointer palindrome test compares s[i] with", o: ["s[i+1]", "s[len − i − 1]", "s[len]", "s[0] always"], a: 1, why: "The mirror position of index i is len − 1 − i." },
  ],
};

const structs: Lesson = {
  intro: "A structure packs several variables of different types under one name, and it is how C models a record such as a student. Questions ask you to declare and use one, to compare it with a union, and to find its size. You will learn the syntax, the dot and arrow operators, why a structure can be bigger than the sum of its members, and exactly how a union differs.",
  sections: [
    { h: "Declaring and using a structure", p: ["struct defines a new type; each member gets its own memory. Declare variables of that type, read members with the dot operator, and through a pointer with the arrow operator (p-&gt;marks is the same as (*p).marks).", "A structure can be initialised with braces in member order and copied with a single assignment. Arrays of structures hold many records, and a structure can contain another structure (nested) or an array."], formula: ["struct Student { char name[30]; int roll_no; float marks; };", `struct Student s = {"Asha", 21, 78.5};`, "s.roll_no = 22;    struct Student *p = &amp;s;    p-&gt;marks = 80;", "struct Student cls[60];   /* array of structures */"] },
    { h: "Size, padding and alignment", p: ["The compiler places each member at an address that suits its type, inserting unused padding bytes. For struct { char c; int i; } the char takes 1 byte, 3 bytes of padding follow so that the int starts at a multiple of 4, then 4 bytes for the int, giving a size of 8 and not 5. Reordering members (int first, then char) can shrink the structure, and the whole size is rounded up to a multiple of the largest alignment."], formula: ["struct A { char c; int i; };        sizeof = 8   (1 + 3 padding + 4)", "struct B { int i; char c; };        sizeof = 8   (4 + 1 + 3 tail padding)", "struct C { char a; char b; int i; }; sizeof = 8   (1 + 1 + 2 padding + 4)"] },
    { h: "Union: members share memory", p: ["A union is declared like a structure but all members start at the same address. Its size is the size of the largest member, and only one member is meaningful at a time. Writing one member overwrites the others.", "Use a structure when all fields are needed together (a record) and a union when only one of several alternatives is stored at a time (saving memory, or viewing the same bytes in two ways)."], formula: ["union U { int i; float f; char c; };   sizeof = 4 (largest member)", "struct: size ≥ sum of members;   union: size = largest member"] },
    { h: "Structure versus union at a glance", p: ["Keyword: struct versus union. Memory: separate space for each member versus one shared space. Size: sum plus padding versus the largest member. Access: all members valid together versus only the last-written member. Initialisation: all members versus only the first member."] },
  ],
  examples: [
    { q: "Write a C program to declare a structure Student with name, roll_no and marks, read one record and display it.", steps: ["Declare struct Student { char name[30]; int roll_no; float marks; };", "In main create struct Student s;", `Read with scanf("%s %d %f", s.name, &s.roll_no, &s.marks); (no & before s.name, it is an array).`.replace("&s.roll_no, &s.marks", "&amp;s.roll_no, &amp;s.marks"), `Print with printf("%s %d %.1f", s.name, s.roll_no, s.marks);`], ans: "Record is read into and printed from the members using the dot operator" },
    { q: "Find sizeof for struct { char a; double b; int c; } and for union { char a; double b; int c; } (double = 8 bytes aligned to 8).", steps: ["Struct: a at offset 0 (1 byte), padding to offset 8, b at 8 (8 bytes), c at 16 (4 bytes) = 20.", "Round the total up to a multiple of 8, the largest alignment: 24.", "Union: largest member is double, 8 bytes."], ans: "Structure 24 bytes, union 8 bytes" },
    { q: "What is printed?  union U { int i; char c; } u;  u.i = 65;  printf(\"%c\", u.c);", steps: ["i and c share the same first byte.", "65 stored in the int has 65 in its lowest byte (little-endian).", "Reading c reads that byte, the ASCII code 65, which is the letter A."], ans: "A (on a little-endian machine)" },
  ],
  mistakes: ["Forgetting the semicolon after the closing brace of the structure definition.", "Using . on a pointer (p.marks) instead of -&gt;, or the reverse.", "Assuming sizeof of a structure is the sum of its members; padding adds bytes.", "Reading a union member different from the one last written and expecting the old value.", "Putting &amp; before a char array name in scanf. The array name is already an address."],
  check: [
    { q: "Members of a union", o: ["have separate memory", "share the same memory", "must all be int", "are accessed with the arrow only"], a: 1, why: "All members of a union start at the same address." },
    { q: "struct { char c; int i; } has sizeof (4-byte int)", o: ["5", "6", "8", "4"], a: 2, why: "1 byte + 3 bytes padding + 4 bytes = 8." },
    { q: "If p is a pointer to struct Student, the marks member is accessed as", o: ["p.marks", "p-&gt;marks", "p::marks", "&amp;p.marks only"], a: 1, why: "The arrow operator dereferences the pointer and selects the member." },
    { q: "The size of a union is", o: ["the sum of its members", "the size of its largest member", "the size of its first member", "always 1"], a: 1, why: "Memory is shared, so it must hold the biggest member." },
  ],
  lab: { id: "structunion", label: "Open the struct, union and FILE bench" },
};

const fileModes: Lesson = {
  intro: "File handling lets a program keep data after it ends. The exam favourite is the table of fopen modes, followed by a program that copies or reads a file. You will learn what each of r, w, a, r+, w+ and a+ does to the file and the position, how to open and close safely, and the standard copy-a-file program.",
  sections: [
    { h: "Opening and closing", p: ["fopen(name, mode) returns a FILE pointer, or NULL if it fails, for example when a file to be read does not exist. Always test for NULL before using it. fclose(fp) flushes the buffer and releases the file; forgetting it can lose data written to the buffer.", "Text-mode functions: fprintf and fscanf (formatted), fgetc and fputc (one character), fgets and fputs (lines). Binary mode adds a b to the mode, as in rb or wb, and uses fread and fwrite."], formula: [`FILE *fp = fopen("data.txt", "r");`, `if (fp == NULL) { printf("cannot open"); return 1; }`, "fclose(fp);"] },
    { h: "The six file modes", p: ["The modes differ in three ways: does the file have to exist, is the old content destroyed, and where does writing start. Memorise them as a table.", "r reads only, file must exist, starts at the beginning. w writes only, creates the file or erases it if it exists. a appends, creates the file if absent, always writes at the end and never overwrites old data. The + modes allow both reading and writing: r+ needs an existing file and keeps its content, w+ creates or erases, a+ creates or keeps content, reads from the start but writes only at the end."], formula: ["r : read,           must exist,       content kept,    position at start", "w : write,          created/erased,   content lost,    position at start", "a : append,         created if absent, content kept,   writes at end", "r+: read + write,   must exist,       content kept,    position at start", "w+: read + write,   created/erased,   content lost,    position at start", "a+: read + append,  created if absent, content kept,   reads from start, writes at end"] },
    { h: "Sequential read and the copy program", p: ["Sequential access means you read from the start to the end in order. fgetc returns EOF (a negative constant, usually −1) at the end of the file, so the loop reads into an int, not a char, and stops when it sees EOF.", "To copy a file open the source with r and the destination with w, then pass each character across."], formula: ["int ch;", `FILE *in = fopen("a.txt", "r"), *out = fopen("b.txt", "w");`, "while ((ch = fgetc(in)) != EOF) fputc(ch, out);", "fclose(in);  fclose(out);"] },
  ],
  examples: [
    { q: "Tabulate the effect of opening a file that already holds the text HELLO in modes w, a and r+ and then writing XY.", steps: ["Mode w: the file is emptied first, then XY is written. Result: XY.", "Mode a: writing always happens at the end. Result: HELLOXY.", "Mode r+: position starts at the beginning and overwrites in place. Result: XYLLO."], ans: "w gives XY, a gives HELLOXY, r+ gives XYLLO" },
    { q: "Write a program to copy one file into another and report if the source cannot be opened.", steps: ["Open source with r and destination with w.", "If the source pointer is NULL print an error and stop.", "Loop with fgetc until EOF, writing each character with fputc.", "Close both files."], ans: "File copied character by character, error shown if source is missing" },
    { q: "Which mode would you use to add one line to a log file without losing earlier lines, and what happens if the file does not exist?", steps: ["The previous content must be kept and writing must be at the end: append mode a.", "Mode a creates the file when it does not exist."], ans: "Mode a; the file is created" },
  ],
  mistakes: ["Opening with w when you meant a, which destroys the existing data.", "Not checking for NULL, so a missing file crashes the program.", "Declaring the variable that receives fgetc as char. Use int so EOF can be detected.", "Forgetting fclose, so the last buffered data may never reach the disk.", "Using r or r+ for a file that does not exist; fopen returns NULL."],
  check: [
    { q: "Which mode erases an existing file?", o: ["r", "a", "w", "r+"], a: 2, why: "w truncates the file to zero length (and creates it if absent)." },
    { q: "In append mode, writing happens", o: ["at the beginning", "at the end always", "at the current read position", "in the middle"], a: 1, why: "Append mode forces every write to the end." },
    { q: "fopen returns what when the file cannot be opened?", o: ["0 characters", "EOF", "NULL", "−1 as int"], a: 2, why: "A NULL FILE pointer signals failure." },
    { q: "The variable that holds the result of fgetc should be", o: ["char", "int", "float", "unsigned char"], a: 1, why: "EOF is outside the char range and needs an int to be told apart." },
  ],
  lab: { id: "structunion", label: "Open the file modes bench" },
};

export const L_BCA001: Record<string, Lesson> = {
  "BCA-001:1:3": dataTypes,
  "BCA-001:1:12": logicalOps,
  "BCA-001:2:6": forLoop,
  "BCA-001:2:15": array2d,
  "BCA-001:3:7": callByValue,
  "BCA-001:3:8": recursion,
  "BCA-001:4:3": pointers,
  "BCA-001:4:7": strings,
  "BCA-001:5:1": structs,
  "BCA-001:5:7": fileModes,
};
