import type { Lesson } from "./types";

const rings: Lesson = {
  intro: "Newton's rings are the dark and bright circles you see when a curved lens rests on a flat glass plate. They are the single most repeated question in Engineering Physics: expect the formation, the diameter formulas and a wavelength or refractive-index numerical. By the end you will derive D² = 4nλR, find λ from two rings, and find μ of a liquid.",
  sections: [
    { h: "How the rings form", p: ["Place a plano-convex lens (radius of curvature R) with its curved face on a flat glass plate. Between them is a thin air film. It is zero thick at the touching point and grows outwards.", "Light from a monochromatic source falls almost normally. A ray reflects once from the curved lens surface (glass to air, no phase change) and once from the plate (air to glass, phase change of π, which is an extra λ/2). The two reflected rays meet and interfere.", "Every point at the same distance from the centre has the same film thickness. So the fringes are circles, centred at the contact point."] },
    { h: "Path difference and the film thickness", p: ["For air (μ = 1) and normal incidence, the path difference is 2t + λ/2, where t is the film thickness at that spot.", "Take a ring of radius r. In the circle geometry, r² = R² − (R − t)² = 2Rt − t². Since t is tiny compared with R, drop t² and get r² = 2Rt, so t = r²/2R."], formula: ["Path difference = 2μt cos θ + λ/2 = 2t + λ/2 (air, normal incidence)", "t = r² / 2R"] },
    { h: "Dark and bright ring diameters", p: ["Dark ring: path difference = (2n + 1)λ/2. So 2t + λ/2 = (2n + 1)λ/2, which gives 2t = nλ. Put t = r²/2R: r² = nλR. With D = 2r: D² = 4nλR.", "Bright ring: path difference = nλ. So 2t + λ/2 = nλ, so 2t = (2n − 1)λ/2. Then r² = (2n − 1)λR/2, and D² = 2(2n − 1)λR.", "At the centre t = 0, so the path difference is λ/2: the centre is dark in reflected light. In transmitted light the pattern is reversed and the centre is bright."], formula: ["Dark rings: D<sub>n</sub><sup>2</sup> = 4nλR", "Bright rings: D<sub>n</sub><sup>2</sup> = 2(2n − 1)λR", "D<sub>n</sub> ∝ √n for dark rings, so rings crowd together as n grows"] },
    { h: "Finding λ and μ", p: ["Measure the diameters of the nth and (n + p)th dark rings. Subtracting removes the unknown zero error at the centre.", "Put a liquid of index μ between lens and plate. The path difference becomes 2μt + λ/2, so D² = 4nλR/μ. The rings shrink, and the ratio of the squares gives μ."], formula: ["λ = (D<sub>n+p</sub><sup>2</sup> − D<sub>n</sub><sup>2</sup>) / (4pR)", "μ = D<sub>n</sub><sup>2</sup>(air) / D<sub>n</sub><sup>2</sup>(liquid)"] },
  ],
  examples: [
    { q: "Describe how Newton's rings are formed and show that the diameters of dark rings in reflected light are proportional to the square roots of natural numbers.", steps: ["Draw lens on plate, air film of thickness t, two reflected rays.", "Path difference = 2t + λ/2 (extra λ/2 from reflection at the denser plate).", "Geometry: r² = 2Rt, so t = r²/2R.", "Dark: 2t + λ/2 = (2n + 1)λ/2 gives 2t = nλ, so r² = nλR.", "D² = 4nλR, so D = 2√(λR) · √n. Hence D ∝ √n."], ans: "D<sub>n</sub><sup>2</sup> = 4nλR; D ∝ √n" },
    { q: "In a Newton's ring experiment, the diameter of the 15th dark ring is 0.590 cm and of the 5th dark ring is 0.336 cm. The radius of curvature of the lens is 100 cm. Find the wavelength of light.", steps: ["Use λ = (D<sub>n+p</sub><sup>2</sup> − D<sub>n</sub><sup>2</sup>)/(4pR), with n = 5, p = 10.", "D<sub>15</sub><sup>2</sup> = 0.3481 cm², D<sub>5</sub><sup>2</sup> = 0.1129 cm². Difference = 0.2352 cm².", "4pR = 4 × 10 × 100 = 4000 cm.", "λ = 0.2352 / 4000 = 5.88 × 10<sup>−5</sup> cm."], ans: "λ ≈ 5880 Å" },
    { q: "The diameter of the nth dark ring changes from 0.30 cm to 0.25 cm when a liquid is introduced between the lens and the plate. Find the refractive index of the liquid.", steps: ["D<sub>n</sub><sup>2</sup> (air) = 4nλR and D<sub>n</sub><sup>2</sup> (liquid) = 4nλR/μ.", "So μ = D<sub>air</sub><sup>2</sup> / D<sub>liq</sub><sup>2</sup>.", "μ = (0.30)² / (0.25)² = 0.09 / 0.0625 = 1.44."], ans: "μ = 1.44" },
  ],
  mistakes: ["Forgetting the λ/2 phase change, which makes the centre bright instead of dark in reflected light.", "Using radius where the formula needs diameter (or the other way round). D² = 4nλR but r² = nλR.", "Mixing units: R in cm with λ in Å. Convert everything to cm or to metres first.", "Using the bright ring formula for a dark ring. Dark has n, bright has (2n − 1).", "Writing μ = D<sub>liq</sub> / D<sub>air</sub>. It is the ratio of the squares, with air on top."],
  check: [
    { q: "In reflected light, the centre of Newton's rings is", o: ["bright", "dark", "coloured", "absent"], a: 1, why: "At the centre t = 0, so only the λ/2 phase change remains. Destructive interference gives a dark spot." },
    { q: "The diameter of the nth dark ring is proportional to", o: ["n", "n²", "√n", "1/n"], a: 2, why: "D² = 4nλR, so D ∝ √n." },
    { q: "If the experiment is done in a liquid of index μ, the ring diameters", o: ["increase by μ", "decrease by a factor √μ", "stay the same", "decrease by a factor μ"], a: 1, why: "D² = 4nλR/μ, so D falls by √μ." },
    { q: "The radius of curvature R is found from the slope of a graph of", o: ["D vs n", "D² vs n", "D vs √n", "1/D vs n"], a: 1, why: "D² = 4λR · n is a straight line through the origin with slope 4λR." },
  ],
  lab: { id: "rings", label: "Open the Newton's rings lab" },
};

const grating: Lesson = {
  intro: "A diffraction grating is a glass plate with thousands of parallel slits per centimetre. It splits light into sharp, bright spectral lines far better than a prism. Questions on grating theory, the grating equation and resolving power come almost every year. You will learn the condition for principal maxima, missing orders, and how many orders you can see.",
  sections: [
    { h: "What a grating is", p: ["A plane transmission grating has equally spaced transparent slits of width a, separated by opaque strips of width b. The distance d = a + b is the grating element (or grating constant).", "If a grating has N₀ lines per cm, then d = 1/N₀ cm. A grating with 6000 lines/cm has d = 1.67 × 10⁻⁴ cm."] },
    { h: "The grating equation", p: ["Send parallel monochromatic light normally onto the grating. Each slit diffracts light. Waves from neighbouring slits reach a far point at angle θ with path difference (a + b) sin θ.", "If this path difference is a whole number of wavelengths, all slits add in phase and you get a bright principal maximum. That is the grating equation."], formula: ["(a + b) sin θ = nλ,  n = 0, 1, 2, …", "n = 0 is the central maximum (white for white light). n is the order."] },
    { h: "Intensity pattern and missing orders", p: ["The total pattern is a product of two effects: the single-slit envelope, with α = (πa sin θ)/λ, and the N-slit interference term, with β = (π(a + b) sin θ)/λ. The intensity is I = I₀ (sin α / α)² (sin Nβ / sin β)².", "Between two principal maxima there are N − 1 minima and N − 2 weak secondary maxima. More slits make the principal maxima sharper.", "If a principal maximum of the interference falls exactly on a zero of the single-slit envelope, that order is missing. This happens when (a + b)/a is a whole number. For a = b, every even order (2, 4, …) is missing."] },
    { h: "Dispersion and the highest visible order", p: ["Different λ goes to different θ, so white light spreads into spectra. The angular dispersion is dθ/dλ = n / ((a + b) cos θ). It is larger for higher orders and finer gratings.", "Since sin θ cannot exceed 1, the highest order is n<sub>max</sub> < (a + b)/λ.", "Resolving power of a grating, covered in the next topic, is R = λ/dλ = nN."], formula: ["dθ/dλ = n / ((a + b) cos θ)", "n<sub>max</sub> < (a + b) / λ", "Missing order when (a + b)/a = integer m: orders m, 2m, 3m … are missing"] },
  ],
  examples: [
    { q: "Describe the construction of a plane transmission grating and derive the condition for principal maxima.", steps: ["Construction: many parallel, equally spaced slits ruled on glass. Slit width a, opaque width b, element a + b.", "Parallel light falls normally. Consider waves from corresponding points of adjacent slits, diffracted at angle θ.", "Path difference = (a + b) sin θ.", "For constructive interference of all slits, (a + b) sin θ = nλ. This is the equation of the principal maxima."], ans: "(a + b) sin θ = nλ" },
    { q: "A grating has 6000 lines per cm. What is the highest order visible for sodium light of λ = 5890 Å, and at what angle is the first order seen?", steps: ["a + b = 1/6000 cm = 1.667 × 10⁻⁴ cm = 16667 Å.", "n<sub>max</sub> < (a + b)/λ = 16667 / 5890 = 2.83. So the highest order is 2.", "First order: sin θ = λ/(a + b) = 5890 / 16667 = 0.3534.", "θ = sin⁻¹(0.3534) ≈ 20.7°."], ans: "Highest order = 2; first order at ≈ 20.7°" },
    { q: "In a grating spectrum, which line in the 4th order overlaps with the 3rd order line of wavelength 6000 Å?", steps: ["Overlap means the same angle, so the same (a + b) sin θ.", "n₁λ₁ = n₂λ₂, so 3 × 6000 = 4 × λ.", "λ = 18000 / 4 = 4500 Å."], ans: "λ = 4500 Å" },
  ],
  mistakes: ["Writing the grating equation with a only. It is (a + b), the full element.", "Converting lines per cm into d wrongly. d = 1 / (lines per cm), not the lines count itself.", "Counting the highest order as the next integer above (a + b)/λ. Take the integer below.", "Forgetting the missing orders when a is comparable to b.", "Thinking the central maximum (n = 0) gets separated into colours. It stays white."],
  check: [
    { q: "The grating equation for normal incidence is", o: ["(a + b) cos θ = nλ", "(a + b) sin θ = nλ", "2(a + b) sin θ = nλ", "(a + b) tan θ = nλ"], a: 1, why: "Path difference between adjacent slits is (a + b) sin θ." },
    { q: "If a = b, which orders are missing?", o: ["all odd", "all even", "none", "only the first"], a: 1, why: "(a + b)/a = 2, so orders 2, 4, 6 … fall on zeros of the single-slit envelope." },
    { q: "A grating has 5000 lines/cm. For λ = 6000 Å the highest visible order is", o: ["2", "3", "4", "5"], a: 1, why: "a + b = 2 × 10⁻⁴ cm = 20000 Å. Ratio 20000/6000 = 3.33, so take the integer below: 3." },
    { q: "Increasing the number of lines on a grating, with d fixed, makes the principal maxima", o: ["sharper", "wider", "farther apart", "dimmer in all cases"], a: 0, why: "The positions are set by d, but more slits narrow each maximum." },
  ],
  lab: { id: "diffraction", label: "Open the N-slit diffraction lab" },
};

const einstein: Lesson = {
  intro: "Einstein's coefficients explain why a laser can exist at all. They connect three processes: absorption, spontaneous emission and stimulated emission. This is one of the most repeated 8–10 mark questions. You will learn to derive A/B = 8πhν³/c³ step by step and show why stimulated emission needs a population inversion.",
  sections: [
    { h: "Three ways light meets atoms", p: ["Take two energy levels E₁ (lower) and E₂ (upper) with E₂ − E₁ = hν. N₁ and N₂ are the numbers of atoms in each, and u(ν) is the energy density of radiation at frequency ν.", "Absorption: an atom in E₁ takes a photon and jumps up. Rate = B₁₂ N₁ u(ν).", "Spontaneous emission: an excited atom drops by itself and emits a photon in a random direction and phase. Rate = A₂₁ N₂. It does not depend on u(ν).", "Stimulated emission: a passing photon of energy hν triggers an excited atom to drop. The new photon has the same frequency, phase, direction and polarisation. Rate = B₂₁ N₂ u(ν). This is what makes laser light coherent."], formula: ["Absorption rate = B<sub>12</sub> N<sub>1</sub> u(ν)", "Spontaneous emission rate = A<sub>21</sub> N<sub>2</sub>", "Stimulated emission rate = B<sub>21</sub> N<sub>2</sub> u(ν)", "A<sub>21</sub>, B<sub>12</sub>, B<sub>21</sub> are Einstein's coefficients"] },
    { h: "Derivation in thermal equilibrium", p: ["Step 1: at equilibrium, upward rate = downward rate. B₁₂ N₁ u = A₂₁ N₂ + B₂₁ N₂ u.", "Step 2: solve for u. u = A₂₁ N₂ / (B₁₂ N₁ − B₂₁ N₂) = (A₂₁/B₂₁) / ((B₁₂/B₂₁)(N₁/N₂) − 1).", "Step 3: Boltzmann's law gives N₁/N₂ = e<sup>hν/kT</sup>. So u = (A₂₁/B₂₁) / ((B₁₂/B₂₁) e<sup>hν/kT</sup> − 1).", "Step 4: compare with Planck's law, u = (8πhν³/c³) / (e<sup>hν/kT</sup> − 1). The two match for all T only if B₁₂ = B₂₁ and A₂₁/B₂₁ = 8πhν³/c³."], formula: ["B<sub>12</sub> = B<sub>21</sub> = B", "A<sub>21</sub> / B<sub>21</sub> = 8πhν³ / c³", "u(ν) = (8πhν³/c³) · 1/(e<sup>hν/kT</sup> − 1)  (Planck)"] },
    { h: "What the result tells us", p: ["A/B grows as ν³. So for high frequencies (X-rays) spontaneous emission dominates, and making a laser is very hard. That is why the first lasers were at microwave and visible frequencies.", "The ratio of spontaneous to stimulated emission rate is A₂₁ / (B₂₁ u) = e<sup>hν/kT</sup> − 1. At room temperature, for visible light, this ratio is huge. Ordinary lamps emit almost entirely by spontaneous emission.", "Ratio of stimulated emission to absorption = N₂ / N₁. In thermal equilibrium N₂ < N₁, so absorption wins and light is weakened. For net amplification we need N₂ > N₁. This is population inversion, created by pumping."], formula: ["Spontaneous / stimulated = e<sup>hν/kT</sup> − 1", "Stimulated emission / absorption = N<sub>2</sub> / N<sub>1</sub>", "Amplification needs N<sub>2</sub> > N<sub>1</sub> (population inversion)"] },
  ],
  examples: [
    { q: "Explain absorption, spontaneous emission and stimulated emission, and derive the relation between Einstein's A and B coefficients.", steps: ["Define the three processes and their rates (see above).", "Equilibrium: B₁₂ N₁ u = A₂₁ N₂ + B₂₁ N₂ u.", "Use N₁/N₂ = e<sup>hν/kT</sup> to get u = (A₂₁/B₂₁) / ((B₁₂/B₂₁) e<sup>hν/kT</sup> − 1).", "Compare with Planck: B₁₂ = B₂₁ and A₂₁/B₂₁ = 8πhν³/c³."], ans: "A<sub>21</sub>/B<sub>21</sub> = 8πhν³/c³, B<sub>12</sub> = B<sub>21</sub>" },
    { q: "Calculate A<sub>21</sub>/B<sub>21</sub> for light of frequency 5 × 10<sup>14</sup> Hz (h = 6.626 × 10<sup>−34</sup> J s, c = 3 × 10<sup>8</sup> m/s).", steps: ["A/B = 8πhν³/c³.", "ν³ = 1.25 × 10⁴⁴ and c³ = 2.7 × 10²⁵.", "8π h = 8 × 3.1416 × 6.626 × 10⁻³⁴ = 1.665 × 10⁻³².", "A/B = 1.665 × 10⁻³² × 1.25 × 10⁴⁴ / 2.7 × 10²⁵ = 7.71 × 10⁻¹⁴ J s m⁻³."], ans: "A/B ≈ 7.7 × 10<sup>−14</sup> J s m<sup>−3</sup>" },
    { q: "Find the ratio of spontaneous to stimulated emission rates for λ = 6000 Å at T = 1000 K (k = 1.381 × 10<sup>−23</sup> J/K).", steps: ["hν = hc/λ = 6.626 × 10⁻³⁴ × 3 × 10⁸ / 6 × 10⁻⁷ = 3.313 × 10⁻¹⁹ J.", "kT = 1.381 × 10⁻²³ × 1000 = 1.381 × 10⁻²⁰ J.", "hν/kT = 23.99 ≈ 24.", "Ratio = e<sup>24</sup> − 1 ≈ 2.6 × 10¹⁰."], ans: "≈ 2.6 × 10<sup>10</sup>: spontaneous emission dominates" },
  ],
  mistakes: ["Saying spontaneous emission depends on the radiation density. It does not.", "Claiming stimulated photons go in random directions. They copy the incident photon exactly.", "Forgetting to state that B₁₂ = B₂₁ came from comparing with Planck's law, not assumed.", "Writing N₂ > N₁ is possible in thermal equilibrium. Boltzmann's law forbids it.", "Skipping the Boltzmann step N₁/N₂ = e<sup>hν/kT</sup> in the derivation."],
  check: [
    { q: "Which process produces coherent light?", o: ["Absorption", "Spontaneous emission", "Stimulated emission", "Thermal radiation"], a: 2, why: "The stimulated photon has the same phase, frequency and direction as the one that triggered it." },
    { q: "In Einstein's derivation the ratio A/B equals", o: ["8πhν/c", "8πhν³/c³", "hν/kT", "8πν²/c²"], a: 1, why: "Matching with Planck's radiation law gives 8πhν³/c³." },
    { q: "For light amplification we need", o: ["N₁ > N₂", "N₁ = N₂", "N₂ > N₁", "A = 0"], a: 2, why: "Stimulated emission must beat absorption: population inversion." },
    { q: "The rate of spontaneous emission is proportional to", o: ["N₂ only", "N₂ u(ν)", "N₁ u(ν)", "N₁ only"], a: 0, why: "Rate = A₂₁ N₂, independent of the radiation density." },
  ],
  lab: { id: "einstein", label: "Open the Einstein coefficients lab" },
};

const poynting: Lesson = {
  intro: "The Poynting vector tells you how much electromagnetic energy flows through each square metre every second, and in which direction. It is the most repeated question in the Electromagnetics unit. You will derive Poynting's theorem from Maxwell's equations, find the intensity of a plane wave, and do the typical sunlight or bulb numerical.",
  sections: [
    { h: "The idea", p: ["Electric and magnetic fields store energy. A wave carries this energy forward. We need a quantity that describes the flow, like current density describes the flow of charge.", "That quantity is the Poynting vector S = E × H, measured in W/m². Its direction is the direction of energy flow, which is the direction the wave travels."] },
    { h: "Deriving Poynting's theorem", p: ["Step 1: Start from two Maxwell equations. ∇ × E = −∂B/∂t and ∇ × H = J + ∂D/∂t.", "Step 2: Use the identity ∇·(E × H) = H·(∇ × E) − E·(∇ × H).", "Step 3: Substitute. ∇·(E × H) = −H·∂B/∂t − E·J − E·∂D/∂t.", "Step 4: For a simple medium, E·∂D/∂t = ∂/∂t(½ εE²) and H·∂B/∂t = ∂/∂t(½ μH²). So ∇·S = −∂u/∂t − J·E, where u = ½εE² + ½μH² is the energy density.", "Step 5: Integrate over a volume and apply the divergence theorem. The power leaving the surface plus the rate of change of stored energy plus the power lost as heat (J·E) is zero. That is energy conservation."], formula: ["S = E × H  (W/m²)", "∇·S + ∂u/∂t + J·E = 0", "u = ½ εE² + ½ μH²", "Integral form: −d/dt ∫u dV = ∮S·dA + ∫J·E dV"] },
    { h: "Plane wave in free space", p: ["For a plane wave E and H are perpendicular, and E/H = η₀ = √(μ₀/ε₀) ≈ 377 Ω. The electric and magnetic energy densities are equal, so u = ε₀E².", "S = EH = E²/η₀ points along the direction of travel. The time-average over a cycle gives half the peak value. This average is the intensity I.", "Radiation pressure, from momentum carried by the wave, is I/c for full absorption."], formula: ["|S| = E H = E² / η₀,  η₀ = √(μ₀/ε₀) ≈ 377 Ω", "I = ⟨S⟩ = E₀² / (2η₀) = ½ ε₀ c E₀²", "B₀ = E₀ / c"] },
  ],
  examples: [
    { q: "State and prove Poynting's theorem.", steps: ["Statement: the rate at which energy flows out of a closed surface plus the rate of increase of stored field energy plus ohmic loss equals zero.", "Use ∇ × E = −∂B/∂t, ∇ × H = J + ∂D/∂t and ∇·(E × H) = H·(∇ × E) − E·(∇ × H).", "Get ∇·S = −∂/∂t(½εE² + ½μH²) − J·E.", "Integrate over volume V and use the divergence theorem: ∮S·dA = −d/dt ∫u dV − ∫J·E dV."], ans: "∮S·dA + d/dt ∫u dV + ∫J·E dV = 0" },
    { q: "Sunlight reaches Earth with intensity 1400 W/m². Find the peak electric and magnetic fields (ε₀ = 8.854 × 10<sup>−12</sup> F/m, c = 3 × 10<sup>8</sup> m/s).", steps: ["I = ½ ε₀ c E₀², so E₀ = √(2I / ε₀c).", "ε₀c = 8.854 × 10⁻¹² × 3 × 10⁸ = 2.656 × 10⁻³.", "E₀ = √(2800 / 2.656 × 10⁻³) = √(1.054 × 10⁶) = 1027 V/m.", "B₀ = E₀/c = 1027 / (3 × 10⁸) = 3.42 × 10⁻⁶ T."], ans: "E₀ ≈ 1.03 × 10³ V/m, B₀ ≈ 3.4 μT" },
    { q: "A 100 W bulb radiates uniformly in all directions. Find the peak electric field at a distance of 2 m.", steps: ["Area of sphere = 4πr² = 4π × 4 = 50.27 m².", "I = P/A = 100 / 50.27 = 1.989 W/m².", "E₀ = √(2I / ε₀c) = √(2 × 1.989 / 2.656 × 10⁻³) = √1498 = 38.7 V/m."], ans: "E₀ ≈ 38.7 V/m" },
  ],
  mistakes: ["Writing S = E · H. It is the cross product E × H, a vector.", "Using the peak value as the intensity. Average intensity has the factor ½.", "Forgetting the J·E term (ohmic loss) in the theorem, or getting its sign wrong.", "Confusing S (W/m²) with total power. Total power needs ∮S·dA.", "Using the 4πr² area for a laser beam or a lamp with a reflector. It only works for a point source in all directions."],
  check: [
    { q: "The SI unit of the Poynting vector is", o: ["W", "W/m²", "J/m³", "N/m²"], a: 1, why: "It is power per unit area." },
    { q: "In a plane EM wave the direction of S is", o: ["along E", "along H", "along E × H, the direction of propagation", "opposite to propagation"], a: 2, why: "S = E × H points along the wave's travel." },
    { q: "The Poynting theorem is a statement of conservation of", o: ["charge", "momentum", "energy", "flux"], a: 2, why: "It balances field energy, flow out and heat loss." },
    { q: "For a plane wave in free space E/H equals", o: ["c", "1/c", "377 Ω", "1 Ω"], a: 2, why: "η₀ = √(μ₀/ε₀) ≈ 377 Ω." },
  ],
  lab: { id: "poynting", label: "Open the Poynting vector lab" },
};

const maxwell: Lesson = {
  intro: "Maxwell's four equations pack all of electricity, magnetism and light into four lines. A question asking you to write them in differential and integral form, explain displacement current, or prove EM waves are transverse appears nearly every year. You will see where each equation comes from and how the displacement current fixes Ampere's law.",
  sections: [
    { h: "The four laws in words", p: ["1. Gauss's law (electric): electric charge is the source of electric field. The flux through a closed surface equals the enclosed charge divided by ε₀ (in a medium, the free charge).", "2. Gauss's law (magnetic): there are no magnetic monopoles. Magnetic field lines are closed loops, so the net flux through any closed surface is zero.", "3. Faraday's law: a changing magnetic flux creates an electric field that circulates around it.", "4. Ampere–Maxwell law: a current, and also a changing electric field, creates a circulating magnetic field."], formula: ["Integral:  ∮D·dA = q<sub>free</sub>",  "∮B·dA = 0", "∮E·dl = −dΦ<sub>B</sub>/dt", "∮H·dl = I + dΦ<sub>D</sub>/dt", "Differential:  ∇·D = ρ,  ∇·B = 0", "∇ × E = −∂B/∂t,  ∇ × H = J + ∂D/∂t"] },
    { h: "Why displacement current was needed", p: ["Ampere's law ∇ × H = J has a problem. Take the divergence: ∇·(∇ × H) = 0 always, so ∇·J must be 0. But charging a capacitor has ∇·J ≠ 0, because charge piles up and ∂ρ/∂t ≠ 0.", "Maxwell added a term. Using ∇·D = ρ, we get ∂ρ/∂t = ∇·(∂D/∂t). Then the continuity equation ∇·J + ∂ρ/∂t = 0 becomes ∇·(J + ∂D/∂t) = 0.", "So replace J by J + J<sub>d</sub>, where J<sub>d</sub> = ∂D/∂t is the displacement current density. Between capacitor plates there is no conduction current, but a changing E gives a displacement current equal to the wire current."], formula: ["J<sub>d</sub> = ∂D/∂t = ε ∂E/∂t", "Continuity: ∇·J + ∂ρ/∂t = 0", "I<sub>d</sub> = ε₀ A dE/dt = dq/dt in a charging capacitor"] },
    { h: "Light from the equations", p: ["In free space (ρ = 0, J = 0) take the curl of Faraday's law: ∇ × (∇ × E) = −∂/∂t(∇ × B) = −μ₀ε₀ ∂²E/∂t². The left side equals −∇²E since ∇·E = 0.", "So ∇²E = μ₀ε₀ ∂²E/∂t². This is a wave equation with speed c = 1/√(μ₀ε₀) ≈ 3 × 10⁸ m/s. Light is an electromagnetic wave.", "Transverse nature: for a plane wave along z, ∇·E = 0 gives ∂E<sub>z</sub>/∂z = 0, so E<sub>z</sub> carries no wave. E and B are perpendicular to each other and to z."], formula: ["∇²E = μ₀ε₀ ∂²E/∂t²", "c = 1 / √(μ₀ε₀)", "E ⊥ B ⊥ direction of travel,  E₀/B₀ = c"] },
  ],
  examples: [
    { q: "Write Maxwell's equations in integral and differential forms and name each law.", steps: ["Gauss (electric): ∮D·dA = q ⇔ ∇·D = ρ.", "Gauss (magnetic): ∮B·dA = 0 ⇔ ∇·B = 0.", "Faraday: ∮E·dl = −dΦ<sub>B</sub>/dt ⇔ ∇ × E = −∂B/∂t.", "Ampere–Maxwell: ∮H·dl = I + dΦ<sub>D</sub>/dt ⇔ ∇ × H = J + ∂D/∂t.", "The differential forms follow from the integral forms by the divergence and Stokes theorems."], ans: "Four equations as above" },
    { q: "A parallel plate capacitor has plate area 0.01 m². The electric field between plates changes at 10<sup>12</sup> V m<sup>−1</sup> s<sup>−1</sup>. Find the displacement current (ε₀ = 8.854 × 10<sup>−12</sup> F/m).", steps: ["I<sub>d</sub> = ε₀ A dE/dt.", "I<sub>d</sub> = 8.854 × 10⁻¹² × 0.01 × 10¹² = 8.854 × 10⁻² A."], ans: "I<sub>d</sub> ≈ 0.0885 A" },
    { q: "In copper (σ = 5.8 × 10<sup>7</sup> S/m) at 1 MHz find the ratio of conduction to displacement current density (ε = ε₀).", steps: ["J<sub>c</sub> = σE and J<sub>d</sub> = ωε₀E (magnitudes).", "Ratio = σ / ωε₀, ω = 2π × 10⁶ = 6.283 × 10⁶ rad/s.", "ωε₀ = 6.283 × 10⁶ × 8.854 × 10⁻¹² = 5.563 × 10⁻⁵.", "Ratio = 5.8 × 10⁷ / 5.563 × 10⁻⁵ = 1.04 × 10¹²."], ans: "≈ 10¹²: displacement current is negligible in a good conductor" },
  ],
  mistakes: ["Dropping the displacement current term from the Ampere equation.", "Mixing up E and D, or B and H, in the integral forms. Use D for free charge and H for free current.", "Writing ∇·B = ρ. It is zero.", "Missing the minus sign in Faraday's law.", "Saying displacement current is a flow of charge. It is a changing electric field, which makes a magnetic field just like a current does."],
  check: [
    { q: "Which Maxwell equation says there are no magnetic monopoles?", o: ["∇·D = ρ", "∇·B = 0", "∇ × E = −∂B/∂t", "∇ × H = J + ∂D/∂t"], a: 1, why: "Zero divergence of B means closed field lines." },
    { q: "Displacement current density is", o: ["J = σE", "ε ∂E/∂t", "μ ∂H/∂t", "ρv"], a: 1, why: "J<sub>d</sub> = ∂D/∂t = ε ∂E/∂t." },
    { q: "Maxwell showed the speed of EM waves in free space is", o: ["√(μ₀ε₀)", "1/√(μ₀ε₀)", "μ₀/ε₀", "ε₀/μ₀"], a: 1, why: "c = 1/√(μ₀ε₀) ≈ 3 × 10⁸ m/s." },
    { q: "Between the plates of a charging capacitor, the current that gives the magnetic field is", o: ["conduction current", "displacement current", "zero", "eddy current"], a: 1, why: "No charge crosses the gap, but the changing E acts as the current." },
  ],
  lab: { id: "dispcurrent", label: "Open the displacement current lab" },
};

const box: Lesson = {
  intro: "A particle trapped in a one-dimensional box is the simplest quantum system you can solve exactly. It shows why energies come in steps, why the lowest energy is not zero, and why the particle is not equally likely to be everywhere. The derivation of its energy levels is a standard 8-mark question. You will learn each step and finish with two quick numericals.",
  sections: [
    { h: "The setup", p: ["A particle of mass m moves freely along x between two impenetrable walls at x = 0 and x = L. Inside the potential is V = 0. At the walls and outside it is infinite, so the particle cannot be outside: ψ = 0 for x ≤ 0 and x ≥ L.", "We need the wave function ψ(x) inside, which obeys the time-independent Schrödinger equation with V = 0."] },
    { h: "Solving the equation", p: ["Step 1: the equation is d²ψ/dx² + (2mE/ħ²) ψ = 0. Write k² = 2mE/ħ². So d²ψ/dx² + k²ψ = 0.", "Step 2: the general solution is ψ = A sin kx + B cos kx.", "Step 3: boundary condition ψ(0) = 0 gives B = 0. So ψ = A sin kx.", "Step 4: boundary condition ψ(L) = 0 gives sin kL = 0, so kL = nπ with n = 1, 2, 3, … (n = 0 would give ψ = 0 everywhere, no particle).", "Step 5: put k = nπ/L into k² = 2mE/ħ². E<sub>n</sub> = n²π²ħ²/2mL² = n²h²/8mL².", "Step 6: normalise: ∫₀ᴸ |ψ|² dx = 1 gives A²·L/2 = 1, so A = √(2/L)."], formula: ["ψ<sub>n</sub>(x) = √(2/L) sin(nπx/L),  n = 1, 2, 3 …", "E<sub>n</sub> = n²h² / 8mL²", "Probability density |ψ<sub>n</sub>|² = (2/L) sin²(nπx/L)"] },
    { h: "What the answer means", p: ["Energy is quantised. The levels go as 1, 4, 9, 16 … times E₁. The gap grows with n.", "The lowest energy E₁ = h²/8mL² is not zero. This is the zero-point energy. A confined particle can never be at rest, in line with the uncertainty principle.", "Squeeze the box (smaller L) and the energies rise as 1/L². This is why electrons in tiny nanostructures behave so differently.", "The ground state has one hump, with the particle most likely in the middle. The nth state has n − 1 nodes inside the box where the particle is never found. A classical particle would be equally likely anywhere."], formula: ["E<sub>1</sub> : E<sub>2</sub> : E<sub>3</sub> = 1 : 4 : 9", "Number of nodes (inside) = n − 1", "Photon from n → m: hν = (n² − m²) h² / 8mL²"] },
  ],
  examples: [
    { q: "Solve the Schrödinger equation for a particle in a one-dimensional infinite potential well of width L and find its energy eigenvalues and normalised eigenfunctions.", steps: ["Inside: d²ψ/dx² + k²ψ = 0 with k² = 2mE/ħ².", "ψ = A sin kx + B cos kx. ψ(0) = 0 gives B = 0.", "ψ(L) = 0 gives kL = nπ, so E<sub>n</sub> = n²h²/8mL².", "Normalising: A²∫₀ᴸ sin²(nπx/L)dx = A²L/2 = 1, so A = √(2/L)."], ans: "ψ<sub>n</sub> = √(2/L) sin(nπx/L);  E<sub>n</sub> = n²h²/8mL²" },
    { q: "An electron is trapped in a box of width 0.2 nm. Find the ground state energy, and the wavelength of the photon emitted when it falls from n = 2 to n = 1 (h = 6.626 × 10<sup>−34</sup> J s, m = 9.109 × 10<sup>−31</sup> kg).", steps: ["E₁ = h²/8mL² = (6.626 × 10⁻³⁴)² / (8 × 9.109 × 10⁻³¹ × (2 × 10⁻¹⁰)²).", "= 4.390 × 10⁻⁶⁷ / 2.915 × 10⁻⁴⁹ = 1.506 × 10⁻¹⁸ J = 9.40 eV.", "E₂ − E₁ = 3E₁ = 28.2 eV.", "λ = hc / ΔE = 1240 eV nm / 28.2 eV = 44.0 nm."], ans: "E₁ ≈ 9.4 eV; λ ≈ 44 nm (ultraviolet)" },
    { q: "Find the probability of finding a particle in its ground state between x = 0 and x = L/4.", steps: ["P = ∫₀^{L/4} (2/L) sin²(πx/L) dx.", "sin²θ = (1 − cos 2θ)/2, so P = [x/L − sin(2πx/L)/(2π)] from 0 to L/4.", "P = 1/4 − sin(π/2)/(2π) = 0.25 − 0.159."], ans: "P ≈ 0.091 (about 9%)" },
  ],
  mistakes: ["Allowing n = 0. It gives ψ = 0, so no particle exists.", "Writing the energy with ħ but using h's formula, or the reverse. E = n²π²ħ²/2mL² = n²h²/8mL². Do not mix them.", "Forgetting to apply both boundary conditions, or applying them in the wrong order. First kills cos, second quantises k.", "Skipping normalisation, so A is left undetermined.", "Saying the probability is maximum at the walls. It is zero at the walls."],
  check: [
    { q: "The allowed energies of a particle in a 1D box are proportional to", o: ["n", "n²", "1/n", "1/n²"], a: 1, why: "E<sub>n</sub> = n²h²/8mL²." },
    { q: "Doubling the width L of the box makes the ground state energy", o: ["double", "halve", "become one quarter", "become four times"], a: 2, why: "E ∝ 1/L²." },
    { q: "The number of nodes inside the box for n = 4 is", o: ["1", "2", "3", "4"], a: 2, why: "n − 1 = 3 nodes." },
    { q: "The normalisation constant for the box is", o: ["√(L/2)", "√(2/L)", "2/L", "L/2"], a: 1, why: "A²L/2 = 1 gives A = √(2/L)." },
  ],
  lab: { id: "box", label: "Open the particle in a box lab" },
};

const hall: Lesson = {
  intro: "The Hall effect lets you find whether a semiconductor is n-type or p-type, and also its carrier density, using only a strip, a current and a magnet. It is a standard 5-mark theory question with a numerical on the Hall coefficient or mobility. You will learn the cause, the derivation of V<sub>H</sub> and R<sub>H</sub>, and how to use them.",
  sections: [
    { h: "What happens", p: ["Take a thin rectangular strip. Pass a current I along its length (x-axis). Apply a magnetic field B perpendicular to the strip (z-axis). A small voltage appears across the width (y-axis). This is the Hall voltage V<sub>H</sub>.", "The reason is the magnetic force. Moving charges feel F = qv × B. This pushes carriers to one side of the strip, so that side becomes charged. A transverse electric field E<sub>H</sub> builds up and balances the magnetic force.", "For an n-type strip the electrons are pushed to one side, so that edge is negative. In a p-type strip the holes pile up on the same edge, which becomes positive. So the sign of V<sub>H</sub> tells the type."] },
    { h: "Derivation", p: ["Step 1: in steady state the electric force balances the magnetic force. eE<sub>H</sub> = e v<sub>d</sub> B, so E<sub>H</sub> = v<sub>d</sub> B.", "Step 2: the current density is J = nev<sub>d</sub>, so v<sub>d</sub> = J/ne = I/(n e w t), where w is the width and t is the thickness (along B).", "Step 3: the Hall voltage is V<sub>H</sub> = E<sub>H</sub> w = v<sub>d</sub> B w = BI/(n e t).", "Step 4: define the Hall coefficient R<sub>H</sub> = E<sub>H</sub>/(JB) = 1/(ne) for electrons (negative sign) and 1/(pe) for holes (positive sign). So V<sub>H</sub> = R<sub>H</sub> B I / t."], formula: ["V<sub>H</sub> = BI / (n e t) = R<sub>H</sub> B I / t", "R<sub>H</sub> = 1/(ne)  (n-type, negative),  R<sub>H</sub> = 1/(pe)  (p-type, positive)", "E<sub>H</sub> = v<sub>d</sub> B"] },
    { h: "What you get out of it", p: ["From V<sub>H</sub>, B, I and t you get n (or p) directly. Together with the conductivity σ you also get the mobility.", "Applications: finding the type and density of carriers, measuring mobility, measuring magnetic fields (Hall probe or gaussmeter), and Hall-effect current sensors."], formula: ["n = BI / (e t V<sub>H</sub>)", "Mobility μ = |R<sub>H</sub>| σ", "σ = neμ"] },
  ],
  examples: [
    { q: "Explain the Hall effect and derive expressions for the Hall voltage and the Hall coefficient.", steps: ["Strip of width w and thickness t carries current I along x with B along z.", "Carriers drift with v<sub>d</sub> and feel a sideways force. Charge builds on the edges until eE<sub>H</sub> = ev<sub>d</sub>B.", "v<sub>d</sub> = I/(newt), so V<sub>H</sub> = E<sub>H</sub>w = BI/(net).", "R<sub>H</sub> = V<sub>H</sub>t/(BI) = 1/(ne)."], ans: "V<sub>H</sub> = BI/(net);  R<sub>H</sub> = 1/(ne)" },
    { q: "A semiconductor strip of thickness 0.1 mm carries 10 mA in a field of 0.5 T. The carrier density is 5 × 10<sup>21</sup> m<sup>−3</sup>. Find the Hall voltage (e = 1.602 × 10<sup>−19</sup> C).", steps: ["V<sub>H</sub> = BI/(net).", "Numerator: 0.5 × 0.01 = 5 × 10⁻³.", "Denominator: 5 × 10²¹ × 1.602 × 10⁻¹⁹ × 10⁻⁴ = 0.0801.", "V<sub>H</sub> = 5 × 10⁻³ / 0.0801 = 0.0624 V."], ans: "V<sub>H</sub> ≈ 62 mV" },
    { q: "For an n-type germanium sample, R<sub>H</sub> = 3.66 × 10<sup>−4</sup> m³/C (magnitude) and σ = 112 Ω<sup>−1</sup>m<sup>−1</sup>. Find the carrier density and mobility.", steps: ["n = 1/(|R<sub>H</sub>|e) = 1 / (3.66 × 10⁻⁴ × 1.602 × 10⁻¹⁹).", "n = 1.71 × 10²² m⁻³.", "μ = |R<sub>H</sub>|σ = 3.66 × 10⁻⁴ × 112 = 0.041 m²/V s."], ans: "n ≈ 1.7 × 10²² m⁻³; μ ≈ 0.041 m²/V s" },
  ],
  mistakes: ["Using the width in V<sub>H</sub> = BI/(net). The thickness t (along the field) is the one that appears.", "Forgetting that R<sub>H</sub> is negative for electrons and positive for holes.", "Using units of mm or cm without converting to metres.", "Applying B along the current. The field must be perpendicular to the current.", "Using mobility = R<sub>H</sub>/σ. It is the product R<sub>H</sub> × σ."],
  check: [
    { q: "The Hall coefficient of an n-type semiconductor is", o: ["positive and equal to 1/ne", "negative and equal to −1/ne", "zero", "equal to σ/ne"], a: 1, why: "Electrons are negative, so R<sub>H</sub> = −1/(ne)." },
    { q: "In V<sub>H</sub> = BI/(net), t is the dimension", o: ["along the current", "along the magnetic field", "across the Hall voltage contacts", "of the contacts"], a: 1, why: "t is the thickness parallel to B." },
    { q: "Hall voltage across a metal strip is much smaller than in a semiconductor because", o: ["metals have very high n", "metals have low conductivity", "B is zero", "mobility is zero"], a: 0, why: "V<sub>H</sub> ∝ 1/n and metals have n ≈ 10²⁸–10²⁹ m⁻³." },
    { q: "The mobility from Hall measurements is", o: ["R<sub>H</sub>/σ", "R<sub>H</sub> σ", "σ/R<sub>H</sub>", "R<sub>H</sub>/B"], a: 1, why: "σ = neμ and R<sub>H</sub> = 1/ne, so μ = R<sub>H</sub> σ." },
  ],
  lab: { id: "hall", label: "Open the Hall effect lab" },
};

/** AHT-001 lessons. Keys are "AHT-001:unit:topic" (topic = 1-based index in the syllabus unit's topics). */
export const L_AHT001: Record<string, Lesson> = {
  "AHT-001:1:7": rings,
  "AHT-001:1:10": grating,
  "AHT-001:2:11": einstein,
  "AHT-001:3:7": maxwell,
  "AHT-001:3:10": poynting,
  "AHT-001:4:13": box,
  "AHT-001:5:5": hall,
};
