import type { Lesson } from "./types";

const mot: Lesson = {
  intro: "Molecular orbital theory explains why O₂ is magnetic, why N₂ is so unreactive and why CO is so strongly bonded. Drawing the MO diagram of O₂, N₂ or CO, with bond order and magnetic behaviour, is the most repeated Unit 1 question in Engineering Chemistry. You will learn the rules, the two filling orders and how to read bond order from any diagram.",
  sections: [
    { h: "The core idea", p: ["When two atoms come together, their atomic orbitals combine (LCAO, linear combination of atomic orbitals). N atomic orbitals give N molecular orbitals.", "Adding the waves in phase gives a bonding MO, lower in energy, with electron density between the nuclei. Subtracting them gives an antibonding MO (marked *), higher in energy, with a node between the nuclei.", "Electrons fill MOs by three rules: lowest energy first (Aufbau), at most two electrons per orbital with opposite spin (Pauli), and one electron in each of equal-energy orbitals before pairing (Hund)."], formula: ["Bond order = ½ (N<sub>b</sub> − N<sub>a</sub>)", "N<sub>b</sub> = electrons in bonding MOs,  N<sub>a</sub> = electrons in antibonding MOs", "Higher bond order ⇒ shorter, stronger bond"] },
    { h: "Two energy orders for second-row diatomics", p: ["For Li₂ to N₂ the 2s and 2p orbitals mix, so π2p lies below σ2p: σ1s < σ*1s < σ2s < σ*2s < π2p<sub>x</sub> = π2p<sub>y</sub> < σ2p<sub>z</sub> < π*2p<sub>x</sub> = π*2p<sub>y</sub> < σ*2p<sub>z</sub>.", "For O₂ and F₂ the mixing is small, so σ2p drops below π2p: σ1s < σ*1s < σ2s < σ*2s < σ2p<sub>z</sub> < π2p<sub>x</sub> = π2p<sub>y</sub> < π*2p<sub>x</sub> = π*2p<sub>y</sub> < σ*2p<sub>z</sub>.", "Always say which order you are using. Examiners give marks for it."] },
    { h: "Oxygen, nitrogen and CO", p: ["N₂ (14 electrons): σ1s² σ*1s² σ2s² σ*2s² π2p<sub>x</sub>² π2p<sub>y</sub>² σ2p<sub>z</sub>². N<sub>b</sub> = 10, N<sub>a</sub> = 4, bond order = 3. No unpaired electrons: diamagnetic. It is a triple bond, very strong, very unreactive.", "O₂ (16 electrons): ... σ2p<sub>z</sub>² π2p<sub>x</sub>² π2p<sub>y</sub>² π*2p<sub>x</sub>¹ π*2p<sub>y</sub>¹. N<sub>b</sub> = 10, N<sub>a</sub> = 6, bond order = 2. Two unpaired electrons in degenerate π* orbitals, so O₂ is paramagnetic, which valence bond theory cannot explain. Liquid oxygen is attracted to a magnet.", "CO (14 electrons) is isoelectronic with N₂, so it has the N₂-type diagram with bond order 3 and is diamagnetic. Because O is more electronegative, the bonding MOs are closer to O and the antibonding MOs closer to C. The HOMO (σ2p) is mostly on carbon, so CO donates through carbon, as in metal carbonyls."], formula: ["N₂: bond order 3, diamagnetic",  "O₂: bond order 2, paramagnetic (2 unpaired e⁻)", "O₂⁺: 2.5,  O₂⁻: 1.5,  O₂²⁻: 1", "Spin-only magnetic moment μ = √(n(n + 2)) BM"] },
  ],
  examples: [
    { q: "Draw the molecular orbital energy level diagram of O₂. Find its bond order and explain why it is paramagnetic.", steps: ["Use the O₂ order: σ2p lies below π2p. Total electrons = 16, of which 4 are in 1s orbitals.", "Configuration: σ1s² σ*1s² σ2s² σ*2s² σ2p<sub>z</sub>² π2p<sub>x</sub>² π2p<sub>y</sub>² π*2p<sub>x</sub>¹ π*2p<sub>y</sub>¹.", "N<sub>b</sub> = 2 + 2 + 2 + 2 + 2 = 10 and N<sub>a</sub> = 2 + 2 + 1 + 1 = 6, so bond order = (10 − 6)/2 = 2.", "The last two electrons occupy separate degenerate π* orbitals (Hund's rule), unpaired and with parallel spins. So O₂ is paramagnetic."], ans: "Bond order 2; paramagnetic (2 unpaired electrons)" },
    { q: "Compare the bond order, bond length and magnetic nature of O₂, O₂⁺, O₂⁻ and O₂²⁻.", steps: ["Start from O₂ (π*)² and add or remove electrons from the π* orbitals.", "O₂⁺: 15 electrons, π*¹, bond order (10 − 5)/2 = 2.5, 1 unpaired, paramagnetic.", "O₂: bond order 2, 2 unpaired, paramagnetic.", "O₂⁻: 17 electrons, π*³, bond order (10 − 7)/2 = 1.5, 1 unpaired, paramagnetic.", "O₂²⁻: 18 electrons, π*⁴, bond order (10 − 8)/2 = 1, 0 unpaired, diamagnetic.", "Bond length increases as bond order falls: O₂⁺ < O₂ < O₂⁻ < O₂²⁻."], ans: "Bond order 2.5, 2, 1.5, 1; bond length increases in that order" },
    { q: "Calculate the spin-only magnetic moment of O₂ and N₂⁺ (use μ = √(n(n + 2)) BM).", steps: ["O₂ has n = 2 unpaired electrons: μ = √(2 × 4) = √8 = 2.83 BM.", "N₂⁺ has 13 electrons: the electron removed comes from σ2p (N₂ order), leaving π2p filled and σ2p¹, so n = 1.", "μ = √(1 × 3) = √3 = 1.73 BM. Bond order of N₂⁺ = (9 − 4)/2 = 2.5."], ans: "O₂: 2.83 BM;  N₂⁺: 1.73 BM, bond order 2.5" },
  ],
  mistakes: ["Using the O₂ filling order for N₂ or the N₂ order for O₂. They are different.", "Counting the 1s electrons wrongly. They cancel (2 bonding + 2 antibonding), but include them in the electron count.", "Writing bond order as N<sub>b</sub> − N<sub>a</sub> without the ½.", "Calling O₂ diamagnetic because valence bond theory shows O=O with all electrons paired.", "Forgetting that removing an electron from an antibonding orbital raises bond order (O₂ → O₂⁺), and adding to bonding orbital does too.", "Drawing CO with equal atomic orbital energies. O's orbitals are lower than C's."],
  check: [
    { q: "The bond order of N₂ is", o: ["1", "2", "2.5", "3"], a: 3, why: "N<sub>b</sub> = 10, N<sub>a</sub> = 4, so (10 − 4)/2 = 3." },
    { q: "O₂ is paramagnetic because it has", o: ["no unpaired electrons", "two unpaired electrons in π* orbitals", "two unpaired electrons in σ orbitals", "a double bond"], a: 1, why: "The last two electrons go into the two degenerate π* orbitals, one each." },
    { q: "Which species has the highest bond order?", o: ["O₂⁻", "O₂", "O₂⁺", "O₂²⁻"], a: 2, why: "O₂⁺ has bond order 2.5; the others are 1.5, 2 and 1." },
    { q: "CO and N₂ have the same bond order because they are", o: ["isotopes", "isoelectronic", "isomers", "allotropes"], a: 1, why: "Both have 14 electrons, so the same MO filling and bond order 3." },
  ],
  lab: { id: "motheory", label: "Open the molecular orbital diagrams lab" },
};

const cft: Lesson = {
  intro: "Crystal field theory (CFT) explains the colour, magnetism and stability of transition metal complexes in one picture: the d-orbitals split in energy when ligands approach. Why [Co(NH₃)₆]³⁺ is diamagnetic and why [Ni(CN)₄]²⁻ is square planar are repeated PYQs. You will learn the splitting, how to decide high or low spin, and how to find CFSE.",
  sections: [
    { h: "The picture", p: ["CFT treats ligands as negative point charges around a positive metal ion. The five d-orbitals are equal in energy in a free ion. Once ligands arrive, the d-electrons are repelled differently depending on the orbital's direction.", "In an octahedral complex, six ligands sit on the x, y and z axes. The orbitals pointing along the axes (d<sub>x²−y²</sub> and d<sub>z²</sub>, called e<sub>g</sub>) are repelled strongly and rise in energy. The orbitals pointing between the axes (d<sub>xy</sub>, d<sub>yz</sub>, d<sub>xz</sub>, called t<sub>2g</sub>) are repelled less and fall.", "The gap is Δ<sub>o</sub> (octahedral splitting). The t<sub>2g</sub> set is at −0.4Δ<sub>o</sub> and the e<sub>g</sub> set at +0.6Δ<sub>o</sub>, measured from the average energy."], formula: ["t<sub>2g</sub>: −0.4 Δ<sub>o</sub> each,  e<sub>g</sub>: +0.6 Δ<sub>o</sub> each", "CFSE = (−0.4 x + 0.6 y) Δ<sub>o</sub>, x = electrons in t<sub>2g</sub>, y = electrons in e<sub>g</sub>", "Tetrahedral: Δ<sub>t</sub> = (4/9) Δ<sub>o</sub>, so almost always high spin"] },
    { h: "Strong and weak field, high and low spin", p: ["Electrons for d⁴ to d⁷ have a choice. If Δ<sub>o</sub> is small (weak field ligand) they spread over all five orbitals before pairing: high spin. If Δ<sub>o</sub> is larger than the pairing energy P (strong field ligand), they fill t<sub>2g</sub> first and pair up: low spin.", "The spectrochemical series orders ligands by field strength: I⁻ < Br⁻ < Cl⁻ < F⁻ < OH⁻ < H₂O < NH₃ < en < NO₂⁻ < CN⁻ < CO. Also a higher charge on the metal and a 4d/5d metal give larger Δ<sub>o</sub>.", "The d⁸ ion with strong ligands forms square planar complexes, as in [Ni(CN)₄]²⁻, because the high-energy d<sub>x²−y²</sub> orbital is left empty."], formula: ["Δ<sub>o</sub> > P  ⇒ low spin (strong field)", "Δ<sub>o</sub> < P  ⇒ high spin (weak field)", "μ = √(n(n + 2)) BM, n = number of unpaired electrons"] },
    { h: "What CFT explains", p: ["Colour: a d-electron absorbs light equal to Δ<sub>o</sub> to jump from t<sub>2g</sub> to e<sub>g</sub>. We see the complementary colour.", "Magnetism: count unpaired electrons from the filling pattern. Stability: more negative CFSE means a more stable complex.", "Limitation: CFT treats ligands as point charges and ignores covalent bonding. It cannot explain why a neutral ligand like CO sits high in the series. For that you need ligand field theory or MOT."] },
  ],
  examples: [
    { q: "Explain on the basis of CFT why [Co(NH₃)₆]³⁺ is diamagnetic.", steps: ["Co is Z = 27. Co³⁺ has configuration 3d⁶.", "NH₃ is a strong field ligand (Δ<sub>o</sub> > P), so the six electrons pair up in t<sub>2g</sub>: t<sub>2g</sub>⁶ e<sub>g</sub>⁰.", "No unpaired electrons, so the complex is diamagnetic (low spin). In valence bond language it is inner orbital d²sp³.", "CFSE = −0.4 × 6 Δ<sub>o</sub> = −2.4 Δ<sub>o</sub> (before pairing energy)."], ans: "Low spin t<sub>2g</sub>⁶, n = 0, diamagnetic" },
    { q: "Explain why [Ni(CN)₄]²⁻ is square planar and diamagnetic while [NiCl₄]²⁻ is tetrahedral and paramagnetic.", steps: ["Ni²⁺ is 3d⁸.", "CN⁻ is a very strong field ligand. It forces the d⁸ electrons to pair in four lower orbitals and leaves the d<sub>x²−y²</sub> orbital empty for dsp² hybridisation. This gives a square planar shape with n = 0, diamagnetic.", "Cl⁻ is weak field. The electrons stay unpaired with sp³ hybridisation and tetrahedral shape. Two unpaired electrons make [NiCl₄]²⁻ paramagnetic, μ = √8 = 2.83 BM."], ans: "[Ni(CN)₄]²⁻ square planar, diamagnetic;  [NiCl₄]²⁻ tetrahedral, paramagnetic" },
    { q: "Find the CFSE and spin-only magnetic moment of [Fe(H₂O)₆]²⁺ (H₂O is a weak field ligand). Then compare with [Fe(CN)₆]⁴⁻ (strong field).", steps: ["Fe²⁺ is 3d⁶ in both complexes.", "[Fe(H₂O)₆]²⁺, high spin: t<sub>2g</sub>⁴ e<sub>g</sub>². CFSE = (−0.4 × 4 + 0.6 × 2) Δ<sub>o</sub> = −0.4 Δ<sub>o</sub>. Unpaired n = 4, μ = √24 = 4.90 BM.", "[Fe(CN)₆]⁴⁻, low spin: t<sub>2g</sub>⁶ e<sub>g</sub>⁰. CFSE = −2.4 Δ<sub>o</sub>. n = 0, μ = 0."], ans: "Aqua: −0.4Δ<sub>o</sub>, 4.90 BM;  cyano: −2.4Δ<sub>o</sub>, diamagnetic" },
  ],
  mistakes: ["Mixing up the names: e<sub>g</sub> are the higher orbitals in an octahedral field, t<sub>2g</sub> the lower.", "Forgetting to find the oxidation state of the metal first. Co in [Co(NH₃)₆]³⁺ is +3 (3d⁶), not 3d⁷.", "Calling every Δ<sub>o</sub> large. Tetrahedral Δ<sub>t</sub> is only 4/9 of Δ<sub>o</sub>, so tetrahedral complexes are high spin.", "Using the CFSE formula with the signs reversed. t<sub>2g</sub> electrons are stabilising (−0.4).", "Counting d electrons from the neutral atom (4s² 3d⁶), without removing 4s electrons first.", "Writing that d¹ to d³ and d⁸ to d¹⁰ can be high or low spin in an octahedral field. Only d⁴ to d⁷ can."],
  check: [
    { q: "In an octahedral field the d-orbitals split into", o: ["t₂ and e", "t<sub>2g</sub> (lower) and e<sub>g</sub> (higher)", "e<sub>g</sub> (lower) and t<sub>2g</sub> (higher)", "three levels"], a: 1, why: "The three orbitals between the axes are lower; the two along the axes are higher." },
    { q: "The CFSE of a low-spin d⁶ octahedral ion is", o: ["−0.4 Δ<sub>o</sub>", "−1.2 Δ<sub>o</sub>", "−2.4 Δ<sub>o</sub>", "0"], a: 2, why: "t<sub>2g</sub>⁶: 6 × (−0.4) = −2.4." },
    { q: "Which ligand produces the largest splitting?", o: ["I⁻", "H₂O", "NH₃", "CN⁻"], a: 3, why: "CN⁻ is near the top of the spectrochemical series." },
    { q: "A high-spin Mn²⁺ (d⁵) octahedral complex has spin-only moment (BM)", o: ["0", "1.73", "3.87", "5.92"], a: 3, why: "n = 5, μ = √(5 × 7) = 5.92 BM." },
  ],
  lab: { id: "cft", label: "Open the crystal field splitting lab" },
};

const nernst: Lesson = {
  intro: "The Nernst equation tells you the voltage of a cell when concentrations are not 1 M. It is derived in the theory question and used in 4-mark numericals nearly every year. You will derive it from free energy, calculate cell EMF at 25 °C and use it to find the equilibrium constant.",
  sections: [
    { h: "Electrode potential and cell EMF", p: ["A galvanic cell has two half-cells: oxidation at the anode, reduction at the cathode. EMF = E<sub>cathode</sub> − E<sub>anode</sub>, both written as reduction potentials.", "Standard potentials E° are measured at 1 M concentration, 1 atm and 298 K. In real cells, concentrations differ, so E changes. The Nernst equation says by how much."] },
    { h: "Deriving the Nernst equation", p: ["Step 1: for a reaction aA + bB → cC + dD the free energy change is ΔG = ΔG° + RT ln Q, where Q = [C]<sup>c</sup>[D]<sup>d</sup> / ([A]<sup>a</sup>[B]<sup>b</sup>).", "Step 2: electrical work from the cell is nFE, so ΔG = −nFE and ΔG° = −nFE°.", "Step 3: substitute. −nFE = −nFE° + RT ln Q.", "Step 4: divide by −nF. E = E° − (RT/nF) ln Q.", "Step 5: put R = 8.314 J/mol K, T = 298 K, F = 96485 C/mol and convert ln to log₁₀ (multiply by 2.303). The factor 2.303RT/F = 0.0591 V."], formula: ["E<sub>cell</sub> = E° − (RT/nF) ln Q", "At 25 °C:  E<sub>cell</sub> = E° − (0.0591/n) log Q", "Single electrode:  E = E° + (0.0591/n) log [M<sup>n+</sup>]  (for M<sup>n+</sup> + ne⁻ → M)"] },
    { h: "What else it gives", p: ["At equilibrium E = 0 and Q = K. So E° = (0.0591/n) log K, or log K = nE°/0.0591. A large positive E° means a very large K.", "Also ΔG° = −nFE°. A positive E° means a spontaneous reaction.", "For a concentration cell the two electrodes are the same metal, so E° = 0 and E = (0.0591/n) log (C₂/C₁), where C₂ is the higher concentration at the cathode.", "Remember: solids and pure liquids are not in Q. Only dissolved species (and gases by pressure) appear."], formula: ["log K = nE° / 0.0591  (25 °C)", "ΔG° = −nFE°", "Concentration cell: E = (0.0591/n) log (C<sub>cathode</sub> / C<sub>anode</sub>)"] },
  ],
  examples: [
    { q: "Derive the Nernst equation for a cell reaction and write it for a single electrode.", steps: ["ΔG = ΔG° + RT ln Q and ΔG = −nFE, ΔG° = −nFE°.", "So −nFE = −nFE° + RT ln Q, giving E = E° − (RT/nF) ln Q.", "At 298 K: E = E° − (0.0591/n) log Q.", "For M<sup>n+</sup> + ne⁻ → M, Q = 1/[M<sup>n+</sup>], so E = E° + (0.0591/n) log [M<sup>n+</sup>]."], ans: "E = E° − (0.0591/n) log Q at 25 °C" },
    { q: "Calculate the EMF at 25 °C of the cell Zn | Zn²⁺(0.01 M) ‖ Cu²⁺(0.1 M) | Cu. E°(Zn²⁺/Zn) = −0.76 V and E°(Cu²⁺/Cu) = +0.34 V.", steps: ["Cell reaction: Zn + Cu²⁺ → Zn²⁺ + Cu, n = 2.", "E° = 0.34 − (−0.76) = 1.10 V.", "Q = [Zn²⁺]/[Cu²⁺] = 0.01/0.1 = 0.1, so log Q = −1.", "E = 1.10 − (0.0591/2)(−1) = 1.10 + 0.0296 = 1.1296 V."], ans: "E ≈ 1.13 V" },
    { q: "For the cell Ni | Ni²⁺(0.02 M) ‖ Cu²⁺(0.2 M) | Cu find the EMF at 25 °C and the equilibrium constant of the cell reaction. E°(Ni²⁺/Ni) = −0.25 V, E°(Cu²⁺/Cu) = +0.34 V.", steps: ["E° = 0.34 − (−0.25) = 0.59 V, n = 2.", "Q = 0.02/0.2 = 0.1, log Q = −1.", "E = 0.59 + 0.0296 = 0.6196 V.", "log K = nE°/0.0591 = 2 × 0.59 / 0.0591 = 19.97, so K ≈ 9.3 × 10¹⁹."], ans: "E ≈ 0.62 V;  K ≈ 10²⁰" },
  ],
  mistakes: ["Putting concentrations of the oxidised form upside down in Q. Q is [products]/[reactants] of the cell reaction, with anode ion on top.", "Using n = 1 when the half-reaction transfers 2 electrons.", "Subtracting the anode from the cathode the wrong way, which gives a negative E° for a working cell.", "Including solid metals in Q.", "Using ln instead of log with the factor 0.0591. With ln, the factor is RT/F = 0.0257.", "Forgetting that 0.0591 is only valid at 25 °C."],
  check: [
    { q: "At 25 °C, the Nernst equation for a cell is", o: ["E = E° + 0.0591 log Q", "E = E° − (0.0591/n) log Q", "E = E° − 0.0591 n log Q", "E = E°/Q"], a: 1, why: "E = E° − (2.303RT/nF) log Q, and 2.303RT/F = 0.0591 V." },
    { q: "In a cell at equilibrium, the EMF is", o: ["E°", "1 V", "0", "infinite"], a: 2, why: "At equilibrium no net work can be drawn: E = 0 and Q = K." },
    { q: "If [Cu²⁺] is raised in the Zn–Cu cell, the EMF", o: ["decreases", "increases", "stays the same", "becomes zero"], a: 1, why: "A larger [Cu²⁺] makes Q smaller, so −(0.0591/n) log Q increases." },
    { q: "A concentration cell has E° equal to", o: ["0 V", "1.10 V", "0.0591 V", "depends on the metal"], a: 0, why: "Both electrodes are the same, so the standard potentials cancel." },
  ],
  lab: { id: "nernst", label: "Open the Galvanic cell and Nernst lab" },
};

const limesoda: Lesson = {
  intro: "Lime–soda softening turns calcium and magnesium into insoluble solids you can filter out. Questions ask for the principle and reactions, and a numerical asks for the lime and soda required per litre of water. You will learn the chemistry, the hardness in CaCO₃ equivalents and the standard formulae.",
  sections: [
    { h: "Principle", p: ["Hard water contains dissolved Ca²⁺ and Mg²⁺. Temporary hardness comes from bicarbonates, and permanent hardness from chlorides and sulphates.", "Slaked lime Ca(OH)₂ removes temporary hardness and magnesium. Soda ash Na₂CO₃ removes the calcium that remains (permanent Ca hardness, including the CaCl₂ or CaSO₄ formed by the lime reactions). The products are CaCO₃ and Mg(OH)₂, which settle as sludge."] },
    { h: "Reactions", p: ["Lime reacts with temporary hardness: Ca(HCO₃)₂ + Ca(OH)₂ → 2CaCO₃↓ + 2H₂O, and Mg(HCO₃)₂ + 2Ca(OH)₂ → 2CaCO₃↓ + Mg(OH)₂↓ + 2H₂O.", "Lime also removes permanent magnesium: MgCl₂ + Ca(OH)₂ → Mg(OH)₂↓ + CaCl₂, and MgSO₄ + Ca(OH)₂ → Mg(OH)₂↓ + CaSO₄. Notice that this just swaps Mg hardness for Ca hardness.", "Soda removes permanent calcium: CaCl₂ + Na₂CO₃ → CaCO₃↓ + 2NaCl, and CaSO₄ + Na₂CO₃ → CaCO₃↓ + Na₂SO₄.", "Lime also uses up dissolved CO₂: CO₂ + Ca(OH)₂ → CaCO₃↓ + H₂O."] },
    { h: "Cold and hot processes, and why mg/L as CaCO₃", p: ["Cold process: done at room temperature. Needs a coagulant (alum or ferrous sulphate), and residual hardness is 50 to 60 mg/L. Hot process: 80 to 150 °C, faster, no coagulant needed, residual hardness only 15 to 30 mg/L.", "To compare different salts, express every hardness as its CaCO₃ equivalent: (mass of salt × 100) / molar mass of salt. Molar masses: Ca(HCO₃)₂ 162, Mg(HCO₃)₂ 146, CaSO₄ 136, CaCl₂ 111, MgSO₄ 120, MgCl₂ 95, CaCO₃ 100, Ca(OH)₂ 74, Na₂CO₃ 106."], formula: ["Equivalent of CaCO₃ = mass × 100 / molar mass", "Lime (mg/L) = 74/100 × [Temp Ca + 2 × Temp Mg + Perm Mg + CO₂]  (all as CaCO₃)", "Soda (mg/L) = 106/100 × [Perm Ca + Perm Mg]  (all as CaCO₃)", "Divide by purity (as a fraction) if the lime or soda is impure"] },
    { h: "Why the factors", p: ["Temporary Mg needs 2 moles of lime for every mole of Mg(HCO₃)₂, once to remove the carbonate and once to precipitate Mg(OH)₂. That is why it has the factor 2.", "Each mole of Ca(OH)₂ is 74 g and is equal to a mole of CaCO₃ (100 g). So lime in mg of Ca(OH)₂ = 74/100 times the hardness in CaCO₃ equivalents. Na₂CO₃ is 106 g per mole, giving the 106/100 factor."] },
  ],
  examples: [
    { q: "Discuss the principle of lime–soda process for softening of hard water, with reactions.", steps: ["Lime Ca(OH)₂ and soda Na₂CO₃ are added to convert soluble Ca²⁺ and Mg²⁺ salts to insoluble CaCO₃ and Mg(OH)₂.", "Temporary hardness is removed by lime alone (give the Ca(HCO₃)₂ and Mg(HCO₃)₂ reactions).", "Permanent Mg hardness is converted by lime to Mg(OH)₂ and an equivalent amount of Ca salt.", "All permanent Ca hardness is then removed by soda (give CaCl₂ and CaSO₄ reactions).", "Cold process needs coagulant, hot process is faster and gives softer water."], ans: "Hardness ions precipitate as CaCO₃ and Mg(OH)₂" },
    { q: "A water sample contains per litre: Ca(HCO₃)₂ = 16.2 mg, Mg(HCO₃)₂ = 14.6 mg, CaSO₄ = 13.6 mg, MgCl₂ = 9.5 mg. Find the temporary, permanent and total hardness.", steps: ["Ca(HCO₃)₂: 16.2 × 100/162 = 10 mg/L.", "Mg(HCO₃)₂: 14.6 × 100/146 = 10 mg/L.", "CaSO₄: 13.6 × 100/136 = 10 mg/L.", "MgCl₂: 9.5 × 100/95 = 10 mg/L.", "Temporary = 10 + 10 = 20 mg/L. Permanent = 10 + 10 = 20 mg/L. Total = 40 mg/L as CaCO₃."], ans: "Temporary 20, permanent 20, total 40 mg/L as CaCO₃" },
    { q: "Using the sample above, calculate the lime (80% pure) and soda (90% pure) required to soften 10,000 L of the water.", steps: ["Lime = 74/100 × [Temp Ca + 2 Temp Mg + Perm Mg] = 0.74 × [10 + 2 × 10 + 10] = 0.74 × 40 = 29.6 mg/L.", "For 10,000 L: 29.6 × 10⁴ mg = 296 g of pure lime. Impure lime = 296 / 0.80 = 370 g.", "Soda = 106/100 × [Perm Ca + Perm Mg] = 1.06 × [10 + 10] = 21.2 mg/L.", "For 10,000 L: 212 g of pure soda. Impure soda = 212 / 0.90 = 235.6 g."], ans: "Lime ≈ 370 g; soda ≈ 236 g" },
  ],
  mistakes: ["Forgetting the factor 2 for temporary magnesium hardness in the lime formula.", "Not converting each salt to CaCO₃ equivalents before adding. Adding raw milligrams of different salts is wrong.", "Putting temporary calcium hardness in the soda formula. Soda handles only permanent hardness.", "Using the soda formula without including permanent Mg hardness (lime turns it into Ca salt).", "Forgetting to divide by purity for impure chemicals, and mixing mg/L with volume (L) at the end.", "Mixing up cold and hot processes. Hot gives lower residual hardness."],
  check: [
    { q: "Temporary hardness is removed by", o: ["soda only", "lime", "boiling only", "alum only"], a: 1, why: "Ca(OH)₂ converts bicarbonates to insoluble CaCO₃ (and Mg(OH)₂)." },
    { q: "Lime required (mg/L) for temporary Mg hardness of x mg/L as CaCO₃ is", o: ["74x/100", "2 × 74x/100", "106x/100", "x"], a: 1, why: "Two moles of lime are consumed per mole of Mg(HCO₃)₂." },
    { q: "Soda ash removes", o: ["temporary hardness", "permanent calcium hardness", "dissolved CO₂", "all dissolved salts"], a: 1, why: "Na₂CO₃ precipitates Ca²⁺ from CaCl₂ and CaSO₄ as CaCO₃." },
    { q: "The CaCO₃ equivalent of 16.2 mg/L of Ca(HCO₃)₂ is", o: ["5", "10", "16.2", "20"], a: 1, why: "16.2 × 100/162 = 10 mg/L." },
  ],
  lab: { id: "softening", label: "Open the water softening lab" },
};

const corrosion: Lesson = {
  intro: "Corrosion is the slow destruction of metals by their surroundings, and rusting of iron is the best-known case. The rusting mechanism, dry versus wet corrosion, and cathodic protection together make up the most repeated block in Unit 3. You will learn the electrochemical mechanism and write the reactions that examiners expect.",
  sections: [
    { h: "Dry and wet corrosion", p: ["Dry (chemical) corrosion is direct attack by gases such as O₂, Cl₂ or SO₂ with no liquid present. A thin oxide layer forms on the metal. If the layer is non-porous and sticks (as in Al, Cr) it protects. If it is porous or cracks (as in Fe, Mg) corrosion goes on. The Pilling–Bedworth rule says the oxide volume must be at least that of the metal to cover it.", "Wet (electrochemical) corrosion needs a liquid electrolyte, an anode and a cathode on the same metal piece. It is much faster, and is how rust forms."] },
    { h: "Mechanism of rusting of iron", p: ["Anode (oxidation): Fe → Fe²⁺ + 2e⁻. Iron dissolves at one spot.", "Cathode (reduction): this depends on the pH. In neutral or basic water with dissolved oxygen: O₂ + 2H₂O + 4e⁻ → 4OH⁻ (oxygen absorption type). In acidic water with no oxygen: 2H⁺ + 2e⁻ → H₂ (hydrogen evolution type).", "The Fe²⁺ and OH⁻ ions meet and react: Fe²⁺ + 2OH⁻ → Fe(OH)₂. With more oxygen: 4Fe(OH)₂ + O₂ + 2H₂O → 4Fe(OH)₃. This hydrates to the brown rust Fe₂O₃·xH₂O.", "Electrons flow through the metal from anode to cathode and ions move through the water, so the circuit is a tiny galvanic cell."], formula: ["Anode: Fe → Fe²⁺ + 2e⁻", "Cathode (neutral/alkaline): ½O₂ + H₂O + 2e⁻ → 2OH⁻", "Cathode (acidic): 2H⁺ + 2e⁻ → H₂↑", "Rust: 4Fe(OH)₂ + O₂ + 2H₂O → 4Fe(OH)₃ ≡ Fe₂O₃·xH₂O"] },
    { h: "Where the anode forms", p: ["Differential aeration: part of the metal with less oxygen (under a drop of water, in a crevice, deep in soil) becomes the anode, and the oxygen-rich part is the cathode. Corrosion happens under the water drop, not at the edge.", "Galvanic corrosion: two different metals in contact in an electrolyte. The more active metal is the anode (Zn with Fe, or Fe with Cu). Small anode with a large cathode makes it far worse.", "Stress, scratches and impurities also create anodic spots."] },
    { h: "Control of corrosion", p: ["Cathodic protection by sacrificial anode: connect a more active metal (Zn, Mg, Al) to the iron. The active metal corrodes instead, and the iron becomes the cathode. Used on ship hulls, pipelines and tanks.", "Impressed current: connect the metal to the negative terminal of a DC source so that it is the cathode, with an inert anode (graphite) as the other terminal.", "Coatings: galvanising puts zinc on iron. It is an anodic coating, which protects even when scratched because Zn is more active. Tinning puts tin on iron. It is a cathodic coating, which protects only while the layer is intact. If scratched, iron corrodes faster, since Fe becomes the anode against a large tin cathode.", "Other methods: paint, anodising, corrosion inhibitors, alloying (stainless steel), and removing oxygen or moisture."] },
  ],
  examples: [
    { q: "Explain the electrochemical theory of rusting of iron with reactions.", steps: ["Different parts of the iron surface become anodic and cathodic in moist air.", "Anode: Fe → Fe²⁺ + 2e⁻.", "Cathode, neutral medium: O₂ + 2H₂O + 4e⁻ → 4OH⁻.", "Overall: 2Fe + O₂ + 2H₂O → 2Fe(OH)₂, then oxidised by air to Fe(OH)₃ and hydrated Fe₂O₃, rust.", "In acidic medium the cathode reaction is hydrogen evolution."], ans: "Rust = hydrated Fe₂O₃, formed by Fe²⁺ + OH⁻ products of the micro-cell" },
    { q: "Differentiate between galvanising and tinning of iron.", steps: ["Galvanising: Zn on Fe. Zn is more active than Fe (E° Zn = −0.76 V, Fe = −0.44 V), so Zn is the anode. It is an anodic coating.", "Even if scratched, Zn corrodes and Fe is protected as the cathode.", "Tinning: Sn on Fe. Sn is less active, so it is a cathodic coating.", "If scratched, Fe becomes the anode and corrodes quickly, faster than bare iron."], ans: "Galvanising protects even when broken; tinning does not" },
    { q: "A corrosion cell produces a steady current of 0.5 A through a steel structure for 24 hours. Find the mass of iron lost (Fe → Fe²⁺ + 2e⁻, atomic mass 55.85, F = 96485 C/mol).", steps: ["Charge = I t = 0.5 × 24 × 3600 = 43200 C.", "Moles of electrons = 43200 / 96485 = 0.4477 mol.", "Each Fe loses 2 electrons, so moles of Fe = 0.2239 mol.", "Mass = 0.2239 × 55.85 = 12.5 g."], ans: "≈ 12.5 g of iron" },
  ],
  mistakes: ["Writing the cathode reaction as Fe²⁺ + 2e⁻ → Fe. Oxygen or hydrogen is reduced, not iron.", "Saying rust forms at the point where oxygen is plentiful. Differential aeration puts the anode at low oxygen, so rust is under the drop.", "Calling a tin coating anodic. Tin is cathodic to iron.", "Forgetting to mention that the electrolyte (moisture) is essential for wet corrosion.", "Writing rust as Fe₂O₃ only. It is hydrated, Fe₂O₃·xH₂O.", "In sacrificial protection, writing that the iron is the anode. The attached active metal is the anode."],
  check: [
    { q: "In rusting of iron in neutral water, the cathodic reaction is", o: ["Fe → Fe²⁺ + 2e⁻", "O₂ + 2H₂O + 4e⁻ → 4OH⁻", "2H⁺ + 2e⁻ → H₂", "Fe³⁺ + e⁻ → Fe²⁺"], a: 1, why: "In neutral or basic media with oxygen, oxygen is reduced to hydroxide ions." },
    { q: "Which coating protects iron even when scratched?", o: ["Tin", "Nickel", "Zinc", "Copper"], a: 2, why: "Zn is more active than Fe, so Zn is sacrificed." },
    { q: "Under a drop of water on iron, the anodic area is", o: ["the edge of the drop", "the centre of the drop", "the dry surface", "nowhere"], a: 1, why: "The centre has the least oxygen, so it is anodic." },
    { q: "Sacrificial anodes used on ship hulls are made of", o: ["copper", "silver", "magnesium or zinc", "gold"], a: 2, why: "Mg and Zn are more active than iron." },
  ],
  lab: { id: "corrosion", label: "Open the corrosion and cathodic protection lab" },
};

const bomb: Lesson = {
  intro: "Calorific value tells you how much heat a fuel gives per kilogram. The bomb calorimeter measures it for solid and liquid fuels. You will be asked to describe the experiment and to calculate gross and net calorific values (GCV and NCV), often from coal analysis. Both parts are quick marks once you know the formulas.",
  sections: [
    { h: "Calorific value", p: ["Calorific value is the heat released when a unit mass of fuel is burnt completely. Units: kcal/kg, kJ/kg, or cal/g.", "Gross calorific value (GCV or HCV) counts all the heat, including the heat given back when the water vapour formed from hydrogen condenses to liquid. Net calorific value (NCV or LCV) assumes that vapour escapes with the flue gas, so the latent heat is lost."], formula: ["NCV = GCV − (mass of H₂O per unit fuel) × latent heat", "NCV = GCV − 0.09 H × 587  (H = % hydrogen, 587 cal/g = latent heat of steam)", "9 g of H₂O forms from each 1 g of H: mass of water = 9H/100"] },
    { h: "Construction", p: ["A strong, sealed, stainless steel bomb with a screw-on lid, an oxygen inlet valve and two electrodes. A small crucible holds a weighed pellet (about 1 g) of fuel. A fine fuse wire joins the electrodes and touches the fuel.", "The bomb stands in a copper calorimeter holding a known mass of water. A stirrer and a Beckmann thermometer sit in the water. The calorimeter is inside an air jacket and water jacket to cut heat loss."] },
    { h: "Working and calculation", p: ["Step 1: fill the bomb with pure oxygen at about 25 atm. Step 2: note the water temperature t₁. Step 3: pass current to fire the fuel. It burns completely at constant volume. Step 4: stir and note the highest temperature t₂.", "Heat gained by water and calorimeter = (W + w)(t₂ − t₁), where W is the mass of water and w is the water equivalent of the calorimeter and bomb. This equals the heat from burning x g of fuel.", "Apply corrections for the heat from the fuse wire burning and from the acids that form (HNO₃ from nitrogen, H₂SO₄ from sulphur). Subtract them from the heat."], formula: ["GCV = (W + w)(t₂ − t₁) / x  (cal/g)", "With corrections: GCV = [(W + w)(t₂ − t₁) − (fuse + acid corrections)] / x", "Dulong's formula: GCV = (1/100)[8080 C + 34500 (H − O/8) + 2240 S]  kcal/kg"] },
    { h: "Why bomb gives GCV", p: ["The bomb is cooled back to near room temperature, so the water vapour formed condenses and gives up its latent heat. So the bomb measures GCV. To get NCV you subtract the latent heat using the hydrogen content.", "Because the fuel burns at constant volume, strictly we measure ΔU, not ΔH. For solids the difference is small and ignored."] },
  ],
  examples: [
    { q: "Describe the construction and working of a bomb calorimeter and show how the GCV of a solid fuel is determined.", steps: ["Draw bomb, crucible, electrodes, oxygen at 25 atm, calorimeter, stirrer, thermometer, jackets.", "Weigh x g of fuel, burn it in oxygen, record t₁ and t₂.", "Heat given by fuel = heat taken by water + calorimeter.", "x × GCV = (W + w)(t₂ − t₁), so GCV = (W + w)(t₂ − t₁)/x.", "NCV = GCV − 0.09 H × 587."], ans: "GCV = (W + w)(t₂ − t₁)/x" },
    { q: "0.8 g of coal is burnt in a bomb calorimeter. The calorimeter holds 2000 g of water, the water equivalent of the apparatus is 500 g, and the temperature rises by 2.4 °C. The fuse-wire and acid corrections total 25 cal. The coal contains 5% hydrogen. Find the GCV and NCV.", steps: ["Heat gained = (2000 + 500) × 2.4 = 6000 cal.", "Corrected heat from coal = 6000 − 25 = 5975 cal.", "GCV = 5975 / 0.8 = 7468.75 cal/g.", "Latent heat loss = 0.09 × 5 × 587 = 264.15 cal/g.", "NCV = 7468.75 − 264.15 = 7204.6 cal/g."], ans: "GCV ≈ 7469 cal/g;  NCV ≈ 7205 cal/g" },
    { q: "A coal sample contains C = 80%, H = 15% and ash = 5% (no oxygen or sulphur). Use Dulong's formula for GCV and then find NCV.", steps: ["GCV = (1/100)[8080 × 80 + 34500 × 15] = (646400 + 517500)/100 = 11639 kcal/kg.", "NCV = GCV − 0.09 H × 587 = 11639 − 0.09 × 15 × 587.", "0.09 × 15 × 587 = 792.45 kcal/kg.", "NCV = 11639 − 792.45 = 10846.55 kcal/kg."], ans: "GCV = 11639 kcal/kg;  NCV ≈ 10847 kcal/kg" },
  ],
  mistakes: ["Forgetting the water equivalent w of the calorimeter. Use (W + w), not W alone.", "Not subtracting the fuse wire and acid corrections from the heat.", "Putting H as a fraction (0.05) in NCV = GCV − 0.09 H × 587. Here H is the percentage, so use 5.", "Saying the bomb calorimeter measures NCV. It measures GCV.", "Mixing units: cal/g equals kcal/kg numerically, but J and cal differ by 4.184.", "Using Dulong's formula but forgetting the O/8 term when oxygen is present."],
  check: [
    { q: "A bomb calorimeter measures", o: ["net calorific value", "gross calorific value", "ash content", "flash point"], a: 1, why: "The water vapour condenses in the cooled bomb, so total heat, GCV, is measured." },
    { q: "NCV is equal to", o: ["GCV + 0.09 H × 587", "GCV − 0.09 H × 587", "GCV × 0.09", "GCV / H"], a: 1, why: "The latent heat of the water vapour formed from hydrogen is lost." },
    { q: "In the bomb calorimeter, oxygen is filled at about", o: ["1 atm", "5 atm", "25 atm", "100 atm"], a: 2, why: "A high oxygen pressure ensures complete combustion." },
    { q: "The mass of water formed on burning 1 g of hydrogen is", o: ["1 g", "9 g", "18 g", "0.5 g"], a: 1, why: "2H₂ + O₂ → 2H₂O, so 2 g of H gives 18 g of water, 1 g gives 9 g." },
  ],
  lab: { id: "calorimeter", label: "Open the bomb calorimeter lab" },
};

const nmr: Lesson = {
  intro: "¹H NMR spectroscopy tells you how many kinds of hydrogen a molecule has and how they are connected. Every year the paper asks for its principle, chemical shift, spin–spin splitting and a spectrum prediction for a small molecule. You will learn how it works and how to read a spectrum using three rules: position, area and splitting.",
  sections: [
    { h: "Principle", p: ["A hydrogen nucleus (proton) has spin ½ and acts like a tiny magnet. In a strong magnetic field B₀ it can line up with the field (lower energy) or against it (higher energy). The gap is ΔE = γħB₀.", "Radio-frequency radiation of the right frequency makes the nucleus flip from low to high energy. This is resonance, and the condition is hν = γħB₀, so ν = γB₀/2π. For ¹H, ν ≈ 42.58 MHz per tesla. The stronger the field, the higher the frequency.", "The spectrometer detects the energy absorbed. Different hydrogens in a molecule absorb at slightly different frequencies, and the spectrum shows these as signals."], formula: ["ΔE = hν = γħB₀  ⇒  ν = γB₀ / 2π", "ν(¹H) ≈ 42.58 MHz × B₀ (in tesla)", "1.41 T ⇒ 60 MHz;  7.05 T ⇒ 300 MHz;  11.74 T ⇒ 500 MHz"] },
    { h: "Chemical shift: where the signal sits", p: ["Electrons circling a nucleus make a small opposing field. This is shielding. A hydrogen near an electronegative atom (O, Cl) loses electron density, is deshielded and feels a stronger net field, so it resonates at a higher frequency (downfield).", "The chemical shift δ measures this in a way that does not depend on the spectrometer. TMS, tetramethylsilane (CH₃)₄Si, is the reference at δ = 0. It has 12 equivalent protons giving one sharp signal, it is inert and volatile, and it is more shielded than almost any organic proton.", "Typical values: alkyl C–H about 0.9 to 1.8; H–C–Cl or H–C–Br about 3 to 4; H–C–O about 3.3 to 4; alkene C–H about 5 to 6; aromatic H about 6.5 to 8; aldehyde H about 9 to 10; carboxylic acid H about 10 to 12."], formula: ["δ = (ν<sub>sample</sub> − ν<sub>TMS</sub>) / ν<sub>spectrometer</sub> × 10⁶  (ppm)", "More electronegative neighbour ⇒ larger δ (deshielded)", "Number of signals = number of chemically different kinds of H"] },
    { h: "Integration and spin–spin splitting", p: ["Area under a signal is proportional to the number of protons giving it. Integration gives the ratio, such as 3 : 2.", "Neighbouring protons on adjacent carbons interact. A signal from a proton with n equivalent neighbours splits into n + 1 lines (the n + 1 rule). Line intensities follow Pascal's triangle: doublet 1:1, triplet 1:2:1, quartet 1:3:3:1.", "The distance between lines in a split signal is the coupling constant J, measured in Hz. It does not change with field strength, which is how you tell splitting from two separate signals.", "Equivalent protons do not split each other. OH protons usually give a singlet because they exchange rapidly."], formula: ["n neighbouring H ⇒ n + 1 lines", "Triplet 1:2:1, quartet 1:3:3:1", "J (Hz) is independent of B₀"] },
  ],
  examples: [
    { q: "What is the principle of ¹H NMR? Explain chemical shift and why TMS is the standard.", steps: ["Protons with spin ½ in a field B₀ occupy two energy states separated by ΔE = γħB₀.", "Absorption of radio waves with hν = ΔE flips the spin (resonance).", "Shielding by electrons means each type of proton resonates at a slightly different frequency, expressed as δ in ppm.", "TMS: 12 equivalent H (one strong sharp singlet), chemically inert, volatile (easy to remove), strongly shielded so δ = 0 lies to one side of nearly all signals."], ans: "ν = γB₀/2π;  δ = (ν − ν<sub>TMS</sub>)/ν<sub>0</sub> × 10⁶" },
    { q: "Predict the number of signals, splitting and relative areas in the ¹H NMR of (a) ethyl bromide CH₃CH₂Br and (b) tert-butyl bromide (CH₃)₃CBr.", steps: ["(a) Two kinds of H, so two signals.", "CH₃ has 2 neighbouring H (on CH₂), so it is a triplet, δ about 1.7, 3H.", "CH₂ has 3 neighbouring H (on CH₃), so it is a quartet, δ about 3.4, 2H. It is further downfield because Br is attached.", "(b) All nine H on the three CH₃ groups are equivalent and the carbon between has no H. So one singlet, 9H, δ about 1.8."], ans: "(a) triplet 3H + quartet 2H;  (b) a single singlet, 9H" },
    { q: "A signal appears 600 Hz downfield from TMS in a 300 MHz spectrometer. Find the chemical shift. At what magnetic field would a 300 MHz spectrometer work for ¹H (γ/2π = 42.58 MHz/T)?", steps: ["δ = (Δν / ν<sub>spectrometer</sub>) × 10⁶ = (600 / 300 × 10⁶) × 10⁶ = 2.0 ppm.", "B₀ = ν / (γ/2π) = 300 / 42.58 = 7.05 T."], ans: "δ = 2.0 ppm;  B₀ ≈ 7.05 T" },
  ],
  mistakes: ["Counting signals by the number of hydrogens instead of the number of different kinds of hydrogen.", "Using the n + 1 rule with the wrong count. n is the neighbours on adjacent atoms, not the protons in the signal itself.", "Saying shielded protons appear downfield. Shielded means upfield (smaller δ).", "Forgetting the unit ppm, or the 10⁶ in the δ formula.", "Using the splitting between lines in ppm. J is in Hz and independent of the field.", "Expecting equivalent protons to split each other, for example the three H of one CH₃ group."],
  check: [
    { q: "TMS is used as a reference in NMR because", o: ["it is highly deshielded", "its 12 equivalent protons give one strong sharp signal at δ = 0", "it is polar", "it dissolves in water"], a: 1, why: "TMS is inert, volatile and gives one singlet far upfield." },
    { q: "A proton with 3 equivalent neighbouring protons appears as a", o: ["doublet", "triplet", "quartet", "quintet"], a: 2, why: "n + 1 = 4 lines, a quartet." },
    { q: "A proton next to an electronegative atom appears", o: ["upfield (small δ)", "downfield (larger δ)", "at δ = 0", "does not appear"], a: 1, why: "The electronegative atom deshields the proton." },
    { q: "The relative areas of the signals of CH₃CH₂OH (CH₃, CH₂, OH) are", o: ["1 : 2 : 3", "3 : 2 : 1", "2 : 2 : 2", "3 : 3 : 1"], a: 1, why: "Areas are proportional to the number of H: 3 : 2 : 1." },
  ],
  lab: { id: "nmr", label: "Open the NMR spectrometer lab" },
};

/** AHT-002 lessons. Keys are "AHT-002:unit:topic" (topic = 1-based index in the syllabus unit's topics). */
export const L_AHT002: Record<string, Lesson> = {
  "AHT-002:1:6": mot,
  "AHT-002:1:14": cft,
  "AHT-002:2:7": nernst,
  "AHT-002:3:4": limesoda,
  "AHT-002:3:11": corrosion,
  "AHT-002:4:21": bomb,
  "AHT-002:5:6": nmr,
};
