import type { Lesson } from "./types";

const thevenin: Lesson = {
  intro: "Thevenin's theorem lets you replace any complicated linear network, seen from two terminals, by one voltage source and one resistor. Then finding the current in a load is a one-line calculation. It is the most repeated circuit-theorem question in Basic Electrical Engineering, both as theory and as a numerical. You will learn the four-step recipe and use it to find load current and maximum power.",
  sections: [
    { h: "The statement", p: ["Any linear two-terminal network that contains voltage sources, current sources and resistors can be replaced by a single voltage source V<sub>th</sub> in series with a single resistance R<sub>th</sub>.", "V<sub>th</sub> is the open-circuit voltage across the terminals when the load is removed. R<sub>th</sub> is the resistance seen looking back into the terminals with all independent sources switched off. A load R<sub>L</sub> connected to this equivalent draws the same current as it did in the original circuit."], formula: ["I<sub>L</sub> = V<sub>th</sub> / (R<sub>th</sub> + R<sub>L</sub>)", "V<sub>th</sub> = open-circuit voltage across a–b", "R<sub>th</sub> = resistance across a–b with sources dead"] },
    { h: "The four-step recipe", p: ["Step 1: remove the load resistor and mark the two terminals a and b.", "Step 2: find V<sub>th</sub>, the voltage across a–b with the load removed. Use voltage divider, KVL or nodal analysis.", "Step 3: find R<sub>th</sub>. Replace every ideal voltage source by a short circuit and every ideal current source by an open circuit. Then work out the resistance across a–b by series and parallel combinations.", "Step 4: redraw V<sub>th</sub> in series with R<sub>th</sub> and reconnect the load. Find the current by Ohm's law."] },
    { h: "Norton and maximum power", p: ["Norton's theorem is the twin: a current source I<sub>N</sub> in parallel with R<sub>N</sub>. They are related by R<sub>N</sub> = R<sub>th</sub> and I<sub>N</sub> = V<sub>th</sub>/R<sub>th</sub> (the short-circuit current).", "A load gets maximum power when R<sub>L</sub> = R<sub>th</sub>. At that point half the source power is wasted in R<sub>th</sub>, so the efficiency is 50%. The theorem hands you the answer at once."], formula: ["I<sub>N</sub> = V<sub>th</sub> / R<sub>th</sub>,  R<sub>N</sub> = R<sub>th</sub>", "Maximum power when R<sub>L</sub> = R<sub>th</sub>", "P<sub>max</sub> = V<sub>th</sub>² / (4 R<sub>th</sub>)"] },
  ],
  examples: [
    { q: "State Thevenin's theorem and explain the steps to find the Thevenin equivalent of a network.", steps: ["Statement: a linear active two-terminal network is equivalent to V<sub>th</sub> in series with R<sub>th</sub>.", "Remove load, find open-circuit voltage V<sub>th</sub> across the terminals.", "Kill the independent sources (voltage → short, current → open) and find R<sub>th</sub> looking into the terminals.", "Draw the equivalent and connect the load: I<sub>L</sub> = V<sub>th</sub>/(R<sub>th</sub> + R<sub>L</sub>)."], ans: "I<sub>L</sub> = V<sub>th</sub>/(R<sub>th</sub> + R<sub>L</sub>)" },
    { q: "A 24 V source is in series with 6 Ω. A 12 Ω resistor is connected across the terminals a–b (after the 6 Ω), and a load R<sub>L</sub> = 8 Ω connects across a–b. Find the load current and power in the load by Thevenin's theorem.", steps: ["Remove R<sub>L</sub>. The 12 Ω now forms a voltage divider with the 6 Ω: V<sub>th</sub> = 24 × 12/(6 + 12) = 16 V.", "Short the 24 V source. R<sub>th</sub> = 6 Ω ∥ 12 Ω = (6 × 12)/18 = 4 Ω.", "I<sub>L</sub> = 16 / (4 + 8) = 1.333 A.", "P = I<sub>L</sub>² R<sub>L</sub> = (1.333)² × 8 = 14.2 W."], ans: "I<sub>L</sub> = 1.33 A;  P = 14.2 W" },
    { q: "For the same circuit find the value of R<sub>L</sub> that draws maximum power and the maximum power.", steps: ["From above V<sub>th</sub> = 16 V and R<sub>th</sub> = 4 Ω.", "Maximum power transfer needs R<sub>L</sub> = R<sub>th</sub> = 4 Ω.", "P<sub>max</sub> = V<sub>th</sub>² / (4 R<sub>th</sub>) = 256 / 16 = 16 W.", "Check: I = 16/8 = 2 A, P = 2² × 4 = 16 W."], ans: "R<sub>L</sub> = 4 Ω;  P<sub>max</sub> = 16 W" },
  ],
  mistakes: ["Leaving the load connected while calculating V<sub>th</sub>. The open-circuit voltage needs the load removed.", "Replacing a voltage source with an open circuit when finding R<sub>th</sub>. A voltage source becomes a short, a current source becomes an open circuit.", "Switching off the internal resistance of a practical source too. Keep it; only the ideal source is removed.", "Adding R<sub>L</sub> into R<sub>th</sub> when finding R<sub>th</sub>. R<sub>th</sub> is calculated without the load.", "Mixing up Thevenin and Norton equivalents: Thevenin has a series resistor, Norton a parallel one.", "Quoting the maximum power as V²/R<sub>th</sub> instead of V²/(4R<sub>th</sub>)."],
  check: [
    { q: "The Thevenin voltage V<sub>th</sub> is", o: ["short-circuit current × R<sub>L</sub>", "open-circuit voltage across the terminals", "source voltage", "voltage across the load"], a: 1, why: "V<sub>th</sub> is measured with the load removed." },
    { q: "To find R<sub>th</sub>, an ideal current source is replaced by", o: ["a short circuit", "an open circuit", "a resistor", "left as it is"], a: 1, why: "A dead current source carries no current: open circuit." },
    { q: "Maximum power is delivered to the load when", o: ["R<sub>L</sub> = 0", "R<sub>L</sub> = R<sub>th</sub>", "R<sub>L</sub> = 2R<sub>th</sub>", "R<sub>L</sub> → ∞"], a: 1, why: "Matching load to source resistance maximises power." },
    { q: "With V<sub>th</sub> = 20 V and R<sub>th</sub> = 5 Ω, the maximum load power is", o: ["20 W", "40 W", "80 W", "10 W"], a: 0, why: "400 / (4 × 5) = 20 W." },
  ],
  lab: { id: "thevenin", label: "Open the Thevenin equivalent lab" },
};

const superposition: Lesson = {
  intro: "The superposition theorem breaks a circuit with many sources into several easy circuits, each with a single source. It is a common 5-mark theory question and an easy numerical once you follow the routine. You will learn when it works, how to switch sources off correctly, and the one thing it cannot do.",
  sections: [
    { h: "Statement", p: ["In a linear circuit with more than one independent source, the current through (or voltage across) any element equals the algebraic sum of the currents (or voltages) produced by each source acting alone, with all the other independent sources replaced by their internal resistances.", "For ideal sources: a voltage source is replaced by a short circuit, a current source by an open circuit."] },
    { h: "The routine", p: ["Step 1: pick one source and kill all the others.", "Step 2: solve the simple circuit for the current or voltage you want. Note its direction.", "Step 3: repeat for each source.", "Step 4: add the results, keeping track of direction. Currents that point in opposite directions subtract."], formula: ["I = I′ + I″ + I‴ + …  (algebraic sum)", "Voltage source off → short;  current source off → open"] },
    { h: "Limits of the theorem", p: ["It works only for linear circuits (resistors, inductors and capacitors with fixed values), where current is proportional to voltage.", "It does not apply to power. Power is I²R, which is not linear. The power from two sources is not the sum of the individual powers.", "Dependent sources are never switched off. They stay in every sub-circuit."] },
  ],
  examples: [
    { q: "State the superposition theorem and list its limitations.", steps: ["Statement: in a linear bilateral network with several independent sources, the response in any element is the algebraic sum of the responses due to each source acting alone.", "Method: other voltage sources are shorted and current sources opened.", "Limits: only for linear networks; cannot be used directly for power; dependent sources stay."], ans: "Response = sum of responses of each source acting alone" },
    { q: "Two batteries V₁ = 10 V (with R₁ = 2 Ω) and V₂ = 5 V (with R₂ = 3 Ω) feed a common load R₃ = 6 Ω. Find the current through R₃ by superposition.", steps: ["V₁ alone, V₂ shorted: R₂ ∥ R₃ = (3 × 6)/9 = 2 Ω. Total resistance = 2 + 2 = 4 Ω. Current from V₁ = 10/4 = 2.5 A. Voltage across R₃ = 2.5 × 2 = 5 V, so I₃′ = 5/6 = 0.833 A.", "V₂ alone, V₁ shorted: R₁ ∥ R₃ = (2 × 6)/8 = 1.5 Ω. Total = 3 + 1.5 = 4.5 Ω. Current from V₂ = 5/4.5 = 1.111 A. Voltage across R₃ = 1.111 × 1.5 = 1.667 V, so I₃″ = 1.667/6 = 0.278 A.", "Both currents flow the same way through R₃, so I₃ = 0.833 + 0.278 = 1.111 A.", "Check by nodal analysis: V<sub>A</sub> = 6.667 V, I₃ = 6.667/6 = 1.111 A. ✓"], ans: "I₃ = 1.11 A" },
    { q: "A 12 V source with R₁ = 4 Ω and a 3 A current source feed node A. R₂ = 6 Ω connects from A to ground. The 3 A source pushes current into A. Find the current through R₂ and show that power is not additive.", steps: ["12 V alone (3 A source open): I = 12/(4 + 6) = 1.2 A through R₂.", "3 A alone (12 V shorted): the current divides between R₁ and R₂. Through R₂ = 3 × 4/(4 + 6) = 1.2 A.", "Total through R₂ = 1.2 + 1.2 = 2.4 A. Check: V<sub>A</sub> = 14.4 V and 14.4/6 = 2.4 A ✓.", "Power in R₂ = 2.4² × 6 = 34.56 W. The sum of the individual powers = 1.2² × 6 + 1.2² × 6 = 17.28 W. They are not equal."], ans: "I = 2.4 A;  power cannot be superposed (34.56 W ≠ 17.28 W)" },
  ],
  mistakes: ["Open-circuiting a voltage source or short-circuiting a current source. It is the other way around.", "Adding magnitudes without checking directions. Opposing currents subtract.", "Adding powers from each source. Power depends on the square of current.", "Removing the internal resistance of a practical source. It stays in the circuit.", "Switching off a dependent source. Dependent sources always remain.", "Applying the theorem to a non-linear element such as a diode."],
  check: [
    { q: "When applying superposition, an ideal voltage source that is switched off is replaced by", o: ["an open circuit", "a short circuit", "a resistor", "a capacitor"], a: 1, why: "A dead voltage source has zero voltage across it: a short." },
    { q: "Superposition cannot be used to find", o: ["current", "voltage", "power", "node voltage"], a: 2, why: "Power is not linear in the sources." },
    { q: "Superposition is valid for", o: ["non-linear circuits", "linear circuits", "only DC circuits with diodes", "only AC circuits"], a: 1, why: "The theorem relies on linearity." },
    { q: "If one source gives +2 A and another gives −0.5 A in the same element, the total current is", o: ["2.5 A", "1.5 A", "2 A", "−1.5 A"], a: 1, why: "Algebraic sum: 2 − 0.5 = 1.5 A." },
  ],
  lab: { id: "superposition", label: "Open the superposition and Norton lab" },
};

const resonance: Lesson = {
  intro: "At resonance a series RLC circuit lets a huge current through and the inductor and capacitor voltages can be many times the supply. Radio tuning works on this idea. The question appears nearly every year as theory with curves and as a numerical on f₀, Q and bandwidth. You will derive the formulas and use them.",
  sections: [
    { h: "Series RLC at a glance", p: ["In a series RLC circuit, X<sub>L</sub> = ωL grows with frequency and X<sub>C</sub> = 1/ωC falls with frequency. The impedance is Z = √(R² + (X<sub>L</sub> − X<sub>C</sub>)²).", "At one special frequency X<sub>L</sub> = X<sub>C</sub>. The two reactances cancel, the circuit looks purely resistive, and Z = R, its minimum value. The current then rises to its maximum, I<sub>0</sub> = V/R, and is in phase with the voltage. The power factor is 1. This is resonance."], formula: ["Z = √(R² + (ωL − 1/ωC)²)", "Resonance: ωL = 1/ωC", "f₀ = 1 / (2π√(LC))", "At resonance Z = R,  I<sub>0</sub> = V/R,  pf = 1"] },
    { h: "Q factor and bandwidth", p: ["At resonance the voltage across L is V<sub>L</sub> = I<sub>0</sub>X<sub>L</sub> and across C is V<sub>C</sub> = I<sub>0</sub>X<sub>C</sub>. They are equal and opposite, so they cancel in the loop, but each can be much bigger than the supply V.", "The quality factor Q = V<sub>L</sub>/V = V<sub>C</sub>/V = X<sub>L</sub>/R = ω₀L/R = (1/R)√(L/C). A high Q means a sharp, tall resonance curve.", "The half-power frequencies f₁ and f₂ are where the current falls to 1/√2 of its maximum. The bandwidth is BW = f₂ − f₁ = f₀/Q. A larger R gives lower Q and wider bandwidth."], formula: ["Q = ω₀L/R = 1/(ω₀CR) = (1/R)√(L/C)", "V<sub>L</sub> = V<sub>C</sub> = QV at resonance", "Bandwidth BW = f₀/Q = R/(2πL)", "Selectivity improves as Q increases"] },
    { h: "Curves and the parallel case", p: ["The current-versus-frequency curve is bell-shaped with its peak at f₀. Below f₀ the circuit is capacitive (current leads), above f₀ it is inductive (current lags).", "Parallel resonance (ideal L and C in parallel) is the reverse. At f₀ the impedance is maximum and the supply current is minimum, so it is called a rejector circuit. The series circuit is the acceptor circuit."] },
  ],
  examples: [
    { q: "Derive the resonant frequency of a series RLC circuit and draw the variation of current with frequency. Define Q factor.", steps: ["Impedance Z = √(R² + (X<sub>L</sub> − X<sub>C</sub>)²). Current I = V/Z.", "Current is maximum when X<sub>L</sub> = X<sub>C</sub>, i.e. ω₀L = 1/ω₀C.", "ω₀² = 1/LC, so f₀ = 1/(2π√LC).", "Current curve: bell shape with peak V/R at f₀, falling on both sides; half-power points at I<sub>0</sub>/√2.", "Q = ω₀L/R = voltage magnification across L or C at resonance."], ans: "f₀ = 1/(2π√LC)" },
    { q: "A series circuit has R = 10 Ω, L = 0.1 H and C = 10 μF, with a 100 V variable-frequency supply. Find f₀, the current at resonance, Q, the voltage across the inductor and the bandwidth.", steps: ["f₀ = 1/(2π√(0.1 × 10 × 10⁻⁶)) = 1/(2π × 10⁻³) = 159.2 Hz.", "I₀ = V/R = 100/10 = 10 A.", "Q = (1/R)√(L/C) = (1/10)√(0.1/10⁻⁵) = (1/10) × 100 = 10.", "V<sub>L</sub> = QV = 10 × 100 = 1000 V.", "BW = f₀/Q = 159.2/10 = 15.9 Hz."], ans: "f₀ = 159 Hz, I₀ = 10 A, Q = 10, V<sub>L</sub> = 1000 V, BW = 15.9 Hz" },
    { q: "A coil of inductance 2 mH is to resonate at 1 MHz. Find the required capacitance.", steps: ["f₀ = 1/(2π√LC) gives C = 1/(4π²f₀²L).", "4π² = 39.48; f₀² = 10¹²; L = 2 × 10⁻³.", "C = 1/(39.48 × 10¹² × 2 × 10⁻³) = 1/(7.896 × 10¹⁰) = 1.267 × 10⁻¹¹ F."], ans: "C ≈ 12.7 pF" },
  ],
  mistakes: ["Using f₀ = 1/(2π LC) without the square root.", "Saying current is maximum when R is zero. At resonance current = V/R, set by R.", "Forgetting that V<sub>L</sub> and V<sub>C</sub> can be larger than the supply voltage.", "Mixing μF with F in calculations. 10 μF = 10 × 10⁻⁶ F.", "Writing bandwidth as f₀ × Q. It is f₀/Q.", "Describing resonance as if power factor is zero. At resonance pf = 1."],
  check: [
    { q: "At resonance in a series RLC circuit the impedance is", o: ["maximum", "equal to R", "equal to X<sub>L</sub>", "infinite"], a: 1, why: "X<sub>L</sub> and X<sub>C</sub> cancel, so Z = R, the minimum." },
    { q: "The resonant frequency of a series RLC circuit is", o: ["1/(2π√LC)", "2π√LC", "1/(2πLC)", "√(LC)/2π"], a: 0, why: "From ω₀L = 1/ω₀C." },
    { q: "If R is doubled with L and C unchanged, the Q factor", o: ["doubles", "halves", "stays the same", "becomes zero"], a: 1, why: "Q = ω₀L/R is inversely proportional to R." },
    { q: "At resonance the phase angle between V and I is", o: ["90° lagging", "90° leading", "0°", "180°"], a: 2, why: "The circuit behaves as pure resistance." },
  ],
  lab: { id: "rlc", label: "Open the series RLC resonance lab" },
};

const efficiency: Lesson = {
  intro: "A transformer wastes a little power as iron loss and copper loss. Efficiency tells you what fraction of input power reaches the load. Condition for maximum efficiency (copper loss = iron loss) is the favourite theory question. Numericals ask for efficiency at a given load and the load for maximum efficiency. You will derive it and calculate both.",
  sections: [
    { h: "The losses", p: ["Iron (core) loss P<sub>i</sub> is the sum of hysteresis loss and eddy current loss. It depends on the supply voltage and frequency, so it is constant from no load to full load.", "Copper loss P<sub>cu</sub> is I²R in the windings. It varies as the square of the load current. If x is the fraction of full load, the copper loss is x² P<sub>cu,fl</sub>, where P<sub>cu,fl</sub> is the full-load copper loss."] },
    { h: "Efficiency", p: ["Efficiency η = output power / input power = output / (output + losses).", "For a transformer of rating S kVA at load fraction x and power factor cos φ, the output is x S cos φ."], formula: ["η = x S cos φ / (x S cos φ + P<sub>i</sub> + x² P<sub>cu</sub>)", "S = rated VA,  x = load / full load,  P<sub>cu</sub> = full-load copper loss", "All-day efficiency = energy out in 24 h / energy in in 24 h"] },
    { h: "Condition for maximum efficiency", p: ["Take x as the variable, with S, cos φ, P<sub>i</sub> and P<sub>cu</sub> fixed. Divide top and bottom by x: η = S cos φ / (S cos φ + P<sub>i</sub>/x + x P<sub>cu</sub>).", "η is largest when the denominator is smallest, i.e. when d/dx (P<sub>i</sub>/x + x P<sub>cu</sub>) = 0. That gives −P<sub>i</sub>/x² + P<sub>cu</sub> = 0, so x² P<sub>cu</sub> = P<sub>i</sub>.", "So maximum efficiency occurs when the copper loss equals the iron loss. The load fraction is x = √(P<sub>i</sub>/P<sub>cu</sub>). The second derivative is positive, which confirms it is a maximum.", "Notice that maximum efficiency does not depend on power factor for the position of the maximum, but the value of η does: higher power factor, higher efficiency."], formula: ["Maximum η when  x² P<sub>cu</sub> = P<sub>i</sub>", "x = √(P<sub>i</sub> / P<sub>cu</sub>)", "η<sub>max</sub> = x S cos φ / (x S cos φ + 2 P<sub>i</sub>)", "kVA at max η = (full-load kVA) × √(P<sub>i</sub>/P<sub>cu</sub>)"] },
  ],
  examples: [
    { q: "Show that the efficiency of a transformer is maximum when copper loss equals iron loss.", steps: ["η = x S cos φ / (x S cos φ + P<sub>i</sub> + x² P<sub>cu</sub>). Divide by x: η = S cos φ / (S cos φ + P<sub>i</sub>/x + x P<sub>cu</sub>).", "η is maximum when D = P<sub>i</sub>/x + x P<sub>cu</sub> is minimum.", "dD/dx = −P<sub>i</sub>/x² + P<sub>cu</sub> = 0, so x² P<sub>cu</sub> = P<sub>i</sub>.", "d²D/dx² = 2P<sub>i</sub>/x³ > 0, so it is a minimum of D and a maximum of η."], ans: "η is maximum when P<sub>cu</sub> (at that load) = P<sub>i</sub>" },
    { q: "A 50 kVA transformer has an iron loss of 500 W and a full-load copper loss of 800 W. Find (a) the efficiency at full load, 0.8 power factor, (b) the efficiency at half load, 0.8 power factor, (c) the load for maximum efficiency and the maximum efficiency at unity power factor.", steps: ["(a) Output = 50000 × 0.8 = 40000 W. Losses = 500 + 800 = 1300 W. η = 40000/41300 = 96.85%.", "(b) x = 0.5. Output = 20000 W. Copper loss = 0.25 × 800 = 200 W. Losses = 700 W. η = 20000/20700 = 96.62%.", "(c) x = √(500/800) = 0.7906, so the load is 0.7906 × 50 = 39.53 kVA.", "At unity pf the output is 39528 W and the losses are 2 × 500 = 1000 W. η<sub>max</sub> = 39528/40528 = 97.53%."], ans: "(a) 96.85%  (b) 96.62%  (c) 39.5 kVA, η<sub>max</sub> = 97.5%" },
  ],
  mistakes: ["Using full-load copper loss at part load. It must be multiplied by x².", "Treating iron loss as varying with load. It is constant for fixed V and f.", "Forgetting the power factor in the output power (kVA × cos φ).", "Computing η as output/losses instead of output/(output + losses).", "Using kW for output and W for losses without converting.", "Saying maximum efficiency occurs at full load. It occurs where P<sub>cu</sub> = P<sub>i</sub>, usually at 50–80% load."],
  check: [
    { q: "Iron loss in a transformer is", o: ["proportional to load current squared", "constant from no load to full load", "zero at no load", "proportional to load"], a: 1, why: "It depends on core flux, which is set by the constant supply voltage." },
    { q: "Maximum efficiency occurs when", o: ["P<sub>cu</sub> = 0", "P<sub>cu</sub> = P<sub>i</sub>", "P<sub>i</sub> = 0", "load is full"], a: 1, why: "Derivation: variable copper loss equals constant iron loss." },
    { q: "With P<sub>i</sub> = 400 W and full-load P<sub>cu</sub> = 900 W, the load fraction for maximum efficiency is", o: ["0.44", "0.67", "0.75", "1.5"], a: 1, why: "x = √(400/900) = 20/30 = 0.67." },
    { q: "At half load the copper loss is what fraction of the full-load copper loss?", o: ["1/2", "1/4", "1/8", "same"], a: 1, why: "Copper loss ∝ I², so (1/2)² = 1/4." },
  ],
  lab: { id: "trtest", label: "Open the transformer tests, efficiency and regulation lab" },
};

const emfEq: Lesson = {
  intro: "The EMF equation tells you how many volts a transformer winding produces from the core flux, frequency and number of turns. You are expected to derive E = 4.44 f N Φ<sub>m</sub> and use it with the turns ratio in numericals. It sits inside the very popular transformer-principle question. You will learn the derivation and the ratios.",
  sections: [
    { h: "Working principle in brief", p: ["A transformer has two windings on a laminated iron core. An AC voltage on the primary sets up an alternating flux in the core. This flux links the secondary and, by Faraday's law, induces an EMF in it. The flux changes, but frequency stays the same. There is no electrical connection between the windings.", "The flux also induces an EMF in the primary that opposes the supply (Lenz's law). This back EMF nearly equals the supply voltage."] },
    { h: "Deriving the EMF equation", p: ["Step 1: let the flux be sinusoidal, Φ = Φ<sub>m</sub> sin ωt.", "Step 2: by Faraday, the EMF in N turns is e = −N dΦ/dt = −N ω Φ<sub>m</sub> cos ωt.", "Step 3: the peak EMF is E<sub>m</sub> = N ω Φ<sub>m</sub> = 2π f N Φ<sub>m</sub>.", "Step 4: rms value E = E<sub>m</sub>/√2 = (2π/√2) f N Φ<sub>m</sub> = 4.44 f N Φ<sub>m</sub>.", "Step 5: write it for both windings. E₁ = 4.44 f N₁ Φ<sub>m</sub> and E₂ = 4.44 f N₂ Φ<sub>m</sub>. The same flux links both, so dividing gives the transformation ratio."], formula: ["E = 4.44 f N Φ<sub>m</sub>  (rms)", "E₁ = 4.44 f N₁ Φ<sub>m</sub>,  E₂ = 4.44 f N₂ Φ<sub>m</sub>", "Φ<sub>m</sub> = B<sub>m</sub> A (A = core cross-section)"] },
    { h: "Transformation ratio", p: ["The turns ratio K = N₂/N₁ = E₂/E₁. For an ideal transformer V₁ = E₁ and V₂ = E₂, and the power in equals the power out, so V₁I₁ = V₂I₂.", "Step-up: K > 1, voltage rises, current falls. Step-down: K < 1, voltage falls, current rises."], formula: ["K = N₂/N₁ = E₂/E₁ = V₂/V₁ = I₁/I₂", "V₁I₁ = V₂I₂ = kVA rating (ideal)"] },
  ],
  examples: [
    { q: "Derive the EMF equation of a single-phase transformer.", steps: ["Flux Φ = Φ<sub>m</sub> sin ωt. EMF in N turns e = −N dΦ/dt.", "e = −N ω Φ<sub>m</sub> cos ωt, so E<sub>max</sub> = 2π f N Φ<sub>m</sub>.", "E<sub>rms</sub> = E<sub>max</sub>/√2 = 4.44 f N Φ<sub>m</sub>.", "Primary: E₁ = 4.44 f N₁ Φ<sub>m</sub>; secondary: E₂ = 4.44 f N₂ Φ<sub>m</sub>; so E₂/E₁ = N₂/N₁ = K."], ans: "E = 4.44 f N Φ<sub>m</sub>" },
    { q: "A 1-phase transformer operates from a 230 V, 50 Hz supply with 400 primary turns. Find the maximum core flux.", steps: ["Neglect the small drop, so E₁ ≈ V₁ = 230 V.", "Φ<sub>m</sub> = E₁/(4.44 f N₁) = 230/(4.44 × 50 × 400).", "Denominator = 88800.", "Φ<sub>m</sub> = 230/88800 = 2.59 × 10⁻³ Wb."], ans: "Φ<sub>m</sub> ≈ 2.59 mWb" },
    { q: "A 25 kVA, 2200/220 V, 50 Hz transformer has 800 turns on the primary. Find the rated currents, the secondary turns, the peak flux and the core area if B<sub>m</sub> = 1.2 T.", steps: ["I₁ = 25000/2200 = 11.36 A and I₂ = 25000/220 = 113.6 A.", "K = 220/2200 = 0.1, so N₂ = 0.1 × 800 = 80 turns.", "Φ<sub>m</sub> = 2200/(4.44 × 50 × 800) = 2200/177600 = 12.39 × 10⁻³ Wb.", "Area A = Φ<sub>m</sub>/B<sub>m</sub> = 0.01239/1.2 = 0.01032 m²."], ans: "I₁ = 11.4 A, I₂ = 113.6 A, N₂ = 80, Φ<sub>m</sub> = 12.4 mWb, A ≈ 103 cm²" },
  ],
  mistakes: ["Using the peak value of EMF with the 4.44 formula. 4.44 gives the rms value.", "Writing 4.44 as 4.44 f N Φ with Φ as the rms flux. Use the maximum flux Φ<sub>m</sub>.", "Getting the turns ratio upside down. K = N₂/N₁ = V₂/V₁ = I₁/I₂.", "Believing a transformer works on DC. DC gives constant flux and no induced EMF.", "Thinking frequency changes between primary and secondary. It stays the same.", "Mixing mWb and Wb, or cm² and m², when finding area."],
  check: [
    { q: "The EMF equation of a transformer is", o: ["E = 2.22 f N Φ<sub>m</sub>", "E = 4.44 f N Φ<sub>m</sub>", "E = 4.44 N Φ<sub>m</sub>/f", "E = 1.11 f N Φ<sub>m</sub>"], a: 1, why: "2π/√2 = 4.44." },
    { q: "A transformer has N₁ = 1000, N₂ = 100. It is a", o: ["step-up with K = 10", "step-down with K = 0.1", "step-up with K = 0.1", "step-down with K = 10"], a: 1, why: "K = N₂/N₁ = 0.1 < 1: step-down." },
    { q: "If the supply frequency is halved at the same voltage, the maximum core flux", o: ["halves", "doubles", "stays the same", "becomes zero"], a: 1, why: "Φ<sub>m</sub> = E/(4.44 f N), so it doubles and the core may saturate." },
    { q: "In an ideal transformer, if the voltage is stepped up 10 times, the current is", o: ["10 times larger", "10 times smaller", "unchanged", "zero"], a: 1, why: "V₁I₁ = V₂I₂." },
  ],
  lab: { id: "transformer", label: "Open the single-phase transformer lab" },
};

const inductionMotor: Lesson = {
  intro: "The three-phase induction motor runs most of the world's industry. It has no electrical connection to its rotor and almost no moving contacts, and it starts by itself. A question on its construction and working principle appears every year, along with a slip and rotor-frequency numerical. You will learn why the rotor turns, why it can never reach synchronous speed, and how slip is calculated.",
  sections: [
    { h: "Construction", p: ["Stator: a laminated steel frame with slots carrying a three-phase winding. When connected to a three-phase supply it produces a rotating magnetic field (RMF).", "Rotor: a laminated cylinder with conductors in slots. There are two types. In a squirrel cage rotor the conductors are bars short-circuited at both ends by end rings, like a cage. It is simple, rugged and cheap, but has low starting torque. In a slip-ring (wound) rotor the rotor has a three-phase winding brought out to three slip rings, so external resistance can be added for high starting torque and speed control.", "A small air gap separates stator and rotor to keep the magnetising current low."] },
    { h: "Working principle", p: ["Step 1: three-phase currents in the stator produce an RMF of constant magnitude turning at the synchronous speed N<sub>s</sub> = 120 f/P rpm.", "Step 2: the RMF cuts the stationary rotor conductors, inducing EMF in them (Faraday's law).", "Step 3: the rotor circuit is closed, so current flows in the rotor conductors.", "Step 4: a current-carrying conductor in a magnetic field feels a force, giving torque on the rotor. By Lenz's law, the direction is such as to oppose the cause, i.e. the relative motion between field and rotor. So the rotor turns in the direction of the field, chasing it.", "Step 5: the rotor can never reach N<sub>s</sub>. At N<sub>s</sub> there would be no relative motion, no induced EMF, no current and no torque. So the rotor speed N is always a little less than N<sub>s</sub>. This is why it is called an asynchronous motor."], formula: ["N<sub>s</sub> = 120 f / P  (rpm)", "N < N<sub>s</sub> always"] },
    { h: "Slip and rotor frequency", p: ["Slip is the fractional difference between synchronous and rotor speeds. It is about 2 to 5% at full load. At starting N = 0, so s = 1.", "The rotor sees the field going past at the relative speed N<sub>s</sub> − N, so the rotor frequency is only a fraction s of the supply frequency. At standstill f<sub>r</sub> = f; at full load it is just 1 to 3 Hz."], formula: ["s = (N<sub>s</sub> − N) / N<sub>s</sub>", "N = N<sub>s</sub>(1 − s)", "f<sub>r</sub> = s f", "At start s = 1;  at N<sub>s</sub> s = 0"] },
  ],
  examples: [
    { q: "Explain the construction and working principle of a three-phase induction motor. Compare squirrel cage and slip-ring rotors.", steps: ["Describe stator (three-phase winding, RMF) and rotor (cage or wound).", "RMF cuts rotor conductors → induced EMF → rotor current → force by Lenz's law → rotor follows the field.", "Rotor speed is always below N<sub>s</sub>, otherwise there would be no induced EMF.", "Squirrel cage: simple, robust, low starting torque, no external resistance. Slip ring: high starting torque, speed control by external resistance, needs brushes and more maintenance."], ans: "Rotor turns because of torque from induced currents; N < N<sub>s</sub>" },
    { q: "A 4-pole, 50 Hz three-phase induction motor runs at 1440 rpm at full load. Find the synchronous speed, slip and rotor frequency.", steps: ["N<sub>s</sub> = 120 × 50/4 = 1500 rpm.", "s = (1500 − 1440)/1500 = 60/1500 = 0.04, i.e. 4%.", "f<sub>r</sub> = s f = 0.04 × 50 = 2 Hz."], ans: "N<sub>s</sub> = 1500 rpm;  s = 4%;  f<sub>r</sub> = 2 Hz" },
    { q: "A 6-pole, 50 Hz induction motor has a full-load slip of 3%. Find the rotor speed and the rotor frequency.", steps: ["N<sub>s</sub> = 120 × 50/6 = 1000 rpm.", "N = N<sub>s</sub>(1 − s) = 1000 × 0.97 = 970 rpm.", "f<sub>r</sub> = 0.03 × 50 = 1.5 Hz."], ans: "N = 970 rpm;  f<sub>r</sub> = 1.5 Hz" },
  ],
  mistakes: ["Saying the rotor runs at synchronous speed. It runs slightly slower, that is why it is called asynchronous.", "Using slip as a percentage in N = N<sub>s</sub>(1 − s) without converting 4% to 0.04.", "Using the number of pole pairs in 120f/P. P is the number of poles.", "Claiming the rotor frequency equals the supply frequency while running. It is s f, a few hertz.", "Forgetting that the rotor turns in the same direction as the RMF.", "Writing slip as (N − N<sub>s</sub>)/N<sub>s</sub>, which gives a negative value."],
  check: [
    { q: "The synchronous speed of a 4-pole motor on a 50 Hz supply is", o: ["750 rpm", "1000 rpm", "1500 rpm", "3000 rpm"], a: 2, why: "120 × 50 / 4 = 1500." },
    { q: "At standstill the slip of an induction motor is", o: ["0", "0.5", "1", "infinite"], a: 2, why: "N = 0, so s = (N<sub>s</sub> − 0)/N<sub>s</sub> = 1." },
    { q: "The rotor frequency at slip s is", o: ["f/s", "s f", "f", "(1 − s) f"], a: 1, why: "Relative speed is s N<sub>s</sub>, so f<sub>r</sub> = s f." },
    { q: "Which rotor allows external resistance to be added at starting?", o: ["Squirrel cage", "Slip ring (wound)", "Both", "Neither"], a: 1, why: "Only the wound rotor has slip rings to connect external resistors." },
  ],
  lab: { id: "rotatingfield", label: "Open the rotating field and induction motor lab" },
};

const mcb: Lesson = {
  intro: "Every wall socket in a house is protected by a fuse or a breaker. The question on LT switchgear asks you to describe SFU, MCB, ELCB and MCCB, and often to choose a rating. The MCB is the one you will use most. You will learn how an MCB trips on overload and short circuit, how it differs from a fuse, and how ELCB and MCCB fit in.",
  sections: [
    { h: "Why we need protection", p: ["A fault can make the current many times its normal value. An overload is a modest rise for a long time, caused by too many appliances. A short circuit is a very large current for a moment, when the live wire touches the neutral. Both overheat the wires and can start fires. A protective device must open the circuit quickly.", "LT (low tension) switchgear means switching and protection devices for voltages up to 1000 V."] },
    { h: "Miniature circuit breaker (MCB)", p: ["An MCB is a resettable switch that trips automatically on abnormal current. After the fault is fixed, you just switch it back on. A fuse, in contrast, melts and must be replaced.", "Overload protection: a bimetallic strip carries the current. If the current stays high, the strip heats, bends and releases the latch, tripping the breaker. The higher the overload, the faster it trips (an inverse time characteristic).", "Short-circuit protection: a solenoid (electromagnet) is in series. A huge current pulls its plunger in at once and trips the breaker in a few milliseconds.", "An arc forms as the contacts open. An arc chute with metal plates splits and cools the arc so it goes out quickly.", "Ratings run from 0.5 A to 63 A, with breaking capacities of 6 to 10 kA. Types B, C and D differ in how large a surge they tolerate before the magnetic trip acts: B (3–5 times rated) for homes, C (5–10 times) for light motors and inductive loads, D (10–20 times) for heavy motors and transformers."], formula: ["Rated current ≥ load current, and ≤ cable current capacity", "Load current I = P / (V cos φ)  (single phase)", "Overload → thermal (bimetal) trip.  Short circuit → magnetic (solenoid) trip"] },
    { h: "Other LT devices", p: ["SFU (switch fuse unit): a manual switch combined with HRC fuses. It isolates and protects, but a blown fuse must be replaced.", "ELCB (earth leakage circuit breaker, now an RCD/RCCB): compares the live current with the neutral return. If some current leaks to earth, as when someone touches a faulty appliance, the two differ. A sensitive coil trips the breaker, usually at 30 mA for personal safety. It protects against shock, not against overload, so it is used along with an MCB.", "MCCB (moulded case circuit breaker): like an MCB but for higher currents, 100 A to 1600 A, in a moulded insulating case. Its thermal and magnetic trip levels are adjustable, and it has a higher breaking capacity (up to 50 kA or more). Used on main feeders and industrial panels."] },
  ],
  examples: [
    { q: "Explain the construction and working of an MCB. How is it better than a fuse?", steps: ["Show a moulded case with a toggle, a bimetallic strip, a solenoid, contacts and an arc chute.", "Overload: heat bends the bimetal strip, which unlatches the contacts after a delay.", "Short circuit: the solenoid plunger strikes the trip lever instantly.", "Arc is cooled in the arc chute.", "Better than a fuse: resettable, faster, more accurate, trips all poles together, shows clearly which circuit has tripped, safer to operate."], ans: "Thermal trip for overload, magnetic trip for short circuit" },
    { q: "A kitchen circuit on 230 V supplies a 2 kW geyser. Choose a suitable MCB rating from 6, 10, 16, 20 and 32 A.", steps: ["Load current I = P/V = 2000/230 = 8.7 A (taking pf = 1).", "The MCB rating must be above the load current so it does not trip in normal use.", "10 A is the next standard size above 8.7 A. (For a margin on a motor-type load, 16 A is also used, if the cable can carry it.)"], ans: "10 A MCB (16 A if the wiring allows)" },
    { q: "A house has a 2 kW geyser, a 1.5 kW heater and 0.5 kW of lights and fans on a single 230 V supply. Find the total current and a sensible main MCB rating. Which device protects a person against shock?", steps: ["Total load = 2 + 1.5 + 0.5 = 4 kW = 4000 W.", "I = 4000/230 = 17.4 A.", "The next standard rating above 17.4 A is 20 A.", "Shock protection is given by an ELCB/RCCB (30 mA); an MCB alone does not protect against small leakage."], ans: "I = 17.4 A, so use a 20 A MCB;  ELCB (30 mA) for shock" },
  ],
  mistakes: ["Saying an MCB trips only on short circuit. It has both thermal and magnetic elements.", "Choosing an MCB rating below the load current, so it trips in normal use, or far above the cable rating, which leaves the wire unprotected.", "Confusing ELCB with MCB. ELCB detects earth leakage, MCB detects overload and short circuit.", "Writing that a fuse is resettable. A fuse is replaced after blowing.", "Forgetting that MCCB is for higher currents with adjustable settings.", "Saying the ELCB trips when the load current is high. It trips on the difference between live and neutral current."],
  check: [
    { q: "An MCB trips on overload because of its", o: ["solenoid", "bimetallic strip", "fuse wire", "capacitor"], a: 1, why: "A heated bimetal bends and releases the latch." },
    { q: "An MCB trips instantly on a short circuit because of its", o: ["solenoid (magnetic trip)", "bimetal", "arc chute", "ground wire"], a: 0, why: "The large current makes the solenoid pull in at once." },
    { q: "The device that protects against earth leakage and electric shock is", o: ["MCB", "ELCB / RCCB", "SFU", "isolator"], a: 1, why: "It detects the imbalance between live and neutral currents." },
    { q: "Load current of a 1.84 kW single-phase load at 230 V and unity power factor is", o: ["4 A", "8 A", "12 A", "16 A"], a: 1, why: "1840 / 230 = 8 A." },
  ],
  lab: { id: "switchgear", label: "Open the fuse, MCB and ELCB lab" },
};

/** EET-001 lessons. Keys are "EET-001:unit:topic" (topic = 1-based index in the syllabus unit's topics). */
export const L_EET001: Record<string, Lesson> = {
  "EET-001:1:7": superposition,
  "EET-001:1:8": thevenin,
  "EET-001:2:13": resonance,
  "EET-001:3:10": emfEq,
  "EET-001:3:14": efficiency,
  "EET-001:4:5": inductionMotor,
  "EET-001:5:5": mcb,
};
