// Builds src/content/* from the raw sources in content/src. Run: node scripts/build-content.cjs
const fs = require("fs"), path = require("path");
const src = (f) => fs.readFileSync(path.join(__dirname, "../content/src", f), "utf8");
const out = path.join(__dirname, "../src/content");

// GEN_ONLY=1 node scripts/build-content.cjs rebuilds only the generators (the syllabus files are then left alone, e.g. the BCA ones built by build-bca.py)
if (!process.env.GEN_ONLY) {
// ---- syllabus -> one JSON file per course + a small index
const SYL = {};
new Function("sylAdd", ["syl_a", "syl_b", "syl_lab1", "syl_lab2"].map((f) => src(f + ".js")).join("\n"))((c, o) => { SYL[c] = o; });
fs.mkdirSync(path.join(out, "syllabus"), { recursive: true });
const index = [];
let topics = 0;
for (const [code, c] of Object.entries(SYL)) {
  const units = (c.units || []).map((u, i) => ({
    n: i + 1, title: u.t, hours: u.h ?? null, topics: u.topics || [], formulas: u.formulas || [], hints: u.hints || [],
  }));
  const exps = (c.exps || []).map((e, i) => ({ n: i + 1, title: e.t, aim: e.aim || "", apparatus: e.app || "", formula: e.f || "", viva: e.viva || [] }));
  const count = units.reduce((s, u) => s + u.topics.length, 0) + exps.length;
  topics += count;
  const rec = { code, name: c.n, short: c.s, type: c.type, ltp: c.ltp, credits: c.cr, sem: c.sem, marks: c.marks, objectives: c.obj || [], outcomes: c.out || [], text: c.text || [], ref: c.ref || [], rule: c.rule || "", note: c.note || "", units, exps };
  fs.writeFileSync(path.join(out, "syllabus", code + ".json"), JSON.stringify(rec));
  index.push({ code, name: c.n, short: c.s, type: c.type, sem: c.sem, credits: c.cr, units: units.length, items: count });
}
fs.writeFileSync(path.join(out, "syllabus", "index.json"), JSON.stringify(index));
console.log(`syllabus: ${index.length} courses, ${topics} topics/experiments`);
}

// ---- question generators -> one CommonJS module (sloppy mode, exactly as the original harness ran them)
const helpers = src("helpers.js").split("\n").filter((l) => !/^"use strict"|^const \$=|^const esc=|^\/\* ---------- UTU facts|^const UNI=/.test(l) && !/^\s*pyq:/.test(l)).join("\n");
const core = src("p14core.js").split("\n").filter((l) => !/^const SYL=|^function sylAdd/.test(l)).join("\n");
const code = `/* generated by scripts/build-content.cjs - do not edit */
const GEN = {};
${helpers}
${src("builders.js")}
${core}
${["gen_a", "gen_b", "gen_c", "gen_d", "gen_e", "gen_f", "gen_g", "gen_h"].map((f) => src(f + ".js")).join("\n")}
module.exports = { GEN, strip };
`;
fs.writeFileSync(path.join(out, "gen.generated.cjs"), code);
console.log("generators written:", (code.length / 1024).toFixed(0) + " KB");
