/* gen_a.js - question templates for AHT-002 Engineering Chemistry and AHT-005 Analytical Mathematics */
const gaX=(c,v)=>{const a=Math.abs(c);return (a===1&&v)?v:a+v};
const gaExpr=terms=>{let s="";terms.forEach(([c,v])=>{if(c===0)return;const t=gaX(c,v);s+=s?(c<0?" − ":" + ")+t:(c<0?"−":"")+t});return s||"0"};
const gaE=(r,v)=>{v=v||"x";return "e<sup>"+(r===1?"":r===-1?"−":neg(r))+v+"</sup>"};
const gaFrac=(n,d)=>{const g=(a,b)=>b?g(b,a%b):Math.abs(a);const k=g(n,d)||1;n/=k;d/=k;if(d<0){n=-n;d=-d}return d===1?String(n):n+"/"+d};
/* MO data: [name, bonding e, antibonding e] over valence MOs */
const gaMO=[["N<sub>2</sub>",8,2,0],["O<sub>2</sub>",8,4,2],["O<sub>2</sub><sup>+</sup>",8,3,1],["O<sub>2</sub><sup>−</sup>",8,5,1],["O<sub>2</sub><sup>2−</sup>",8,6,0],["N<sub>2</sub><sup>+</sup>",7,2,1],["C<sub>2</sub>",6,2,0],["B<sub>2</sub>",4,2,2],["F<sub>2</sub>",8,6,0],["Ne<sub>2</sub>",8,8,0],["He<sub>2</sub><sup>+</sup>",2,1,1],["H<sub>2</sub>",2,0,0],["NO",8,3,1],["CO",8,2,0],["Be<sub>2</sub>",2,2,0]];
const gaHS=n=>{let t,e;if(n<=5){t=Math.min(n,3);e=n-t}else{t=Math.min(6,n-2);e=n-t}const up=n<=5?n:10-n;return {t,e,up,cfse:r2(-0.4*t+0.6*e)}};
const gaLS=n=>{const t=Math.min(n,6),e=n-t;const up=n<=3?n:n<=6?6-n:n<=8?n-6:10-n;return {t,e,up,cfse:r2(-0.4*t+0.6*e)}};
const gaIon=[["Ti<sup>3+</sup>",1],["V<sup>3+</sup>",2],["Cr<sup>3+</sup>",3],["Cr<sup>2+</sup>",4],["Mn<sup>2+</sup>",5],["Fe<sup>3+</sup>",5],["Fe<sup>2+</sup>",6],["Co<sup>2+</sup>",7],["Ni<sup>2+</sup>",8],["Cu<sup>2+</sup>",9],["Zn<sup>2+</sup>",10]];
const gaEo=[["Mg",-2.37],["Al",-1.66],["Zn",-0.76],["Fe",-0.44],["Ni",-0.25],["Sn",-0.14],["Cu",0.34],["Ag",0.80]];
const gaSalt=[["Ca(HCO<sub>3</sub>)<sub>2</sub>",162,1],["Mg(HCO<sub>3</sub>)<sub>2</sub>",146,1],["CaSO<sub>4</sub>",136,0],["MgSO<sub>4</sub>",120,0],["CaCl<sub>2</sub>",111,0],["MgCl<sub>2</sub>",95,0]];

genAdd("AHT-002",{
1:[
 ()=>{const s=pick(gaMO),bo=(s[1]-s[2])/2;const Q=`Using molecular orbital theory, what is the bond order of ${s[0]}?`,W=`Bond order = (N<sub>b</sub> − N<sub>a</sub>)/2 = (${s[1]} − ${s[2]})/2 = ${bo}, counting the valence-shell MOs.`;return either(.5,()=>nat(Q+" (Give the number.)",bo,W),()=>mcq(Q,String(bo),[String(bo+0.5),String(bo+1),String(bo+1.5)],W))},
 ()=>{const s=pick(gaMO);return nat(`How many unpaired electrons does ${s[0]} have in its MO configuration?`,s[3],`Fill the valence MOs in order of energy and apply Hund's rule to the degenerate π orbitals. ${s[0]} ends up with ${s[3]} unpaired electron(s)${s[3]?", so it is paramagnetic":", so it is diamagnetic"}.`)},
 ()=>{const V=pick([100,225,400,625,900,1600]),l=r2(12.27/Math.sqrt(V));return either(.5,()=>nat(`An electron is accelerated through ${V} V. Its de Broglie wavelength in Å? (use λ = 12.27/√V Å)`,l,`λ = 12.27/√${V} = 12.27/${Math.sqrt(V)} = ${l} Å.`),()=>{const k=rnd(1,8),lam=r2(6.626e-34/(9.11e-31*k*1e6)*1e10);return nat(`An electron moves at ${k}×10<sup>6</sup> m/s. Find its de Broglie wavelength in Å. (h = 6.626×10<sup>−34</sup> J s, m = 9.11×10<sup>−31</sup> kg)`,lam,`λ = h/mv = 6.626×10<sup>−34</sup>/(9.11×10<sup>−31</sup> × ${k}×10<sup>6</sup>) m = ${lam} Å.`)})},
 ()=>{const d=pick([0.5,1,2,4,5]),dv=r2(6.626e-34/(4*Math.PI*9.11e-31*d*1e-10)/1e5);return nat(`The position of an electron is known to within ${d} Å. Minimum uncertainty in its velocity, in units of 10<sup>5</sup> m/s? (Δx·Δp ≥ h/4π)`,dv,`Δv = h/(4π m Δx) = 6.626×10<sup>−34</sup>/(4π × 9.11×10<sup>−31</sup> × ${d}×10<sup>−10</sup>) = ${dv}×10<sup>5</sup> m/s.`)},
 ()=>either(.5,()=>{const n2=rnd(2,6),n1=rnd(1,n2-1),E=r2(13.6*(1/(n1*n1)-1/(n2*n2)));return nat(`Energy (in eV) of the photon emitted when a hydrogen electron falls from n = ${n2} to n = ${n1}? (E<sub>n</sub> = −13.6/n² eV)`,E,`ΔE = 13.6(1/${n1}² − 1/${n2}²) = 13.6(${r2(1/(n1*n1))} − ${+(1/(n2*n2)).toFixed(4)}) = ${E} eV.`)},()=>{const n=rnd(2,5),l=rnd(0,Math.min(n-1,3)),L="spdf"[l],r=n-l-1;return mcq(`How many radial nodes does the ${n}${L} orbital have?`,String(r),shuffle([...new Set([r+1,r+2,r+3,r-1,l,n-1,n].filter(x=>x>=0&&x!==r))]).slice(0,3).map(String),`Radial nodes = n − l − 1 = ${n} − ${l} − 1 = ${r}. Angular nodes = l = ${l}.`)}),
 ()=>{const [ion,n]=pick(gaIon),hs=coin(.5);const r=hs?gaHS(n):gaLS(n);const mu=r2(Math.sqrt(r.up*(r.up+2)));return either(.34,()=>nat(`An octahedral complex of ${ion} (d<sup>${n}</sup>) has a ${hs?"weak":"strong"}-field ligand. How many unpaired electrons?`,r.up,`${hs?"Weak field: Δ<sub>o</sub> &lt; pairing energy, so t<sub>2g</sub> and e<sub>g</sub> fill singly first":"Strong field: Δ<sub>o</sub> &gt; pairing energy, so t<sub>2g</sub> fills completely first"}. Configuration t<sub>2g</sub><sup>${r.t}</sup>e<sub>g</sub><sup>${r.e}</sup> gives ${r.up} unpaired electron${r.up===1?"":"s"}.`),()=>nat(`Spin-only magnetic moment (in BM) of an octahedral ${hs?"high-spin":"low-spin"} d<sup>${n}</sup> ion (${ion})? Use μ = √(n(n+2)).`,mu,`Configuration t<sub>2g</sub><sup>${r.t}</sup>e<sub>g</sub><sup>${r.e}</sup> has ${r.up} unpaired electrons, so μ = √(${r.up}×${r.up+2}) = ${mu} BM.`),()=>nat(`Find the CFSE (in units of Δ<sub>o</sub>, as a signed number) of an octahedral ${hs?"high-spin":"low-spin"} d<sup>${n}</sup> complex, ignoring pairing energy.`,r.cfse,`CFSE = (−0.4 × ${r.t} + 0.6 × ${r.e})Δ<sub>o</sub> = ${r.cfse}Δ<sub>o</sub>, using t<sub>2g</sub><sup>${r.t}</sup>e<sub>g</sub><sup>${r.e}</sup>.`))},
 ()=>{const L=[["H<sub>2</sub>O","bent (V-shaped)","sp³"],["NH<sub>3</sub>","trigonal pyramidal","sp³"],["XeO<sub>3</sub>","trigonal pyramidal","sp³"],["XeO<sub>4</sub>","tetrahedral","sp³"]];const [m,g,h]=pick(L);const G=["bent (V-shaped)","trigonal pyramidal","tetrahedral","linear","trigonal planar","square planar"];return either(.5,()=>mcq(`What is the shape of ${m} according to VSEPR theory?`,g,shuffle(G.filter(x=>x!==g)).slice(0,3),`${m}: the central atom has four electron domains (bond pairs plus lone pairs), so the electron geometry is tetrahedral and the shape is ${g}.`),()=>mcq(`Hybridisation of the central atom in ${m}?`,h,["sp","sp²","sp³d","sp³d²"],`${m} has four electron domains around the central atom (sigma bonds plus lone pairs), which needs sp³ hybrid orbitals.`))},
 ()=>msq("Which of these are paramagnetic according to MOT?",shuffle(gaMO.filter(x=>x[3]>0).map(x=>x[0])).slice(0,2),shuffle(gaMO.filter(x=>x[3]===0&&x[1]>x[2]).map(x=>x[0])).slice(0,2),"Paramagnetism needs at least one unpaired electron in the MO diagram. Species with all electrons paired are diamagnetic."),

 ()=>{const a=pick([["In band theory, a metal is characterised by…","overlapping (or partly filled) valence and conduction bands",["a large forbidden gap of about 6 eV","a completely filled valence band and empty conduction band separated by 1 eV","no conduction band"],"In a metal the highest occupied band is only partly filled or overlaps the next band, so electrons move freely."],["Which solid has a large band gap (about 5 eV or more)?","an insulator",["a metal","a semiconductor at 0 K only","a conductor"],"Insulators have a filled valence band separated from an empty conduction band by a large gap, so thermal energy cannot promote electrons."],["With rising temperature the resistivity of a semiconductor…","decreases",["increases","stays constant","becomes infinite"],"More electrons are excited across the small band gap, so carriers increase and resistivity falls (opposite to a metal)."]]);return mcq(a[0],a[1],a[2],a[3])},
],
2:[
 ()=>{const H=rnd(-200,200),S=rnd(-25,25)*10,T=rnd(2,12)*50,G=r2(H-T*S/1000);return nat(`For a reaction ΔH = ${neg(H)} kJ/mol and ΔS = ${neg(S)} J/(K mol). Find ΔG at ${T} K in kJ/mol.`,G,`ΔG = ΔH − TΔS = ${neg(H)} − ${T}×(${neg(S)}/1000) = ${neg(H)} − (${neg(r2(T*S/1000))}) = ${neg(G)} kJ/mol.`)},
 ()=>either(.5,()=>{const a=rnd(-2,3),b=rnd(-3,0),n=2,E0=pick([1.10,0.46,0.78]),E=r2(E0-0.0591/n*(a-b));return nat(`A cell with n = 2 has E° = ${E0.toFixed(2)} V at 298 K. Q = [products]/[reactants] = 10<sup>${a-b}</sup>. Find E<sub>cell</sub> in V (0.0591 constant, 2 decimals).`,E,`Nernst: E = E° − (0.0591/n) log Q = ${E0.toFixed(2)} − (0.0591/2)(${a-b}) = ${E} V.`)},()=>{const [m,E0]=pick(gaEo.slice(2,7)),n=2,k=rnd(-3,0),E=r2(E0+0.0591/n*k);return nat(`Electrode potential (V) of an M<sup>2+</sup>/M electrode (E° = ${E0.toFixed(2)} V, like ${m}) at 298 K when [M<sup>2+</sup>] = 10<sup>${k}</sup> M? Use E = E° + (0.0591/n) log C and give 2 decimals.`,E,`E = ${E0.toFixed(2)} + (0.0591/2)(${k}) = ${E} V.`)}),
 ()=>{const a=pick(gaEo),b=pick(gaEo.filter(x=>x[0]!==a[0])),cat=a[1]>b[1]?a:b,an=a[1]>b[1]?b:a,E=r2(cat[1]-an[1]);return either(.5,()=>nat(`Standard electrode potentials: ${cat[0]}<sup>n+</sup>/${cat[0]} = ${cat[1].toFixed(2)} V and ${an[0]}<sup>n+</sup>/${an[0]} = ${an[1].toFixed(2)} V. Find E° of the cell in V.`,E,`E°<sub>cell</sub> = E°<sub>cathode</sub> − E°<sub>anode</sub> = ${cat[1].toFixed(2)} − (${an[1].toFixed(2)}) = ${E} V, with ${cat[0]} as cathode.`),()=>mcq(`In a cell made from ${a[0]} (${a[1].toFixed(2)} V) and ${b[0]} (${b[1].toFixed(2)} V) standard electrodes, which acts as the anode?`,an[0],[cat[0],"both","neither"],`The metal with the lower (more negative) reduction potential is oxidised, so ${an[0]} is the anode.`))},
 ()=>{const n=pick([1,2,3]),E=rnd(5,25)/10*(n===1?0.5:1),G=r2(-n*96500*E/1000);return nat(`Find ΔG° in kJ/mol for a cell with n = ${n} and E° = ${E.toFixed(2)} V. (F = 96500 C/mol)`,G,`ΔG° = −nFE° = −${n}×96500×${E.toFixed(2)} J = ${G} kJ/mol.`)},
 ()=>either(.5,()=>{const a=rnd(390,395),b=rnd(280,290);return nat(`(i) C + O₂ → CO₂, ΔH = −${a} kJ; (ii) CO + ½O₂ → CO₂, ΔH = −${b} kJ. Find ΔH (kJ) for C + ½O₂ → CO using Hess's law.`,-(a-b),`Subtract (ii) from (i): ΔH = −${a} − (−${b}) = −${a-b} kJ.`)},()=>{const c=pick([-393.5,-393.51]),w=pick([-285.8,-241.8]),m=pick([-74.8,-74.9,-74.6]);const H=r2(c+2*w-m);return nat(`ΔH<sub>f</sub> (kJ/mol): CO₂ = ${c}, H₂O = ${w}, CH₄ = ${m}. Find ΔH for CH₄ + 2O₂ → CO₂ + 2H₂O.`,H,`ΔH = ΣΔH<sub>f</sub>(products) − ΣΔH<sub>f</sub>(reactants) = (${c} + 2×${w}) − (${m}) = ${H} kJ (O₂ has ΔH<sub>f</sub> = 0).`)}),
 ()=>either(.5,()=>{const q=rnd(2,9)*100,w=rnd(1,8)*100;return nat(`A gas absorbs ${q} J of heat and does ${w} J of work on the surroundings. Find ΔU in J.`,q-w,`ΔU = q − w<sub>by system</sub> = ${q} − ${w} = ${q-w} J.`)},()=>{const dn=pick([-2,-1,1,2]),T=rnd(3,10)*100,d=r2(dn*8.314*T);return nat(`For a reaction with Δn<sub>gas</sub> = ${neg(dn)} at ${T} K, find ΔH − ΔU in J/mol. (R = 8.314 J/K mol)`,d,`ΔH = ΔU + Δn RT, so ΔH − ΔU = ${neg(dn)} × 8.314 × ${T} = ${neg(d)} J/mol.`)}),
 ()=>either(.5,()=>{const H=pick([6.01,6.0,3.35,9.0]),T=pick([273,300,250,180]),S=r2(H*1000/T);return nat(`Enthalpy of fusion is ${H} kJ/mol at its melting point ${T} K. Find ΔS of fusion in J/(K mol).`,S,`At equilibrium ΔS = ΔH/T = ${H}×1000/${T} = ${S} J/(K mol).`)},()=>{const n=rnd(1,4),S=r2(n*8.314*0.693);return nat(`${n} mol of an ideal gas expand isothermally and reversibly to twice its volume. Find ΔS in J/K. (R = 8.314; ln 2 = 0.693)`,S,`ΔS = nR ln(V₂/V₁) = ${n}×8.314×ln2 = ${S} J/K.`)}),
 ()=>{const T=rnd(3,10)*100,S=rnd(4,20)*10,H=T*S/1000;return nat(`A reaction has ΔH = ${H} kJ and ΔS = ${S} J/K. At what temperature (K) does ΔG = 0 (spontaneity switches)?`,T,`ΔG = 0 ⇒ T = ΔH/ΔS = ${H}×1000/${S} = ${T} K. Above this the reaction is spontaneous because ΔS &gt; 0.`)},
 ()=>{const c=pick([[-1,1,"spontaneous at all temperatures"],[1,-1,"non-spontaneous at all temperatures"],[-1,-1,"spontaneous only at low temperature"],[1,1,"spontaneous only at high temperature"]]);const O=["spontaneous at all temperatures","non-spontaneous at all temperatures","spontaneous only at low temperature","spontaneous only at high temperature"];return mcq(`A reaction has ΔH ${c[0]<0?"&lt; 0":"&gt; 0"} and ΔS ${c[1]<0?"&lt; 0":"&gt; 0"}. It is…`,c[2],O.filter(x=>x!==c[2]),"Use ΔG = ΔH − TΔS. Negative ΔH and positive ΔS always give negative ΔG; the opposite signs never do; if the signs are equal, temperature decides.")},
 ()=>{const k=rnd(1,5),j=rnd(1,3),pKa=pick([4.0,4.5,5.0,6.0]);return either(.5,()=>nat(`pH of 10<sup>−${k}</sup> M HCl (strong acid)?`,k,`A strong acid dissociates completely: [H⁺] = 10<sup>−${k}</sup>, pH = ${k}.`),()=>nat(`A buffer has [salt]/[acid] = ${Math.pow(10,j)} and the acid's pK<sub>a</sub> = ${pKa}. Find its pH (Henderson–Hasselbalch).`,r2(pKa+j),`pH = pK<sub>a</sub> + log([salt]/[acid]) = ${pKa} + log(10<sup>${j}</sup>) = ${r2(pKa+j)}.`))},
 ()=>{const L=[["An Ellingham diagram plots…","ΔG° of oxide formation against temperature",["ΔH against pressure","EMF against concentration","entropy against volume"],"Ellingham diagrams show ΔG° per mole of O₂ vs T for oxide formation."],["In an Ellingham diagram, a metal whose oxide line lies lower can reduce an oxide whose line lies…","higher",["lower","at any place","at the same position"],"The lower line has the more negative ΔG°, so that metal reduces oxides above it (e.g. Al reduces Fe₂O₃)."],["The slope of a line in an Ellingham diagram equals…","−ΔS°",["ΔH°","+ΔS° for gas consumed","ΔG°"],"ΔG° = ΔH° − TΔS°, so the slope is −ΔS°."]];const a=pick(L);return mcq(a[0],a[1],a[2],a[3])},
]});

genAdd("AHT-002",{
3:[
 ()=>{const t=pick(gaSalt.filter(x=>x[2])),p=pick(gaSalt.filter(x=>!x[2])),k1=rnd(1,6),k2=rnd(1,6),m1=t[1]*k1/2,m2=p[1]*k2/2,T=50*k1,P=50*k2,w=pick(["temporary","permanent","total"]),ans=w==="temporary"?T:w==="permanent"?P:T+P;return nat(`A water sample contains ${m1} mg/L of ${t[0]} and ${m2} mg/L of ${p[0]}. Find its ${w} hardness in ppm as CaCO₃. (Ca = 40, Mg = 24, C = 12, S = 32, Cl = 35.5, O = 16, H = 1)`,ans,`Hardness (as CaCO₃) = mass × 100/M. ${t[0]}: ${m1}×100/${t[1]} = ${T} ppm (temporary). ${p[0]}: ${m2}×100/${p[1]} = ${P} ppm (permanent). ${w==="temporary"?"Temporary":w==="permanent"?"Permanent":"Total"} = ${ans} ppm.`)},
 ()=>{const a=rnd(1,8)*10,b=rnd(1,6)*10,c=rnd(1,8)*10,d=rnd(1,6)*10,L=r2(0.74*(a+2*b+d)),S=r2(1.06*(c+d)),w=coin(.5);return nat(`A water sample has (in ppm as CaCO₃) temporary Ca hardness ${a}, temporary Mg hardness ${b}, permanent Ca hardness ${c} and permanent Mg hardness ${d}. Find the ${w?"pure lime":"pure soda"} needed in mg per litre.`,w?L:S,w?`Lime = 74/100 [Ca(HCO₃)₂ + 2 Mg(HCO₃)₂ + permanent Mg] = 0.74(${a} + 2×${b} + ${d}) = ${L} mg/L.`:`Soda = 106/100 [permanent Ca + permanent Mg] = 1.06(${c} + ${d}) = ${S} mg/L.`)},
 ()=>{const t=coin(.5),k=rnd(1,8),M=t?162:146,w=(t?81:73)*k,L=t?37*k:74*k;return nat(`Clark's process: ${w} mg/L of ${t?"Ca(HCO₃)₂":"Mg(HCO₃)₂"} is treated with lime. How many mg of Ca(OH)₂ are needed per litre? (Ca(OH)₂ = 74)`,L,t?`Ca(HCO₃)₂ + Ca(OH)₂ → 2CaCO₃↓ + 2H₂O, 162 g needs 74 g lime: ${w}×74/162 = ${L} mg.`:`Mg(HCO₃)₂ + 2Ca(OH)₂ → 2CaCO₃↓ + Mg(OH)₂↓ + 2H₂O; 146 g needs 148 g lime: ${w}×148/146 = ${L} mg.`)},
 ()=>{const cs=rnd(0,4);let P,M;if(cs===0){M=rnd(2,10)*20;P=0}else if(cs===1){P=rnd(1,6)*20;M=2*P}else if(cs===2){P=rnd(1,4)*20;M=2*P+rnd(1,5)*20}else if(cs===3){M=rnd(2,6)*20;P=M/2+10*rnd(1,Math.max(1,M/20-1)); if(P>=M)P=M-10}else{M=rnd(2,8)*20;P=M}let OH=0,CO=0,HC=0;if(P===0)HC=M;else if(P===M)OH=M;else if(2*P===M)CO=M;else if(2*P<M){CO=2*P;HC=M-2*P}else{OH=2*P-M;CO=2*(M-P)}const sp=pick([["hydroxide","OH",OH],["carbonate","CO",CO],["bicarbonate","HC",HC]]);return nat(`In an alkalinity determination, phenolphthalein alkalinity P = ${P} ppm and total (methyl orange) alkalinity M = ${M} ppm, both as CaCO₃. Find the ${sp[0]} alkalinity in ppm.`,sp[2],`Case analysis on P and M: OH = ${OH}, CO₃ = ${CO}, HCO₃ = ${HC} ppm. (P = 0: only HCO₃ = M; P = M/2: only CO₃; P &lt; M/2: CO₃ = 2P, HCO₃ = M − 2P; P &gt; M/2: OH = 2P − M, CO₃ = 2(M − P); P = M: only OH.)`)},
 ()=>{const N=pick([0.02,0.05,0.1]),V=rnd(4,20),S=pick([50,100]),A=r2(N*V*50000/S);return nat(`${S} mL of water needs ${V} mL of ${N} N HCl to reach the methyl orange end point. Total alkalinity in ppm as CaCO₃?`,A,`Alkalinity = N×V×50 000/V<sub>sample</sub> = ${N}×${V}×50000/${S} = ${A} ppm.`)},
 ()=>either(.5,()=>{const M=pick([0.01,0.02]),V=rnd(5,25),Vs=pick([50,100]),H=r2(M*V*100*1000/Vs);return nat(`${Vs} mL of hard water is titrated with ${M} M EDTA; ${V} mL is needed. Hardness in ppm as CaCO₃? (CaCO₃ = 100 g/mol)`,H,`Moles Ca²⁺ = ${M}×${V}/1000, mass CaCO₃ = ${r2(M*V*100)} mg in ${Vs} mL, i.e. ${H} mg/L (ppm).`)},()=>{const k=rnd(1,6),H=pick([200,250,500]),N=k*H/10;const V=N*1000/H;return nat(`A zeolite bed can exchange ${N} g of CaCO₃-equivalent hardness before regeneration. How many litres of water of hardness ${H} ppm can it soften?`,V,`Hardness removed per litre = ${H} mg. Volume = ${N}×1000 mg/${H} mg/L = ${V} L. The bed is then regenerated with brine (NaCl).`)}),
 ()=>{const i=pick([1,2]),c=pick([0.05,0.1,0.2]),T=pick([300,298,310]),pi=r2(i*c*0.0821*T);return nat(`Osmotic pressure (atm) of a ${c} M ${i===2?"NaCl (i = 2)":"glucose (i = 1)"} solution at ${T} K, which is the minimum pressure a reverse osmosis unit must exceed? (R = 0.0821 L atm/K mol)`,pi,`π = iCRT = ${i}×${c}×0.0821×${T} = ${pi} atm. In RO the applied pressure must exceed π so water flows from the concentrated side.`)},
 ()=>{const a=pick(gaEo),b=pick(gaEo.filter(x=>x[0]!==a[0])),an=a[1]<b[1]?a:b,ct=a[1]<b[1]?b:a;return mcq(`When ${a[0]} and ${b[0]} are in electrical contact in a moist environment (galvanic corrosion), which one corrodes?`,an[0],[ct[0],"both equally","neither"],`The metal with the lower electrode potential (${an[0]}, ${an[1].toFixed(2)} V) acts as the anode and is oxidised; ${ct[0]} (${ct[1].toFixed(2)} V) is the cathode and is protected.`)},
 ()=>{const L=[["Rusting of iron in neutral water: the cathodic reaction is…","O₂ + 2H₂O + 4e⁻ → 4OH⁻",["Fe → Fe²⁺ + 2e⁻","2H⁺ + 2e⁻ → H₂","Fe²⁺ → Fe³⁺ + e⁻"],"In neutral or alkaline solution oxygen is reduced at the cathode; iron oxidation (Fe → Fe²⁺ + 2e⁻) is the anodic reaction."],["In acidic solution, the cathodic reaction during iron corrosion is…","2H⁺ + 2e⁻ → H₂",["O₂ + 2H₂O + 4e⁻ → 4OH⁻","Fe → Fe²⁺ + 2e⁻","Fe³⁺ + e⁻ → Fe²⁺"],"Without oxygen, hydrogen ions are reduced, evolving hydrogen (hydrogen-evolution type corrosion)."],["Water-line corrosion is a type of…","differential aeration corrosion",["stress corrosion","galvanic corrosion only","intergranular corrosion only"],"The part of the metal below the water line is poorly aerated (anode) while the part just above is rich in oxygen (cathode)."],["Zinc coating on iron protects it even when scratched because zinc…","is sacrificially oxidised (acts as anode)",["is a noble metal","forms no oxide","is cathodic to iron"],"Zn has a lower electrode potential than Fe, so it becomes the anode and corrodes instead of iron (cathodic protection)."],["Which is a sacrificial anode for protecting buried iron pipes?","Magnesium",["Copper","Silver","Tin"],"Magnesium is more active than iron, so it corrodes preferentially."]];const a=pick(L);return mcq(a[0],a[1],a[2],a[3])},
 ()=>{const L=[["Scale formation","CaSO₄ (low solubility in hot water) and CaCO₃"],["Caustic embrittlement","high concentration of NaOH in the boiler water"],["Priming and foaming","dissolved solids, suspended impurities, and oil in boiler water"],["Boiler corrosion","dissolved O₂, CO₂ and MgCl₂ (hydrolysis to HCl)"]];const a=pick(L),ws=L.filter(x=>x!==a).map(x=>x[1]);return mcq(`In boilers, ${a[0].toLowerCase()} is mainly due to…`,a[1],ws,`${a[0]} arises from ${a[1]}; each boiler trouble has its own specific cause.`)},
 ()=>msq("Which methods soften hard water?",shuffle(["Lime–soda process","Zeolite (permutit) process","Reverse osmosis","Ion exchange"]).slice(0,rnd(2,3)),shuffle(["Adding chlorine","Filtration through sand","Aeration","Coagulation with alum only"]).slice(0,2),"Hardness ions are removed by precipitation (lime–soda), exchange (zeolite/ion exchange) or membranes (RO). Chlorination, sand filtration and aeration do not remove Ca²⁺ and Mg²⁺."),
],
4:[
 ()=>{const P=[["polyethylene",28],["polypropylene",42],["PVC",62.5],["polyacrylonitrile (PAN)",53],["PMMA",100],["polystyrene",104]],p=pick(P),n=rnd(2,50)*100,M=r2(n*p[1]);return either(.5,()=>nat(`A sample of ${p[0]} has average molar mass ${M} g/mol (repeat unit mass ${p[1]}). Find its degree of polymerisation.`,n,`DP = M<sub>polymer</sub>/M<sub>repeat unit</sub> = ${M}/${p[1]} = ${n}.`),()=>nat(`${p[0]} has degree of polymerisation ${n} and repeat unit mass ${p[1]}. Find its molar mass in g/mol.`,M,`M = DP × M<sub>repeat unit</sub> = ${n} × ${p[1]} = ${M} g/mol.`))},
 ()=>{const N1=rnd(1,5)*100,N2=rnd(1,5)*100,M1=rnd(1,5)*10000,M2=rnd(6,15)*10000,Mn=r2((N1*M1+N2*M2)/(N1+N2)),Mw=r2((N1*M1*M1+N2*M2*M2)/(N1*M1+N2*M2)),w=pick(["Mn","Mw","PDI"]);const ans=w==="Mn"?Mn:w==="Mw"?Mw:r2(Mw/Mn);return nat(`A polymer sample has ${N1} molecules of molar mass ${M1} and ${N2} molecules of molar mass ${M2}. Find its ${w==="Mn"?"number-average molar mass M<sub>n</sub>":w==="Mw"?"weight-average molar mass M<sub>w</sub>":"polydispersity index M<sub>w</sub>/M<sub>n</sub>"}.`,ans,`M<sub>n</sub> = ΣN<sub>i</sub>M<sub>i</sub>/ΣN<sub>i</sub> = ${Mn}; M<sub>w</sub> = ΣN<sub>i</sub>M<sub>i</sub>²/ΣN<sub>i</sub>M<sub>i</sub> = ${Mw}; PDI = ${r2(Mw/Mn)}.`)},
 ()=>{const C=rnd(55,68),H=rnd(4,6),O=rnd(1,3)*8,S=rnd(0,2),G=r2((8080*C+34500*(H-O/8)+2240*S)/100),N=r2(G-0.09*H*587);return either(.5,()=>nat(`A coal contains C = ${C}%, H = ${H}%, O = ${O}%, S = ${S}%. Find its gross calorific value in kcal/kg using Dulong's formula GCV = [8080C + 34500(H − O/8) + 2240S]/100.`,G,`H available = ${H} − ${O}/8 = ${H-O/8}. GCV = (8080×${C} + 34500×${H-O/8} + 2240×${S})/100 = ${G} kcal/kg.`),()=>nat(`A coal has C = ${C}%, H = ${H}%, O = ${O}%, S = ${S}%. Find its net calorific value in kcal/kg. (NCV = GCV − 0.09 H × 587)`,N,`GCV = ${G} kcal/kg (Dulong). Latent heat loss = 0.09×${H}×587 = ${r2(0.09*H*587)}. NCV = ${G} − ${r2(0.09*H*587)} = ${N} kcal/kg.`))},
 ()=>{const W=pick([1000,2000]),w=pick([500,300,250]),x=pick([0.5,0.8,1]),dt=rnd(3,20)/10,G=r2((W+w)*dt/x);return nat(`In a bomb calorimeter, ${x} g of fuel raises ${W} g of water by ${dt} °C. Water equivalent of the calorimeter = ${w} g. Find the gross calorific value in cal/g. (specific heat of water = 1 cal/g°C)`,G,`GCV = (W + w)Δt/x = (${W} + ${w})×${dt}/${x} = ${G} cal/g.`)},
 ()=>{const H=rnd(5,12)*10,L=H+rnd(4,9)*10,U=H+rnd(1,L-H-1),VI=r2((L-U)/(L-H)*100);return nat(`Viscosity index (VI) of an oil: L = ${L} (oil with VI 0), H = ${H} (oil with VI 100), U = ${U} (test oil), all at the same viscosity. Find VI = (L − U)/(L − H) × 100.`,VI,`VI = (${L} − ${U})/(${L} − ${H}) × 100 = ${L-U}/${L-H} × 100 = ${VI}.`)},
 ()=>{const L=[["flash point","lowest temperature at which the oil gives enough vapour to ignite momentarily with a flame"],["fire point","temperature at which the oil vapour burns continuously for at least 5 seconds"],["pour point","lowest temperature at which the oil still flows under prescribed conditions"],["cloud point","temperature at which wax crystals first make the oil turbid on cooling"],["aniline point","minimum temperature at which equal volumes of the oil and aniline become miscible"]],a=pick(L);return mcq(`Which is the correct definition of the ${a[0]} of a lubricant?`,a[1],L.filter(x=>x!==a).map(x=>x[1]),`${a[0]}: ${a[1]}. Do not confuse the terms; flash and fire points concern burning, pour and cloud points concern cold flow.`)},
 ()=>{const L=[["Vinyl chloride","PVC","addition"],["Propene","polypropylene","addition"],["Acrylonitrile","PAN","addition"],["Methyl methacrylate","PMMA","addition"],["Ethylene glycol and terephthalic acid","PET","condensation"],["Hexamethylenediamine and adipic acid","nylon-6,6","condensation"],["Phenol and formaldehyde","Bakelite","condensation"]],a=pick(L);return either(.5,()=>mcq(`Which polymer is made from ${a[0].toLowerCase()}?`,a[1],L.filter(x=>x!==a).map(x=>x[1]).slice(0,3),`${a[1]} is prepared from ${a[0].toLowerCase()} by ${a[2]} polymerisation.`),()=>mcq(`${a[1]} is prepared by which type of polymerisation?`,a[2],["addition"==a[2]?"condensation":"addition","cationic ring-opening","none of these"],`${a[1]} is made from ${a[0].toLowerCase()} by ${a[2]} polymerisation.`))},
 ()=>msq("Which polymers are formed by addition polymerisation?",shuffle(["polyethylene","PVC","polypropylene","PAN","PMMA"]).slice(0,rnd(2,3)),shuffle(["nylon-6,6","PET (terylene)","Bakelite"]).slice(0,2),"Addition polymers form from unsaturated monomers (C=C) without losing a small molecule. Nylon-6,6, PET and Bakelite form by condensation with loss of water."),
 ()=>{const L=[["Vulcanisation of rubber means heating it with…","sulphur",["chlorine","oxygen","carbon black"],"Sulphur forms cross-links between polyisoprene chains, giving strength and elasticity."],["Toughened glass is made by…","heating to near the softening point and rapidly cooling (quenching) the surface",["slow annealing","adding lead oxide","coating with silver"],"Quenching leaves the surface in compression and the interior in tension, which makes the glass several times stronger."],["Chemical strengthening of glass is done by…","ion exchange of Na⁺ with larger K⁺ ions at the surface",["cooling slowly","adding NaOH","melting at higher temperature"],"Larger K⁺ ions crowd the surface, creating compressive stress."],["The main constituent of biogas is…","methane",["ethane","carbon monoxide","hydrogen"],"Anaerobic digestion of biomass produces about 55–65% CH₄ with CO₂."],["Polyacetylene becomes a conducting polymer when…","doped (e.g. with I₂ or AsF₅)",["cross-linked","hydrogenated","vulcanised"],"Doping creates mobile charge carriers along the conjugated backbone."],["Which of these is a biodegradable polymer?","PHBV",["PVC","polystyrene","Teflon"],"PHBV (poly-β-hydroxybutyrate-co-β-hydroxyvalerate) is broken down by microbes."]],a=pick(L);return mcq(a[0],a[1],a[2],a[3])},
 ()=>msq("Which are primary air pollutants?",shuffle(["SO₂","CO","NO","Hydrocarbons"]).slice(0,rnd(2,3)),shuffle(["Ozone (tropospheric)","Peroxyacetyl nitrate (PAN)","Sulphuric acid mist"]).slice(0,2),"Primary pollutants are emitted directly. Ozone, PAN and H₂SO₄ mist form in the atmosphere from primary pollutants, so they are secondary."),
 ()=>{const L=[["Complete fluid-film (hydrodynamic) lubrication","the surfaces are fully separated by a thick oil film",["the surfaces touch at asperities","a solid additive is needed at high pressure","no lubricant is present"]],["Boundary lubrication","a thin adsorbed film protects when the fluid film breaks down",["the surfaces are fully separated by a thick film","only solid lubricants are used","it occurs at very low load"]],["Extreme pressure lubrication","additives (such as sulphur or chlorine compounds) form a film at high load and temperature",["a thick oil wedge separates the surfaces","a gas film is used","water is the lubricant"]]],a=pick(L);return mcq(`In ${a[0].toLowerCase()}…`,a[1],a[2],`${a[0]}: ${a[1]}.`)},
],
5:[
 ()=>either(.5,()=>{const e=pick([500,1000,1500,2000,5000]),cc=pick([2,4,5,8]),l=pick([1,2]),A=r2(e*cc*1e-4*l);return nat(`A solution with molar absorptivity ε = ${e} L mol⁻¹ cm⁻¹ and concentration ${cc}×10⁻⁴ M is in a ${l} cm cell. Find its absorbance A (Beer–Lambert law).`,A,`A = εcl = ${e} × ${cc}×10⁻⁴ × ${l} = ${A}.`)},()=>{const T=pick([10,1,0.1]),A=-Math.log10(T/100);return nat(`A sample transmits ${T}% of the light passing through. Find its absorbance A = log₁₀(I₀/I).`,r2(A),`A = −log₁₀(T/100) = −log₁₀(${T/100}) = ${r2(A)}.`)}),
 ()=>{const f=pick([1,4,9]),g=pick([1,4,9,16]),n=pick([1000,1200,1600,2000]),r=r2(n*Math.sqrt(f/g));return nat(`A diatomic bond vibrates at ${n} cm⁻¹. A second bond has ${f} times the force constant and ${g} times the reduced mass of the first. Its vibrational wavenumber in cm⁻¹? (ν̃ ∝ √(k/μ))`,r,`ν̃₂/ν̃₁ = √(${f}/${g}) = ${r2(Math.sqrt(f/g))}, so ν̃₂ = ${r} cm⁻¹.`)},
 ()=>either(.5,()=>{const B=pick([2,5,10,20]),J=rnd(0,5);return nat(`A rigid rotor has B = ${B} cm⁻¹. Find the wavenumber (cm⁻¹) of the rotational absorption J = ${J} → ${J+1}. (ν̃ = 2B(J + 1))`,2*B*(J+1),`ν̃ = 2B(J + 1) = 2×${B}×${J+1} = ${2*B*(J+1)} cm⁻¹. Adjacent lines are 2B apart.`)},()=>{const N=rnd(2,7),lin=N===2||coin(.5),d=lin?3*N-5:3*N-6;return nat(`How many vibrational modes does a ${lin?"linear":"non-linear"} molecule of ${N} atoms have?`,d,`Vibrational modes = ${lin?"3N − 5":"3N − 6"} = 3×${N} − ${lin?5:6} = ${d}.`)}),
 ()=>{const l=pick([200,248,310,400,500,620,800]),E=r2(1240/l),k=r2(1e7/l);return either(.5,()=>nat(`Photon energy (eV) of light of wavelength ${l} nm? (E = 1240/λ eV with λ in nm)`,E,`E = 1240/${l} = ${E} eV.`),()=>nat(`Convert a wavelength of ${l} nm to a wavenumber in cm⁻¹.`,k,`ν̃ = 1/λ = 10⁷/${l} = ${k} cm⁻¹ (1 nm = 10⁻⁷ cm).`))},
 ()=>{const M=pick([60,90,100,300,400,500]),d=pick([0.9,1.2,2.1,3.5,7.2,9.6]),Hz=r2(d*M);return either(.5,()=>nat(`A proton signal appears ${Hz} Hz downfield of TMS on a ${M} MHz spectrometer. Its chemical shift δ in ppm?`,d,`δ = (Δν in Hz)/(spectrometer frequency in MHz) = ${Hz}/${M} = ${d} ppm.`),()=>nat(`On a ${M} MHz NMR spectrometer, how many Hz from TMS does a proton with δ = ${d} ppm appear?`,Hz,`Shift in Hz = δ × spectrometer MHz = ${d}×${M} = ${Hz} Hz.`))},
 ()=>{const L=[["CH₃CH₂OH",3],["CH₃COCH₃",1],["CH₃OCH₃",1],["benzene",1],["propane",2],["ethyl acetate",3],["toluene",4],["p-xylene",2],["acetic acid",2],["2-propanol",3],["tert-butanol",2]],a=pick(L);return either(.5,()=>nat(`How many different signals does ${a[0]} show in its ¹H NMR spectrum (all sets of chemically equivalent protons)?`,a[1],`Count groups of chemically equivalent hydrogens; ${a[0]} has ${a[1]}.`),()=>{const n=rnd(0,5);return nat(`By the n+1 rule, a proton with ${n} equivalent neighbouring protons splits into how many lines?`,n+1,`Number of lines = n + 1 = ${n} + 1 = ${n+1}.`)})},
 ()=>{const B=pick([1.5,3,7,9.4]);return nat(`¹H resonates at 42.58 MHz per tesla. Find the resonance frequency in MHz for an MRI magnet of ${B} T.`,r2(42.58*B),`ν = 42.58 × B = 42.58×${B} = ${r2(42.58*B)} MHz. MRI images the ¹H of water and fat in tissue.`)},
 ()=>{const L=[["CH₂=CH₂ + Br₂ → CH₂Br–CH₂Br","addition"],["CH₃CH₂Br + alc. KOH → CH₂=CH₂","elimination"],["CH₃Br + OH⁻ → CH₃OH + Br⁻","nucleophilic substitution"],["butadiene + ethene → cyclohexene","Diels–Alder cycloaddition"],["benzene + Br₂/FeBr₃ → bromobenzene","electrophilic substitution"],["(CH₃)₃CBr + H₂O → (CH₃)₃COH","nucleophilic substitution"],["CH₃CH₂OH → CH₂=CH₂ (conc. H₂SO₄, heat)","elimination"]],a=pick(L),O=["addition","elimination","nucleophilic substitution","Diels–Alder cycloaddition","electrophilic substitution"];return mcq(`Classify the reaction: ${a[0]}`,a[1],shuffle(O.filter(x=>x!==a[1])).slice(0,3),`The reaction is ${a[1]}. Adding across a C=C is addition; loss of HX or H₂O forming C=C is elimination; replacing one group with another is substitution.`)},
 ()=>{const k=rnd(1,5),m=r2(6.9*k),T=r2(9*k),p=pick([50,60,70,80,90]);return either(.5,()=>nat(`Aspirin is made from salicylic acid (M = 138) and acetic anhydride. Theoretical yield of aspirin (M = 180) from ${m} g of salicylic acid, in g?`,T,`1 mol salicylic acid gives 1 mol aspirin: ${m}/138 = ${r2(m/138)} mol × 180 = ${T} g.`),()=>nat(`${m} g of salicylic acid (M = 138) gives ${r2(T*p/100)} g of aspirin (M = 180). Find the percentage yield.`,p,`Theoretical = ${m}×180/138 = ${T} g. Yield = ${r2(T*p/100)}/${T} × 100 = ${p}%.`))},
 ()=>{const L=[["Aspirin is chemically…","acetylsalicylic acid",["salicylic acid","methyl salicylate","p-acetamidophenol"],"Aspirin is the acetate ester of the phenolic OH of salicylic acid."],["Aspirin is prepared by acetylating salicylic acid with…","acetic anhydride (acid catalyst)",["acetone","ethanol","formic acid"],"Salicylic acid + (CH₃CO)₂O → aspirin + CH₃COOH, catalysed by a few drops of H₂SO₄ or H₃PO₄."],["Unreacted salicylic acid in an aspirin sample is detected using…","neutral FeCl₃ (violet colour)",["Tollens' reagent","Br₂ water","Fehling's solution"],"Salicylic acid has a free phenolic OH which gives a violet colour with FeCl₃; pure aspirin does not."],["Phenacetin is prepared by acetylating…","p-phenetidine (p-ethoxyaniline)",["p-nitrophenol","aniline only","salicylic acid"],"Acetylation of the NH₂ group of p-ethoxyaniline gives p-ethoxyacetanilide (phenacetin), an analgesic and antipyretic."]],a=pick(L);return mcq(a[0],a[1],a[2],a[3])},
 ()=>{const M=["HCl","CO","H₂O","NO","HBr"],N=["N₂","O₂","H₂","Cl₂"],C=["CO₂","CH₄","BF₃"];return msq("Which molecules show a pure rotational (microwave) spectrum?",shuffle(M).slice(0,rnd(2,3)),shuffle(N.concat(C)).slice(0,2),"Microwave absorption needs a permanent dipole moment. Homonuclear diatomics and symmetric molecules such as CO₂ and CH₄ have none.")},
 ()=>{const L=[["σ→σ*","n→σ*","π→π*","n→π*"]],t=shuffle(["σ→σ*","n→σ*","π→π*","n→π*"]).slice(0,2),rk={"σ→σ*":4,"n→σ*":3,"π→π*":2,"n→π*":1},hi=rk[t[0]]>rk[t[1]]?t[0]:t[1],lo=hi===t[0]?t[1]:t[0];return mcq(`Which of the transitions ${t[0]} and ${t[1]} needs more energy?`,hi,[lo,"both equal","cannot be compared"],`Energy order: σ→σ* &gt; n→σ* &gt; π→π* &gt; n→π*. So ${hi} needs more energy than ${lo}.`)},
]});

const gaZ=a=>a===0?"z":`(z ${a<0?"+":"−"} ${Math.abs(a)})`;
const gaSg=n=>n<0?"− "+(-n):"+ "+n;
const gaDE=(p,q)=>gaExpr([[1,"y″"],[p,"y′"],[q,"y"]])+" = 0";
const gaOD=[["(y″)³ + (y′)⁴ + y = 0",2,3],["y‴ + 2y″ + y = x",3,1],["(y′)² + y = 0",1,2],["y″ + (y′)³ = x²",2,1],["(y‴)² + y′ = 0",3,2],["(y″)⁴ + x y′ = 0",2,4],["y′ + y = sin x",1,1]];

genAdd("AHT-005",{
1:[
 ()=>{const a=rnd(1,3),c=rnd(-3,4),y0=c+8*rnd(-2,2),ans=r2(c+(y0-c)/Math.pow(2,a));return nat(`Solve dy/dx + ${a===1?"":a}y = ${neg(a*c)} with y(0) = ${neg(y0)}. Find y(ln 2).`,ans,`Integrating factor e<sup>${a===1?"":a}x</sup> gives y = ${neg(c)} + (${neg(y0-c)})e<sup>−${a===1?"":a}x</sup>, using y(0) = ${neg(y0)}. At x = ln 2, e<sup>−${a===1?"":a}x</sup> = 2<sup>−${a}</sup> = 1/${Math.pow(2,a)}, so y = ${neg(ans)}.`)},
 ()=>{const a=rnd(1,5),b=rnd(1,5),k=rnd(1,4);return either(.5,()=>nat(`For what value of k is (${a}xy² + ${b}y) dx + (kx²y + ${b}x) dy = 0 exact?`,a,`Exactness needs ∂M/∂y = ∂N/∂x. ∂M/∂y = ${2*a}xy + ${b}; ∂N/∂x = 2kxy + ${b}. So 2k = ${2*a}, k = ${a}.`),()=>nat(`The exact equation (2xy + ${a}) dx + (x² + ${b}) dy = 0 has general solution F(x, y) = C. If the curve passes through (1, ${k}), find C.`,k+a+b*k,`F = x²y + ${a}x + ${b}y, since F<sub>x</sub> = 2xy + ${a} and F<sub>y</sub> = x² + ${b}. At (1, ${k}): C = ${k} + ${a} + ${b}×${k} = ${k+a+b*k}.`))},
 ()=>{const a=rnd(1,4),b=rnd(0,3),y0=rnd(1,4),d=a+b+1;const xp=k=>k===1?"x":`x<sup>${k}</sup>`;return either(.5,()=>mcq(`The integrating factor of dy/dx + (${a}/x)y = ${b===0?"1":xp(b)} (x &gt; 0) is…`,xp(a),[gaE(a),xp(a+1),`1/${xp(a)}`],`IF = e<sup>∫(${a}/x)dx</sup> = e<sup>${a} ln x</sup> = ${xp(a)}.`),()=>nat(`Solve x dy/dx + ${a===1?"":a}y = ${xp(b+1)} with y(1) = ${y0}. The solution is y = ${xp(b+1)}/${d} + C${xp(-a)}; find C.`,r2(y0-1/d),`Put x = 1: ${y0} = 1/${d} + C, so C = ${y0} − 1/${d} = ${r2(y0-1/d)}.`))},
 ()=>{const a=rnd(1,4),n=pick([2,3,4]);return either(.5,()=>nat(`Bernoulli's equation dy/dx + ${a}y = x y<sup>${n}</sup> is reduced to a linear equation by v = y<sup>−${n-1}</sup>. In the form dv/dx + P v = Q, find P.`,(1-n)*a,`Divide by y<sup>${n}</sup> and put v = y<sup>${1-n}</sup>, so dv/dx = (1 − ${n})y<sup>−${n}</sup>dy/dx = (1 − ${n})(x − ${a}v). Hence dv/dx + (1 − ${n})(${a})v = (1 − ${n})x, and P = ${neg((1-n)*a)}.`),()=>{const c=rnd(1,4),m=rnd(c+1,c+5),C=m-c;return nat(`For dy/dx + ${a}y = ${a*c}y² with y(0) = 1/${m}, v = 1/y gives v = ${c} + Ce<sup>${a}x</sup>. Find C.`,C,`At x = 0, v = ${m} = ${c} + C, so C = ${C}.`)})},
 ()=>{const a=rnd(1,5),y0=rnd(1,4);return nat(`Solve x dy/dx = y + ${a}x (homogeneous type) with y(1) = ${y0}. Find y(e)/e, given y = ${a}x ln x + Cx.`,a+y0,`y(1) = ${y0} gives C = ${y0}. y(e) = ${a}e·1 + ${y0}e, so y(e)/e = ${a+y0}.`)},
 ()=>{const a=rnd(2,4),c=pick([1,2,3]);return either(.5,()=>mcq(`General solution of the Clairaut equation y = px + ${a}p² (p = dy/dx)?`,`y = cx + ${a}c²`,[`y = cx + ${a}c`,`y = px + ${a}c²`,`y = ${a}cx + c²`],`Clairaut's equation y = px + f(p) has general solution y = cx + f(c): replace p by a constant c.`),()=>nat(`A line of the family y = cx + ${a}c² (Clairaut equation y = px + ${a}p²) has c = ${c}. Find y at x = ${a+1}.`,c*(a+1)+a*c*c,`y = cx + ${a}c² = ${c}×${a+1} + ${a}×${c*c} = ${c*(a+1)+a*c*c}.`))},
 ()=>{const a=rnd(1,4),b=rnd(a+1,5),ex=gaExpr([[1,"p²"],[-(a+b),"p"],[a*b,""]]);return msq(`For the equation solvable for p, ${ex} = 0 (p = dy/dx), which are solutions?`,[`y = ${a}x + c`,`y = ${b}x + c`],[`y = −${a}x + c`,`y = −${b}x + c`],`The left side factorises: (p − ${a})(p − ${b}) = 0, so dy/dx = ${a} or dy/dx = ${b}, giving y = ${a}x + c or y = ${b}x + c.`)},
 ()=>{const k=rnd(1,3),y0=pick([1,3]),d=rnd(1,3),Y=y0+2*d,a=6*d*(y0+d);return nat(`Solve y dy/dx = ${a}x² with y(0) = ${y0}. Find y(1) (take y &gt; 0).`,Y,`Separate: y dy = ${a}x² dx, so y²/2 = ${a/3}x³ + C. y² = ${2*a/3}x³ + ${y0*y0}. At x = 1: y² = ${2*a/3} + ${y0*y0} = ${Y*Y}, so y = ${Y}.`)},
 ()=>{const [e,o,d]=pick(gaOD);return either(.5,()=>nat(`Find the order of the differential equation ${e}.`,o,`Order = the highest derivative present, which is ${o}.`),()=>nat(`Find the degree of the differential equation ${e}.`,d,`Degree = the power of the highest-order derivative once the equation is polynomial in its derivatives: ${d}.`))},
 ()=>{const c=pick([["y = px + 1/p","y² = 4x","1/c"],["y = px + 2/p","y² = 8x","2/c"],["y = px + 3/p","y² = 12x","3/c"],["y = px + p²","x² = −4y","c²"]]);return mcq(`The singular solution of Clairaut's equation ${c[0]} is…`,c[1],["y = cx + "+c[2],"xy = 1","x² + y² = 1"].filter(x=>x!==c[1]),c[0].includes("/p")?`General solution y = cx + a/c. Eliminating c from y = cx + a/c and 0 = x − a/c² gives y² = 4ax.`:`Differentiating gives (x + 2p)dp/dx = 0, so p = −x/2 and y = −x²/4, that is x² = −4y.`)},
],
2:[
 ()=>{const ty=rnd(0,2),ex=(r)=>gaE(r),tr=(b)=>(b===1?"":b)+"x";if(ty===0){let r1,r2;do{r1=rnd(-4,4);r2=rnd(-4,4)}while(!r1||!r2||r1===r2||r1+r2===0);const f=(a,b)=>`C₁${ex(a)} + C₂${ex(b)}`;return mcq(`The general solution of ${gaDE(-(r1+r2),r1*r2)} is…`,f(r1,r2),[f(-r1,-r2),`(C₁ + C₂x)${ex(r1)}`,`C₁cos ${tr(Math.abs(r1))} + C₂sin ${tr(Math.abs(r2))}`],`Auxiliary equation m² ${gaSg(-(r1+r2))}m ${gaSg(r1*r2)} = 0 factorises as (m ${gaSg(-r1)})(m ${gaSg(-r2)}) = 0. Two distinct real roots give C₁e<sup>m₁x</sup> + C₂e<sup>m₂x</sup>.`)}if(ty===1){const r=pick([-3,-2,-1,1,2,3]);return mcq(`The general solution of ${gaDE(-2*r,r*r)} is…`,`(C₁ + C₂x)${ex(r)}`,[`C₁${ex(r)} + C₂${ex(-r)}`,`C₁${ex(r)} + C₂${ex(2*r)}`,`C₁cos ${tr(Math.abs(r))} + C₂sin ${tr(Math.abs(r))}`],`Auxiliary equation (m ${gaSg(-r)})² = 0 has a repeated root m = ${r}, so y = (C₁ + C₂x)${ex(r)}.`)}const al=rnd(-2,2),be=rnd(1,3),pre=al===0?"":ex(al),f=(a,b)=>(a===0?"":ex(a))+`(C₁cos ${tr(b)} + C₂sin ${tr(b)})`;return mcq(`The general solution of ${gaDE(-2*al,al*al+be*be)} is…`,f(al,be),[f(al,be+1),f(al,be+2),`C₁${ex(al+be)} + C₂${ex(al-be)}`].filter(x=>x!==f(al,be)),`Roots m = ${al} ± ${be}i (discriminant negative), so y = ${al===0?"":"e^(αx)"}(C₁cos βx + C₂sin βx) with α = ${al}, β = ${be}.`)},
 ()=>{let p,q,a,f;do{p=rnd(-4,4);q=rnd(-4,4);a=pick([-3,-2,-1,1,2,3]);f=a*a+p*a+q}while(f===0);const m=rnd(1,4)*pick([1,-1]),k=f*m;return nat(`A particular integral of ${gaExpr([[1,"y″"],[p,"y′"],[q,"y"]])} = ${gaExpr([[k,gaE(a)]])} is y<sub>p</sub> = A${gaE(a)}. Find A.`,m,`Replace D by ${neg(a)}: y<sub>p</sub> = ${neg(k)}${gaE(a)}/(${a}² ${gaSg(p*a)} ${gaSg(q)}) = (${neg(k)}/${neg(f)})${gaE(a)}, so A = ${neg(m)}.`)},
 ()=>{let r1,r2;do{r1=rnd(-3,3);r2=rnd(-3,3)}while(r1===r2||!r1||!r2);const d=r1-r2,m=rnd(1,4)*pick([1,-1]),k=d*m;return nat(`(D ${gaSg(-r1)})(D ${gaSg(-r2)})y = ${gaExpr([[k,gaE(r1)]])}. The particular integral has the form Bx${gaE(r1)} (resonance). Find B.`,m,`The RHS solves the homogeneous equation (D ${gaSg(-r1)} is a factor), so multiply by x: PI = x·(${neg(k)})${gaE(r1)}/φ′(${neg(r1)}), where φ′(${neg(r1)}) = ${neg(r1)} − (${neg(r2)}) = ${neg(d)}. B = ${neg(k)}/${neg(d)} = ${neg(m)}.`)},
 ()=>{let r1,r2;do{r1=rnd(-3,3);r2=rnd(-3,3)}while(r1===r2||!r1||!r2);const C1=rnd(-4,4),C2=rnd(-4,4),A=C1+C2,B=r1*C1+r2*C2;return nat(`y = C₁${gaE(r1)} + C₂${gaE(r2)} solves ${gaDE(-(r1+r2),r1*r2)} with y(0) = ${neg(A)} and y′(0) = ${neg(B)}. Find C₁.`,C1,`y(0) = C₁ + C₂ = ${neg(A)}; y′(0) = (${r1})C₁ + (${r2})C₂ = ${neg(B)}. C₁ = (${neg(B)} − (${r2})(${neg(A)}))/(${r1} − (${r2})) = ${neg(C1)}.`)},
 ()=>{let m1,m2;do{m1=rnd(-2,4);m2=rnd(-2,4)}while(m1===m2||!m1||!m2);const a=1-(m1+m2),b=m1*m2,C1=rnd(-3,4),C2=rnd(-3,4),A=C1+C2,B=m1*C1+m2*C2;return nat(`For the Cauchy–Euler equation ${gaExpr([[1,"x²y″"],[a,"xy′"],[b,"y"]])} = 0, the solution is y = C₁x<sup>${m1}</sup> + C₂x<sup>${m2}</sup> with y(1) = ${neg(A)} and y′(1) = ${neg(B)}. Find C₁.`,C1,`Substituting y = x<sup>m</sup> gives m(m − 1) + (${a})m + (${b}) = 0, roots ${m1} and ${m2}. y(1): C₁ + C₂ = ${neg(A)}; y′(1): (${m1})C₁ + (${m2})C₂ = ${neg(B)}. Solving, C₁ = ${neg(C1)}.`)},
 ()=>{const t=rnd(0,2);if(t===0){let r1,r2;do{r1=rnd(-3,3);r2=rnd(-3,3)}while(r1===r2||!r1||!r2);return nat(`Wronskian W(y₁, y₂) at x = 0 for y₁ = ${gaE(r1)}, y₂ = ${gaE(r2)}?`,r2-r1,`W = y₁y₂′ − y₂y₁′ = (${neg(r2)} − (${neg(r1)}))e<sup>${neg(r1+r2)}x</sup> = ${neg(r2-r1)}e<sup>${neg(r1+r2)}x</sup>. At x = 0: ${neg(r2-r1)}.`)}if(t===1){const b=rnd(1,4),a=pick([-2,-1,1,2]);return nat(`Wronskian of y₁ = ${gaE(a)}cos ${b}x and y₂ = ${gaE(a)}sin ${b}x at x = 0?`,b,`W = ${b}${gaE(2*a)} for e<sup>ax</sup>cos bx, e<sup>ax</sup>sin bx. At x = 0: ${b}.`)}const m1=rnd(1,3),m2=rnd(4,7);return nat(`Wronskian of y₁ = x<sup>${m1}</sup> and y₂ = x<sup>${m2}</sup> at x = 1?`,m2-m1,`W = y₁y₂′ − y₂y₁′ = (${m2} − ${m1})x<sup>${m1+m2-1}</sup>. At x = 1: ${m2-m1}.`)},
 ()=>{let a,b,c,d,D,s;do{a=rnd(-3,4);b=rnd(-3,4);c=rnd(-3,4);d=rnd(-3,4);D=(a+d)*(a+d)-4*(a*d-b*c);s=Math.round(Math.sqrt(D))}while(D<0||s*s!==D||b*c===0||D===0);const hi=r2(((a+d)+s)/2),lo=r2(((a+d)-s)/2),big=coin(.5);return nat(`For the system dx/dt = ${gaExpr([[a,"x"],[b,"y"]])}, dy/dt = ${gaExpr([[c,"x"],[d,"y"]])}, find the ${big?"larger":"smaller"} root of its characteristic equation.`,big?hi:lo,`Characteristic equation λ² − (${a+d})λ + (${a*d-b*c}) = 0, discriminant ${D}, roots ${hi} and ${lo}.`)},
 ()=>{let a,b;do{a=rnd(1,4);b=rnd(1,4)}while(a===b);const m=rnd(1,4)*pick([1,-1]),k=m*(a*a-b*b);return nat(`For (D² + ${a*a})y = ${k===1?"":k===-1?"−":neg(k)}cos ${b===1?"":b}x, the particular integral is y<sub>p</sub> = A cos ${b===1?"":b}x. Find A.`,m,`Replace D² by −${b*b}: y<sub>p</sub> = ${neg(k)}cos ${b===1?"":b}x/(${a*a} − ${b*b}) = (${neg(k)}/${neg(a*a-b*b)})cos ${b===1?"":b}x. A = ${neg(m)}.`)},
 ()=>{const I=["e<sup>x</sup>, e<sup>2x</sup>","sin x, cos x","x, x²","e<sup>x</sup>, xe<sup>x</sup>","e<sup>x</sup>, e<sup>−x</sup>","1, x"],D=["x, 3x","e<sup>x</sup>, 5e<sup>x</sup>","sin 2x, sin x cos x","cos²x, 1 − sin²x","ln x², ln x"];return msq("Which pairs of functions are linearly independent (on an interval where they are defined)?",shuffle(I).slice(0,2),shuffle(D).slice(0,2),"Independent means neither function is a constant multiple of the other (W ≠ 0). x and 3x, e<sup>x</sup> and 5e<sup>x</sup>, sin 2x and sin x cos x, cos²x and 1 − sin²x, ln x² and ln x are all proportional.")},
 ()=>either(.5,()=>{const m=pick([1,2,4,5]),w=rnd(1,5),k=m*w*w;return nat(`A mass ${m} kg on a spring of stiffness ${k} N/m undergoes free undamped motion m x″ + kx = 0. Find its angular frequency ω in rad/s.`,w,`ω = √(k/m) = √(${k}/${m}) = √${w*w} = ${w} rad/s.`)},()=>{const m=pick([1,2,4,5]),w=rnd(1,5),k=m*w*w,c=2*m*w;return nat(`In m x″ + c x′ + kx = 0 with m = ${m} kg, k = ${k} N/m, find the damping constant c (N s/m) for critical damping.`,c,`Critical damping when c² = 4mk: c = 2√(mk) = 2√(${m}×${k}) = ${c} N s/m.`)}),
],
3:[
 ()=>{const [a,b]=pick([[1,2],[3,4],[3,5],[4,5],[3,2],[5,2],[7,4],[1,4],[9,5],[3,8]]),rho=r2(a/b);return either(.5,()=>nat(`D'Alembert's ratio test on Σ n(${a}/${b})<sup>n</sup>: find ρ = lim a<sub>n+1</sub>/a<sub>n</sub>.`,rho,`a<sub>n+1</sub>/a<sub>n</sub> = ((n+1)/n)(${a}/${b}) → ${a}/${b} = ${rho}.`),()=>mcq(`By the ratio test, the series Σ n(${a}/${b})<sup>n</sup> …`,a<b?"converges":"diverges",[a<b?"diverges":"converges","is inconclusive since ρ = 1","converges only conditionally"],`ρ = ${a}/${b} ${a<b?"&lt; 1, so the series converges":"&gt; 1, so the series diverges"}.`))},
 ()=>either(.5,()=>{const k=pick([2,4,5]),c=rnd(0,3);return nat(`Σ 1/n<sup>${k}p${c?" − "+c:""}</sup> converges (p-series) exactly when p &gt; p₀. Find p₀.`,r2((1+c)/k),`A p-series Σ1/nˢ converges iff s &gt; 1. Here s = ${k}p − ${c} &gt; 1 gives p &gt; ${1+c}/${k} = ${r2((1+c)/k)}.`)},()=>{const P=[["1/2",.5],["1",1],["3/2",1.5],["2",2],["3",3],["1/3",1/3]],[t,v]=pick(P);return mcq(`The series Σ 1/n<sup>${t}</sup> …`,v>1?"converges":"diverges",[v>1?"diverges":"converges","oscillates","converges only conditionally"],`p-series test: Σ1/n<sup>p</sup> converges iff p &gt; 1. Here p = ${t}, so it ${v>1?"converges":"diverges"}.`)}),
 ()=>{const lam=pick([0.5,1,1.5,2,3]),B=rnd(1,3),A2=2*B+2*lam,B2=2*B,l=r2(lam);return either(.5,()=>nat(`A positive series has a<sub>n+1</sub>/a<sub>n</sub> = (2n + ${B2})/(2n + ${A2}). Find Raabe's limit lim n(a<sub>n</sub>/a<sub>n+1</sub> − 1).`,l,`a<sub>n</sub>/a<sub>n+1</sub> − 1 = (${A2 - B2})/(2n + ${B2}). Multiply by n and let n → ∞: ${A2-B2}/2 = ${l}.`),()=>mcq(`A positive series has a<sub>n+1</sub>/a<sub>n</sub> = (2n + ${B2})/(2n + ${A2}). The ratio test gives ρ = 1. What does Raabe's test say?`,l>1?"converges":l<1?"diverges":"the test fails (λ = 1)",l>1?["diverges","the test fails (λ = 1)","converges only conditionally"]:l<1?["converges","the test fails (λ = 1)","converges only conditionally"]:["converges","diverges","converges only conditionally"],`Raabe's limit λ = ${l}. Converges if λ &gt; 1, diverges if λ &lt; 1, and fails if λ = 1.`))},
 ()=>{const P=[["1/2",.5],["1",1],["3/2",1.5],["2",2],["3",3],["1/3",1/3]],[t,v]=pick(P);const ans=v>1?"absolutely convergent":"conditionally convergent";return mcq(`Classify the alternating series Σ (−1)<sup>n</sup>/n<sup>${t}</sup>.`,ans,[v>1?"conditionally convergent":"absolutely convergent","divergent","oscillating without limit"],`Terms decrease to 0, so by Leibniz's test it converges. Σ1/n<sup>${t}</sup> ${v>1?"converges (p &gt; 1), so it is absolutely convergent":"diverges (p ≤ 1), so it converges only conditionally"}.`)},
 ()=>{let a,c;do{a=rnd(1,7);c=pick([1,2,4,5])}while(a===c);const b=rnd(1,5),d=rnd(1,5),rho=r2(a/c);return nat(`Cauchy's root test on Σ ((${gaExpr([[a,"n"],[b,""]])})/(${gaExpr([[c,"n"],[d,""]])}))<sup>n</sup>: find lim (a<sub>n</sub>)<sup>1/n</sup>.`,rho,`(a<sub>n</sub>)<sup>1/n</sup> = (${gaExpr([[a,"n"],[b,""]])})/(${gaExpr([[c,"n"],[d,""]])}) → ${a}/${c} = ${rho}. The series ${a<c?"converges (limit &lt; 1)":"diverges (limit &gt; 1)"}.`)},
 ()=>{const n=pick([1,2,4,5]),t=rnd(0,3);if(t===0){const k=2*n;return nat(`Fourier series of f(x) = x on (−π, π): f(x) = Σ b<sub>m</sub> sin mx. Find b<sub>${n}</sub>.`,r2(2*(n%2?1:-1)/n),`b<sub>m</sub> = (2/π)∫₀^π x sin mx dx = 2(−1)<sup>m+1</sup>/m. For m = ${n}: ${r2(2*(n%2?1:-1)/n)}.`)}if(t===1)return nat(`Fourier series of f(x) = x² on (−π, π): f(x) = a₀/2 + Σ a<sub>m</sub> cos mx. Find a<sub>${n}</sub>.`,r2(4*(n%2?-1:1)/(n*n)),`a<sub>m</sub> = (2/π)∫₀^π x² cos mx dx = 4(−1)<sup>m</sup>/m². For m = ${n}: ${r2(4*(n%2?-1:1)/(n*n))}.`);if(t===2){const m=pick([1,5]);return nat(`For f(x) = |x| on (−π, π), the Fourier cosine coefficient is a<sub>m</sub> = 2((−1)<sup>m</sup> − 1)/(πm²). Find π·a<sub>${m}</sub>.`,r2(-4/(m*m)),`For odd m, (−1)<sup>m</sup> − 1 = −2, so π a<sub>m</sub> = −4/m² = ${r2(-4/(m*m))}.`)}const k=rnd(1,5),m=pick([1,5]);return nat(`Half-range Fourier sine series of f(x) = ${k} on (0, π). Find π·b<sub>${m}</sub>.`,r2(4*k/m),`b<sub>m</sub> = (2/π)∫₀^π ${k} sin mx dx = 2${k===1?"":"·"+k}(1 − cos mπ)/(mπ). For odd m this is 4·${k}/(mπ), so π b<sub>${m}</sub> = ${r2(4*k/m)}.`)},
 ()=>{const a=rnd(-4,4),b=rnd(-4,4),x=pick(["0","π","π/2"]),v=x==="π/2"?b:(a+b)/2;return nat(`f(x) = ${a} for −π &lt; x &lt; 0 and f(x) = ${b} for 0 &lt; x &lt; π, with period 2π. To what value does its Fourier series converge at x = ${x}?`,v,x==="π/2"?`f is continuous at π/2, so the series converges to f(π/2) = ${b}.`:`${x==="0"?"x = 0":"x = π (jump between f(π⁻) = "+b+" and f(−π⁺) = "+a+")"} is a jump, so the series converges to the average (${a} + ${b})/2 = ${v}.`)},
 ()=>either(.5,()=>{const t=coin(.5);return nat(t?`Apply Parseval's identity to f(x) = x on (−π, π) (Σ b<sub>n</sub>² = (1/π)∫f²dx, b<sub>n</sub> = 2(−1)<sup>n+1</sup>/n). Find Σ 1/n² from n = 1 to ∞ (2 decimal places).`:`Using Parseval's identity for f(x) = x² on (−π, π), (a₀²/2 + Σa<sub>n</sub>² = (1/π)∫f²dx with a₀ = 2π²/3 and a<sub>n</sub> = 4(−1)<sup>n</sup>/n²), find Σ 1/n⁴ from n = 1 to ∞ (2 decimal places).`,t?r2(Math.PI*Math.PI/6):r2(Math.pow(Math.PI,4)/90),t?`(1/π)∫x²dx = 2π²/3 = Σ4/n², so Σ1/n² = π²/6 = ${r2(Math.PI*Math.PI/6)}.`:`(1/π)∫x⁴dx = 2π⁴/5 = 2π⁴/9 + 16Σ1/n⁴, so Σ1/n⁴ = π⁴/90 = ${r2(Math.pow(Math.PI,4)/90)}.`)},()=>mcq("Parseval's identity for f(x) on (−π, π) with a₀ = (1/π)∫f dx states…","(1/π)∫f(x)² dx = a₀²/2 + Σ(a<sub>n</sub>² + b<sub>n</sub>²)",["(1/π)∫f(x)² dx = Σ(a<sub>n</sub> + b<sub>n</sub>)²","∫f(x)² dx = a₀ + Σ a<sub>n</sub>b<sub>n</sub>","(1/π)∫f(x) dx = Σ(a<sub>n</sub>² + b<sub>n</sub>²)"],"Parseval equates the mean-square of f to the sum of the squares of its Fourier coefficients (energy in time = energy in frequency).")),
 ()=>either(.5,()=>{const [a,b]=pick([[1,2],[1,3],[2,3],[3,4],[3,5],[4,5]]);return nat(`Sum to infinity of the geometric series ${a}/${b} + (${a}/${b})² + (${a}/${b})³ + …`,r2((a/b)/(1-a/b)),`S = first term/(1 − r) = (${a}/${b})/(1 − ${a}/${b}) = ${gaFrac(a,b-a)} = ${r2(a/(b-a))}.`)},()=>{const k=rnd(1,2);let H=0;for(let i=1;i<=k;i++)H+=1/i;const S=r2(H/k);return nat(`Find Σ 1/(n(n + ${k})) from n = 1 to ∞. (Use partial fractions: 1/(n(n+${k})) = (1/${k})(1/n − 1/(n+${k})).)`,S,`The sum telescopes to (1/${k})(1 + 1/2 + … + 1/${k}) = ${r2(H)}/${k} = ${S}.`)}),
 ()=>{const a=rnd(1,6),d=pick([1,2,4,5]),b=rnd(-5,5),c=rnd(-5,5),e=rnd(-5,5),f=rnd(1,5);return nat(`Find lim<sub>n→∞</sub> (${gaExpr([[a,"n²"],[b,"n"],[c,""]])})/(${gaExpr([[d,"n²"],[e,"n"],[f,""]])}).`,r2(a/d),`Divide by n²: the terms b/n, c/n² → 0, so the limit is ${a}/${d} = ${r2(a/d)}.`)},
 ()=>msq("Which of these series converge?",shuffle(["Σ 1/n²","Σ 1/n<sup>3/2</sup>","Σ (1/2)<sup>n</sup>","Σ 1/n!","Σ (−1)<sup>n</sup>/n"]).slice(0,rnd(2,3)),shuffle(["Σ 1/n","Σ 1/√n","Σ n/(n + 1)","Σ (−1)<sup>n</sup>·n"]).slice(0,2),"p-series with p &gt; 1, geometric with |r| &lt; 1, Σ1/n! (ratio test) and the alternating harmonic series (Leibniz) converge. The harmonic series and Σ1/√n diverge (p ≤ 1), and Σn/(n+1) and Σ(−1)ⁿn have terms that do not tend to 0."),
 ()=>{const L=[["x",1],["x²",0],["|x|",0],["x³",1],["x cos x",1],["x sin x",0],["sin x",1],["cos 2x",0]],a=pick(L);return mcq(`The Fourier series of f(x) = ${a[0]} on (−π, π) contains…`,a[1]?"only sine terms":"only cosine terms (including the constant)",[a[1]?"only cosine terms (including the constant)":"only sine terms","both sine and cosine terms in general","only a constant term"],`f(x) = ${a[0]} is ${a[1]?"odd, so a₀ = a<sub>n</sub> = 0":"even, so b<sub>n</sub> = 0"} on a symmetric interval.`)},
],
4:[
 ()=>{const L=[["z = f(x + y)","p − q = 0"],["z = f(x − y)","p + q = 0"],["z = f(xy)","xp = yq"],["z = f(x² + y²)","yp = xq"],["z = f(y/x)","xp + yq = 0"]],a=pick(L);return mcq(`Eliminating the arbitrary function f from ${a[0]} gives (p = ∂z/∂x, q = ∂z/∂y)…`,a[1],L.filter(x=>x!==a).map(x=>x[1]).slice(0,3),`Differentiate ${a[0]} with respect to x and y and divide the two results to remove f′. This leaves ${a[1]}.`)},
 ()=>{let m1,m2;do{m1=rnd(-4,4);m2=rnd(-4,4)}while(!m1||!m2||m1===m2||m1+m2===0);const Y=m=>`y ${m<0?"−":"+"} ${Math.abs(m)===1?"":Math.abs(m)}x`,pr=(a,b)=>`φ₁(${Y(a)}) + φ₂(${Y(b)})`,eq=gaExpr([[1,"z<sub>xx</sub>"],[-(m1+m2),"z<sub>xy</sub>"],[m1*m2,"z<sub>yy</sub>"]]);return mcq(`The general solution of ${eq} = 0 is z = …`,pr(m1,m2),[pr(-m1,-m2),pr(m1,-m2),pr(-m1,m2)],`Factorise (${gaExpr([[1,"D"],[-m1,"D′"]])})(${gaExpr([[1,"D"],[-m2,"D′"]])})z = 0. Each factor (D − mD′)z = 0 has solution φ(y + mx), so z = φ₁(${Y(m1)}) + φ₂(${Y(m2)}).`)},
 ()=>either(.5,()=>{let A=rnd(1,4),C=rnd(-4,4),B=rnd(-5,5);if(coin(.3)){const k=rnd(1,3);A=k*k;C=1;B=coin(.5)?2*k:-2*k}const D=B*B-4*A*C,t=D<0?"elliptic":D===0?"parabolic":"hyperbolic";return mcq(`The PDE ${gaExpr([[A,"z<sub>xx</sub>"],[B,"z<sub>xy</sub>"],[C,"z<sub>yy</sub>"]])} = 0 is…`,t,["elliptic","parabolic","hyperbolic"].filter(x=>x!==t).concat(["none of these"]),`B² − 4AC = ${B*B} − 4(${A})(${C}) = ${D}, ${D<0?"which is negative: elliptic":D===0?"which is zero: parabolic":"which is positive: hyperbolic"}.`)},()=>{const L=[["one-dimensional wave equation u<sub>tt</sub> = c²u<sub>xx</sub>","hyperbolic"],["one-dimensional heat equation u<sub>t</sub> = c²u<sub>xx</sub>","parabolic"],["Laplace equation u<sub>xx</sub> + u<sub>yy</sub> = 0","elliptic"]],a=pick(L);return mcq(`The ${a[0]} is…`,a[1],["elliptic","parabolic","hyperbolic"].filter(x=>x!==a[1]).concat(["not classifiable"]),`Using B² − 4AC: the wave equation has A = c², C = −1 (positive discriminant); the heat equation has one second-order term (zero); Laplace has A = C = 1 (negative).`)}),
 ()=>either(.5,()=>{const n=rnd(1,3),c=pick([2,4,6,10]),L=pick([1,2,5]);return nat(`A string of length ${L} is fixed at both ends and obeys u<sub>tt</sub> = ${c*c}u<sub>xx</sub>. Its n = ${n} mode is sin(nπx/L)cos(nπct/L). Find the angular frequency ω<sub>n</sub> divided by π (rad/s ÷ π).`,r2(n*c/L),`ω<sub>n</sub> = nπc/L with c = ${c}, L = ${L}. So ω<sub>n</sub>/π = ${n}×${c}/${L} = ${r2(n*c/L)}.`)},()=>{const c=pick([1,2,4,5,10]),L=pick([1,2,4,5,10]);return nat(`For u<sub>tt</sub> = ${c*c}u<sub>xx</sub> on 0 &lt; x &lt; ${L} with fixed ends, find the period of the fundamental mode in seconds. (T = 2L/c)`,r2(2*L/c),`c = √${c*c} = ${c}. Fundamental ω₁ = πc/L, so T = 2π/ω₁ = 2L/c = ${r2(2*L/c)} s.`)}),
 ()=>{const c=rnd(1,4),L=pick([1,2,5]),n=rnd(1,3);return nat(`For the heat equation u<sub>t</sub> = ${c*c===1?"":c*c}u<sub>xx</sub> on 0 &lt; x &lt; ${L} with u(0,t) = u(${L},t) = 0, the n = ${n} mode decays as e<sup>−λt</sup>. Find λ/π².`,r2(c*c*n*n/(L*L)),`Separating variables gives T′ = −λT with λ = c²n²π²/L² = ${c*c}×${n*n}π²/${L*L}. So λ/π² = ${r2(c*c*n*n/(L*L))}.`)},
 ()=>{const L=pick([4,8,10,20]),T1=rnd(0,4)*10,T2=T1+rnd(1,6)*10,f=pick([1,2,3]),x0=L*f/4;return nat(`A rod of length ${L} cm has ends held at ${T1} °C (x = 0) and ${T2} °C (x = ${L}). Find the steady-state temperature at x = ${x0} cm.`,r2(T1+(T2-T1)*x0/L),`In steady state u<sub>xx</sub> = 0, so u = T₁ + (T₂ − T₁)x/L = ${T1} + ${T2-T1}×${x0}/${L} = ${r2(T1+(T2-T1)*x0/L)} °C.`)},
 ()=>{const t=rnd(0,2);if(t===0){const a=rnd(1,5);return nat(`u = ${a}x² + ky² satisfies Laplace's equation u<sub>xx</sub> + u<sub>yy</sub> = 0. Find k.`,-a,`u<sub>xx</sub> = ${2*a}, u<sub>yy</sub> = 2k. Sum = ${2*a} + 2k = 0, so k = ${-a}.`)}if(t===1){const c=rnd(1,4),b=rnd(1,4);return nat(`u = e<sup>−λt</sup> sin(${b}x) solves u<sub>t</sub> = ${c*c===1?"":c*c}u<sub>xx</sub>. Find λ.`,c*c*b*b,`u<sub>t</sub> = −λu and u<sub>xx</sub> = −${b*b}u. So −λ = ${c*c}(−${b*b}), λ = ${c*c*b*b}.`)}const c=rnd(1,5),b=rnd(1,4);return nat(`u = cos(${b}x)cos(ωt) solves the wave equation u<sub>tt</sub> = ${c*c}u<sub>xx</sub>. Find ω (positive).`,c*b,`u<sub>tt</sub> = −ω²u and u<sub>xx</sub> = −${b*b}u, so ω² = ${c*c}×${b*b}, ω = ${c*b}.`)},
 ()=>{const a=rnd(1,4),b=rnd(1,4),x=rnd(1,4),y=rnd(1,4),F=pick([["pq",(a,b)=>a*b],["p² + q²",(a,b)=>a*a+b*b],["p + q",(a,b)=>a+b]]),z=a*x+b*y+F[1](a,b);return nat(`The complete integral of the Clairaut-type PDE z = px + qy + f(p, q) with f(p, q) = ${F[0]} is z = ax + by + f(a, b). For a = ${a}, b = ${b}, find z at (x, y) = (${x}, ${y}).`,z,`z = ${a}×${x} + ${b}×${y} + f(${a}, ${b}) = ${a*x+b*y} + ${F[1](a,b)} = ${z}.`)},
 ()=>{const L=[["u<sub>t</sub> = c²u<sub>xx</sub>",2,1],["u<sub>t</sub> + u·u<sub>x</sub> = 0",1,0],["u<sub>xx</sub> + u<sub>yy</sub> = 0",2,1],["(u<sub>x</sub>)² + (u<sub>y</sub>)² = 1",1,0],["u<sub>tt</sub> = c²u<sub>xx</sub>",2,1],["u<sub>xx</sub> + u<sub>yy</sub> = u²",2,0]],a=pick(L);return either(.5,()=>mcq(`The PDE ${a[0]} is…`,a[2]?"linear":"non-linear",[a[2]?"non-linear":"linear","not a PDE","cannot be classified"],a[2]?"Linear means the unknown and its derivatives appear only to the first power and are never multiplied together.":"A product or power of the unknown or its derivatives (u·u<sub>x</sub>, u<sub>x</sub>², u²) makes the PDE non-linear."),()=>nat(`What is the order of the PDE ${a[0]}?`,a[1],`Order = highest derivative present = ${a[1]}.`))},
 ()=>msq("Which of these are solutions of Laplace's equation u<sub>xx</sub> + u<sub>yy</sub> = 0?",shuffle(["x² − y²","xy","x³ − 3xy²","e<sup>x</sup> cos y","ln(x² + y²)"]).slice(0,rnd(2,3)),shuffle(["x² + y²","x³ + y³","x²y","sin x sin y"]).slice(0,2),"Harmonic functions satisfy u<sub>xx</sub> + u<sub>yy</sub> = 0. For x² + y² the sum is 4, x³ + y³ gives 6x + 6y, x²y gives 2y, and sin x sin y gives −2 sin x sin y, so these are not harmonic."),
],
5:[
 ()=>{const x=rnd(1,4),y=rnd(1,4);if(coin(.5)){const a=rnd(1,3),p=rnd(0,4);return nat(`u = ${a}(x² − y²) + ${p}x is harmonic. Find its harmonic conjugate v with v(0, 0) = 0, evaluated at (x, y) = (${x}, ${y}).`,2*a*x*y+p*y,`By CR: v<sub>y</sub> = u<sub>x</sub> = ${2*a}x + ${p}, so v = ${2*a}xy + ${p}y + g(x); v<sub>x</sub> = −u<sub>y</sub> = ${2*a}y forces g′ = 0. At (${x}, ${y}): v = ${2*a*x*y+p*y}.`)}const a=rnd(1,3);return nat(`u = ${a}(x³ − 3xy²) is harmonic. Find its harmonic conjugate v with v(0, 0) = 0 at (x, y) = (${x}, ${y}).`,a*(3*x*x*y-y*y*y),`u is Re(${a}z³), so v = Im(${a}z³) = ${a}(3x²y − y³). At (${x}, ${y}): ${a*(3*x*x*y-y*y*y)}.`)},
 ()=>msq("Which functions are analytic everywhere in ℂ (entire)?",shuffle(["z² + 3z","e<sup>z</sup>","sin z","cos z","z³ − 2"]).slice(0,rnd(2,3)),shuffle(["z̄ (conjugate)","|z|²","Re z","1/z"]).slice(0,2),"Polynomials, e<sup>z</sup>, sin z and cos z satisfy the Cauchy–Riemann equations everywhere. z̄, |z|² and Re z fail CR (except at isolated points), and 1/z is singular at 0."),
 ()=>either(.5,()=>{const a=rnd(1,4);return nat(`For u = ${a}x³ + kxy² to be harmonic, find k.`,-3*a,`u<sub>xx</sub> = ${6*a}x and u<sub>yy</sub> = 2kx. Laplace: ${6*a}x + 2kx = 0, so k = ${-3*a}.`)},()=>{const a=rnd(1,5),m=rnd(1,5);return mcq(`f(z) = u + iv with u = ${gaExpr([[1,"x²"],[-1,"y²"],[a,"x"]])} and v = ${gaExpr([[2,"xy"],[m,"y"]])} — which statement about the Cauchy–Riemann equations is correct?`,a===m?"they hold everywhere (f is analytic)":"they hold nowhere (f is not analytic)",["they hold only on the line y = 0","they hold only at the origin","they hold only when x = y"],a===m?`u<sub>x</sub> = 2x + ${a} = v<sub>y</sub> = 2x + ${m} and u<sub>y</sub> = −2y = −v<sub>x</sub>. Both hold everywhere, and f = z² + ${a}z.`:`u<sub>x</sub> = 2x + ${a} but v<sub>y</sub> = 2x + ${m}; they differ by ${a-m} for all points, so CR never holds.`)}),
 ()=>{const R=pick([2,3,4]);let z0;do{z0=pick([-3,-2,-1,1,2,3,5])}while(Math.abs(z0)===R);const c2=rnd(1,3),c1=rnd(-3,3),c0=rnd(-3,3),f=z=>c2*z*z+c1*z+c0,fp=z=>2*c2*z+c1,inside=Math.abs(z0)<R,d=coin(.5);const F=gaExpr([[c2,"z²"],[c1,"z"],[c0,""]]);return nat(d?`Evaluate (1/2πi)∮ (${F})/(z ${gaSg(-z0)})² dz around the circle |z| = ${R}.`:`Evaluate (1/2πi)∮ (${F})/(z ${gaSg(-z0)}) dz around the circle |z| = ${R}.`,inside?(d?fp(z0):f(z0)):0,inside?(d?`Cauchy's integral formula for derivatives: (1/2πi)∮ f(z)/(z − z₀)² dz = f′(z₀). Here z₀ = ${z0} lies inside, f′(z) = ${2*c2}z + ${c1}, so the value is ${fp(z0)}.`:`z₀ = ${z0} lies inside |z| = ${R}, so (1/2πi)∮ f(z)/(z − z₀) dz = f(z₀) = ${f(z0)}.`):`The pole z₀ = ${z0} lies outside |z| = ${R}, so the integrand is analytic inside and the integral is 0 (Cauchy–Goursat).`)},
 ()=>{const t=rnd(0,2);if(t===0){let a,b;do{a=rnd(-4,4);b=rnd(-4,4)}while(a===b);const mm=pick([-3,-2,-1,1,2,3]),c=(a-b)*mm-a;return nat(`Find the residue of f(z) = (${gaExpr([[1,"z"],[c,""]])})/(${gaZ(a)}${gaZ(b)}) at the simple pole z = ${a}.`,mm,`Res = lim (z − ${a})f(z) = (${a} ${gaSg(c)})/(${a} − (${b})) = ${a+c}/${a-b} = ${mm}.`)}if(t===1){const a=rnd(-4,4),k=rnd(1,3),c=rnd(-3,3);return nat(`Find the residue of f(z) = (${gaExpr([[k,"z²"],[c,""]])})/${gaZ(a)}² at its double pole z = ${a}.`,2*k*a,`For a double pole, Res = d/dz[(z − ${a})²f(z)] at z = ${a} = d/dz(${gaExpr([[k,"z²"],[c,""]])}) = ${2*k}z = ${2*k*a}.`)}const k=rnd(1,4),m=rnd(1,4),f=[1,1,1,2,6][m];return nat(`Find the residue of e<sup>${k}z</sup>/z<sup>${m}</sup> at z = 0.`,r2(Math.pow(k,m-1)/f),`e<sup>${k}z</sup> = Σ(${k}z)<sup>j</sup>/j!, so the coefficient of 1/z in e<sup>${k}z</sup>/z<sup>${m}</sup> is ${k}<sup>${m-1}</sup>/${m-1}! = ${r2(Math.pow(k,m-1)/f)}.`)},
 ()=>{const R=pick([2,3,5]);let a,b;do{a=rnd(-4,4);b=rnd(-4,4)}while(a===b||Math.abs(a)===R||Math.abs(b)===R);const mm=pick([-3,-2,-1,2,3]),c=(a-b)*mm-a,ra=(a+c)/(a-b),rb=(b+c)/(b-a),S=(Math.abs(a)<R?ra:0)+(Math.abs(b)<R?rb:0);return nat(`Evaluate (1/2πi)∮ (${gaExpr([[1,"z"],[c,""]])})/(${gaZ(a)}${gaZ(b)}) dz over the circle |z| = ${R}.`,r2(S),`By the residue theorem the integral equals the sum of residues at poles inside the circle. Res at ${a} = ${r2(ra)} (${Math.abs(a)<R?"inside":"outside"}); Res at ${b} = ${r2(rb)} (${Math.abs(b)<R?"inside":"outside"}). Sum inside = ${r2(S)}.`)},
 ()=>{const [a,b]=pick([[5,3],[13,5],[5,4],[10,6],[25,7],[17,15],[13,12]]),r=Math.sqrt(a*a-b*b);return nat(`Evaluate ∫₀^{2π} dθ/(${a} ${coin(.5)?"+":"−"} ${b} cos θ), using the unit circle z = e<sup>iθ</sup> and the residue theorem. Give the answer divided by π.`,r2(2/r),`For a &gt; b &gt; 0 the standard result is 2π/√(a² − b²) = 2π/√(${a*a} − ${b*b}) = 2π/${r}. Divided by π: ${r2(2/r)}.`)},
 ()=>either(.5,()=>{const m=rnd(2,4);return nat(`Find the order of the pole of f(z) = 1/((z − ${rnd(1,3)})<sup>${m}</sup>(z + 5)) at its repeated pole (the factor raised to the power ${m}). Answer with the order.`,m,`A factor (z − a)<sup>m</sup> in the denominator gives a pole of order m at z = a, so the order is ${m}.`)},()=>{const L=[["e<sup>1/z</sup> at z = 0","an essential singularity"],["sin z/z at z = 0","a removable singularity"],["(cos z − 1)/z² at z = 0","a removable singularity"],["1/z³ at z = 0","a pole of order 3"],["1/(z² + 1) at z = i","a simple pole"],["1/(z − 2)² at z = 2","a pole of order 2"]],a=pick(L),O=["an essential singularity","a removable singularity","a simple pole","a pole of order 3","a pole of order 2"];return mcq(`The function ${a[0]} has…`,a[1],shuffle(O.filter(x=>x!==a[1])).slice(0,3),a[1]==="an essential singularity"?"The Laurent series of e<sup>1/z</sup> has infinitely many negative powers of z.":a[1]==="a removable singularity"?"The limit exists and is finite (sin z/z → 1, (cos z − 1)/z² → −1/2), so the singularity is removable.":`The highest negative power in the Laurent series at that point gives the order of the pole: ${a[1]}.`)}),
 ()=>{const T=pick([[3,4],[5,12],[8,15],[6,8],[7,24]]),U=pick([[3,4],[5,12],[8,15],[6,8]]),n=rnd(1,3);return either(.5,()=>nat(`If z₁ = ${T[0]} + ${T[1]}i and z₂ = ${U[0]} + ${U[1]}i, find |z₁z₂|.`,Math.hypot(...T)*Math.hypot(...U),`|z₁z₂| = |z₁||z₂| = ${Math.hypot(...T)} × ${Math.hypot(...U)} = ${Math.hypot(...T)*Math.hypot(...U)}.`),()=>nat(`Find |z<sup>${n}</sup>| for z = ${T[0]} + ${T[1]}i.`,Math.pow(Math.hypot(...T),n),`|z| = √(${T[0]*T[0]} + ${T[1]*T[1]}) = ${Math.hypot(...T)}, so |z<sup>${n}</sup>| = |z|<sup>${n}</sup> = ${Math.pow(Math.hypot(...T),n)}.`))},
 ()=>mcq(pick(["If f(z) is analytic inside and on a simple closed curve C, then ∮<sub>C</sub> f(z) dz equals…","By the Cauchy–Goursat theorem, ∮<sub>C</sub> f(z) dz for f analytic on and inside C is…"]),"0",["2πi","f(0)","2πi f(0)"],"The Cauchy–Goursat theorem says the integral of a function analytic in a simply connected region around a closed contour vanishes."),
]});
