/* gen_d.js: AHT-000 Basic Mathematics and BTT-001 Biology for Engineers (bridge subjects) */
(function(){
/* ---- local helpers (wrapped in an IIFE so names never clash with other gen_*.js files) ---- */
/* self-check: the bank test sets globalThis.__GEN_VERIFY__ so any wrong analytic answer throws; in the app it does nothing */
const V=(ok,msg)=>{if(globalThis.__GEN_VERIFY__&&!ok)throw new Error("gen_d verify failed: "+msg)};
const near=(a,b)=>Math.abs(a-b)<=1e-6*Math.max(1,Math.abs(a),Math.abs(b));
const near3=(a,b)=>Math.abs(a-b)<=1e-3*Math.max(1,Math.abs(a),Math.abs(b));
const gcd=(a,b)=>b?gcd(b,a%b):Math.abs(a);
/* reduced fraction as text: fr(-2,4) -> "−1/2" */
const fr=(n,d)=>{const g=gcd(n,d)||1;n/=g;d/=g;if(d<0){n=-n;d=-d}return d===1?neg(n):neg(n)+"/"+d};
/* true when x has at most two decimals */
const dec2=x=>Math.abs(x*100-Math.round(x*100))<1e-7;
/* numeric derivative and Simpson integral used only by the self-check */
const nd=(f,x)=>(f(x+1e-5)-f(x-1e-5))/2e-5;
const simpson=(f,a,b,n=600)=>{const h=(b-a)/n;let s=f(a)+f(b);for(let i=1;i<n;i++)s+=f(a+i*h)*(i%2?4:2);return s*h/3};
/* mcq with a pool of distractors: drops duplicates and the answer itself, needs at least 3 left */
function M(q,ans,pool,why){ans=String(ans);const d=[];for(const x of pool){const s=String(x);if(s!==ans&&s!==""&&!d.includes(s))d.push(s)}if(d.length<3)throw new Error("gen_d: fewer than 3 distractors: "+q);return mcq(q,ans,d.slice(0,3),why)}
/* table question: rows [key, value]; asks key -> value, or value -> key when b is given */
function T(rows,f,b,w){const r=pick(rows),o=shuffle(rows.filter(x=>x!==r));if(!b||coin(.5))return M(f(r[0]),r[1],o.map(x=>x[1]),w(r));return M(b(r[1]),r[0],o.map(x=>x[0]),w(r))}
/* msq from pools with nr right and nw wrong options */
function S(q,rights,wrongs,nr,nw,why){const r=shuffle(rights).slice(0,Math.max(1,nr)),w=shuffle(wrongs).slice(0,nw);return msq(q,r,w,why)}
/* polynomial text from coefficients, highest power first: pl([2,-3,5]) -> "2x² − 3x + 5" */
const pl=(cs,v)=>{v=v||"x";const n=cs.length-1;let s="";cs.forEach((c,i)=>{const p=n-i;if(c===0)return;const a=Math.abs(c);const body=p===0?String(a):(a===1?"":String(a))+v+(p===1?"":"<sup>"+p+"</sup>");s+=s?(c<0?" − ":" + ")+body:(c<0?"−":"")+body});return s||"0"};
const ev=(cs,x)=>cs.reduce((s,c)=>s*x+c,0);
/* (x + a) written as (x − 3) or (x + 2) */
const lf=a=>"(x "+(a<0?"−":"+")+" "+Math.abs(a)+")";
/* a x + b y + c = 0 */
const eq3=(a,b,c)=>{let s="";[[a,"x"],[b,"y"],[c,""]].forEach(([k,v])=>{if(k===0)return;const t=(Math.abs(k)===1&&v)?v:Math.abs(k)+v;s+=s?(k<0?" − ":" + ")+t:(k<0?"−":"")+t});return s+" = 0"};
const nz=(lo,hi)=>{let v=0;while(v===0)v=rnd(lo,hi);return v};
const TRIPLES=[[3,4,5],[6,8,10],[5,12,13],[8,15,17],[9,12,15],[12,16,20],[7,24,25],[15,20,25]];

/* =============================== AHT-000 Basic Mathematics =============================== */
genReplace("AHT-000",{
 /* ---------- Unit 1: Analytical geometry ---------- */
 1:[
  ()=>{const [a,b,c]=pick(TRIPLES),x1=rnd(-6,6),y1=rnd(-6,6),sx=coin(.5)?1:-1,sy=coin(.5)?1:-1,x2=x1+sx*a,y2=y1+sy*b;V(near(Math.hypot(x2-x1,y2-y1),c),"distance");
   return nat(`Find the distance between the points A(${neg(x1)}, ${neg(y1)}) and B(${neg(x2)}, ${neg(y2)}).`,c,`d = √[(x₂ − x₁)² + (y₂ − y₁)²] = √[(${neg(x2-x1)})² + (${neg(y2-y1)})²] = √(${a*a} + ${b*b}) = √${c*c} = ${c}.`)},
  ()=>{const [a,b,c]=pick(TRIPLES),sx=coin(.5)?1:-1,sy=coin(.5)?1:-1,x=sx*a,y=sy*b;V(near(Math.hypot(x,y),c),"origin distance");
   return either(.5,()=>nat(`How far is the point P(${neg(x)}, ${neg(y)}) from the origin?`,c,`The distance from the origin is √(x² + y²) = √(${a*a} + ${b*b}) = √${c*c} = ${c}.`),
    ()=>nat(`A circle with its centre at the origin passes through the point (${neg(x)}, ${neg(y)}). What is its radius?`,c,`The radius is the distance from the centre (0, 0) to the point: √(${x*x} + ${y*y}) = ${c}.`))},
  ()=>{const x1=rnd(-6,6),y1=rnd(-6,6),dx=pick([1,2,4,5]),dy=nz(-8,8),x2=x1+dx,y2=y1+dy,m=dy/dx;V(near((y2-y1)/(x2-x1),m),"slope");
   return nat(`Find the slope of the line through P(${neg(x1)}, ${neg(y1)}) and Q(${neg(x2)}, ${neg(y2)}).`,r2(m),`m = (y₂ − y₁)/(x₂ − x₁) = (${neg(y2)} − ${neg(y1)})/(${neg(x2)} − ${neg(x1)}) = ${neg(dy)}/${dx} = ${r2(m)}.`)},
  ()=>{const x=nz(-9,9),y=nz(-9,9),q=x>0?(y>0?0:3):(y>0?1:2),names=["first quadrant (x > 0, y > 0)","second quadrant (x < 0, y > 0)","third quadrant (x < 0, y < 0)","fourth quadrant (x > 0, y < 0)"];
   return either(.6,()=>mcq(`In which quadrant does the point (${neg(x)}, ${neg(y)}) lie?`,names[q],names.filter((_,i)=>i!==q),`x is ${x>0?"positive":"negative"} and y is ${y>0?"positive":"negative"}, so the point is in the ${names[q]}. The quadrants are numbered anticlockwise from the top right.`),
    ()=>{const k=nz(-9,9),onY=coin(.5),P=onY?`(0, ${neg(k)})`:`(${neg(k)}, 0)`;return mcq(`The point ${P} lies…`,onY?"on the y-axis":"on the x-axis",[onY?"on the x-axis":"on the y-axis","in the first quadrant","in no quadrant and not on any axis"].slice(0,3),`A point with x = 0 lies on the y-axis and a point with y = 0 lies on the x-axis. Points on an axis belong to no quadrant.`)})},
  ()=>{const m=nz(-5,5),c=rnd(-9,9),b=pick([1,2,3,4]),a=-m*b,c0=-c*b;V(near(-a/b,m)&&near(-c0/b,c),"slope-intercept");
   const askSlope=coin(.5);
   return nat(`For the line ${eq3(a,b,c0)}, find its ${askSlope?"slope":"y-intercept"}.`,askSlope?m:c,`Solve for y: ${b===1?"":b}y = ${pl([-a,-c0],"x")}, so y = ${pl([m,c])}. The slope is ${neg(m)} and the y-intercept is ${neg(c)}. In y = mx + c, m is the slope and c the y-intercept.`)},
  ()=>{const p=nz(-6,6),q=nz(1,6),k=coin(.5);const m1=p/q;
   const perp=fr(-q,p),par=fr(p,q);
   return either(.5,()=>M(`A line has slope ${fr(p,q)}. What is the slope of a line perpendicular to it?`,perp,[par,fr(q,p),fr(-p,q),neg(p*q),fr(2*p,q),"0","not defined"],`Perpendicular lines have slopes whose product is −1: m₁m₂ = −1, so m₂ = −1/m₁ = ${perp}.`),
    ()=>M(`A line has slope ${fr(p,q)}. What is the slope of a line parallel to it?`,par,[perp,fr(q,p),fr(-p,q),neg(p*q),fr(2*p,q),"0","not defined"],`Parallel lines have equal slopes, so the slope is ${par}.`))},
  ()=>{const m=nz(-4,4),c1=rnd(-6,6),c2=rnd(-6,6),v=rnd(0,2);
   if(v===0)return nat(`The line y = ${pl([m,c1])} is parallel to the line y = kx ${c2<0?"−":"+"} ${Math.abs(c2)}. Find k.`,m,`Parallel lines have equal slopes, so k = ${neg(m)}.`);
   const mm=pick([2,3,4,5,-2,-3,-4,-5]);V(near(mm*(-1/mm),-1),"perp");return M(`The line y = ${mm===1?"":neg(mm)}x ${c1<0?"−":"+"} ${Math.abs(c1)} is perpendicular to y = kx + ${Math.abs(c2)}. What is k?`,fr(-1,mm),[fr(1,mm),neg(mm),neg(-mm),fr(-mm,1)+"/2"],`Perpendicular lines satisfy m₁·m₂ = −1, so k = −1/${neg(mm)} = ${fr(-1,mm)}.`)},
  ()=>{const x1=rnd(-5,5),y1=rnd(-5,5),dx=rnd(1,4),dy=rnd(-4,4),col=coin(.5);let x3,y3;if(col){const t=rnd(2,3);x3=x1+t*dx;y3=y1+t*dy}else{const t=rnd(2,3);x3=x1+t*dx;y3=y1+t*dy+pick([1,2,-1,-2])}
   const x2=x1+dx,y2=y1+dy,cross=(x2-x1)*(y3-y1)-(y2-y1)*(x3-x1);V((cross===0)===col,"collinear");
   return M(`Are the points A(${neg(x1)}, ${neg(y1)}), B(${neg(x2)}, ${neg(y2)}) and C(${neg(x3)}, ${neg(y3)}) collinear (on one straight line)?`,col?"Yes: slope AB equals slope AC":"No: slope AB differs from slope AC",[col?"No: slope AB differs from slope AC":"Yes: slope AB equals slope AC","Yes: any three points are collinear","No: only two points can lie on a line"],`Three points are collinear when the slope of AB equals the slope of AC. Slope AB = ${fr(dy,dx)}; slope AC = ${fr(y3-y1,x3-x1)}. They are ${col?"equal":"different"}.`)},
  ()=>{const m=nz(-4,4),x1=rnd(-4,4),y1=rnd(-6,6),c=y1-m*x1;V(near(m*x1+c,y1),"point-slope");
   return either(.5,()=>nat(`A line with slope ${neg(m)} passes through (${neg(x1)}, ${neg(y1)}). What is its y-intercept?`,c,`y − y₁ = m(x − x₁) gives y = ${neg(m)}x + c with c = y₁ − m x₁ = ${neg(y1)} − (${neg(m)})(${neg(x1)}) = ${neg(c)}.`),
    ()=>{const dx=rnd(1,4),x2=x1+dx,y2=y1+m*dx;return nat(`Find the y-intercept of the line through (${neg(x1)}, ${neg(y1)}) and (${neg(x2)}, ${neg(y2)}).`,c,`Slope m = (${neg(y2)} − ${neg(y1)})/(${neg(x2)} − ${neg(x1)}) = ${neg(m)}. Then c = y₁ − m x₁ = ${neg(y1)} − (${neg(m)})(${neg(x1)}) = ${neg(c)}.`)})},
  ()=>T([["The slope of a horizontal line","0"],["The slope of a vertical line","not defined (infinite)"],["Two non-vertical lines with equal slopes are","parallel"],["Two lines whose slopes multiply to −1 are","perpendicular"],["The slope of the line joining (x₁, y₁) and (x₂, y₂)","(y₂ − y₁)/(x₂ − x₁)"],["The distance between (x₁, y₁) and (x₂, y₂)","√[(x₂ − x₁)² + (y₂ − y₁)²]"],["The equation y = mx + c is called the","slope-intercept form"],["The x-coordinate of any point on the y-axis","0"]],
   k=>`${k} is…`,null,r=>`${r[0]}: ${r[1]}.`),
  ()=>{const m=nz(-4,4),c=rnd(-8,8),x=rnd(-4,4),y=m*x+c;V(near(y,m*x+c),"eval");
   return either(.5,()=>nat(`A line has equation y = ${pl([m,c])}. What is y when x = ${neg(x)}?`,y,`y = ${neg(m)}(${neg(x)}) ${c<0?"−":"+"} ${Math.abs(c)} = ${neg(y)}.`),
    ()=>{if(c%m!==0)return nat(`Where does y = ${pl([m,c])} cut the y-axis (give the y value)?`,c,`On the y-axis x = 0, so y = c = ${neg(c)}.`);return nat(`At what value of x does the line y = ${pl([m,c])} cut the x-axis?`,-c/m,`On the x-axis y = 0, so ${neg(m)}x ${c<0?"−":"+"} ${Math.abs(c)} = 0 and x = ${neg(-c/m)}.`)})}
 ],
 /* ---------- Unit 2: Partial fractions, limits and continuity ---------- */
 2:[
  ()=>{const d=rnd(1,5),cs=[nz(1,5)*(coin(.5)?1:-1)].concat(Array.from({length:d},()=>rnd(-6,6))),x=rnd(-2,3),v=rnd(0,2);
   if(v===0)return nat(`What is the degree of the polynomial ${pl(cs)}?`,d,`The degree is the highest power of x with a non-zero coefficient: ${d}.`);
   if(v===1)return nat(`What is the coefficient of the highest power of x (the leading coefficient) in ${pl(cs)}?`,cs[0],`The highest power is x${d===1?"":"<sup>"+d+"</sup>"}, whose coefficient is ${neg(cs[0])}.`);
   return nat(`If p(x) = ${pl(cs)}, find p(${neg(x)}).`,ev(cs,x),`Substitute x = ${neg(x)}: p(${neg(x)}) = ${neg(ev(cs,x))}.`)},
  ()=>{const dn=rnd(0,4),dd=rnd(1,4),proper=dn<dd,N=Array.from({length:dn+1},(_,i)=>i===0?nz(1,4):rnd(-3,3)),D=Array.from({length:dd+1},(_,i)=>i===0?nz(1,3):rnd(-3,3));
   return M(`Is the rational fraction (${pl(N)})/(${pl(D)}) proper or improper?`,proper?"Proper (numerator degree < denominator degree)":"Improper (numerator degree ≥ denominator degree)",[proper?"Improper (numerator degree ≥ denominator degree)":"Proper (numerator degree < denominator degree)","Proper (numerator degree > denominator degree)","Neither: a fraction is only proper if both degrees are equal"],`Compare degrees: the numerator has degree ${dn} and the denominator degree ${dd}. A fraction is proper when the numerator's degree is less than the denominator's; otherwise divide first to make it proper.`)},
  ()=>{const a=rnd(1,5),b=nz(-5,5),r=nz(-9,9),v=rnd(0,1);V(true,"");
   /* (x + a)(x + b) + r divided by (x + a): quotient x + b, remainder r */
   const N=[1,a+b,a*b+r];return nat(`Divide the improper fraction (${pl(N)})/(x ${a<0?"−":"+"} ${Math.abs(a)}). Writing it as (quotient) + remainder/(x + ${a}), what is the ${v===0?"constant term of the quotient x + …":"remainder"}?`,v===0?b:r,`(${pl(N)}) = (x + ${a})(x ${b<0?"−":"+"} ${Math.abs(b)}) ${r<0?"−":"+"} ${Math.abs(r)}. So the fraction is x ${b<0?"−":"+"} ${Math.abs(b)} ${r<0?"−":"+"} ${Math.abs(r)}/(x + ${a}): quotient constant ${neg(b)}, remainder ${neg(r)}.`)},
  ()=>{let p=nz(-5,5),q=nz(-5,5);while(q===p)q=nz(-5,5);const A=nz(-6,6),B=nz(-6,6),N=[A+B,-(A*q+B*p)],x0=7;
   /* N(x)/((x−p)(x−q)) = A/(x−p) + B/(x−q); cover-up: A = N(p)/(p−q), B = N(q)/(q−p) */
   V(near(A/(x0-p)+B/(x0-q),ev(N,x0)/((x0-p)*(x0-q))),"partial fractions");V(near(ev(N,p)/(p-q),A)&&near(ev(N,q)/(q-p),B),"cover-up");
   const askA=coin(.5);
   return nat(`Write (${pl(N)})/(${lf(-p)}${lf(-q)}) = A/(x ${p<0?"+":"−"} ${Math.abs(p)}) + B/(x ${q<0?"+":"−"} ${Math.abs(q)}). Find ${askA?"A":"B"}.`,askA?A:B,`Multiply through by the denominator: ${pl(N)} = A(x ${q<0?"+":"−"} ${Math.abs(q)}) + B(x ${p<0?"+":"−"} ${Math.abs(p)}). Put x = ${askA?p:q}: ${neg(ev(N,askA?p:q))} = ${askA?"A":"B"}(${neg(askA?p-q:q-p)}), so ${askA?"A":"B"} = ${neg(askA?A:B)}. (A = ${neg(A)}, B = ${neg(B)}.)`)},
  ()=>{const p=rnd(1,6),q=rnd(1,6),v=rnd(0,3);
   if(v===0)return nat(`Evaluate the limit as x → ${p} of (x² − ${p*p})/(x − ${p}).`,2*p,`Factorise: (x² − ${p*p}) = (x − ${p})(x + ${p}). Cancel (x − ${p}) (allowed since x ≠ ${p} in a limit) to get x + ${p} → ${2*p}.`);
   if(v===1){let s=q;if(s===p)s=p+1;{const h=1e-6,x=p+h;V(near3((x*x-(p+s)*x+p*s)/(x-p),p-s),"limit")};return nat(`Evaluate the limit as x → ${p} of (x² − ${p+s}x + ${p*s})/(x − ${p}).`,p-s,`The numerator factorises as (x − ${p})(x − ${s}). Cancel (x − ${p}): the limit of (x − ${s}) is ${p} − ${s} = ${p-s}.`)}
   if(v===2){const a=nz(-5,5),b=nz(-5,5),c=rnd(-5,5),x0=rnd(-3,3);return nat(`Evaluate the limit as x → ${neg(x0)} of (${pl([a,b,c])}).`,ev([a,b,c],x0),`A polynomial is continuous everywhere, so the limit is found by substitution: ${neg(ev([a,b,c],x0))}.`)}
   const k=pick([2,3,4,5]);return nat(`Evaluate the limit as x → ${k} of (x³ − ${k**3})/(x − ${k}).`,3*k*k,`x³ − ${k**3} = (x − ${k})(x² + ${k}x + ${k*k}); after cancelling (x − ${k}) the limit is ${k*k} + ${k*k} + ${k*k} = ${3*k*k}.`)},
  ()=>{const a=nz(1,5),b=nz(-5,5),c=rnd(-5,5),d=nz(1,5),e=rnd(-5,5),f=rnd(-5,5),v=rnd(0,2);
   if(v===0)return M(`Evaluate the limit as x → ∞ of (${pl([a,b,c])})/(${pl([d,e,f])}).`,fr(a,d),[fr(d,a),"0","∞","1",fr(a+b,d+e),"−1","2","1/2"],`Divide the numerator and denominator by x²: every term with x in the denominator tends to 0, leaving the ratio of leading coefficients ${a}/${d} = ${fr(a,d)}.`);
   if(v===1)return M(`Evaluate the limit as x → ∞ of (${pl([b===0?1:b,c])})/(${pl([d,e,f])}).`,"0",[fr(b===0?1:b,d),"1","∞",fr(d,b===0?1:b),"−1","2"],`The numerator has a lower degree than the denominator, so dividing top and bottom by x² sends the fraction to 0.`);
   return M(`Evaluate the limit as x → ∞ of (${pl([a,b,c,e])})/(${pl([d,f])}).`,"∞ (it grows without bound)",["0",fr(a,d),"1","−∞ (it falls without bound)","2"],`The numerator has degree 3 and the denominator degree 1, so the fraction behaves like (${a}/${d})x², which grows without bound.`)},
  ()=>{const k=pick([2,3,4,5,6,7]),m=pick([2,3,4,5]),v=rnd(0,4);
   if(v===0)return nat(`Evaluate the limit as x → 0 of sin(${k}x)/x.`,k,`Using lim sin(θ)/θ = 1: sin(${k}x)/x = ${k}·sin(${k}x)/(${k}x) → ${k}·1 = ${k}.`);
   if(v===1){V(near3(Math.sin(k*1e-5)/(m*1e-5),k/m),"sin ratio");return nat(`Evaluate the limit as x → 0 of sin(${k}x)/(${m}x).`,r2(k/m),`sin(${k}x)/(${m}x) = (${k}/${m})·sin(${k}x)/(${k}x) → ${k}/${m} = ${r2(k/m)}.`)}
   if(v===2){V(near3(Math.tan(k*1e-5)/1e-5,k),"tan");return nat(`Evaluate the limit as x → 0 of tan(${k}x)/x.`,k,`tan(${k}x)/x = [sin(${k}x)/x]·[1/cos(${k}x)] → ${k}·1 = ${k}.`)}
   if(v===3){V(near3((Math.exp(k*1e-6)-1)/1e-6,k),"exp");return nat(`Evaluate the limit as x → 0 of (e<sup>${k}x</sup> − 1)/x.`,k,`Use lim (eᵗ − 1)/t = 1 with t = ${k}x: (e<sup>${k}x</sup> − 1)/x = ${k}·(e<sup>${k}x</sup> − 1)/(${k}x) → ${k}.`)}
   return M(`Evaluate the limit as x → 0 of (1 − cos x)/x².`,"1/2",["1","0","2","∞"],`1 − cos x = 2sin²(x/2), so (1 − cos x)/x² = ½·[sin(x/2)/(x/2)]² → ½.`)},
  ()=>{const p=rnd(1,4),m=nz(-3,3),c=rnd(-4,4),n=nz(-3,3),d=rnd(-6,6),v=rnd(0,2);
   if(v===0){const L=m*p+c;return M(`f(x) = ${pl([m,c])} for x < ${p} and f(x) = ${pl([n,d])} for x ≥ ${p}. What is the left-hand limit of f as x → ${p}?`,L,[n*p+d,L+1,L-1,m+c,L+2,L-2],`As x → ${p} from the left, f(x) = ${pl([m,c])}, so the limit is ${neg(m)}(${p}) ${c<0?"−":"+"} ${Math.abs(c)} = ${neg(L)}.`)}
   if(v===1){const R=n*p+d,L=m*p+c;return M(`f(x) = ${pl([m,c])} for x < ${p} and f(x) = ${pl([n,d])} for x ≥ ${p}. Does the limit of f(x) as x → ${p} exist?`,L===R?`Yes, it equals ${L}`:"No: the left-hand and right-hand limits differ",[L===R?"No: the left-hand and right-hand limits differ":`Yes, it equals ${L}`,`Yes, it equals ${R}`,"No: a limit never exists at a point where the formula changes",`Yes, it equals ${L+1}`,`Yes, it equals ${L-1}`],`Left-hand limit = ${neg(L)}, right-hand limit = ${neg(R)}. A limit exists only if both one-sided limits are equal.`)}
   const t=pick([1,2,3,4]),s2=pick([-3,-2,-1,0,5,6].filter(z=>z!==t)),ans=r2(2*t/(t-s2)),h=1e-6,x=t+h;V(near3((x*x-t*t)/(x*x-(t+s2)*x+t*s2),2*t/(t-s2)),"factor limit");
   return nat(`Evaluate the limit as x → ${t} of (x² − ${t*t})/(${pl([1,-(t+s2),t*s2])}).`,ans,`Factor: numerator (x − ${t})(x + ${t}); denominator (x − ${t})(x ${s2<0?"+":"−"} ${Math.abs(s2)}). Cancel (x − ${t}): the limit is (${t} + ${t})/(${t} − ${neg(s2)}) = ${2*t}/${t-s2} = ${ans}.`)},
  ()=>{const a=rnd(1,6),k=rnd(0,2),v=rnd(0,2);
   if(v===0)return nat(`f(x) = (x² − ${a*a})/(x − ${a}) for x ≠ ${a} and f(${a}) = k. For what value of k is f continuous at x = ${a}?`,2*a,`Continuity needs the limit to equal f(${a}). For x ≠ ${a}, f(x) = x + ${a}, so the limit is ${2*a}. Hence k = ${2*a}.`);
   if(v===1){const m=nz(-3,3),c=rnd(-5,5),n=nz(-3,3),d=(m*a+c)-n*a,nx=n===1?"":n===-1?"−":neg(n);return nat(`f(x) = ${pl([m,c])} for x < ${a} and f(x) = ${nx}x + d for x ≥ ${a}. Find d so that f is continuous at x = ${a}.`,d,`Continuity at x = ${a} needs both pieces to agree: ${neg(m*a+c)} = ${neg(n*a)} + d, so d = ${neg(m*a+c)} − ${neg(n*a)} = ${neg(d)}.`)}
   const kk=pick([2,3,4,5,6]);return nat(`f(x) = sin(${kk}x)/x for x ≠ 0 and f(0) = A. For what A is f continuous at x = 0?`,kk,`lim sin(${kk}x)/x = ${kk} as x → 0, so f is continuous at 0 only if A = ${kk}.`)},
  ()=>either(.5,()=>{const bad=["The graph has a jump at x = a","The limit as x → a is ∞","f(a) is not defined","The left-hand and right-hand limits are different"],good=["The limit as x → a exists and equals f(a)","You can draw the graph through x = a without lifting the pen","f(a) is defined, the limit exists and the two are equal"];
     return either(.5,()=>M(`Which of these is a sign that f is NOT continuous at x = a?`,pick(bad),good,`Continuity at a needs three things: f(a) is defined, the limit as x → a exists, and the limit equals f(a). A jump, an infinite limit, a missing f(a) or unequal one-sided limits each break one of them.`),
       ()=>M(`Which of these tells you that f IS continuous at x = a?`,pick(good),bad,`f is continuous at a exactly when f(a) is defined, the limit as x → a exists and the two are equal. A jump, an infinite limit, a missing f(a) or unequal one-sided limits all break continuity.`))},
    ()=>S("Which of these functions are continuous for every real x?",["x³ − 2x + 1","sin x","e<sup>x</sup>","|x|","cos(3x)"],["1/x","tan x","(x² − 1)/(x − 1)","ln x","1/(x² − 4)"],rnd(2,3),2,"Polynomials, sin, cos, eˣ and |x| are continuous on all reals. 1/x and 1/(x² − 4) blow up at a point, tan x has vertical asymptotes, ln x is not defined for x ≤ 0, and (x² − 1)/(x − 1) is not defined at x = 1.")),
  ()=>{const a=rnd(1,5),b=rnd(1,5),c=rnd(1,4),v=rnd(0,2);
   const f=[
    [`1/(${lf(a)}${lf(-b-6)})`,`A/(x + ${a}) + B/(x − ${b+6})`,"two distinct linear factors: one constant over each"],
    [`(x + 1)/((x + ${a})(x + ${b+6})²)`,`A/(x + ${a}) + B/(x + ${b+6}) + C/(x + ${b+6})²`,"a repeated linear factor needs a term for each power up to the repeat"],
    [`(x + 2)/((x + ${a})(x² + ${c}))`,`A/(x + ${a}) + (Bx + C)/(x² + ${c})`,"an irreducible quadratic factor needs a linear numerator Bx + C"]][v];
   const wrong=[`A/(x + ${a}) + B/(x + ${b+6})`,`A/(x + ${a}) + B/(x² + ${c})`,`A/(x + ${a}) + B/(x + ${b+6})²`,`A/((x + ${a})(x + ${b+6}))`,`A/(x + ${a}) + Bx/(x² + ${c})`,`A/(x + ${a}) + B/(x + ${b+6}) + C`];
   return M(`Which is the correct form of the partial fraction decomposition of ${f[0]}?`,f[1],wrong,`For ${f[2]}. The correct form is ${f[1]}.`)},
  ()=>S("Which of these rational fractions are proper (numerator degree less than denominator degree)?",["(x + 1)/(x² + 3)","3/(x − 2)","2x/(x² − 1)","(x² + 1)/(x³ + x)","(x + 5)/((x + 1)(x + 2))"],["(x² + 1)/(x − 1)","x³/(x² + 1)","(x + 2)/(x + 3)","x²/(x + 1)","(2x + 1)/(x − 4)"],rnd(2,3),2,"A fraction is proper only when the numerator's degree is strictly less than the denominator's. (x + 2)/(x + 3) and (2x + 1)/(x − 4) have equal degrees, so they are improper.")
 ],
 /* ---------- Unit 3: Derivatives ---------- */
 3:[
  ()=>{const a=nz(-4,4),n=rnd(2,5),b=rnd(-5,5),c=rnd(-5,5),x0=rnd(-2,3),ans=a*n*x0**(n-1)+b;V(near3(nd(x=>a*x**n+b*x+c,x0),ans),"power rule");
   return nat(`If f(x) = ${pl([a].concat(Array(n-2).fill(0),[b,c]))}, find f′(${neg(x0)}).`,ans,`f′(x) = ${neg(a*n)}x${n-1===1?"":"<sup>"+(n-1)+"</sup>"} ${b<0?"−":"+"} ${Math.abs(b)}. At x = ${neg(x0)}: ${neg(ans)}.`)},
  ()=>T([["sin x","cos x"],["cos x","−sin x"],["tan x","sec²x"],["cot x","−cosec²x"],["sec x","sec x tan x"],["cosec x","−cosec x cot x"],["eˣ","eˣ"],["ln x","1/x"],["aˣ (a > 0)","aˣ ln a"],["√x","1/(2√x)"],["1/x","−1/x²"],["x<sup>n</sup>","n x<sup>n−1</sup>"]],
   k=>`What is the derivative of ${k}?`,v=>`Which function has derivative ${v}?`,r=>`d/dx(${r[0]}) = ${r[1]}.`),
  ()=>{const a=nz(-3,3),b=rnd(-4,4),c=nz(-3,3),d=rnd(-4,4),x0=rnd(-2,3),u=a*x0+b,v=c*x0*x0+d*x0,ans=a*v+u*(2*c*x0+d);V(near3(nd(x=>(a*x+b)*(c*x*x+d*x),x0),ans),"product rule");
   return nat(`Use the product rule to find f′(${neg(x0)}) for f(x) = (${pl([a,b])})(${pl([c,d,0])}).`,ans,`Product rule: (uv)′ = u′v + uv′ with u = ${pl([a,b])}, v = ${pl([c,d,0])}. At x = ${neg(x0)}: u = ${neg(u)}, u′ = ${neg(a)}, v = ${neg(v)}, v′ = ${neg(2*c*x0+d)}. So f′ = ${neg(a)}(${neg(v)}) + (${neg(u)})(${neg(2*c*x0+d)}) = ${neg(ans)}.`)},
  ()=>{let a,b,c,d,x0,k,ans,tries=0;do{a=nz(-4,4);b=rnd(-5,5);c=nz(1,3);d=rnd(-4,4);x0=rnd(0,3);k=c*x0+d;ans=(a*d-b*c)/(k*k);tries++}while((k===0||!dec2(ans))&&tries<400);
   if(k===0||!dec2(ans)){a=2;b=1;c=1;d=1;x0=1;k=2;ans=(a*d-b*c)/(k*k)}
   V(near3(nd(x=>(a*x+b)/(c*x+d),x0),ans),"quotient rule");
   return nat(`Use the quotient rule to find f′(${x0}) for f(x) = (${pl([a,b])})/(${pl([c,d])}).`,ans,`(u/v)′ = (u′v − uv′)/v². With u = ${pl([a,b])}, v = ${pl([c,d])}: f′(x) = (${a}(${pl([c,d])}) − (${pl([a,b])})(${c}))/(${pl([c,d])})² = ${neg(a*d-b*c)}/(${pl([c,d])})². At x = ${x0} the denominator is ${k}² = ${k*k}, so f′ = ${neg(ans)}.`)},
  ()=>{const v=rnd(0,3);
   if(v===0){const a=nz(1,3),b=rnd(-3,3),n=rnd(2,4),x0=rnd(-1,2),ans=n*a*(a*x0+b)**(n-1);V(near3(nd(x=>(a*x+b)**n,x0),ans),"chain");return nat(`Use the chain rule to find dy/dx at x = ${neg(x0)} for y = (${pl([a,b])})<sup>${n}</sup>.`,ans,`dy/dx = ${n}(${pl([a,b])})<sup>${n-1}</sup> × ${a}. At x = ${neg(x0)}: ${n}(${neg(a*x0+b)})<sup>${n-1}</sup> × ${a} = ${neg(ans)}.`)}
   if(v===1){const k=nz(2,7);return nat(`If y = sin(${k}x), find dy/dx at x = 0.`,k,`dy/dx = ${k}cos(${k}x). At x = 0 cos 0 = 1, so dy/dx = ${k}.`)}
   if(v===2){const k=nz(-5,5);V(near3(nd(x=>Math.exp(k*x),0),k),"exp chain");return nat(`If y = e<sup>${k===1?"":k===-1?"−":neg(k)}x</sup>, find dy/dx at x = 0.`,k,`dy/dx = ${neg(k)}e<sup>${neg(k)}x</sup>. At x = 0 e⁰ = 1, so dy/dx = ${neg(k)}.`)}
   let a=pick([1,2,4,5]),x0,b,kk;do{x0=rnd(0,4);b=rnd(-3,5);kk=a*x0+b}while(![1,2,4,5].includes(kk));V(near3(nd(x=>Math.log(a*x+b),x0),a/kk),"ln chain");return nat(`If y = ln(${pl([a,b])}), find dy/dx at x = ${x0}.`,r2(a/kk),`dy/dx = ${a}/(${pl([a,b])}). At x = ${x0} the bracket is ${kk}, so dy/dx = ${a}/${kk} = ${r2(a/kk)}.`)},
  ()=>{const v=rnd(0,4);
   if(v===0){const a=nz(1,4),b=nz(-4,4),ans=r2(a*Math.E+b);V(near3(nd(x=>a*Math.exp(x)+b*Math.log(x),1),a*Math.E+b),"e ln");return nat(`Find f′(1) for f(x) = ${a===1?"":a}e<sup>x</sup> ${b<0?"−":"+"} ${Math.abs(b)===1?"":Math.abs(b)}ln x. (Use e ≈ 2.718; give 2 decimals.)`,ans,`f′(x) = ${a===1?"":a}eˣ ${b<0?"−":"+"} ${Math.abs(b)}/x. At x = 1: ${a}e ${b<0?"−":"+"} ${Math.abs(b)} = ${ans}.`)}
   if(v===1)return nat(`If y = x·eˣ, find dy/dx at x = 0.`,1,`Product rule: dy/dx = eˣ + x eˣ. At x = 0: 1 + 0 = 1.`);
   if(v===2){V(near3(nd(x=>x*Math.log(x),Math.E),2),"x ln x");return nat(`If y = x ln x, find dy/dx at x = e (e ≈ 2.718).`,2,`Product rule: dy/dx = ln x + x·(1/x) = ln x + 1. At x = e: 1 + 1 = 2.`)}
   if(v===3){const k=nz(2,6);return M(`What is d/dx of ln(${k}x)?`,"1/x",[`${k}/x`,`1/(${k}x)`,`${k}x`],`ln(${k}x) = ln ${k} + ln x, and ln ${k} is a constant, so the derivative is 1/x. (Chain rule gives the same: ${k}·1/(${k}x) = 1/x.)`)}
   const k=nz(2,6);return M(`What is d/dx of e<sup>${k}x</sup>?`,`${k}e<sup>${k}x</sup>`,[`e<sup>${k}x</sup>`,`${k}xe<sup>${k}x−1</sup>`,`e<sup>${k}</sup>`],`By the chain rule the derivative of e^(u) is e^(u)·u′, and u = ${k}x has u′ = ${k}.`)},
  ()=>{const v=rnd(0,5);
   if(v===0){const a=nz(1,3),b=nz(-6,6),c=rnd(-5,5),x0=rnd(-2,3);return nat(`Find the slope of the tangent to y = ${pl([a,b,c])} at x = ${neg(x0)}.`,2*a*x0+b,`The slope of the tangent is dy/dx = ${neg(2*a)}x ${b<0?"−":"+"} ${Math.abs(b)}. At x = ${neg(x0)} it is ${neg(2*a*x0+b)}.`)}
   if(v===1){const a=nz(1,4),h=rnd(-4,4),b=-2*a*h,c=rnd(-5,5);return nat(`At what value of x does y = ${pl([a,b,c])} have a horizontal tangent (a stationary point)?`,h,`Set dy/dx = ${neg(2*a)}x ${b<0?"−":"+"} ${Math.abs(b)} = 0, which gives x = ${neg(h)}.`)}
   if(v===2){const a=pick([1,2,3,4]),h=rnd(-3,3),k=rnd(-9,9),b=-2*a*h,c=a*h*h+k;return nat(`Find the minimum value of y = ${pl([a,b,c])}.`,k,`dy/dx = ${neg(2*a)}x ${b<0?"−":"+"} ${Math.abs(b)} = 0 at x = ${neg(h)}, and d²y/dx² = ${2*a} > 0, so it is a minimum. Its value is y = ${neg(k)}.`)}
   if(v===3){const a=nz(1,4),b=nz(-4,4),c=rnd(-4,4),d=rnd(-4,4),t0=rnd(1,3),acc=6*a*t0+2*b;V(near3((nd(t=>3*a*t*t+2*b*t+c,t0)),acc),"accel");return nat(`A particle moves along a line with position s = ${pl([a,b,c,d],"t")} metres. Find its acceleration at t = ${t0} s (in m/s²).`,acc,`v = ds/dt = ${neg(3*a)}t² ${2*b<0?"−":"+"} ${Math.abs(2*b)}t ${c<0?"−":"+"} ${Math.abs(c)}, so a = dv/dt = ${neg(6*a)}t ${2*b<0?"−":"+"} ${Math.abs(2*b)}. At t = ${t0}: ${neg(acc)} m/s².`)}
   if(v===4){const r=pick([2,3,4,5,10]);return nat(`How fast does the area A = πr² of a circle change with respect to the radius when r = ${r} cm? (Answer in cm²/cm, use π ≈ 3.1416, 2 decimals.)`,r2(2*Math.PI*r),`dA/dr = 2πr = 2π(${r}) = ${r2(2*Math.PI*r)}. This is the circumference of the circle.`)}
   const x0=pick([1,2,3]),a=pick([1,2,3]),b=rnd(1,9),c0=rnd(10,50),ans=2*a*x0+b;V(near3(nd(x=>a*x*x+b*x+c0,x0),ans),"marginal");return nat(`The cost of making x items is C(x) = ${pl([a,b,c0])} rupees. The marginal cost is dC/dx. Find the marginal cost at x = ${x0}.`,ans,`dC/dx = ${2*a}x + ${b}. At x = ${x0}: ${ans} rupees per extra item.`)},
  ()=>{const x0=rnd(-3,4),a=nz(1,3),b=rnd(-4,4),ans=2*a*x0+b,v=rnd(0,2);
   if(v===0)return M(`The derivative of f at x is defined by the first-principle formula…`,"f′(x) = lim (h→0) [f(x + h) − f(x)]/h",["f′(x) = lim (h→0) [f(x) − f(x + h)]/h","f′(x) = lim (h→∞) [f(x + h) − f(x)]/h","f′(x) = [f(x) + f(x + h)]/2h"],`The derivative is the limit of the slope of the secant line [f(x + h) − f(x)]/h as h shrinks to 0.`);
   if(v===1)return M(`For f(x) = x², what does [f(x + h) − f(x)]/h simplify to?`,"2x + h",["2x","x + h","2x + 2h"],`(x + h)² − x² = 2xh + h², and dividing by h gives 2x + h. As h → 0 this tends to 2x.`);
   V(near3(nd(x=>a*x*x+b*x,x0),ans),"first principle");return nat(`Using the first principle, find the derivative of f(x) = ${pl([a,b,0])} at x = ${neg(x0)}.`,ans,`[f(x + h) − f(x)]/h = ${neg(2*a)}x + ${a}h ${b<0?"−":"+"} ${Math.abs(b)}. As h → 0 this is ${neg(2*a)}x ${b<0?"−":"+"} ${Math.abs(b)}, which at x = ${neg(x0)} is ${neg(ans)}.`)},
  ()=>{const x=pick([[0,1],[0.5,4],[0.75,16],[0.6,6.25],[0.8,25],[0.9,100]]);V(near3(nd(t=>1/(1-t),x[0]),x[1]),"geometric series");
   return either(.6,()=>nat(`The series f(x) = 1 + x + x² + x³ + … equals 1/(1 − x) for |x| < 1. Differentiate term by term and find f′(${x[0]}).`,x[1],`Term by term: f′(x) = 1 + 2x + 3x² + … = 1/(1 − x)². At x = ${x[0]}: 1/(1 − ${x[0]})² = ${x[1]}.`),
    ()=>M(`Differentiating the series x + x²/2 + x³/3 + x⁴/4 + … term by term gives…`,"1 + x + x² + x³ + …",["x + x² + x³ + …","1 + x/2 + x²/3 + …","x + 2x² + 3x³ + …"],`d/dx of xⁿ/n is xⁿ⁻¹, so the terms become 1, x, x², x³, …`))}
 ],
 /* ---------- Unit 4: Integration ---------- */
 4:[
  ()=>{const n=rnd(2,6),a=n+1,k=rnd(1,4),b=rnd(1,3);const c=k*a,ans=c*b**(n+1)/a;V(near3(simpson(x=>c*x**n,0,b),ans),"power integral");
   return nat(`Evaluate the definite integral of ${c}x${n===1?"":"<sup>"+n+"</sup>"} from x = 0 to x = ${b}.`,ans,`∫ ${c}x<sup>${n}</sup> dx = ${c}x<sup>${n+1}</sup>/${n+1} = ${k}x<sup>${n+1}</sup>. From 0 to ${b}: ${k}(${b})<sup>${n+1}</sup> = ${ans}.`)},
  ()=>T([["sin x","−cos x + C"],["cos x","sin x + C"],["sec²x","tan x + C"],["cosec²x","−cot x + C"],["sec x tan x","sec x + C"],["eˣ","eˣ + C"],["1/x","ln|x| + C"],["aˣ","aˣ/ln a + C"],["1/(1 + x²)","tan⁻¹x + C"],["1/√(1 − x²)","sin⁻¹x + C"],["x<sup>n</sup> (n ≠ −1)","x<sup>n+1</sup>/(n + 1) + C"]],
   k=>`What is ∫ ${k} dx?`,v=>`Which function has the integral ${v}?`,r=>`∫ ${r[0]} dx = ${r[1]}.`),
  ()=>{let a,b,c,p,q,ans,t=0;do{a=nz(-3,3);b=rnd(-4,4);c=rnd(-4,4);p=rnd(-2,2);q=p+rnd(1,3);ans=(a/3)*(q**3-p**3)+(b/2)*(q**2-p**2)+c*(q-p);t++}while(!dec2(ans)&&t<500);
   if(!dec2(ans)){a=3;b=2;c=1;p=0;q=2;ans=(a/3)*(q**3-p**3)+(b/2)*(q**2-p**2)+c*(q-p)}
   V(near3(simpson(x=>a*x*x+b*x+c,p,q),ans),"poly integral");
   return nat(`Evaluate the definite integral of (${pl([a,b,c])}) from x = ${neg(p)} to x = ${q}.`,ans,`Antiderivative: ${a}x³/3 ${b<0?"−":"+"} ${Math.abs(b)}x²/2 ${c<0?"−":"+"} ${Math.abs(c)}x. Evaluating at ${q} and at ${neg(p)} and subtracting gives ${neg(ans)}.`)},
  ()=>{const v=rnd(0,3);
   if(v===0){const A=rnd(2,9),B=rnd(1,A-1),C=rnd(1,9);return nat(`If ∫ from 0 to 2 of f(x) dx = ${A + B} and ∫ from 2 to 5 of f(x) dx = ${C}, find ∫ from 0 to 5 of f(x) dx.`,A+B+C,`Integrals over adjacent intervals add: ∫₀⁵ = ∫₀² + ∫₂⁵ = ${A+B} + ${C} = ${A+B+C}.`)}
   if(v===1){const A=nz(-9,9);return nat(`If ∫ from 1 to 4 of f(x) dx = ${neg(A)}, find ∫ from 4 to 1 of f(x) dx.`,-A,`Reversing the limits changes the sign: ∫₄¹ f dx = −∫₁⁴ f dx = ${neg(-A)}.`)}
   if(v===2){const F=nz(-6,6),G=nz(-6,6),a=nz(-3,3),b=nz(-3,3);return nat(`Given ∫ from 0 to 1 of f(x) dx = ${neg(F)} and ∫ from 0 to 1 of g(x) dx = ${neg(G)}, find ∫ from 0 to 1 of (${a===1?"":a===-1?"−":neg(a)}f(x) ${b<0?"−":"+"} ${Math.abs(b)===1?"":Math.abs(b)}g(x)) dx.`,a*F+b*G,`Integration is linear: ∫(a f + b g) = a∫f + b∫g = ${neg(a)}(${neg(F)}) + (${neg(b)})(${neg(G)}) = ${neg(a*F+b*G)}.`)}
   const t=pick([1,2,3,4]);return either(.5,()=>nat(`Evaluate the integral of x³ from x = −${t} to x = ${t}.`,0,`x³ is an odd function, so the areas on either side of 0 cancel: the integral is 0.`),
    ()=>nat(`Evaluate the integral of x² from x = −${t} to x = ${t}. (Give 2 decimals.)`,r2(2*t**3/3),`x² is even, so the integral is 2∫₀ᵗ x² dx = 2t³/3 = 2(${t})³/3 = ${r2(2*t**3/3)}.`))},
  ()=>{const v=rnd(0,4);
   if(v===0){let a,b,n,p,q,ans,t=0;do{a=pick([1,2,3]);b=rnd(-3,4);n=rnd(2,4);p=rnd(0,2);q=p+rnd(1,2);ans=((a*q+b)**(n+1)-(a*p+b)**(n+1))/(a*(n+1));t++}while(!dec2(ans)&&t<400);
    if(!dec2(ans)){a=1;b=1;n=2;p=0;q=2;ans=((a*q+b)**(n+1)-(a*p+b)**(n+1))/(a*(n+1))}
    V(near3(simpson(x=>(a*x+b)**n,p,q),ans),"substitution");
    return nat(`Use the substitution u = ${pl([a,b])} to evaluate the integral of (${pl([a,b])})<sup>${n}</sup> from x = ${p} to x = ${q}.`,ans,`With u = ${pl([a,b])}, du = ${a}dx, so ∫ u<sup>${n}</sup> du/${a} = u<sup>${n+1}</sup>/${a*(n+1)}. Limits become u = ${a*p+b} to u = ${a*q+b}: (${(a*q+b)**(n+1)} − ${(a*p+b)**(n+1)})/${a*(n+1)} = ${neg(ans)}.`)}
   if(v===1)return nat(`Use u = sin x to evaluate the integral of sin x cos x from x = 0 to x = π/2.`,0.5,`Let u = sin x, du = cos x dx. The limits become u = 0 to u = 1, and ∫₀¹ u du = ½.`);
   if(v===2)return nat(`Use u = ln x to evaluate the integral of (ln x)/x from x = 1 to x = e. (e ≈ 2.718)`,0.5,`Let u = ln x, du = dx/x. The limits become u = 0 to u = 1 and ∫₀¹ u du = ½.`);
   if(v===3)return nat(`Use u = x² to evaluate the integral of 2x·e<sup>x²</sup> from x = 0 to x = 1. (e ≈ 2.718, give 2 decimals.)`,r2(Math.E-1),`Let u = x², du = 2x dx. The limits become u = 0 to 1, so the integral is ∫₀¹ eᵘ du = e − 1 = ${r2(Math.E-1)}.`);
   const k=pick([1,3]),ans=r2(((2**(k+1))-1)/(2*(k+1)));V(near3(simpson(x=>x*(1+x*x)**k,0,1),((2**(k+1))-1)/(2*(k+1))),"x(1+x²)^k");
   return nat(`Use u = 1 + x² to evaluate the integral of x(1 + x²)<sup>${k}</sup> from x = 0 to x = 1.`,ans,`u = 1 + x², du = 2x dx, so the integral is ½∫ from u = 1 to 2 of u<sup>${k}</sup> du = ½·(2<sup>${k+1}</sup> − 1)/${k+1} = ${ans}.`)},
  ()=>{const v=rnd(0,2);
   if(v===0)return M(`To integrate sin²x, which identity turns it into something easy to integrate?`,"sin²x = (1 − cos 2x)/2",["sin²x = 1 + cos 2x","sin²x = (1 + cos 2x)/2","sin²x = 2 sin x cos x"],`sin²x = (1 − cos 2x)/2, so ∫ sin²x dx = x/2 − sin 2x/4 + C.`);
   if(v===1)return M(`To integrate cos²x, which identity is used?`,"cos²x = (1 + cos 2x)/2",["cos²x = (1 − cos 2x)/2","cos²x = 1 + sin²x","cos²x = 2 cos x − 1"],`cos²x = (1 + cos 2x)/2, so ∫ cos²x dx = x/2 + sin 2x/4 + C.`);
   const t=pick([[Math.PI,"π","sin²x","0 to π",1.57,"π/2",x=>Math.sin(x)**2],[Math.PI/2,"π/2","sin²x","0 to π/2",0.79,"π/4",x=>Math.sin(x)**2],[2*Math.PI,"2π","cos²x","0 to 2π",3.14,"π",x=>Math.cos(x)**2],[Math.PI,"π","cos²x","0 to π",1.57,"π/2",x=>Math.cos(x)**2]]);
   V(near3(simpson(t[6],0,t[0]),t[4]*1.0)||Math.abs(simpson(t[6],0,t[0])-t[4])<0.01,"trig integral");
   return nat(`Evaluate the integral of ${t[2]} over ${t[3]}. (Give 2 decimals; π ≈ 3.1416.)`,t[4],`Use the half-angle identity: the integral over ${t[3]} equals ${t[5]} = ${t[4]}.`)},
  ()=>{const v=rnd(0,4);
   if(v===0)return M(`Integration by parts uses ∫u dv = uv − ∫v du. For ∫ x eˣ dx, which choice of u is best?`,"u = x, dv = eˣ dx",["u = eˣ, dv = x dx","u = x eˣ, dv = dx","u = 1, dv = x eˣ dx"],`Choose u so that du is simpler than u. Differentiating x gives 1, while integrating eˣ stays eˣ, so u = x, dv = eˣ dx.`);
   const L=[["x eˣ","0 to 1",1,x=>x*Math.exp(x),0,1,"[x eˣ − eˣ] from 0 to 1 = (e − e) − (0 − 1) = 1"],["ln x","1 to e",1,x=>Math.log(x),1,Math.E,"[x ln x − x] from 1 to e = (e − e) − (0 − 1) = 1"],["x sin x","0 to π",3.14,x=>x*Math.sin(x),0,Math.PI,"[−x cos x + sin x] from 0 to π = π ≈ 3.14"],["x cos x","0 to π/2",0.57,x=>x*Math.cos(x),0,Math.PI/2,"[x sin x + cos x] from 0 to π/2 = π/2 − 1 ≈ 0.57"],["x e<sup>2x</sup>","0 to 1",2.10,x=>x*Math.exp(2*x),0,1,"[x e²ˣ/2 − e²ˣ/4] from 0 to 1 = e²/4 + 1/4 ≈ 2.10"]];
   const r=pick(L);V(Math.abs(simpson(r[3],r[4],r[5])-r[2])<0.011,"by parts "+r[0]);
   return nat(`Use integration by parts to evaluate the integral of ${r[0]} from x = ${r[1].split(" to ")[0]} to x = ${r[1].split(" to ")[1]}. (Give 2 decimals; e ≈ 2.718, π ≈ 3.1416.)`,r[2],`Integration by parts gives ${r[6]}.`)},
  ()=>{let p=rnd(1,4),d=pick([1,2,4,5]),q=p+d;const A=r2(1/d),B=r2(-1/d);V(near(1/((3+p)*(3+q)),(1/d)/(3+p)-(1/d)/(3+q)),"pf integral");
   return either(.5,()=>nat(`To integrate 1/((x + ${p})(x + ${q})), write it as A/(x + ${p}) + B/(x + ${q}). Find A.`,A,`Cover-up: A = 1/(x + ${q}) at x = −${p}, that is 1/(${q} − ${p}) = 1/${d} = ${A}. (B = ${B}.)`),
    ()=>M(`∫ dx/((x + ${p})(x + ${q})) equals…`,`(1/${d})ln|(x + ${p})/(x + ${q})| + C`,[`(1/${d})ln|(x + ${p})(x + ${q})| + C`,`${d}ln|(x + ${p})/(x + ${q})| + C`,`ln|(x + ${p})/(x + ${q})| + C`],`Partial fractions give (1/${d})[1/(x + ${p}) − 1/(x + ${q})]. Integrating each term gives logarithms, and the difference of logs is a log of a quotient.`))},
  ()=>{const v=rnd(0,4);
   if(v===0){const a=pick([3,6,9]),b=rnd(1,4);V(near3(simpson(x=>a*x*x,0,b),a*b**3/3),"area");return nat(`Find the area under y = ${a}x² between x = 0 and x = ${b}.`,a*b**3/3,`Area = ∫₀^${b} ${a}x² dx = ${a}x³/3 from 0 to ${b} = ${a/3}(${b})³ = ${a*b**3/3}.`)}
   if(v===1){const a=nz(1,6),b=rnd(2,8);return nat(`Find the area under the line y = ${a}x from x = 0 to x = ${b}.`,a*b*b/2,`Area = ∫₀^${b} ${a}x dx = ${a}x²/2 = ${a}(${b*b})/2 = ${a*b*b/2}. (It is a triangle of base ${b} and height ${a*b}.)`)}
   if(v===2){const a=rnd(1,5),b=rnd(0,6),T=rnd(2,6);return nat(`A car has velocity v = ${a}t + ${b} m/s. How far does it travel between t = 0 and t = ${T} s?`,a*T*T/2+b*T,`Distance = ∫₀^${T}(${a}t + ${b}) dt = ${a}t²/2 + ${b}t = ${a*T*T/2} + ${b*T} = ${a*T*T/2+b*T} m.`)}
   if(v===3){const a=pick([2,4,6]),b=pick([2,4]);return nat(`Find the average value of f(x) = ${a}x over the interval from x = 0 to x = ${b}.`,a*b/2,`Average value = (1/(b − a))∫f dx = (1/${b})·(${a}${b}²/2) = ${a*b/2}.`)}
   return M(`Find the area enclosed between the curve y = x² and the line y = x.`,"1/6",["1/3","1/2","1/4"],`They meet at x = 0 and x = 1. Area = ∫₀¹ (x − x²) dx = 1/2 − 1/3 = 1/6.`)}
 ],
 /* ---------- Unit 5: Differential equations ---------- */
 5:[
  ()=>{const L=[["dy/dx + 3y = x²",1,1],["d²y/dx² + 4y = 0",2,1],["(d²y/dx²)² + dy/dx = 0",2,2],["d³y/dx³ + (dy/dx)² = 0",3,1],["(dy/dx)³ + y = 0",1,3],["d²y/dx² + y = sin x",2,1],["(d²y/dx²)³ + (dy/dx)⁴ + y = 0",2,3],["x·dy/dx + y = x³",1,1],["d³y/dx³ − 3d²y/dx² + 2dy/dx = 0",3,1],["(dy/dx)² + y = x",1,2]],r=pick(L),askOrder=coin(.5);
   return nat(`What is the ${askOrder?"order":"degree"} of the differential equation ${r[0]} ?`,askOrder?r[1]:r[2],`The order is the highest derivative present (${r[1]}); the degree is the power of that highest derivative once the equation is a polynomial in the derivatives (${r[2]}).`)},
  ()=>{const L=[["dy/dx + 3y = 0","an ordinary differential equation (ODE)"],["d²y/dx² + 4y = sin x","an ordinary differential equation (ODE)"],["∂u/∂t = c² ∂²u/∂x²","a partial differential equation (PDE)"],["∂²u/∂x² + ∂²u/∂y² = 0","a partial differential equation (PDE)"],["x dy = y dx","an ordinary differential equation (ODE)"],["∂u/∂x + ∂u/∂y = u","a partial differential equation (PDE)"]],r=pick(L);
   return M(`The equation ${r[0]} is…`,r[1],["an ordinary differential equation (ODE)","a partial differential equation (PDE)","an algebraic equation","an integral equation"].filter(x=>x!==r[1]),`An ODE has derivatives with respect to one independent variable only; a PDE has partial derivatives with respect to two or more.`)},
  ()=>{const L=[["dy/dx + 2y = x",true],["d²y/dx² + 5dy/dx + 6y = 0",true],["y·dy/dx = x",false],["dy/dx + y² = 0",false],["d²y/dx² + sin y = 0",false],["x²·d²y/dx² + x·dy/dx + y = 0",true]],r=pick(L);
   return M(`Is the differential equation ${r[0]} linear or non-linear?`,r[1]?"Linear":"Non-linear",[r[1]?"Non-linear":"Linear","Both linear and non-linear","Neither: it has no order"],`An ODE is linear if y and all its derivatives appear only to the first power and are not multiplied together or inside functions such as sin y. ${r[1]?"That holds here.":"Here y appears in a product, a square or a sine, so it is non-linear."}`)},
  ()=>{const n=rnd(1,4);return nat(`How many arbitrary constants does the general solution of an ordinary differential equation of order ${n} contain?`,n,`The general solution of an nth-order ODE contains n independent arbitrary constants. Here n = ${n}.`)},
  ()=>{const v=rnd(0,2);
   if(v===0){const k=nz(-5,5),y0=rnd(-6,6),x1=rnd(1,5);return nat(`Solve dy/dx = ${neg(k)} with y(0) = ${neg(y0)}. Find y(${x1}).`,y0+k*x1,`Integrate: y = ${neg(k)}x + C. Using y(0) = ${neg(y0)} gives C = ${neg(y0)}, so y(${x1}) = ${neg(k)}(${x1}) + (${neg(y0)}) = ${neg(y0+k*x1)}.`)}
   if(v===1){const a=nz(-4,4),b=rnd(-4,4),y0=rnd(-5,5),x1=pick([2,4]);const y=y0+a*x1*x1/2+b*x1;return nat(`Solve dy/dx = ${pl([a,b])} with y(0) = ${neg(y0)}. Find y(${x1}).`,y,`Integrate: y = ${a}x²/2 ${b<0?"−":"+"} ${Math.abs(b)}x + C, and C = ${neg(y0)} from y(0). At x = ${x1}: ${neg(y)}.`)}
   const c=pick([1,2,3]);return M(`What is the general solution of dy/dx = ${3*c}x²?`,`y = ${c}x³ + C`,[`y = ${3*c}x³ + C`,`y = ${c}x² + C`,`y = ${6*c}x + C`],`Integrate both sides: y = ∫${3*c}x² dx = ${c}x³ + C.`)},
  ()=>{const v=rnd(0,3);
   if(v===0){const k=pick([1,2,3]),A=r2(Math.LN2/k);return nat(`A quantity obeys dy/dx = ${k}y with y(0) > 0. After what value of x does y double? (ln 2 ≈ 0.693, give 2 decimals.)`,A,`The solution is y = y₀e^(${k}x). It doubles when e^(${k}x) = 2, so x = ln 2/${k} = ${A}.`)}
   if(v===1){const k=pick([1,2,4,5]),A=r2(Math.LN2/k);return nat(`A radioactive sample follows dN/dt = −${k}N (t in hours). Find its half-life in hours. (ln 2 ≈ 0.693, give 2 decimals.)`,A,`N = N₀e^(−${k}t). It halves when e^(−${k}t) = ½, so t = ln 2/${k} = ${A} h.`)}
   if(v===2){const [y0,x1,y1]=pick([[3,4,5],[4,3,5],[5,12,13],[12,5,13],[8,6,10],[6,8,10]]);V(near(Math.hypot(x1,y0),y1),"separable");return nat(`Solve y·dy/dx = x with y(0) = ${y0} (y > 0). Find y(${x1}).`,y1,`Separate: y dy = x dx, so y²/2 = x²/2 + C, i.e. y² = x² + C. From y(0) = ${y0}, C = ${y0*y0}. At x = ${x1}: y² = ${x1*x1} + ${y0*y0} = ${y1*y1}, so y = ${y1}.`)}
   const x0=pick([2,3,4]),y1=pick([4,6,8,10]),x2=pick([5,6,7]);return nat(`Solve x·dy/dx = y with y(${x0}) = ${y1}. Find y(${x2}). (Answer to 2 decimals.)`,r2(y1*x2/x0),`Separate: dy/y = dx/x, so ln y = ln x + C, i.e. y = Cx. From y(${x0}) = ${y1}, C = ${y1}/${x0}. Then y(${x2}) = ${y1}(${x2})/${x0} = ${r2(y1*x2/x0)}.`)},
  ()=>{const L=[["dy/dx + 2y = x","e<sup>2x</sup>","P = 2, and the integrating factor is e^(∫P dx) = e^(2x)"],["dy/dx + y = eˣ","eˣ","P = 1, integrating factor e^(∫1 dx) = eˣ"],["dy/dx + (1/x)y = x²","x","P = 1/x, integrating factor e^(ln x) = x"],["dy/dx + (2/x)y = 1","x²","P = 2/x, integrating factor e^(2 ln x) = x²"],["dy/dx − y = x","e<sup>−x</sup>","P = −1, integrating factor e^(∫−1 dx) = e⁻ˣ"],["dy/dx + (tan x)y = sin x","sec x","P = tan x, integrating factor e^(∫tan x dx) = e^(ln sec x) = sec x"]],r=pick(L);
   return M(`What is the integrating factor of ${r[0]} ?`,r[1],L.map(x=>x[1]).concat(["x<sup>−1</sup>"]),`${r[2]}.`)},
  ()=>{const k=pick([2,3,4,5]);return either(.5,()=>S(`Which of these are solutions of dy/dx = ${k}y?`,[`y = C e<sup>${k}x</sup>`,`y = 5e<sup>${k}x</sup>`,`y = e<sup>${k}x</sup>`,`y = −2e<sup>${k}x</sup>`],[`y = C e<sup>x</sup>`,`y = ${k}x + C`,`y = C x<sup>${k}</sup>`,`y = e<sup>x/${k}</sup>`],rnd(2,3),2,`Substituting y = C e^(${k}x) gives dy/dx = ${k}C e^(${k}x) = ${k}y, so every multiple of e^(${k}x) is a solution. The others fail: for example y = ${k}x + C has dy/dx = ${k}, not ${k}y.`),
    ()=>M(`What is the general solution of dy/dx = ${k}y?`,`y = C e<sup>${k}x</sup>`,[`y = ${k}x + C`,`y = C x<sup>${k}</sup>`,`y = e<sup>x</sup> + ${k}`],`Separating variables gives dy/y = ${k}dx, so ln y = ${k}x + c, i.e. y = C e^(${k}x).`))},
  ()=>{const A=nz(1,3),B=nz(-3,3),C=nz(1,3),D=A*A*(0)+B*B-4*A*C,disc=B*B-4*A*C;
   const name=disc<0?"elliptic":disc===0?"parabolic":"hyperbolic";
   return M(`Classify the second-order PDE ${A===1?"":A}u<sub>xx</sub> ${B<0?"−":"+"} ${Math.abs(B)===1?"":Math.abs(B)}u<sub>xy</sub> + ${C===1?"":C}u<sub>yy</sub> = 0 using B² − 4AC.`,name,["elliptic","parabolic","hyperbolic","not a partial differential equation"].filter(x=>x!==name),`With A = ${A}, B = ${B}, C = ${C}: B² − 4AC = ${B*B} − ${4*A*C} = ${disc}. Negative means elliptic, zero parabolic, positive hyperbolic. So it is ${name}.`)},
  ()=>{const R=[["Laplace equation u<sub>xx</sub> + u<sub>yy</sub> = 0","elliptic"],["heat equation u<sub>t</sub> = c²u<sub>xx</sub>","parabolic"],["wave equation u<sub>tt</sub> = c²u<sub>xx</sub>","hyperbolic"]],r=pick(R);
   return M(`What type of PDE is the ${r[0]}?`,r[1],["elliptic","parabolic","hyperbolic","not a partial differential equation"],`The ${r[0]} is ${r[1]}: with the form Au<sub>xx</sub> + Bu<sub>xy</sub> + Cu<sub>yy</sub>, B² − 4AC &lt; 0 is elliptic, = 0 parabolic and &gt; 0 hyperbolic.`)}
 ]
});

/* =============================== BTT-001 Biology for Engineers =============================== */
const CODON={AUG:"Methionine",UUU:"Phenylalanine",UUC:"Phenylalanine",UGG:"Tryptophan",AAA:"Lysine",AAG:"Lysine",GGG:"Glycine",GGC:"Glycine",CCC:"Proline",CCU:"Proline",GAA:"Glutamic acid",GAG:"Glutamic acid",GCU:"Alanine",GCC:"Alanine",UGU:"Cysteine",UGC:"Cysteine",CAU:"Histidine",CAC:"Histidine",GAU:"Aspartic acid",GAC:"Aspartic acid",AAU:"Asparagine",UAU:"Tyrosine",CGU:"Arginine",AGU:"Serine",UCU:"Serine",ACU:"Threonine",GUU:"Valine",CUU:"Leucine",AUU:"Isoleucine",CAA:"Glutamine"};
const AA_NAMES=[...new Set(Object.values(CODON))];
const COMP={A:"U",T:"A",C:"G",G:"C"};
const rndBases=n=>Array.from({length:n},()=>pick(["A","T","C","G"])).join("");
const lc=k=>k==="Golgi apparatus"?k:k.toLowerCase();
const oneOf=(...f)=>pick(f)();
const KIND=["Ammonia","Urea","Uric acid","Creatinine"];

genReplace("BTT-001",{
 /* ---------- Unit 1: Introduction to biology and the cell ---------- */
 1:[
  ()=>T([["Red biotechnology","medical and pharmaceutical work such as vaccines, antibiotics and gene therapy"],["Green biotechnology","agriculture, such as pest-resistant and drought-tolerant crops"],["White biotechnology","industrial processes, such as enzymes and bio-based chemicals and fuels"],["Blue biotechnology","marine and aquatic organisms and their products"]],k=>`In the colour code of biotechnology, "${k}" mainly refers to…`,v=>`Which branch of biotechnology deals with ${v}?`,r=>`${r[0]} covers ${r[1]}.`),
  ()=>T([["Robert Hooke","coined the word “cell” after looking at cork under a microscope (1665)"],["Anton van Leeuwenhoek","was the first to see living single-celled organisms, which he called animalcules"],["Schleiden and Schwann","proposed that plants and animals are made of cells (1838–39)"],["Rudolf Virchow","stated that every cell arises from a pre-existing cell"]],k=>`What is ${k} known for in the story of the cell theory?`,v=>`Who ${v}?`,r=>`${r[0]} ${r[1]}.`),
  ()=>{const U=["Amoeba","Yeast","Paramecium","E. coli","Euglena"],Mu=["Mushroom","Oak tree","Earthworm","Housefly","Human"];
   return either(.5,()=>M(`Which of these organisms is unicellular?`,pick(U),shuffle(Mu),`Amoeba, yeast, Paramecium, E. coli and Euglena each live as a single cell. Mushrooms, trees, worms, insects and humans are multicellular.`),
    ()=>M(`Which of these organisms is multicellular?`,pick(Mu),shuffle(U),`Mushrooms, trees, worms, insects and humans are made of many cells. Amoeba, yeast, Paramecium, E. coli and Euglena are single-celled.`))},
  ()=>{const P=[["a membrane-bound nucleus","Eukaryotic cells only"],["mitochondria","Eukaryotic cells only"],["an endoplasmic reticulum","Eukaryotic cells only"],["a Golgi apparatus","Eukaryotic cells only"],["a nucleoid, a DNA region with no membrane around it","Prokaryotic cells only"],["a plasma membrane","Both prokaryotic and eukaryotic cells"],["ribosomes","Both prokaryotic and eukaryotic cells"],["DNA as the genetic material","Both prokaryotic and eukaryotic cells"]],r=pick(P);
   return M(`Which cells have ${r[0]}?`,r[1],["Eukaryotic cells only","Prokaryotic cells only","Both prokaryotic and eukaryotic cells","Neither of them"],`${r[1]==="Eukaryotic cells only"?"Membrane-bound organelles are a hallmark of eukaryotes; prokaryotes have none.":r[1]==="Prokaryotic cells only"?"Prokaryotes keep their DNA in a nucleoid, which is not enclosed by a nuclear membrane.":"Every cell needs a boundary membrane, ribosomes to make protein and DNA to store its instructions."}`)},
  ()=>T([["Photoautotroph","uses light for energy and CO<sub>2</sub> for carbon (for example plants and cyanobacteria)"],["Chemoautotroph","gets energy by oxidising inorganic compounds and carbon from CO<sub>2</sub> (for example nitrifying bacteria)"],["Photoheterotroph","uses light for energy but needs organic compounds for carbon (for example purple non-sulphur bacteria)"],["Chemoheterotroph","uses organic compounds for both energy and carbon (for example humans, fungi and most bacteria)"]],k=>`What describes a ${k.toLowerCase()}?`,v=>`Which nutritional type ${v}?`,r=>`A ${r[0].toLowerCase()} ${r[1]}. The prefix says the energy source (photo = light, chemo = chemicals) and the ending says the carbon source (auto = CO<sub>2</sub>, hetero = organic).`),
  ()=>T([["Mushroom (a fungus)","Chemoheterotroph"],["Cyanobacteria","Photoautotroph"],["Nitrosomonas, which oxidises ammonia for energy and fixes CO<sub>2</sub>","Chemoautotroph"],["Purple non-sulphur bacteria, which use light and organic acids","Photoheterotroph"]],k=>`How is ${k} classified by how it gets energy and carbon?`,null,r=>`${r[0]} is a ${r[1].toLowerCase()}.`),
  ()=>{const A=[["Freshwater bony fish",0],["Tadpoles",0],["Humans",1],["Cattle",1],["Adult frogs",1],["Sharks",1],["Birds",2],["Lizards",2],["Insects",2],["Snakes",2]],r=pick(A),out=["Ammonia","Urea","Uric acid"][r[1]];
   return M(`Which nitrogenous waste does the following animal mainly excrete: ${r[0].toLowerCase()}?`,out,KIND,`${r[0]} ${r[1]===0?"are ammonotelic: ammonia is very toxic and needs plenty of water to flush it out, which suits aquatic life":r[1]===1?"are ureotelic: urea is far less toxic than ammonia, so it can be stored briefly and passed out with modest water loss":"are uricotelic: uric acid is almost insoluble and leaves as a paste, saving water, which suits reptiles, birds and insects"}.`)},
  ()=>T([["Mitochondrion","makes most of the cell’s ATP by aerobic respiration"],["Ribosome","assembles proteins by translating mRNA"],["Golgi apparatus","modifies, sorts and packages proteins and lipids"],["Lysosome","digests worn-out organelles and large molecules with hydrolytic enzymes"],["Rough endoplasmic reticulum","makes proteins for secretion and for membranes"],["Chloroplast","carries out photosynthesis"],["Nucleus","stores the DNA and controls gene expression"],["Smooth endoplasmic reticulum","makes lipids and detoxifies drugs"]],k=>`What is the main function of the ${lc(k)}?`,v=>`Which organelle ${v}?`,r=>`The ${lc(r[0])} ${r[1]}.`),
  ()=>T([["Nucleoid","holds the single circular chromosome and has no membrane around it"],["Plasmid","is a small circular DNA molecule that often carries resistance genes"],["Pilus","is a hair-like appendage used for attachment or for passing DNA to another cell"],["Flagellum","is a whip-like structure used for swimming"],["Capsule","is a slimy outer layer that helps a bacterium resist drying and phagocytosis"],["Peptidoglycan cell wall","gives the bacterial cell its shape and stops it bursting in dilute surroundings"]],k=>`In a bacterial cell, the ${k.toLowerCase()}…`,v=>`Which bacterial structure ${v}?`,r=>`The ${r[0].toLowerCase()} ${r[1]}.`),
  ()=>either(.5,()=>{const L=pick([1,2,4,5]),d=pick([1,2,5]);return nat(`A rod-shaped bacterium is ${L} µm long. How many of them placed end to end would span ${d} mm? (1 mm = 1000 µm.)`,d*1000/L,`${d} mm = ${d*1000} µm. Number = ${d*1000} ÷ ${L} = ${d*1000/L}.`)},
    ()=>{const a=pick([2,4,5,10,20]),i=pick([20,40,50,80,100]);return nat(`A cell that is really ${a} µm across appears ${i} mm across in a photomicrograph. What is the magnification (× times)?`,i*1000/a,`Magnification = image size ÷ actual size = ${i*1000} µm ÷ ${a} µm = ${i*1000/a}×.`)}),
  ()=>either(.5,()=>M(`Which statement best separates biology as a science from biotechnology as engineering?`,`Science seeks to understand living systems, while engineering designs and builds useful products and processes from that understanding.`,[`Science studies plants only, while engineering studies animals only.`,`Science uses machines, while engineering uses living cells only.`,`Science produces products for sale, while engineering only writes theory.`],`Science asks “how and why does it work?”. Engineering asks “how can we use this to make something that solves a problem?”. Biotechnology is the second kind of activity.`),
    ()=>M(`Which of these is an example of biological engineering rather than pure biological science?`,pick([`Designing a bacterium that makes human insulin`,`Building a bioreactor that grows yeast for ethanol`,`Engineering a plant to resist a pest`]),[`Counting chromosomes in a dividing onion root tip`,`Naming a newly found beetle species`,`Measuring the resting potential of a squid axon`],`Engineering is about building something useful: an insulin-making microbe, a bioreactor or a pest-resistant crop. The other options only observe or describe nature.`)),
  ()=>T([["Thermophile","hot environments"],["Psychrophile","cold environments"],["Halophile","very salty environments"],["Acidophile","acidic environments (low pH)"],["Alkaliphile","alkaline environments (high pH)"],["Piezophile","high-pressure environments such as the deep sea"]],k=>`An extremophile called a ${k.toLowerCase()} thrives in…`,v=>`Which type of extremophile lives in ${v}?`,r=>`A ${r[0].toLowerCase()} loves ${r[1]}.`)
 ],
 /* ---------- Unit 2: Microorganisms, classification, culture and growth ---------- */
 2:[
  ()=>either(.5,()=>M(`In microbiology, what is a “strain”?`,`A genetic variant or subtype within a species, often isolated from a particular source`,[`Another word for a species`,`A group of related genera`,`A group of species that share one habitat`],`Members of the same species can differ slightly, for example E. coli K-12 and E. coli O157:H7. Each such variant is a strain.`),
    ()=>M(`In the name Escherichia coli, which part is the genus?`,`Escherichia`,[`coli`,`Both words together`,`Neither: it is the family name`],`Binomial names give the genus first (capitalised) and the species second (lower case), both in italics.`)),
  ()=>T([["Coccus","spherical"],["Bacillus","rod-shaped"],["Spirillum","rigid and spiral"],["Vibrio","comma-shaped"]],k=>`What shape is a ${k.toLowerCase()}?`,v=>`Which bacterial shape is ${v}?`,r=>`A ${r[0].toLowerCase()} is ${r[1]}.`),
  ()=>T([["Diplococci","pairs of cocci"],["Streptococci","chains of cocci"],["Staphylococci","grape-like clusters of cocci"],["Tetrads","packets of four cocci"]],k=>`What arrangement do ${k.toLowerCase()} show?`,v=>`Which arrangement consists of ${v}?`,r=>`${r[0]} are ${r[1]}: “diplo” means two, “strepto” a chain, “staphylo” a bunch of grapes.`),
  ()=>{const P=["Staphylococcus aureus","Bacillus subtilis","Streptococcus pyogenes","Clostridium tetani"],N=["Escherichia coli","Pseudomonas aeruginosa","Salmonella typhi","Vibrio cholerae"],pos=coin(.5),o=pos?pick(P):pick(N);
   return M(`After a Gram stain, ${o} appears…`,pos?"Purple (violet)":"Pink or red",["Purple (violet)","Pink or red","Colourless","Green"].filter(x=>x!==(pos?"Purple (violet)":"Pink or red")),pos?`${o} is Gram-positive. Its thick peptidoglycan wall traps the crystal violet–iodine complex, so it stays purple after the alcohol wash.`:`${o} is Gram-negative. Its thin peptidoglycan layer and outer membrane let the alcohol wash out the crystal violet, so it takes up the pink safranin counterstain.`)},
  ()=>either(.5,()=>M(`In Gram staining, which reagent is the decolouriser?`,`Alcohol or acetone`,[`Crystal violet`,`Iodine`,`Safranin`],`The order is crystal violet (primary stain), iodine (mordant), alcohol or acetone (decolouriser) and safranin (counterstain).`),
    ()=>M(`What is the role of iodine in the Gram stain?`,`It acts as a mordant, locking crystal violet inside the cell as a large complex`,[`It kills the bacteria`,`It colours Gram-negative cells pink`,`It dissolves the cell wall`],`Iodine forms a crystal violet–iodine complex that is too big to leave thick Gram-positive walls when alcohol is added.`)),
  ()=>either(.5,()=>M(`Which gene is most widely sequenced to identify and classify bacteria?`,`16S rRNA gene`,[`Insulin gene`,`18S rRNA gene`,`lacZ gene`],`The 16S rRNA gene is present in all bacteria and archaea, has conserved regions to design primers and variable regions that tell species apart.`),
    ()=>{const D=[["Bacteria","Escherichia coli and cyanobacteria"],["Archaea","methanogens, extreme halophiles and thermoacidophiles"],["Eukarya","fungi, plants and animals"]],r=pick(D);return M(`In Woese’s three-domain system, which domain contains ${r[1]}?`,r[0],["Bacteria","Archaea","Eukarya","Viruses"],`${r[0]} contains ${r[1]}. Carl Woese used 16S rRNA sequences to show there are three domains: Bacteria, Archaea and Eukarya. Viruses are not a domain because they are not cells.`)}),
  ()=>{const gc=pick([30,36,40,44,50,56,60,68]);return nat(`A double-stranded DNA has a G+C content of ${gc}%. What percentage of its bases is adenine?`,(100-gc)/2,`A + T = 100 − ${gc} = ${100-gc}%. By Chargaff’s rule A = T, so A = ${100-gc} ÷ 2 = ${(100-gc)/2}%.`)},
  ()=>T([["Streak plate","thins out cells by drawing a loop across the agar in several sectors"],["Spread plate","spreads a measured volume of diluted culture over the agar with a sterile spreader"],["Pour plate","mixes the sample with molten agar at about 45 °C and pours it into a dish"],["Serial dilution","dilutes the sample step by step, for example 1 in 10, until colonies can be counted"]],k=>`What does the ${k.toLowerCase()} method do?`,v=>`Which technique ${v}?`,r=>`The ${r[0].toLowerCase()} method ${r[1]}. Pure cultures come from a single colony, which grows from one cell or cluster.`),
  ()=>{const c=rnd(40,280),d=pick([3,4,5,6]),V2=pick([0.1,1]),ans=r2(c*Math.pow(10,d)/V2/1e6);
   return nat(`${V2} mL of a 10<sup>−${d}</sup> dilution gave ${c} colonies on a plate. How many CFU per mL were in the original sample? Give your answer in millions (10<sup>6</sup>) of CFU/mL, to 2 decimals.`,ans,`CFU/mL = colonies ÷ (dilution × volume plated) = ${c} ÷ (10<sup>−${d}</sup> × ${V2}) = ${c*Math.pow(10,d)/V2}. In millions: ${ans}.`)},
  ()=>T([["Nutrient agar","a general-purpose complex medium for many ordinary bacteria"],["MacConkey agar","selective for Gram-negative bacteria and differential for lactose fermenters, which form pink colonies"],["Blood agar","an enriched, differential medium that shows haemolysis"],["Minimal medium","a defined medium containing only chemically known ingredients in known amounts"],["LB broth","a rich liquid complex medium widely used to grow E. coli"]],k=>`What is ${k}?`,v=>`Which medium is ${v}?`,r=>`${r[0]} is ${r[1]}.`),
  ()=>either(.5,()=>M(`Why is agar used to solidify microbiological media?`,`Very few microbes digest it, it melts near 100 °C and it sets at about 40 °C`,[`It is the best nitrogen source for bacteria`,`It is a vitamin that all bacteria need`,`It kills contaminating microbes`],`Agar is a seaweed polysaccharide. Because most microbes cannot break it down it stays solid, and it can be melted, cooled and poured.`),
    ()=>{const Vm=pick([200,400,500,1000]),a=pick([1.5,2]);return nat(`How many grams of agar are needed to make ${Vm} mL of solid medium containing ${a}% (w/v) agar?`,r2(Vm*a/100),`${a}% w/v means ${a} g per 100 mL. For ${Vm} mL: ${a} × ${Vm} ÷ 100 = ${r2(Vm*a/100)} g.`)}),
  ()=>T([["Autoclave (moist heat)","121 °C at 15 psi for 15–20 minutes"],["Hot-air oven (dry heat)","160–170 °C for about 1–2 hours"],["Membrane filtration","pores of 0.22 µm that remove bacteria from heat-sensitive liquids"],["Ultraviolet light","damages DNA on surfaces and in air, but penetrates poorly"],["Flaming","heating an inoculating loop red hot so it is sterile at once"]],k=>`Sterilisation by ${k.toLowerCase()} uses…`,v=>`Which method uses ${v}?`,r=>`${r[0]}: ${r[1]}.`),
  ()=>{const v=rnd(0,3);
   if(v===0){const a=rnd(6,9),b=rnd(1,4),k=pick([0.5,1,2,0.25]),t=r2((a-b)*2.303/k);return nat(`Heat kills a culture by first-order kinetics, N = N<sub>0</sub>e<sup>−kt</sup>, with k = ${k} min<sup>−1</sup>. How long does it take to fall from 10<sup>${a}</sup> to 10<sup>${b}</sup> cells? (ln 10 = 2.303; answer in minutes to 2 decimals.)`,t,`t = ln(N<sub>0</sub>/N) ÷ k = (${a} − ${b}) × 2.303 ÷ ${k} = ${t} min.`)}
   if(v===1){const D=pick([1,2,3,4,5]),n=rnd(2,5),a=rnd(6,8),m=pick([2,5]);return nat(`The decimal reduction time D of a spore is ${D} min at the sterilising temperature. A sample starts with ${m}×10<sup>${a}</sup> spores. How many survive after ${D*n} min?`,m*Math.pow(10,a-n),`D is the time for a 10-fold (90%) fall. ${D*n} min = ${n} × D, so the count falls by 10<sup>${n}</sup>: ${m}×10<sup>${a}</sup> ÷ 10<sup>${n}</sup> = ${m*Math.pow(10,a-n)}.`)}
   if(v===2){const D=pick([1,2,3,4,5]);return nat(`A heat-resistant spore has D = ${D} min. What is its first-order death rate constant k in min<sup>−1</sup>? (k = 2.303 ÷ D; give 2 decimals.)`,r2(2.303/D),`D = ln 10 ÷ k, so k = 2.303 ÷ ${D} = ${r2(2.303/D)} min<sup>−1</sup>.`)}
   const z=10,D0=pick([1,2,4,5]),n=rnd(1,2),up=coin(.5),T2=121+(up?1:-1)*z*n,ans=up?r2(D0/Math.pow(10,n)):D0*Math.pow(10,n);
   return nat(`A spore has D = ${D0} min at 121 °C and a z-value of ${z} °C (the temperature change that alters D by a factor of 10). What is D at ${T2} °C, in minutes?`,ans,`${up?"Heating":"Cooling"} by ${z*n} °C is ${n} z-value${n>1?"s":""}, so D ${up?"falls":"rises"} by 10<sup>${n}</sup>: ${up?`${D0} ÷ ${Math.pow(10,n)}`:`${D0} × ${Math.pow(10,n)}`} = ${ans} min.`)},
  ()=>{const v=rnd(0,3);
   if(v===0){const N0=pick([100,500,1000,5000]),td=pick([20,30,40]),n=rnd(2,6);return nat(`A culture starts with ${N0} cells and has a doubling time of ${td} min. How many cells are there after ${n*td} min of exponential growth?`,N0*Math.pow(2,n),`${n*td} min is ${n} generations, so N = ${N0} × 2<sup>${n}</sup> = ${N0*Math.pow(2,n)}.`)}
   if(v===1){const N0=pick([100,1000,2000]),td=pick([15,20,30,45]),n=rnd(2,6);return nat(`A culture grows from ${N0} to ${N0*Math.pow(2,n)} cells in ${n*td} minutes of exponential growth. What is the doubling time, in minutes?`,td,`The number of cells rose by ${Math.pow(2,n)} = 2<sup>${n}</sup>, so there were ${n} generations. Doubling time = ${n*td} ÷ ${n} = ${td} min.`)}
   if(v===2){const td=pick([0.25,0.5,1,2]);return nat(`A bacterium doubles every ${td} h. What is its specific growth rate μ in h<sup>−1</sup>? (μ = ln 2 ÷ doubling time, ln 2 = 0.693; give 2 decimals.)`,r2(0.693/td),`μ = 0.693 ÷ ${td} = ${r2(0.693/td)} h<sup>−1</sup>.`)}
   const mx=pick([0.4,0.8,1.2]),Ks=pick([1,2,4]),S=pick([1,2,4,8,12]);return nat(`In the Monod model μ = μ<sub>max</sub>·S ÷ (K<sub>s</sub> + S), μ<sub>max</sub> = ${mx} h<sup>−1</sup> and K<sub>s</sub> = ${Ks} g/L. Find μ at S = ${S} g/L, to 2 decimals.`,r2(mx*S/(Ks+S)),`μ = ${mx} × ${S} ÷ (${Ks} + ${S}) = ${r2(mx*S/(Ks+S))} h<sup>−1</sup>.`)},
  ()=>either(.5,()=>T([["Lag phase","cells adapt and make enzymes, with little or no rise in number"],["Log (exponential) phase","cells divide at a constant, maximum rate"],["Stationary phase","new cells and dying cells balance, so the viable count is constant, as nutrients run out and wastes build up"],["Death phase","viable cells decline because cells die faster than they divide"]],k=>`In a batch culture, what happens in the ${k.toLowerCase()}?`,v=>`Which growth phase is this: ${v}?`,r=>`${r[0]}: ${r[1]}.`),
    ()=>{const F=pick([100,200,250,500]),Vv=pick([500,1000,2000]);return nat(`A chemostat of ${Vv} mL receives fresh medium at ${F} mL/h. At steady state the specific growth rate equals the dilution rate D = F ÷ V. What is μ in h<sup>−1</sup>? (2 decimals.)`,r2(F/Vv),`D = F ÷ V = ${F} ÷ ${Vv} = ${r2(F/Vv)} h<sup>−1</sup>, and at steady state μ = D.`)})
 ],
 /* ---------- Unit 3: Biomolecules ---------- */
 3:[
  ()=>T([["Glycine","is the simplest amino acid: its R group is just H, so it is not chiral"],["Cysteine","has an −SH group that can form disulfide bridges"],["Proline","is a cyclic imino acid that bends the polypeptide chain"],["Lysine","has a positively charged (basic) side chain"],["Aspartic acid","has a negatively charged (acidic) side chain"],["Phenylalanine","has a nonpolar aromatic side chain with a benzene ring"],["Serine","has a polar side chain with an −OH group"]],k=>`Which fact is true of ${k.toLowerCase()}?`,v=>`Which amino acid ${v}?`,r=>`${r[0]} ${r[1]}.`),
  ()=>M(`What is attached to the α-carbon of a standard amino acid?`,`An amino group, a carboxyl group, a hydrogen atom and an R group`,[`Two amino groups, a carboxyl group and an R group`,`A phosphate group, a sugar, a hydrogen atom and an R group`,`An amino group, two carboxyl groups and a hydrogen atom`],`All 20 standard amino acids share this backbone; only the side chain (R group) differs.`),
  ()=>{const n=rnd(3,60);return either(.5,()=>nat(`How many peptide bonds are in a linear polypeptide made of ${n} amino acids?`,n-1,`Each bond joins two neighbouring residues, so n residues give n − 1 bonds: ${n} − 1 = ${n-1}.`),
    ()=>nat(`How many water molecules are released when ${n} amino acids join into one linear chain?`,n-1,`Each peptide bond forms by condensation and releases one water molecule, so ${n} residues release ${n-1}.`))},
  ()=>{const A=[["Gly",75],["Ala",89],["Ser",105],["Val",117],["Leu",131],["Asp",133]],n=rnd(2,4),s=shuffle(A).slice(0,n),tot=s.reduce((x,y)=>x+y[1],0)-18*(n-1);
   return nat(`Free amino acid masses (in daltons): Gly 75, Ala 89, Ser 105, Val 117, Leu 131, Asp 133. What is the mass of the peptide ${s.map(x=>x[0]).join("–")}? (Water = 18 Da.)`,tot,`Add the free amino acids: ${s.map(x=>x[1]).join(" + ")} = ${tot+18*(n-1)}. Then subtract ${n-1} water molecules (${n-1} × 18 = ${18*(n-1)}): ${tot} Da.`)},
  ()=>either(.5,()=>M(`A peptide bond forms between…`,`the carboxyl group of one amino acid and the amino group of the next, with loss of water`,[`the two R groups, with loss of water`,`the two amino groups, with loss of ammonia`,`two carboxyl groups, with loss of CO<sub>2</sub>`],`This is a condensation (dehydration) reaction that makes a −CO−NH− link.`),
    ()=>M(`Which bonds stabilise an α-helix?`,`Hydrogen bonds between backbone C=O and N−H groups`,[`Peptide bonds between distant residues`,`Phosphodiester bonds`,`Glycosidic bonds`],`In an α-helix each backbone C=O hydrogen-bonds to an N−H four residues further along. This is secondary structure.`)),
  ()=>T([["Primary structure","the linear sequence of amino acids joined by peptide bonds"],["Secondary structure","local folding into α-helices and β-sheets held by backbone hydrogen bonds"],["Tertiary structure","the overall 3D fold of one polypeptide, held by R-group interactions such as disulfide bridges, ionic and hydrophobic interactions"],["Quaternary structure","the assembly of two or more polypeptide subunits, as in haemoglobin"]],k=>`What does the ${k.toLowerCase()} of a protein describe?`,v=>`Which level of protein structure is ${v}?`,r=>`${r[0]}: ${r[1]}.`),
  ()=>either(.5,()=>nat(`Adult haemoglobin is a tetramer of 2 α and 2 β chains. How many polypeptide chains are in one molecule?`,4,`2 α + 2 β = 4 polypeptides, which is why haemoglobin has quaternary structure.`),
    ()=>M(`When a protein is denatured by heat or extreme pH, which level of structure is normally left intact?`,`Primary structure (the peptide bonds and sequence)`,[`Secondary structure`,`Tertiary structure`,`Quaternary structure`],`Denaturation breaks the weak bonds behind secondary, tertiary and quaternary structure, but the strong covalent peptide bonds stay, so the sequence is unchanged.`)),
  ()=>T([["Nucleotide","a phosphate group, a pentose sugar and a nitrogenous base"],["Nucleoside","a pentose sugar and a nitrogenous base, with no phosphate"],["Purines","adenine and guanine, which have a double-ring structure"],["Pyrimidines","cytosine, thymine and uracil, which have a single-ring structure"]],k=>`What ${k==="Nucleotide"||k==="Nucleoside"?`is a ${k.toLowerCase()} made of`:`are the ${k.toLowerCase()}`}?`,v=>`Which term describes ${v}?`,r=>`${r[0]}: ${r[1]}.`),
  ()=>{const v=rnd(0,3);
   if(v===0){const x=pick([20,22,25,30,35]);return nat(`A double-stranded DNA sample contains ${x}% adenine. What percentage is guanine?`,50-x,`A = T = ${x}%, so G + C = ${100-2*x}%, and since G = C each is ${50-x}%.`)}
   if(v===1){const N=pick([500,1000,2000]),x=pick([20,25,30,35]);return nat(`A DNA fragment has ${N} base pairs and ${x}% of its bases are adenine. How many guanine bases does it contain?`,2*N*(50-x)/100,`Bases in total = ${2*N}. G = (50 − ${x})% = ${50-x}% of ${2*N} = ${2*N*(50-x)/100}.`)}
   if(v===2){const a=rnd(10,60),g=rnd(10,60);return nat(`A short DNA segment has ${a} A–T base pairs and ${g} G–C base pairs. How many hydrogen bonds hold the two strands together?`,2*a+3*g,`A–T pairs have 2 hydrogen bonds and G–C pairs have 3: 2 × ${a} + 3 × ${g} = ${2*a+3*g}.`)}
   const N=pick([100,200,500,1000]),p=pick([40,50,60]);return nat(`A ${N} bp DNA molecule has ${p}% G+C content. How many hydrogen bonds does it contain in total?`,2*N+N*p/100,`GC pairs = ${p}% of ${N} = ${N*p/100}; AT pairs = ${N-N*p/100}. Bonds = 2 × ${N-N*p/100} + 3 × ${N*p/100} = ${2*N+N*p/100}.`)},
  ()=>T([["DNA","contains deoxyribose and thymine and is usually double-stranded"],["mRNA","contains ribose and uracil and carries the coding message to the ribosome"],["tRNA","is a clover-leaf shaped RNA that carries an amino acid to the ribosome"],["rRNA","is the RNA part of ribosomes and helps form peptide bonds"]],k=>`Which description fits ${k}?`,v=>`Which nucleic acid ${v}?`,r=>`${r[0]} ${r[1]}.`),
  ()=>either(.5,()=>M(`Which disaccharide is made of glucose and fructose?`,`Sucrose`,[`Lactose`,`Maltose`,`Cellulose`],`Sucrose = glucose + fructose. Lactose = glucose + galactose. Maltose = glucose + glucose. Cellulose is a polysaccharide.`),
    ()=>{const D=[["Sucrose","glucose + fructose"],["Lactose","glucose + galactose"],["Maltose","glucose + glucose"]],r=pick(D);return M(`What is ${r[0].toLowerCase()} made of?`,r[1],["glucose + fructose","glucose + galactose","glucose + glucose","fructose + galactose","galactose + galactose"],`${r[0]} is ${r[1]}, joined by a glycosidic bond with loss of one water molecule.`)}),
  ()=>either(.5,()=>T([["Starch","the energy store of plants, made of α-glucose"],["Glycogen","the highly branched energy store of animals and fungi"],["Cellulose","a structural polymer of β-glucose in plant cell walls"],["Chitin","a structural polymer of N-acetylglucosamine in fungal walls and insect exoskeletons"]],k=>`What is ${k.toLowerCase()}?`,v=>`Which polysaccharide is ${v}?`,r=>`${r[0]} is ${r[1]}.`),
    ()=>{const n=rnd(2,10);return either(.5,()=>nat(`How many water molecules are released when ${n} glucose molecules join into one unbranched chain?`,n-1,`Each glycosidic bond releases one water, and ${n} units need ${n-1} bonds.`),
      ()=>nat(`Glucose has a mass of 180 Da and water 18 Da. What is the mass of a linear chain of ${n} glucose units?`,180*n-18*(n-1),`${n} × 180 = ${180*n}, minus ${n-1} × 18 = ${18*(n-1)}, gives ${180*n-18*(n-1)} Da.`))}),
  ()=>either(.5,()=>T([["Triglyceride","glycerol joined to three fatty acids by ester bonds, the main energy-storage fat"],["Phospholipid","glycerol, two fatty acids and a phosphate head, so it is amphipathic and forms membranes"],["Cholesterol","a steroid that adjusts membrane fluidity and is the parent of steroid hormones"],["Wax","a long-chain fatty acid joined to a long-chain alcohol, giving a waterproof coating"]],k=>`What is a ${k.toLowerCase()}?`,v=>`Which lipid is ${v}?`,r=>`A ${r[0].toLowerCase()} is ${r[1]}.`),
    ()=>{const f=rnd(5,40),c=rnd(20,80),p=rnd(10,40);return nat(`Using 9 kcal/g for fat and 4 kcal/g for carbohydrate and for protein, how much energy is in a food with ${f} g fat, ${c} g carbohydrate and ${p} g protein?`,9*f+4*c+4*p,`Energy = 9 × ${f} + 4 × ${c} + 4 × ${p} = ${9*f} + ${4*c} + ${4*p} = ${9*f+4*c+4*p} kcal.`)}),
  ()=>either(.5,()=>{const C=[["Oxidoreductase",1,"transfers electrons or hydrogen atoms, for example dehydrogenases"],["Transferase",2,"moves a functional group from one molecule to another, for example kinases"],["Hydrolase",3,"splits bonds by adding water, for example amylase and proteases"],["Lyase",4,"breaks bonds without water or oxidation, often leaving a double bond"],["Isomerase",5,"rearranges atoms within one molecule"],["Ligase",6,"joins two molecules using ATP, for example DNA ligase"]],r=pick(C);
      return either(.5,()=>M(`Which enzyme class ${r[2]}?`,r[0],C.map(x=>x[0]),`${r[0]}s (EC ${r[1]}) ${r[2]}.`),()=>nat(`Enzymes are numbered by the Enzyme Commission (EC) from 1 to 6: oxidoreductases, transferases, hydrolases, lyases, isomerases, ligases. Which EC class number do ${r[0].toLowerCase()}s belong to?`,r[1],`In the standard order ${r[0]}s are class ${r[1]}.`))},
    ()=>{const v=rnd(0,2);
      if(v===0){const Vm=pick([20,40,50,100]),Km=pick([2,5,10]),S=pick([1,2,4,5,10,20]);return nat(`An enzyme obeys v = V<sub>max</sub>·S ÷ (K<sub>m</sub> + S) with V<sub>max</sub> = ${Vm} µmol/min and K<sub>m</sub> = ${Km} mM. What is v at S = ${S} mM? (2 decimals.)`,r2(Vm*S/(Km+S)),`v = ${Vm} × ${S} ÷ (${Km} + ${S}) = ${r2(Vm*S/(Km+S))} µmol/min.`)}
      if(v===1){const Vm=pick([20,40,60,100]);return nat(`When the substrate concentration equals K<sub>m</sub>, the rate is ${Vm/2} µmol/min. What is V<sub>max</sub> in µmol/min?`,Vm,`At S = K<sub>m</sub>, v = V<sub>max</sub>/2. So V<sub>max</sub> = 2 × ${Vm/2} = ${Vm} µmol/min.`)}
      const I=[["competitive","V<sub>max</sub> stays the same and the apparent K<sub>m</sub> rises"],["non-competitive","V<sub>max</sub> falls and K<sub>m</sub> stays the same"],["uncompetitive","both V<sub>max</sub> and K<sub>m</sub> fall"]],r=pick(I);return M(`What happens to the kinetics in ${r[0]} inhibition?`,r[1],I.map(x=>x[1]).concat(["V<sub>max</sub> rises and K<sub>m</sub> falls"]),`In ${r[0]} inhibition, ${r[1]}.`)}),
  ()=>either(.5,()=>M(`How does an enzyme speed up a reaction?`,`It lowers the activation energy without changing ΔG or the equilibrium position`,[`It raises the temperature of the reaction`,`It makes ΔG more negative`,`It is used up as the reaction proceeds`],`An enzyme gives an easier route (lower activation energy) but the start and end energies, and so ΔG and the equilibrium constant, stay the same. The enzyme is regenerated.`),
    ()=>M(`Which digestive enzyme works best at a strongly acidic pH of about 2?`,`Pepsin`,[`Trypsin`,`Salivary amylase`,`Pancreatic lipase`],`Pepsin works in the acid stomach. Trypsin and pancreatic lipase prefer the mildly alkaline small intestine, and salivary amylase prefers near-neutral pH.`))
 ],
 /* ---------- Unit 4: Genetic information and heredity ---------- */
 4:[
  ()=>T([["Griffith (1928)","showed that heat-killed virulent bacteria could transform harmless bacteria into virulent ones"],["Avery, MacLeod and McCarty (1944)","showed that the transforming principle is DNA"],["Hershey and Chase (1952)","used radioactive phosphorus and sulphur in phages to show that DNA is the genetic material"],["Meselson and Stahl (1958)","used heavy nitrogen to show that DNA replication is semi-conservative"],["Watson and Crick (1953)","proposed the double-helix model of DNA"]],k=>`Which discovery is linked to ${k}?`,v=>`Which experiment or work ${v}?`,r=>`${r[0]} ${r[1]}.`),
  ()=>either(.5,()=>M(`In the Hershey–Chase experiment, which radioactive label marked the phage DNA?`,`<sup>32</sup>P`,[`<sup>35</sup>S`,`<sup>14</sup>C`,`<sup>3</sup>H`],`DNA contains phosphorus but no sulphur, so <sup>32</sup>P labels DNA. Proteins contain sulphur (in cysteine and methionine) but no phosphorus, so <sup>35</sup>S labels protein. The radioactive phosphorus entered the bacteria.`),
    ()=>{const n=rnd(2,6);return nat(`One <sup>15</sup>N/<sup>15</sup>N DNA molecule is grown in <sup>14</sup>N medium for ${n} generations. How many of the resulting DNA molecules are fully light (<sup>14</sup>N/<sup>14</sup>N)?`,Math.pow(2,n)-2,`After ${n} generations there are 2<sup>${n}</sup> = ${Math.pow(2,n)} molecules. Semi-conservative replication keeps the two original heavy strands in exactly 2 hybrid molecules. The rest, ${Math.pow(2,n)} − 2 = ${Math.pow(2,n)-2}, are fully light.`)}),
  ()=>T([["Replication","DNA → DNA, made by DNA polymerase"],["Transcription","DNA → RNA, made by RNA polymerase"],["Translation","mRNA → protein, carried out on the ribosome"],["Reverse transcription","RNA → DNA, made by reverse transcriptase in retroviruses such as HIV"]],k=>`What is the flow of information in ${k.toLowerCase()}?`,v=>`Which process is ${v}?`,r=>`${r[0]}: ${r[1]}.`),
  ()=>either(.5,()=>M(`Which enzyme makes RNA from a DNA template?`,`RNA polymerase`,[`DNA polymerase`,`Reverse transcriptase`,`DNA ligase`],`RNA polymerase reads the template strand and builds a complementary RNA chain in the 5′→3′ direction.`),
    ()=>M(`In which direction is mRNA read by the ribosome?`,`5′ → 3′`,[`3′ → 5′`,`Both directions at once`,`It has no fixed direction`],`mRNA is made and read in the 5′→3′ direction, and the ribosome moves along it codon by codon.`)),
  ()=>{let t;do{t=rndBases(6)}while(!(/A/.test(t)&&/T/.test(t)&&/[CG]/.test(t)));const m=[...t].map(b=>COMP[b]).join(""),same=t.replace(/T/g,"U"),rev=[...m].reverse().join(""),dna=[...t].map(b=>({A:"T",T:"A",C:"G",G:"C"})[b]).join("");
   return M(`The template strand of a gene reads 3′-${t}-5′. What is the mRNA made from it, written 5′→3′?`,`5′-${m}-3′`,[`5′-${dna}-3′`,`5′-${same}-3′`,`5′-${rev}-3′`,`5′-${t}-3′`,`5′-${[...dna].reverse().join("")}-3′`],`RNA polymerase pairs A with U, T with A, C with G and G with C, reading the template 3′→5′. That gives 5′-${m}-3′. (The template itself, T for U, or the reversed order are common slips.)`)},
  ()=>{const cs=Object.keys(CODON),c=pick(cs),a=CODON[c];return M(`Which amino acid does the mRNA codon ${c} code for?`,a,AA_NAMES,`${c} codes for ${a.toLowerCase()}.`)},
  ()=>{const n=rnd(2,7),body=Array.from({length:n},()=>pick(Object.keys(CODON).filter(x=>x!=="AUG"))),stop=pick(["UAA","UAG","UGA"]),m=["AUG",...body,stop].join(" ");
   return nat(`A ribosome reads the mRNA 5′-${m}-3′. How many amino acids are in the polypeptide it makes?`,n+1,`Translation starts at AUG (methionine) and each following sense codon adds one amino acid. The stop codon ${stop} adds none. Codons before the stop: ${n+1}, so ${n+1} amino acids.`)},
  ()=>either(.5,()=>{const k=pick([2,3,4]);return nat(`How many different codons are possible if each codon is made of ${k} bases chosen from A, U, G and C?`,Math.pow(4,k),`Each position can hold 4 bases, so there are 4<sup>${k}</sup> = ${Math.pow(4,k)} combinations. ${k===3?"The real code uses triplets: 64 codons for 20 amino acids and stop signals.":k===2?"That is too few for 20 amino acids, so the code must be longer.":""}`)},
    ()=>{const n=rnd(50,600);return nat(`A gene’s coding region specifies a protein of ${n} amino acids. How many nucleotides are in the mRNA coding region, counting the stop codon?`,3*(n+1),`Each amino acid needs one codon of 3 nucleotides, and the stop codon adds one more codon: 3 × (${n} + 1) = ${3*(n+1)}.`)}),
  ()=>either(.5,()=>S(`Which of these amino acids are encoded by only ONE codon?`,[`Methionine`,`Tryptophan`],[`Leucine`,`Serine`,`Arginine`,`Glycine`,`Alanine`],2,2,`Only methionine (AUG) and tryptophan (UGG) have a single codon. Leucine, serine and arginine have six each; glycine and alanine have four each.`),
    ()=>M(`What does it mean that the genetic code is “degenerate”?`,`More than one codon can specify the same amino acid`,[`Each codon specifies more than one amino acid`,`The code changes from one organism to another`,`Codons overlap along the mRNA`],`With 61 sense codons for 20 amino acids, most amino acids have several codons. The code is not ambiguous, because each codon gives one amino acid.`)),
  ()=>either(.5,()=>M(`What does “universal” mean for the genetic code?`,`Nearly all organisms use the same codons for the same amino acids`,[`Every codon codes for a different amino acid`,`Only prokaryotes use it`,`It is read in both directions`],`Because the code is shared, a human gene such as insulin can be read correctly by E. coli. Minor exceptions exist, for example UGA codes for tryptophan in mitochondria.`),
    ()=>T([["Silent mutation","changes a codon to a synonymous one, so the amino acid stays the same"],["Missense mutation","changes a codon so that a different amino acid is inserted"],["Nonsense mutation","changes a sense codon into a stop codon, so the protein is cut short"],["Frameshift mutation","adds or removes nucleotides in a number not divisible by three, changing every later codon"]],k=>`What is a ${k.toLowerCase()}?`,v=>`Which type of mutation ${v}?`,r=>`A ${r[0].toLowerCase()} ${r[1]}.`)),
  ()=>T([["Gene","a segment of DNA that codes for a functional product, a protein or an RNA"],["Allele","one of the alternative forms of a gene at the same locus"],["Genotype","the genetic makeup of an organism, for example Aa"],["Phenotype","the observable characteristics of an organism"],["Homozygous","carrying two identical alleles of a gene, for example AA or aa"],["Heterozygous","carrying two different alleles of a gene, for example Aa"],["Locus","the fixed position of a gene on a chromosome"]],k=>`What does the term “${k.toLowerCase()}” mean?`,v=>`Which term means ${v}?`,r=>`${r[0]} means ${r[1]}.`),
  ()=>{const P=[["tall","dwarf"],["round seeds","wrinkled seeds"],["yellow seeds","green seeds"],["purple flowers","white flowers"]],r=pick(P);
   return M(`In pea plants ${r[0]} is dominant over ${r[1]}. What is the phenotype of a heterozygous plant?`,r[0],[r[1],`A blend of ${r[0]} and ${r[1]}`,`Half of the plants are ${r[0]} and half ${r[1]}`],`In complete dominance the dominant allele hides the recessive one in a heterozygote, so a heterozygous plant shows the dominant trait: ${r[0]}.`)},
  ()=>{const N=pick([400,800,1200,1600,2000]),v=rnd(0,2);
   if(v===0)return nat(`Two heterozygous pea plants (Aa × Aa) produce ${N} offspring. How many are expected to show the recessive phenotype?`,N/4,`The cross gives 1 AA : 2 Aa : 1 aa, so ¼ are aa: ${N} ÷ 4 = ${N/4}.`);
   if(v===1)return nat(`Two heterozygous pea plants (Aa × Aa) produce ${N} offspring. How many are expected to show the dominant phenotype?`,3*N/4,`The phenotypic ratio is 3 dominant : 1 recessive, so ¾ of ${N} = ${3*N/4}.`);
   return nat(`In an AaBb × AaBb dihybrid cross with ${N} offspring, how many are expected to show BOTH recessive traits (aabb)?`,N/16,`The dihybrid ratio is 9 : 3 : 3 : 1, and the double recessive is 1 part in 16: ${N} ÷ 16 = ${N/16}.`)},
  ()=>either(.5,()=>{const n=rnd(1,4);return oneOf(()=>nat(`An individual is heterozygous at ${n} independent gene pair${n>1?"s":""} (AaBb… with ${n} pair${n>1?"s":""}). How many different types of gametes can it make?`,Math.pow(2,n),`Each heterozygous pair gives 2 kinds of allele in the gametes, so ${n} pair${n>1?"s":""} give 2<sup>${n}</sup> = ${Math.pow(2,n)} kinds.`),
      ()=>nat(`Two individuals heterozygous at ${n} independent gene pair${n>1?"s":""} are crossed, with complete dominance. How many different phenotypes are possible among the offspring?`,Math.pow(2,n),`Each pair gives 2 phenotypes (dominant or recessive), so ${n} pair${n>1?"s":""} give 2<sup>${n}</sup> = ${Math.pow(2,n)}.`),
      ()=>nat(`Two individuals heterozygous at ${n} independent gene pair${n>1?"s":""} are crossed. How many different genotypes are possible among the offspring?`,Math.pow(3,n),`Each pair gives 3 genotypes (AA, Aa, aa), so ${n} pair${n>1?"s":""} give 3<sup>${n}</sup> = ${Math.pow(3,n)}.`))},
    ()=>T([["Law of dominance","when two different alleles are present, the dominant one decides the phenotype"],["Law of segregation","the two alleles of a gene separate during gamete formation, so each gamete carries only one"],["Law of independent assortment","alleles of different genes (on different chromosomes) are sorted into gametes independently of one another"],["Test cross","crossing an individual of dominant phenotype with a homozygous recessive to find its genotype"]],k=>`What does Mendel’s ${k.toLowerCase()==="test cross"?"test cross":k.toLowerCase()} say or do?`,v=>`Which is it: ${v}?`,r=>`${r[0]}: ${r[1]}.`)),
  ()=>oneOf(()=>M(`How many pairs of contrasting characters did Mendel study in the garden pea?`,`7`,[`2`,`4`,`14`],`Mendel followed seven pairs of contrasting traits in Pisum sativum, such as tall/dwarf and round/wrinkled seeds.`),
    ()=>M(`In which year did Mendel publish his pea experiments?`,`1866`,[`1856`,`1900`,`1953`],`Mendel began the work in 1856 and published in 1866. It was ignored until de Vries, Correns and Tschermak rediscovered it in 1900.`),
    ()=>{const B=[["I<sup>A</sup>I<sup>A</sup> or I<sup>A</sup>i","A"],["I<sup>B</sup>I<sup>B</sup> or I<sup>B</sup>i","B"],["I<sup>A</sup>I<sup>B</sup>","AB"],["ii","O"]],r=pick(B);return M(`Which ABO blood group results from the genotype ${r[0]}?`,r[1],["A","B","AB","O"],`I<sup>A</sup> and I<sup>B</sup> are codominant and both dominant over i. ${r[1]==="AB"?"So I<sup>A</sup>I<sup>B</sup> shows both A and B antigens, giving group AB.":r[1]==="O"?"Only ii has neither antigen, so it gives group O.":`So ${r[0]} gives group ${r[1]}.`}`)})
 ],
 /* ---------- Unit 5: Metabolism and bioenergetics ---------- */
 5:[
  ()=>{const P=[["photosynthesis","Anabolic (builds molecules, uses energy)"],["protein synthesis","Anabolic (builds molecules, uses energy)"],["DNA replication","Anabolic (builds molecules, uses energy)"],["glycogen synthesis from glucose","Anabolic (builds molecules, uses energy)"],["glycolysis","Catabolic (breaks molecules down, releases energy)"],["the Krebs cycle","Catabolic (breaks molecules down, releases energy)"],["β-oxidation of fatty acids","Catabolic (breaks molecules down, releases energy)"],["digestion of starch into glucose","Catabolic (breaks molecules down, releases energy)"]],r=pick(P);
   return M(`Is ${r[0]} anabolic or catabolic?`,r[1],["Anabolic (builds molecules, uses energy)","Catabolic (breaks molecules down, releases energy)","Neither: it only moves molecules across a membrane","Both, in equal amounts"],`${r[1].startsWith("Ana")?"It builds larger molecules from smaller ones, which needs energy (usually ATP).":"It breaks larger molecules into smaller ones and releases energy."}`)},
  ()=>either(.5,()=>M(`What does the second law of thermodynamics say?`,`The entropy (disorder) of the universe increases in every spontaneous process`,[`Energy can be created but not destroyed`,`The energy of the universe keeps falling`,`All reactions reach equilibrium instantly`],`Living things stay ordered only by using energy and releasing heat and waste, which raises the entropy of their surroundings by more than the order they create.`),
    ()=>M(`What does the first law of thermodynamics say?`,`Energy cannot be created or destroyed, only converted from one form to another`,[`Entropy always decreases`,`Heat flows from cold to hot`,`Living things create energy`],`Cells convert energy (light to chemical, chemical to mechanical) but never make it from nothing.`)),
  ()=>{const dH=pick([-60,-40,-20,0,20,40,60]),dS=pick([-100,-50,50,100,150,200]),T2=pick([298,300,310]),g=r2(dH-T2*dS/1000);
   return either(.6,()=>nat(`A reaction has ΔH = ${neg(dH)} kJ/mol and ΔS = ${neg(dS)} J/(mol·K). Find ΔG in kJ/mol at ${T2} K. (ΔG = ΔH − TΔS; 2 decimals.)`,g,`Convert ΔS to kJ: ${neg(dS)} J = ${neg(dS/1000)} kJ. ΔG = ${neg(dH)} − ${T2} × (${neg(dS/1000)}) = ${neg(g)} kJ/mol.`),
    ()=>M(`A reaction has ΔH = ${neg(dH)} kJ/mol and ΔS = ${neg(dS)} J/(mol·K) at ${T2} K. Is it spontaneous?`,g<0?"Yes, ΔG is negative":g>0?"No, ΔG is positive":"It is exactly at equilibrium (ΔG = 0)",["Yes, ΔG is negative","No, ΔG is positive","It is exactly at equilibrium (ΔG = 0)","Cannot be told without the activation energy"],`ΔG = ΔH − TΔS = ${neg(dH)} − ${T2} × ${neg(dS/1000)} = ${neg(g)} kJ/mol. ${g<0?"Negative ΔG means spontaneous (exergonic).":g>0?"Positive ΔG means it does not proceed on its own (endergonic).":"ΔG = 0 is equilibrium."} Activation energy affects speed, not spontaneity.`))},
  ()=>{const TT=pick([300,350,400]),dS=pick([100,150,200]),dH=TT*dS/1000;return nat(`A reaction has ΔH = ${dH} kJ/mol and ΔS = ${dS} J/(mol·K). At what temperature in kelvin is ΔG = 0? (T = ΔH ÷ ΔS.)`,TT,`ΔG = 0 when ΔH = TΔS, so T = ${dH} × 1000 ÷ ${dS} = ${TT} K.`)},
  ()=>{const P=[["ATP hydrolysis","Exergonic (ΔG &lt; 0)"],["Oxidation of glucose in respiration","Exergonic (ΔG &lt; 0)"],["Sodium ions moving down their gradient","Exergonic (ΔG &lt; 0)"],["Photosynthesis (making glucose from CO<sub>2</sub> and water)","Endergonic (ΔG &gt; 0)"],["Protein synthesis from amino acids","Endergonic (ΔG &gt; 0)"],["Active transport of ions against their gradient","Endergonic (ΔG &gt; 0)"]],r=pick(P);
   return M(`Is this process exergonic or endergonic: ${r[0].toLowerCase()==="atp hydrolysis"?"ATP hydrolysis":r[0]}?`,r[1],["Exergonic (ΔG &lt; 0)","Endergonic (ΔG &gt; 0)","At equilibrium (ΔG = 0)","Energy-neutral, with no free-energy change at all"],`${r[1].startsWith("Exer")?"It releases free energy and can drive other reactions.":"It needs an input of free energy, usually supplied by ATP or light."}`)},
  ()=>either(.5,()=>T([["Adenosine triphosphate","adenine + ribose + three phosphate groups"],["ATP hydrolysis","ATP + H<sub>2</sub>O → ADP + P<sub>i</sub>, releasing about 30.5 kJ/mol under standard conditions"],["Substrate-level phosphorylation","direct transfer of a phosphate group from a substrate to ADP, as in glycolysis"],["Oxidative phosphorylation","ATP made using the proton gradient built by the electron transport chain"]],k=>`Which statement is correct for ${k==='Adenosine triphosphate'?'ATP':k.toLowerCase()}?`,v=>`Which term means ${v}?`,r=>`${r[0]}: ${r[1]}.`),
    ()=>either(.5,()=>{const n=rnd(2,20);return nat(`If hydrolysing 1 mol of ATP releases 30.5 kJ, how much energy is released by ${n} mol? (kJ)`,r2(30.5*n),`30.5 × ${n} = ${r2(30.5*n)} kJ.`)},
      ()=>{const x=pick([10,14,20,25]),net=r2(x-30.5);return nat(`A reaction has ΔG = +${x} kJ/mol. It is coupled to ATP hydrolysis (ΔG = −30.5 kJ/mol). What is the net ΔG of the coupled process in kJ/mol?`,net,`Add the two free-energy changes: +${x} + (−30.5) = ${neg(net)} kJ/mol. It is negative, so the coupled process is spontaneous.`)})),
  ()=>{const n=rnd(1,12),v=rnd(0,3);const W=[["net ATP molecules",2],["NADH molecules",2],["pyruvate molecules",2],["ATP molecules used up in the investment phase",2],["ATP molecules made in total (gross) in the payoff phase",4]],r=W[v];
   return nat(`How many ${r[0]} does glycolysis make (or use) from ${n} glucose molecule${n>1?"s":""}?`,r[1]*n,`Per glucose glycolysis gives ${r[1]} ${r[0]}. For ${n} glucose: ${r[1]} × ${n} = ${r[1]*n}. (It spends 2 ATP, makes 4 ATP, so net 2 ATP, plus 2 NADH and 2 pyruvate.)`)},
  ()=>either(.5,()=>T([["Hexokinase","phosphorylates glucose to glucose-6-phosphate using ATP"],["Phosphofructokinase-1","is the main regulatory, rate-limiting enzyme of glycolysis"],["Pyruvate kinase","transfers a phosphate from phosphoenolpyruvate to ADP, making pyruvate and ATP"],["Lactate dehydrogenase","reduces pyruvate to lactate and regenerates NAD<sup>+</sup>"]],k=>`Which statement is true of ${k} in glycolysis?`,v=>`Which enzyme ${v}?`,r=>`${r[0]} ${r[1]}.`),
    ()=>{const P=[["most cells with plenty of oxygen","It is converted to acetyl-CoA and enters the Krebs cycle"],["muscle cells working without enough oxygen","It is reduced to lactate"],["yeast cells growing without oxygen","It is converted to ethanol and CO<sub>2</sub>"]],r=pick(P);return M(`What is the usual fate of pyruvate in ${r[0]}?`,r[1],P.map(x=>x[1]).concat(["It is converted back into glucose in the cytoplasm"]),`${r[1]}. In fermentation this step regenerates NAD<sup>+</sup>, so glycolysis can carry on making its 2 net ATP.`)}),
  ()=>{const n=rnd(1,8),W=[["NADH molecules do the Krebs cycle turns make",6,"Two turns of the cycle (one per acetyl-CoA), each giving 3 NADH."],["FADH<sub>2</sub> molecules do the Krebs cycle turns make",2,"One FADH<sub>2</sub> per turn, two turns per glucose."],["ATP (or GTP) molecules does the Krebs cycle make directly",2,"One ATP or GTP per turn by substrate-level phosphorylation, two turns per glucose."],["CO<sub>2</sub> molecules does the Krebs cycle release",4,"Two CO<sub>2</sub> per turn, two turns per glucose."],["CO<sub>2</sub> molecules are released in total when glucose is completely oxidised (pyruvate step plus Krebs cycle)",6,"2 from the pyruvate-to-acetyl-CoA step and 4 from the Krebs cycle: all 6 carbons of glucose leave as CO<sub>2</sub>."],["NADH molecules are made in total by glycolysis, the pyruvate step and the Krebs cycle",10,"2 from glycolysis, 2 from the pyruvate step and 6 from the Krebs cycle."]],r=pick(W);
   return nat(`How many ${r[0]} from ${n} glucose molecule${n>1?"s":""}?`,r[1]*n,`${r[2]} Per glucose: ${r[1]}. For ${n}: ${r[1]} × ${n} = ${r[1]*n}.`)},
  ()=>either(.5,()=>M(`Which 4-carbon compound combines with acetyl-CoA at the start of the Krebs cycle?`,`Oxaloacetate`,[`Pyruvate`,`Citrate`,`Succinate`],`Acetyl-CoA (2 C) joins oxaloacetate (4 C) to form citrate (6 C). Oxaloacetate is regenerated at the end of the cycle.`),
    ()=>M(`How much NADH, FADH<sub>2</sub> and ATP does one turn of the Krebs cycle make?`,`3 NADH, 1 FADH<sub>2</sub> and 1 ATP (or GTP)`,[`1 NADH, 3 FADH<sub>2</sub> and 1 ATP`,`3 NADH, 3 FADH<sub>2</sub> and 3 ATP`,`2 NADH, 2 FADH<sub>2</sub> and 2 ATP`],`One acetyl-CoA is fully oxidised per turn: 3 NADH, 1 FADH<sub>2</sub>, 1 ATP/GTP and 2 CO<sub>2</sub>.`)),
  ()=>T([["Glycolysis","the cytosol (cytoplasm)"],["Pyruvate to acetyl-CoA, and the Krebs cycle","the mitochondrial matrix"],["Electron transport chain and ATP synthase","the inner mitochondrial membrane"],["Calvin cycle","the stroma of the chloroplast"],["Light reactions of photosynthesis","the thylakoid membranes"]],k=>`Where does this stage happen: ${k}?`,v=>`Which stage happens in ${v}?`,r=>`${r[0]} occurs in ${r[1]}.`),
  ()=>{const n=rnd(1,6),pr=pick([[2.5,1.5],[3,2]]),tot=10*pr[0]+2*pr[1]+4;
   return nat(`Complete oxidation of one glucose gives 10 NADH, 2 FADH<sub>2</sub> and 4 ATP by substrate-level phosphorylation. If each NADH yields ${pr[0]} ATP and each FADH<sub>2</sub> yields ${pr[1]} ATP, how many ATP come from ${n} glucose molecule${n>1?"s":""}? (Ignore the cost of shuttles.)`,tot*n,`Per glucose: 10 × ${pr[0]} + 2 × ${pr[1]} + 4 = ${10*pr[0]} + ${2*pr[1]} + 4 = ${tot} ATP. For ${n}: ${tot} × ${n} = ${tot*n}. (Newer values, 2.5 and 1.5, give 32 per glucose, and shuttle costs bring it to 30–32 in cells; older textbooks used 3 and 2, giving 38.)`)},
  ()=>either(.5,()=>M(`Why do cells ferment pyruvate when oxygen is absent?`,`To regenerate NAD<sup>+</sup> so that glycolysis can keep making a small amount of ATP`,[`To make more NADH for the electron transport chain`,`To produce a large amount of ATP`,`To convert lactate back into glucose`],`Glycolysis needs NAD<sup>+</sup>. Without oxygen the electron transport chain cannot recycle it, so fermentation does, allowing 2 net ATP per glucose.`),
    ()=>{const W=[["oxygen molecules are used up",6],["water molecules are produced",6],["carbon dioxide molecules are produced",6]],r=pick(W),n=rnd(1,5);return nat(`In the balanced equation for aerobic respiration, C<sub>6</sub>H<sub>12</sub>O<sub>6</sub> + 6O<sub>2</sub> → 6CO<sub>2</sub> + 6H<sub>2</sub>O, how many ${r[0]} when ${n} glucose molecule${n>1?"s are":" is"} oxidised?`,r[1]*n,`The equation shows ${r[1]} per glucose, so ${r[1]} × ${n} = ${r[1]*n}.`)})
 ]
});


})();
