/* Syllabus records: labs CSP-001, MEP-002, MEP-003, AHP-003, AHP-004, AHP-005, CSP-002, AHP-006 */
const CAPP="C compiler (GCC / Turbo C / Code::Blocks)";
sylAdd("CSP-001",{
 n:"Programming for Problem Solving Lab", s:"PPS Lab", type:"lab", ltp:"0-0-2", cr:1, sem:"I or II (group-wise; alternative to Basic Mechanical Engineering Lab MEP-001)",
 marks:{sess:25,ext:25,total:50},
 obj:["Acquire knowledge about the basic concept of writing a program.","Understand the role of constants, variables, identifiers, operators, type conversion and other building blocks of C.","Use conditional expressions and looping statements to solve problems involving conditions and repetitions.","Use functions for modularity, and understand arrays and pointers for memory management.","Learn structures and unions through which derived data types can be formed."],
 out:["CO1 Acquire knowledge about the basic concept of writing a program.","CO2 Understand the role of constants, variables, identifiers, operators, type conversion and other building blocks of the C language.","CO3 Learn how to use conditional expressions and looping statements to solve problems associated with conditions and repetitions.","CO4 Understand the role of functions involving the idea of modularity, and understand the concept of arrays and pointers dealing with memory management.","CO5 Learn structures and unions through which derived data types can be formed."],
 rule:"All 12 programs (each with its a/b/c parts) are listed in the official table",
 note:"Program numbering follows the official table (12 programs); each part is listed separately here.",
 exps:[
 {t:"1(a) Write a C program to find sum and average of three numbers", aim:"Read three numbers and print their sum and average.", app:CAPP, f:"sum = a + b + c ; avg = sum / 3 (use float, else integer division truncates)", viva:[["Why declare avg as float?","sum/3 with ints does integer division and drops the fractional part; a float (or 3.0) keeps it."],["What does scanf need before a variable name?","The address-of operator &, e.g. scanf(\"%d\",&a), so scanf can store the value at that address."]]},
 {t:"1(b) Write a C program to find the sum of individual digits of a given positiveinteger", aim:"Extract digits of a positive integer and add them.", app:CAPP, f:"while(n>0){ s += n%10; n /= 10; }", viva:[["What does n%10 give?","The last (units) digit of n."],["What does n/10 do for an int?","Removes the last digit (integer division)."]]},
 {t:"2(a) Write a C program to generate the first n terms of the Fibonacci sequence", aim:"Print first n Fibonacci numbers 0, 1, 1, 2, 3, 5 ...", app:CAPP, f:"F(1)=0, F(2)=1, F(k)=F(k-1)+F(k-2); loop: c=a+b; a=b; b=c", viva:[["Which loop suits this program?","for/while loop running n times, updating two previous terms."],["What are the first two terms?","0 and 1."]]},
 {t:"2(b) Write a C program to generate prime numbers between 1 to n", aim:"List all primes up to n using divisibility tests.", app:CAPP, f:"i is prime if no d in 2..√i divides i (i ≥ 2)", viva:[["Why test divisors only up to √i?","If i has a factor larger than √i it must also have a smaller one, so checking up to √i is enough."],["Is 1 prime?","No; a prime has exactly two distinct divisors."]]},
 {t:"2(c) Write a C program to check if the given number is Armstrong or not", aim:"Check whether the sum of cubes of digits equals the number.", app:CAPP, f:"n is Armstrong (3-digit) if Σ digit³ = n, e.g. 153 = 1³+5³+3³", viva:[["Give an Armstrong number.","153, 370, 371, 407."],["For a k-digit number what power is used?","Each digit is raised to power k."]]},
 {t:"3(a) Write a C program to check whether the given number is perfect or not", aim:"Check if the sum of proper divisors equals the number.", app:CAPP, f:"perfect if Σ divisors d (d < n, n%d==0) = n, e.g. 6 = 1+2+3", viva:[["Name the first perfect numbers.","6, 28, 496, 8128."],["Which divisors are added?","All proper divisors, i.e. excluding the number itself."]]},
 {t:"3(b) Write a C program to check whether the given number is strong or not", aim:"Check if the sum of factorials of digits equals the number.", app:CAPP, f:"strong if Σ (digit)! = n, e.g. 145 = 1!+4!+5!", viva:[["Give a strong number.","1, 2, 145, 40585."],["What is 0! ?","1."]]},
 {t:"4(a) Write a C program to find the roots of a quadratic equation", aim:"Find real/equal/complex roots of ax² + bx + c = 0 using the discriminant.", app:CAPP+", math.h (sqrt)", f:"D = b² − 4ac; x = (−b ± √D)/2a; D>0 real distinct, D=0 equal, D<0 complex", viva:[["Which header gives sqrt()?","math.h (link with -lm on GCC)."],["What if a = 0?","The equation is linear, not quadratic; handle separately."]]},
 {t:"4(b) Write a C program perform arithmetic operations using switch statement", aim:"Perform +, −, *, / on two numbers chosen by a menu character.", app:CAPP, f:"switch(op){case '+': r=a+b; break; ... default: invalid}", viva:[["Why is break used in switch?","To stop fall-through into the next case."],["Can switch use float values?","No; the expression must be integral or char."]]},
 {t:"5(a) Write a C program to find factorial of a given integer using non-recursive function", aim:"Compute n! with a loop inside a user-defined function.", app:CAPP, f:"n! = 1×2×...×n, 0! = 1; loop: f *= i", viva:[["Which data type is safe for large factorials?","unsigned long long; even this overflows beyond 20!."],["What is a user-defined function?","A function written by the programmer with a return type, name and parameters."]]},
 {t:"5(b) Write a C program to find factorial of a given integer using recursive function", aim:"Compute n! by a function that calls itself.", app:CAPP, f:"fact(n) = n × fact(n−1), base case fact(0) = 1", viva:[["What is the base case?","fact(0) = 1 (or fact(1) = 1), which stops recursion."],["What happens without a base case?","Infinite recursion and stack overflow."]]},
 {t:"6(a) Write C program to find GCD of two integers by using recursive function", aim:"Find GCD using Euclid's algorithm recursively.", app:CAPP, f:"gcd(a,b) = a if b == 0, else gcd(b, a mod b)", viva:[["Who devised the algorithm?","Euclid."],["gcd(48,18)?","6."]]},
 {t:"6(b) Write C program to find GCD of two integers by using non-recursive function", aim:"Find GCD using Euclid's algorithm with a loop.", app:CAPP, f:"while(b!=0){ t=b; b=a%b; a=t; } gcd = a", viva:[["Relation between GCD and LCM?","GCD × LCM = a × b."],["Advantage over recursion?","No function-call overhead or stack growth."]]},
 {t:"7(a) Write a C program to find the largest and smallest number in a list of integers", aim:"Scan an array to find its maximum and minimum.", app:CAPP, f:"max = min = a[0]; for i=1..n-1: update if a[i] > max or a[i] < min", viva:[["Why initialise with a[0]?","It is a real element of the list, so the comparison is always valid."],["Time complexity?","O(n)."]]},
 {t:"7(b) Write a C program to Sort the Array in an Ascending Order", aim:"Sort n integers in ascending order (bubble/selection sort).", app:CAPP, f:"Bubble sort: repeatedly swap adjacent a[j] > a[j+1]; O(n²)", viva:[["How many passes does bubble sort need?","At most n−1 passes."],["Name another simple sort.","Selection sort or insertion sort."]]},
 {t:"7(c) Write a C program to find whether the given matrix is symmetric or not", aim:"Check if a square matrix satisfies A = Aᵀ.", app:CAPP, f:"symmetric iff a[i][j] = a[j][i] for all i, j (square matrix only)", viva:[["Must a symmetric matrix be square?","Yes."],["Define skew-symmetric.","Aᵀ = −A, so diagonal entries are 0."]]},
 {t:"8(a) Write a C program to perform addition of two matrices", aim:"Add two m×n matrices element by element.", app:CAPP, f:"C[i][j] = A[i][j] + B[i][j]; both must have the same order", viva:[["When can two matrices be added?","When they have the same number of rows and columns."],["How is a 2-D array stored in C?","In row-major order."]]},
 {t:"8(b) Write a C program using function to perform multiplication of two matrices", aim:"Multiply A(m×n) and B(n×p) using a function.", app:CAPP, f:"C[i][j] = Σk A[i][k]·B[k][j]; needs columns(A) = rows(B); three nested loops", viva:[["Order of the product?","m × p."],["Is matrix multiplication commutative?","No, AB ≠ BA in general."]]},
 {t:"9(a) Write a C program to use function to insert a sub-string in to given main stringfrom a given position", aim:"Insert a substring into a main string at position p.", app:CAPP+", string.h", f:"shift chars from p onward right by strlen(sub), then copy sub into the gap", viva:[["What ends a C string?","The null character '\\0'."],["Which functions help?","strlen, strcpy, strcat."]]},
 {t:"9(b) Write a C program to swap the values of two variables using (i) Call by value (ii) Call by reference", aim:"Show that call by value does not swap, call by reference (pointers) does.", app:CAPP, f:"by reference: void swap(int *a,int *b){int t=*a;*a=*b;*b=t;} called as swap(&x,&y)", viva:[["Why does call by value fail to swap?","The function works on copies of the arguments."],["How does C achieve call by reference?","By passing addresses and using pointers."]]},
 {t:"10(a) Write a C program using user-defined functions to determine whether the givenstring is palindrome or not", aim:"Check whether a string reads the same forwards and backwards.", app:CAPP+", string.h", f:"compare s[i] with s[len−1−i] for i < len/2", viva:[["Give a palindrome.","madam, level, 121."],["How many comparisons are needed?","len/2."]]},
 {t:"10(b) Write a C program that displays the position or index in the main string Swhere the sub string T begins, or - 1 if S doesn't contain T", aim:"Find first occurrence of substring T in S (naive search).", app:CAPP+", string.h", f:"for each i, compare S[i..i+m−1] with T; return i on match, else −1", viva:[["Which library function does this?","strstr()."],["Worst-case complexity of naive search?","O(n·m)."]]},
 {t:"11(a) Write C program to count the number of lines, words and characters in a giventext", aim:"Count lines, words and characters in an input text.", app:CAPP, f:"chars++ per char; lines++ on '\\n'; words++ when a non-space follows a space/newline/tab", viva:[["How do you detect a word boundary?","A transition from whitespace to a non-whitespace character."],["Which function reads one character?","getchar()."]]},
 {t:"11(b) Write a C program to find the sum of integer array elements using pointers", aim:"Traverse an array with a pointer and add elements.", app:CAPP, f:"sum += *(p + i), where p = a (base address); a[i] ≡ *(a+i)", viva:[["What does the array name denote?","The address of its first element."],["What does p++ do for an int pointer?","Moves it by sizeof(int) bytes to the next element."]]},
 {t:"12(a) Write a C Program to Calculate Total and Percentage marks of a student usingstructure", aim:"Store student data in a struct and compute total and percentage.", app:CAPP, f:"total = m1+m2+...+mn ; percentage = total × 100 / (n × max marks)", viva:[["What is a structure?","A user-defined type grouping variables of different types under one name."],["Which operator accesses members?","Dot (.) for variables, arrow (->) for pointers."]]},
 {t:"12(b) Write a program to open and read a file using file handling", aim:"Open a text file, read its contents and display them.", app:CAPP, f:"FILE *fp = fopen(name,\"r\"); while((ch=fgetc(fp))!=EOF) putchar(ch); fclose(fp);", viva:[["What does fopen return on failure?","NULL."],["Why fclose()?","To flush buffers and release the file handle."]]}
 ],
 text:["C Programming and Data Structures, P.Padmanabham, Third Edition, BS Publications","Computer programming in C.V.RAjaraman, PHI Publishers.","C Programming, E.Balagurusamy, 3rd edition, TMH Publishers.","C Programming, M.V.S.S.N Venkateswarlu and E.V.Prasad,S.Chand Publishers","Mastering C,K.R.Venugopal and S.R.Prasad, TMH Publishers."],
 ref:[]
});

sylAdd("MEP-002",{
 n:"Engineering Graphics & Design Lab", s:"EG&D Lab", type:"lab", ltp:"0-1-2", cr:2, sem:"I or II (group-wise; alternative to Workshop Practices Lab MEP-003)",
 marks:{sess:50,ext:50,total:100},
 obj:["Design a system, component or process to meet desired needs within realistic constraints such as economic, environmental, social, political, ethical, health and safety, manufacturability and sustainability.","Communicate effectively.","Use the techniques, skills and modern engineering tools necessary for engineering practice.","Convert new ideas and design concepts into the basic line language of graphics using CAD software."],
 out:["CO1 Basic knowledge of engineering graphics using letter writing, different types of scales, lines and dimensions.","CO2 Draw orthographic projections of points, lines, planes and solids.","CO3 Understand the principle of isometric projection and develop isometric views by different methods.","CO4 Become familiar with AutoCAD 2-D and 3-D drawings and the various AutoCAD commands.","CO5 Use appropriate computer technology and work as a team."],
 note:"Marks 50 sessional + 50 external = 100 for the combined MEP-002/MEP-003 row (credit 2, L-T-P 0-1-2).",
 units:[
 {t:"Introduction to Engineering drawing", topics:["Introduction to Engineering drawing","Usage of drawing instruments","Types of lines","Lettering","Scales","Orthographic Projection","Dimensioning"], formulas:["RF = length of drawing / actual length of object","Plain scale reads units and primary divisions; diagonal scale reads up to three units","Lines: continuous thick (visible), thin (dimension/projection), dashed (hidden), chain (centre)"], hints:["Practise BIS lettering (5 mm, 7 mm) and line types on a sheet.","Draw plain and diagonal scales for a given RF.","Draw the three views of a simple block in first-angle projection."]},
 {t:"Projection of points, lines, simple objects and conventions", topics:["Projection of points","Projection of lines","Projection of simple objects","Conventions"], formulas:["Point above HP: front view above XY; in front of VP: top view below XY","True length of an inclined line = top-view length ÷ cosθ (θ = inclination to HP) = front-view length ÷ cosφ (φ = inclination to VP)","Line parallel to a plane shows true length on that plane"], hints:["Practise line inclined to HP and VP: find true length and true inclinations.","Draw projections of a point in all four quadrants."]},
 {t:"Isometric and oblique views, Auxiliary Views, Development of surfaces", topics:["Isometric views","Oblique views","Auxiliary Views","Development of surfaces of simple solids","Development of Prism","Development of Pyramid","Development of Cylinder","Development of Cone"], formulas:["Isometric scale = cos 45° / cos 30° ≈ 0.816 (isometric length = 0.816 × true length)","Isometric axes are 120° apart","Development of a right cone: sector angle θ = (r/l) × 360°, l = slant height","Development of a cylinder is a rectangle πd × h"], hints:["Draw an isometric view from given orthographic views.","Develop lateral surfaces of a prism, pyramid, cylinder and cone."]},
 {t:"Orthographic and sectional views of simple assembly", topics:["Orthographic views of simple assembly","Sectional views of simple assembly","Joints","Couplings"], formulas:["Section lines: thin lines at 45° to the axis, equally spaced","Cutting plane shown by chain line thick at ends","Bolts, nuts and shafts are not sectioned longitudinally by convention"], hints:["Draw front view in section and top view of a socket-and-spigot or cotter joint.","Draw a muff or flange coupling in section."]},
 {t:"Introduction to computer aided drafting", topics:["Introduction to computer aided drafting in engineering drawing","Usage of toolbars","Setting up and use of Layers","Printing of the documents"], formulas:["Layers group objects by line type, colour and lineweight","Common commands: LINE, CIRCLE, ARC, OFFSET, TRIM, EXTEND, FILLET, DIMENSION, HATCH","Absolute coordinates x,y; relative @dx,dy; polar @d<θ"], hints:["Set up limits, units and layers, then draw a simple 2-D part with dimensions.","Plot to a scaled sheet using the Plot/Print dialog."]}
 ],
 text:["N.D. Bhatt, Panchal V.M. & Ingle P.R., (2014), Engineering Drawing, Charotar Publishing House","M.B. Shah & Rana B.C. (2008), Engineering Drawing and Computer Graphics, Pearson Education","An Introduction To AutoCAD for Beginners by Autodesk","K.L. Narayana & P Kannaiah (2008), Text book on Engineering Drawing, Scitech Publishers"],
 ref:[]
});

const WT1="Hand tools, measuring instruments and safety practice of the shop.";
sylAdd("MEP-003",{
 n:"Workshop Practices Lab", s:"Workshop Lab", type:"lab", ltp:"0-1-2", cr:2, sem:"I or II (group-wise; alternative to Engineering Graphics & Design Lab MEP-002)",
 marks:{sess:50,ext:50,total:100},
 obj:["Ability to prepare simple objects using machines and machine tools.","Make students aware of fundamental operations of manufacturing an engineering component, enhance visualization and motivate them to innovate."],
 out:["CO1 Capability to identify hand tools and instruments for machining and other workshop practices.","CO2 Obtain basic skills in the trades of fitting, carpentry, welding and machining.","CO3 Acquire measuring skills using standard workshop instruments and tools.","CO4 Gain eye-hand coordination, enhance psychomotor skills and attitude.","CO5 Apply basic electrical engineering knowledge for house wiring practice."],
 note:"Marks 50 sessional + 50 external = 100 for the combined MEP-002/MEP-003 row (credit 2, L-T-P 0-1-2).",
 exps:[
 {t:"Tutorial", aim:"Manufacturing methods: casting, forming, machining, joining, advanced manufacturing methods, CNC machining and additive manufacturing; Fitting operations and power tools; Electrical and electronics; Study of carpentry tools, equipment and different joints; Plastic moulding and glass cutting; Metal casting; Welding (arc and gas welding) and brazing.", app:"Charts, models, shop manuals", f:"Manufacturing classes: casting (shape by pouring), forming (plastic deformation), machining (material removal), joining (welding, brazing, soldering)", viva:[["Name the four basic manufacturing process groups.","Casting, forming, machining and joining."],["What is additive manufacturing?","Building a part layer by layer from a digital model, e.g. 3D printing."]]},
 {t:"Machine shop", aim:"Study of machine tools in particular lathe machine; demonstration of different operations on lathe machine; practice of facing, plane turning, step turning, taper turning, knurling and parting; study of quick return mechanism in shaper; to make a machined component using lathe with mild steel round bar or hexagonal bar comprising common turning operations with reference to drawing given in the manual.", app:"Lathe machine, single-point cutting tools, chuck, vernier caliper, shaper, knurling tool, parting tool", f:"Cutting speed V = πDN/1000 m/min (D in mm, N in rpm)", viva:[["Name the main parts of a lathe.","Bed, headstock, tailstock, carriage, lead screw and tool post."],["Why is a quick return mechanism used in a shaper?","The return stroke is faster than the cutting stroke, saving idle time."]]},
 {t:"Fitting and sheet metal shop", aim:"Study of fitting and sheet metal shop tools; making a perfect male-female joint; simple exercise involving drilling/tapping/dieing; to make a sheet metal component with galvanized iron sheet as per the drawing provided in the manual having spot welding joint.", app:"Hacksaw, files, try square, scriber, surface plate, vice, drill, taps and dies, tin snips, GI sheet, spot welding machine", f:"Tap drill size ≈ major diameter − pitch", viva:[["What is the use of a tap and a die?","A tap cuts internal threads; a die cuts external threads."],["Why is a hacksaw blade fitted with teeth pointing forward?","It cuts on the forward stroke only."]]},
 {t:"Carpentry", aim:"Study of tools and operation and carpentry joints; simple exercise using jack plane; to prepare half-lap corner joint, mortise and tenon joints as per drawing provided in the lab manual; simple exercise on woodworking lathe.", app:"Jack plane, tenon saw, chisel, mallet, marking gauge, try square, wood, woodworking lathe", f:"Tenon thickness ≈ one-third of stock thickness (rule of thumb)", viva:[["Name some carpentry joints.","Lap, mortise and tenon, dovetail, mitre, dado."],["What is seasoning of timber?","Removing moisture from timber to prevent warping and shrinkage."]]},
 {t:"Electrical and electronics", aim:"Soldering and desoldering application in electronic equipment; introduction to house wiring and different types of cables; types of power supply, types of motors and starters, distribution of power supply and electric wiring symbols.", app:"Soldering iron, solder wire, flux, desoldering pump, wire stripper, cables, switches, MCB, lamp holder", f:"Power P = VI; Ohm's law V = IR", viva:[["Why is flux used in soldering?","It removes oxide and helps solder wet the joint."],["What does an MCB do?","Protects the circuit by tripping on overload or short circuit."]]},
 {t:"Welding shop", aim:"Instruction of BI standards and reading of welding drawings; to prepare butt and lap joints using metal arc welding machine as per given manual and drawing; hands-on experience with MIG, TIG and gas welding.", app:"Arc welding machine, electrode, electrode holder, chipping hammer, wire brush, face shield, gloves, MIG/TIG/gas welding set", f:"Heat input H = (V × I × 60)/(1000 × S) kJ/mm, S = travel speed in mm/min", viva:[["Why is a face shield with a dark glass used?","To protect eyes and face from arc radiation and spatter."],["What gases are used in gas welding?","Oxygen and acetylene."]]},
 {t:"Foundry shop", aim:"Study of tools and operations; demo of mould preparation; practice and preparation of mould of any pattern; casting of any simple pattern.", app:"Moulding box (cope and drag), pattern, moulding sand, rammer, riddle, trowel, vent wire, furnace, ladle", f:"Pattern is made larger than the casting by the shrinkage allowance", viva:[["What is a pattern?","A replica of the casting used to make the mould cavity."],["Why are vent holes made in a mould?","To let gases escape during pouring."]]},
 {t:"Smithy shop", aim:"Study of tools and operations; simple exercises based on black smithy operations such as upsetting, drawing down, punching, bending, fullering and swaging.", app:"Hearth, anvil, tongs, hammers, flatter, swage, fuller, punch, chisels", f:"Upsetting increases cross-section and reduces length; drawing down does the reverse", viva:[["What is upsetting?","Increasing the cross-section of a heated rod by hammering it along its length."],["What is swaging?","Reducing or finishing round work using a swage tool."]]},
 {t:"Minor Project", aim:"To make a minor project by the students in batches comprising the operations performed in different shops.", app:"Tools and machines of the machine, fitting, carpentry, welding, foundry and smithy shops", f:"Plan: drawing, material list, sequence of operations, finishing and inspection", viva:[["How do you plan a job across shops?","Prepare drawing and bill of material, choose sequence of operations, and inspect each stage."],["Why is safety important?","To prevent injuries: wear PPE and follow shop rules."]]}
 ],
 text:[],
 ref:["A course in Workshop Technology Vol I and Vol II by Prof. B.S. Raghuwanshi, Dhanpat Rai & Co.(P) Ltd.","Elements of Workshop Technology Vol I and Vol II by S.K. Hajara Choudhury, A.K. Hajara Choudhury & Nirjhar Roy; Media Promoters & Publishers Pvt. Ltd, Mumbai.","Workshop Technology Part 1, Part 2 & Part 3 by W.A.J. Chapman; CBS Publishers & Distributors, New Delhi."]
});

sylAdd("AHP-003",{
 n:"Introduction to Digital Marketing Practical", s:"Digital Mktg", type:"lab", ltp:"0-0-2", cr:1, sem:"I or II (group-wise)",
 marks:{sess:25,ext:25,total:50},
 obj:["Understand the applications of Digital Marketing.","Undertake marketing campaigns in digital format and apply the tools of Digital Marketing to gain competitive advantage in the market.","Analyze consumer buying behavior using Web Analytics and offer the right products or services to the right customers."],
 out:["CO1 Learn digital marketing tools like search engine optimization and associated analytics.","CO2 Apply digital marketing tools to (a) improve websites' rankings and optimize them, (b) improve the brand's visibility, (c) improve brand reach which physically is relatively difficult and less effective.","CO3 Analyze the relative importance of digital marketing strategies to optimize a digital marketing campaign.","CO4 Evaluate the performance of different social media in conjunction with the overall digital marketing plan.","CO5 Design search engine optimization and search engine marketing campaigns."],
 note:"Pre-requisite: basic knowledge of computer and internet.",
 exps:[
 {t:"Digital Marketing Implementation in Business Scenario", aim:"Pick a business case and outline how digital channels are used to reach its customers.", app:"Computer, internet, browser, case study", f:"Funnel: Awareness → Interest → Consideration → Purchase → Loyalty", viva:[["What is digital marketing?","Promotion of products or services through digital channels such as search, social media, email and websites."],["Name main digital channels.","SEO, SEM, social media, email, content and display advertising."]]},
 {t:"Create the Digital Marketing Webpage", aim:"Build a simple landing page for a product with a clear call to action.", app:"Website builder (Wix / WordPress / Google Sites) or HTML editor, images, browser", f:"Landing page = headline + benefits + visuals + call to action (CTA)", viva:[["What is a landing page?","A focused page where visitors arrive from an ad or link, designed for one action."],["What is a CTA?","A prompt such as 'Buy now' or 'Sign up' that tells visitors what to do."]]},
 {t:"Conducting the Search Engine Optimization and Search Engine Marketing", aim:"Optimise a page with keywords and set up a sample paid search campaign.", app:"Google Keyword Planner, Google Ads (demo), SEO checker, browser", f:"CTR = clicks / impressions × 100; CPC = cost / clicks", viva:[["Difference between SEO and SEM?","SEO earns organic ranking by optimising the site; SEM buys paid placement in search results."],["What are on-page SEO elements?","Title, meta description, headings, keywords, alt text and internal links."]]},
 {t:"Using Google Analytics to analyze website performance", aim:"Study traffic, source, bounce rate and audience reports of a website.", app:"Google Analytics account or demo account, browser", f:"Bounce rate = single-page sessions / total sessions × 100; Conversion rate = conversions / visitors × 100", viva:[["What is bounce rate?","Percentage of visits that leave after viewing one page."],["What is a session?","A group of user interactions on a site within a time frame."]]},
 {t:"Creating Promotional banner through Canva", aim:"Design a promotional banner with text, image and brand colours.", app:"Canva (web), browser, images/logo", f:"Design principles: contrast, alignment, hierarchy, white space", viva:[["Why use a consistent brand palette?","It builds recognition and trust."],["Which size is chosen for a Facebook banner?","Use the platform's recommended dimensions, e.g. Facebook cover 820 × 312 px."]]},
 {t:"Facebook Promotion using banners", aim:"Create a business page and publish or boost a banner post.", app:"Facebook page, Meta Ads Manager (demo), banner from Canva", f:"CPM = cost / impressions × 1000; reach = unique people who saw the post", viva:[["Difference between reach and impressions?","Reach counts unique viewers; impressions count total views."],["What is boosting a post?","Paying to show a post to a wider targeted audience."]]},
 {t:"Creating YouTube Channel for Marketing", aim:"Set up a channel, upload a promotional video and optimise title, tags and thumbnail.", app:"Google account, YouTube Studio, video/screen recorder", f:"Watch time and click-through rate drive video ranking", viva:[["Why optimise video titles and tags?","They help YouTube search recommend the video."],["What is a thumbnail?","The preview image that attracts viewers to click."]]},
 {t:"Twitter Marketing", aim:"Create a profile, post with hashtags and study engagement.", app:"Twitter/X account, analytics dashboard", f:"Engagement rate = (likes + replies + reposts) / impressions × 100", viva:[["Use of hashtags?","They group content by topic and increase discoverability."],["What is engagement?","Interactions with a post such as likes, comments and shares."]]},
 {t:"Instagram Marketing", aim:"Create a business profile and plan posts, reels and stories.", app:"Instagram business account, Canva, smartphone", f:"Content mix plan: posts, reels, stories, with a posting calendar", viva:[["What is an influencer?","A person with a following who promotes brands to their audience."],["Why use stories and reels?","They give short, high-visibility formats with high engagement."]]},
 {t:"Email Marketing", aim:"Create a mailing list and send a designed campaign email.", app:"Mailchimp / Gmail, email template, contact list", f:"Open rate = opened / delivered × 100; CTR = clicks / delivered × 100", viva:[["What is an email subject line for?","It decides whether the recipient opens the message."],["What does opt-in mean?","Recipients give consent before receiving marketing mail."]]},
 {t:"Digital Marketing Final Analysis and Report", aim:"Compile results from all channels into a final analysis report.", app:"Analytics reports, spreadsheet, word processor", f:"ROI = (revenue − cost) / cost × 100", viva:[["What is ROI?","Return on investment: the profit from a campaign relative to its cost."],["Which metrics go into the report?","Reach, engagement, CTR, conversions and cost per result."]]}
 ],
 text:["\"Digital Marketing\" By Vandana Ahuja, Publisher- Oxford University Press.","\"Digital Marketing Strategy- An integrated approach to online marketing\" by Simon Kingsnorth, Publisher- Kogan Page.","\"Digital Marketing- A practical approach\" by Alan Charlesworth, Publisher: Routledge - Taylor & Francis Group."],
 ref:["Learning websites: http://www.books.google.co.in/Digital Marketing ; http://www.investopedia.com ; http://www.neilpatel.com ; different social media websites"]
});

sylAdd("AHP-004",{
 n:"Emerging Technologies and Their Applications in Engineering", s:"Emerg. Tech", type:"lab", ltp:"0-0-2", cr:1, sem:"I or II (group-wise)",
 marks:{sess:25,ext:25,total:50},
 obj:["Provide brief knowledge about the emerging technologies of the present time which are changing the world at a speed humanity has never seen, e.g. 3D printing, 5G technology, virtual reality, fortification, cyber security and many others."],
 out:["CO1 Be familiar with 3D printing, robots and drones.","CO2 Know and be familiar with developments in transport systems like Hyperloop and Maglev.","CO3 Understand the need of fast internet and its application in various fields; understand nanotechnology and ceramics.","CO4 Know the basics of Artificial Intelligence and machine learning, blockchain and quantum computing.","CO5 Know augmented reality (AR), virtual reality (VR), cyber security and satellite technology."],
 exps:[
 {t:"Modern Manufacturing: 3D printing, study of 3D printer, generation of stl files, making small objects on 3D printer, basics of Ceramic material", aim:"Study a 3D printer, generate an STL file from a CAD model and print a small object.", app:"3D printer (FDM), filament, CAD software, slicer software", f:"CAD model → STL → slicing (G-code) → layer-by-layer printing", viva:[["What is an STL file?","A triangulated-surface file format describing a 3D model for printing."],["Name a 3D printing process.","FDM (fused deposition modelling), SLA, SLS."]]},
 {t:"Robotics: Introduction about different types of robots, Study components of a real robot, Power point presentation on different robotic applications", aim:"Study types of robots and the components of a real robot; present applications.", app:"Robot kit or model, PowerPoint", f:"Robot = sensors + controller + actuators + power supply + end effector", viva:[["Name the components of a robot.","Manipulator/arm, end effector, sensors, controller, actuators and power source."],["What is degree of freedom?","Number of independent motions a robot joint set can perform."]]},
 {t:"Drones and their applications in various fields", aim:"Study parts of a drone and its uses in agriculture, surveying, delivery and defence.", app:"Drone model or videos, presentation", f:"Parts: frame, motors, propellers, ESC, flight controller, battery, radio", viva:[["What does a flight controller do?","Stabilises the drone using sensor data and controls the motors."],["Give two drone applications.","Aerial photography and crop spraying."]]},
 {t:"Scope of developments in transport systems: Hyperloop, Magnetic leviathan (Maglev) by model making or using computer animation", aim:"Make a model or animation showing how Hyperloop and Maglev work.", app:"Model materials or animation software, magnets", f:"Maglev: magnetic levitation removes wheel friction; Hyperloop: pods in low-pressure tube", viva:[["How does Maglev float?","Magnetic repulsion or attraction lifts the train above the guideway."],["Why is the Hyperloop tube at low pressure?","To reduce air drag."]]},
 {t:"Introduction to 5G technology: Benefits of 5G in IOT and other applications, Comparison with 2G, 3G, 4G", aim:"Compare generations of mobile networks and note 5G benefits for IoT.", app:"Presentation, internet", f:"5G: high speed, very low latency (~1 ms), massive device density", viva:[["Give two benefits of 5G.","Very high data rate and low latency."],["Which 'G' introduced data/internet at scale?","3G (and 4G for broadband/LTE)."]]},
 {t:"Study of fortification machines for Rice and other cereals with the help of Videos and animation tools", aim:"Understand how nutrients are added to rice and cereals using machines.", app:"Videos, animation tools", f:"Fortification = adding micronutrients (iron, folic acid, B12) to staple food", viva:[["What is food fortification?","Adding essential vitamins and minerals to foods to improve nutrition."],["Name a fortified staple.","Fortified rice, wheat flour or salt."]]},
 {t:"Nanotechnology: Introduction to Nano materials and brief theory of nanotechnology", aim:"Learn what nanomaterials are and how their properties differ.", app:"Presentation, videos", f:"1 nm = 10⁻⁹ m; nano scale ≈ 1–100 nm; surface-to-volume ratio rises as size falls", viva:[["What is a nanomaterial?","A material with at least one dimension in the 1–100 nm range."],["Why do properties change at nano scale?","High surface-to-volume ratio and quantum effects."]]},
 {t:"Artificial Intelligence and Machine learning: Introduction, applications, challenges and threats associated", aim:"Study AI/ML basics, applications and risks.", app:"Python / online ML demo tools, presentation", f:"ML types: supervised, unsupervised, reinforcement", viva:[["Difference between AI and ML?","ML is a subset of AI where systems learn patterns from data."],["Name a challenge of AI.","Bias, privacy, job impact, or lack of explainability."]]},
 {t:"Blockchain and Distributed ledger technology: what is blockchain, its application, cryptocurrencies", aim:"Understand blocks, hashes, chain and cryptocurrencies.", app:"Presentation, online blockchain demo", f:"Block = data + hash + previous hash; changing one block breaks the chain", viva:[["What is a blockchain?","A distributed, tamper-evident ledger of blocks linked by hashes."],["Name a cryptocurrency.","Bitcoin or Ethereum."]]},
 {t:"Quantum computing: its practical application, Building Quantum dice", aim:"Learn qubit basics and build a quantum dice (random number) demo.", app:"Quantum simulator (e.g. IBM Quantum / Qiskit), computer", f:"Qubit state |ψ⟩ = α|0⟩ + β|1⟩, |α|² + |β|² = 1; n qubits in superposition give 2ⁿ outcomes", viva:[["What is a qubit?","The quantum unit of information that can be in a superposition of 0 and 1."],["How does a quantum dice work?","Put qubits in superposition with Hadamard gates and measure to get a random outcome."]]},
 {t:"Electric vehicle: development of simple battery system in laboratory", aim:"Assemble a simple battery pack and study its voltage and capacity.", app:"Cells, holder, multimeter, connecting wires, charger", f:"Series: V = V1 + V2 + ...; Parallel: capacity adds (Ah); Energy = V × Ah", viva:[["Series vs parallel cells?","Series adds voltage; parallel adds capacity."],["Which battery type is common in EVs?","Lithium-ion."]]},
 {t:"Other Future trends: Cyber security, Augmented Reality and Virtual Reality, Data sciences", aim:"Survey cyber security, AR/VR and data science trends.", app:"Presentation, AR/VR demo apps, Python", f:"CIA triad: Confidentiality, Integrity, Availability", viva:[["Difference between AR and VR?","AR overlays digital content on the real world; VR creates a fully virtual environment."],["What is phishing?","Tricking users into revealing sensitive information through fake messages or sites."]]},
 {t:"Different types of satellites and their application using videos and Power point presentations", aim:"Study satellite orbits (LEO, MEO, GEO) and applications.", app:"Videos, PowerPoint", f:"GEO orbit height ≈ 35,786 km above the equator (period 24 h)", viva:[["Name types of satellites.","Communication, navigation, weather, earth observation and scientific."],["What is a geostationary satellite?","One that stays fixed over a point on the equator, orbiting at ≈ 35,786 km."]]}
 ],
 text:[],
 ref:["Mastering Cloud Computing: Foundations and Applications Programming, Christian Vecchiola, Rajkumar Buyya and S. Thamarai Selvi","Daniel Drescher, Blockchain Basics: A Non-Technical Introduction in 25 Steps","Ian Gibson, Additive Manufacturing Technologies: 3D Printing, Rapid Prototyping and Direct Digital Manufacturing","Barry Davies, Build a Drone: A Step-by-Step Guide to Designing, Constructing, and Flying Your Very Own Drone","Simon Haykin, \"Communication Systems\", 4th Edition, Wiley India","K. C. Mahajan, R. Kumar & P. K. Pattnaik, Robotics for Engineers - Concepts and Techniques, Vikas Publishing House","Michael A. Nielsen, \"Quantum Computation and Quantum Information\", Cambridge University Press","Joel Grus, \"Data Science from Scratch: First Principles with Python\", O'Reilly Media"]
});

sylAdd("AHP-005",{
 n:"Self Employment and Entrepreneurship Development", s:"Entrepreneur", type:"lab", ltp:"0-0-2", cr:1, sem:"I or II (group-wise)",
 marks:{sess:25,ext:25,total:50},
 obj:["Develop different types of skills (psychomotor and affective domain) so that students acquire the competencies/programme outcomes through properly designed and implemented practicals/exercises."],
 out:[],
 rule:"6 practical exercises, approx 28 hours in total",
 note:"a) It is compulsory to prepare a log book of exercises; each exercise must be recorded in the logbook, checked and duly dated and signed by the teacher. The practical marks depend on continuous and timely evaluation of exercises. b) Term work report must not include any photocopy, printed manual/pages, litho etc.; it must be hand written / hand drawn by the student only. c) For practical ESE, students are assessed for competencies achieved.",
 exps:[
 {t:"1 Preparatory activity: a) List various types of industries. b) Narrate need of self employment. c) Anticipate importance of entrepreneurship development.", aim:"Approx 2 hours. List industries, explain the need for self-employment and the importance of entrepreneurship development.", app:"Logbook, internet, library", f:"Industry types: primary, secondary, tertiary; also micro, small, medium, large scale", viva:[["Who is an entrepreneur?","A person who starts and manages a venture, taking risk to earn profit."],["Why is self-employment needed?","It creates jobs, uses local skills and reduces dependence on salaried jobs."]]},
 {t:"2 Creativeness and innovativeness: a) List at least ten uses of an assigned mechanical feature based item/product (pen, gear, mouse, notebook, chair, table, fan, mobile, bicycle etc.) other than pre-defined. b) List at least ten innovations of an assigned process, product or service. c) List at least ten engineering products which have passed through innovativeness.", aim:"Approx 4 hours. Group of 5-6 students: think out of the box to list ten alternate uses, ten innovations, and ten innovated engineering products.", app:"Logbook, group discussion", f:"Creativity = new ideas; innovation = new ideas put to use", viva:[["Difference between creativity and innovation?","Creativity generates ideas; innovation implements them to create value."],["Give an innovated product example.","The mobile phone evolving into a smartphone."]]},
 {t:"3 Identification of self-employment areas: a) Group of 5-6 students. b) List at least five mechanical feature based areas with self-employment potential; select one promising area. c) Develop market survey format. d) Perform market survey nearby the institute. e) Describe the outcome and narrate the experience. f) Attach photographs of group conducting the survey (compulsory).", aim:"Approx 4 hours. Choose a promising area, design a survey format, conduct a market survey and report the outcome with photographs.", app:"Questionnaire format, camera, logbook", f:"Sample survey: define objective → questionnaire → collect data → analyse → conclude", viva:[["Why do a market survey?","To learn customer needs, demand and competition before starting a venture."],["What goes in a survey format?","Respondent details, product/service questions, price and demand questions."]]},
 {t:"4 Visit report: a) Visit any one near institute: industries/financial institutions/bank/training institute/hotel/farming/agribusiness etc. b) Prepare the visit report including: i. brief history of organization; ii. type and details of product/services/support/assistance being given; iii. any other information useful to be a self-employer or entrepreneur; iv. brochures/technical literature collected from agencies.", aim:"Approx 4 hours. Visit one organisation and write a visit report with history, products/services, useful information and brochures.", app:"Logbook, camera, brochures", f:"Report structure: introduction, organisation profile, observations, learning, attachments", viva:[["What is included in a visit report?","History, products/services, useful entrepreneur information and collected brochures."],["Name a financial institution helping entrepreneurs.","SIDBI, NSIC, or nationalised banks under PMEGP/MUDRA."]]},
 {t:"5 Preparing project feasibility report of assigned product: a) Teacher assigns one product (physical or service based) to the group of 5-6 students. b) Prepare project feasibility report (technical and financial), specifically including capacity requirement calculations and project set up planning details; present to the whole batch.", aim:"Approx 8 hours. Prepare and present a technical and financial feasibility report for the assigned product.", app:"Logbook, spreadsheet, presentation", f:"Break-even quantity = Fixed cost / (Selling price per unit − Variable cost per unit); Payback = Investment / annual net cash flow", viva:[["What is a feasibility report?","A study of whether a project is technically and financially viable."],["Define break-even point.","The output at which total revenue equals total cost."]]},
 {t:"6 Case analysis and presentations: teacher assigns one case of a successful entrepreneur and one case of a failed entrepreneur to the group of 5-6 students; discuss, analyze and present to the whole batch; prepare the report on analysis. Case may be put up with printed pages but analysis has to be hand written.", aim:"Approx 6 hours. Analyse one successful and one failed entrepreneur case, present and submit a handwritten analysis.", app:"Case material, logbook, presentation", f:"Compare: idea, funding, market, management, risk handling, reasons for success/failure", viva:[["Common causes of business failure?","Poor planning, lack of funds, weak market understanding, poor management."],["Qualities of a successful entrepreneur?","Risk taking, innovation, leadership, persistence and planning."]]}
 ],
 text:[],
 ref:["Learning websites: http://www.ediindia.org ; http://niesbud.nic.in/docs/SelfEmploymentBook.pdf ; http://smallb.in/ ; http://www.msme.gov.in/ ; http://nimsme.org/ ; http://www.nsic.co.in/ ; http://iie.nic.in/ ; http://msme.gov.in/guidelines_pmegp_24092008.pdf"]
});

sylAdd("CSP-002",{
 n:"Computer Applications and IoT", s:"Comp App&IoT", type:"lab", ltp:"0-0-2", cr:1, sem:"I or II (group-wise)",
 marks:{sess:25,ext:25,total:50},
 obj:["Solve basic information systems problems using MS Office products.","Communicate in a business environment using MS Office.","Understand DOS commands and Linux.","Describe and analyze computer hardware and software.","Understand the concepts of IoT."],
 out:["CO1 Solve basic information systems problems using MS Office products appropriate for the solution.","CO2 Communicate in a business environment using the MS Office product.","CO3 Understanding DOS commands and Linux programming.","CO4 Describe and analyze computer hardware and software.","CO5 Understanding the concepts of IOT."],
 rule:"8 experiments as listed in the official table",
 exps:[
 {t:"1 Experiments on dismantling of PC: Dismantling the system unit, recognize all major components inside a PC, describe function of each component and define the relationship of internal components.", aim:"Open a system unit, identify components and describe their functions and relationships.", app:"Screwdriver set, anti-static wrist strap, PC cabinet", f:"Data flow: input → CPU + RAM (motherboard) → storage/output", viva:[["Name the main internal components.","Motherboard, CPU, RAM, SMPS, HDD/SSD, graphics/network cards, cooling fan."],["What does the SMPS do?","Converts AC mains to regulated DC voltages for the components."]]},
 {t:"2(a) Experiments on DOS: Perform these internal commands: DIR, TYPE, DEL, ERASE, MD, CD, COPY, RMDIR, VER, DATE, TIME, PATH, CLS, RMDIR, VER, DATE, TIME, PATH, CLS, BREAK, SET, EXIT.", aim:"Run DOS internal commands at the command prompt.", app:"Command Prompt (cmd) / DOSBox", f:"Internal commands are built into COMMAND.COM; e.g. MD dir, CD dir, COPY src dest", viva:[["What is an internal command?","One built into the command interpreter, needing no separate file."],["What does DIR do?","Lists files and folders of the current directory."]]},
 {t:"2(b) Perform external commands: APPEND, CHKDISK, ATTRIB, SYS, EDIT.", aim:"Run DOS external commands.", app:"Command Prompt (cmd) / DOSBox", f:"External commands are separate program files, e.g. ATTRIB +R file sets read-only", viva:[["Difference between internal and external commands?","External commands are stored as separate files on disk and loaded when run."],["Use of ATTRIB?","Displays or changes file attributes (read-only, hidden, system, archive)."]]},
 {t:"3(a) Experiments on system utilities: Explore and describe some system utility like regedit, memory portioning, control panel, window tools.", aim:"Explore system utilities and describe their functions.", app:"Windows PC, regedit, Disk Management, Control Panel", f:"Utilities: regedit (registry), Disk Management (partitions), Control Panel (settings)", viva:[["What is the registry?","A hierarchical database of Windows configuration settings."],["What is disk partitioning?","Dividing a physical disk into separate logical volumes."]]},
 {t:"3(b) List various keys in registry and perform experiments to back up a key in registry using regedit.", aim:"List the root registry keys and export a key as a backup.", app:"Windows PC, regedit", f:"Root keys: HKEY_CLASSES_ROOT, HKEY_CURRENT_USER, HKEY_LOCAL_MACHINE, HKEY_USERS, HKEY_CURRENT_CONFIG; File > Export", viva:[["How do you back up a key?","Select it in regedit and use File > Export to save a .reg file."],["Why be careful with regedit?","Wrong edits can make the system unstable."]]},
 {t:"4(a) Experiments on Linux: Perform an experiment to install any rpm or debian linux distribution.", aim:"Install an RPM-based (Fedora/CentOS) or Debian-based (Ubuntu) Linux distribution.", app:"Bootable USB/ISO, VirtualBox or spare PC", f:"Steps: boot media → choose language → partition disk → create user → install", viva:[["Give examples of rpm and debian based distros.","Fedora, CentOS (rpm); Ubuntu, Debian (deb)."],["What is a kernel?","The core of the OS managing hardware, processes and memory."]]},
 {t:"4(b) Install rpm and deb packages.", aim:"Install software using rpm/dpkg package tools.", app:"Linux terminal", f:"rpm -ivh pkg.rpm ; dpkg -i pkg.deb ; apt install / yum install", viva:[["Command to install a .deb package?","sudo dpkg -i package.deb."],["Command to install a .rpm package?","rpm -ivh package.rpm."]]},
 {t:"4(c) Perform these commands in linux: chmod, su, chown, chgrp, ls, mkdir, pwd, date, who, find, uname, wc, ifconfig.", aim:"Practise common Linux shell commands.", app:"Linux terminal", f:"chmod 755 file (rwxr-xr-x); ls -l; find . -name f; wc -l file", viva:[["What does chmod 644 mean?","Owner read/write; group and others read only."],["What does pwd show?","The present working directory."]]},
 {t:"4(d) Create, open, edit, view file in linux.", aim:"Create and edit files using shell commands and editors.", app:"Linux terminal, vi/nano, cat", f:"touch f; cat > f; vi f; cat f; less f", viva:[["How do you save and quit in vi?","Press Esc then type :wq."],["What does cat do?","Displays or concatenates file contents."]]},
 {t:"4(e) Create user and group through CLI.", aim:"Create users and groups from the command line.", app:"Linux terminal (root/sudo)", f:"groupadd grp ; useradd -m -G grp user ; passwd user", viva:[["Which file stores user accounts?","/etc/passwd."],["Command to add a group?","groupadd."]]},
 {t:"5(a) Experiments on MS Office Word/Open Office Writer: Create an office writer document and using tables distinguish between different types of memories.", aim:"Insert a table comparing types of memory (RAM, ROM, cache, secondary).", app:"MS Word / LibreOffice Writer", f:"Insert > Table; rows = memory types, columns = speed, volatility, use", viva:[["How to insert a table in Word?","Insert > Table and choose rows and columns."],["Is RAM volatile?","Yes, it loses data when power is off."]]},
 {t:"5(b) Draft a letter asking for quotations of different peripheral devices for your computer lab and mail the letter using mail merge in MS Word/open office writer.", aim:"Write a quotation request letter and merge it with a recipient list.", app:"MS Word / LibreOffice Writer, data source (Excel/CSV)", f:"Mail merge = main document + data source + merge fields", viva:[["What is mail merge?","Combining a template letter with a data list to make personalised copies."],["What are merge fields?","Placeholders such as «Name» replaced by data source values."]]},
 {t:"5(c) Create a MS Word/open office writer document and implement macro function.", aim:"Record and run a macro to automate a task.", app:"MS Word / LibreOffice Writer (macro recorder)", f:"View > Macros > Record Macro > perform actions > Stop > Run", viva:[["What is a macro?","A recorded or coded sequence of actions that can be replayed."],["Which language does MS Office use for macros?","VBA (Visual Basic for Applications)."]]},
 {t:"5(d) Create a template and draw a basic block diagram of computer & using graphs compare the performance of different laptop/notebook PC.", aim:"Save a document template, draw a block diagram and add a chart comparing laptops.", app:"MS Word / LibreOffice Writer, shapes and chart tools", f:"Block diagram: Input → CPU (ALU, CU) + Memory → Output", viva:[["What is a template?","A preset document layout that can be reused."],["Name the parts of the CPU.","Arithmetic logic unit, control unit and registers."]]},
 {t:"6 Experiments on MS Office Excel/Open Office Calc: Create a database of students, which contains marks obtained by students of a class in different subjects and then calculate maximum, minimum, average and sum of marks in each subject. Also calculate % of each student using functions and formulas in MS Excel/Open Office Calc; also draw pie chart and bar graph.", aim:"Build a marks sheet and compute MAX, MIN, AVERAGE, SUM, percentage, and draw charts.", app:"MS Excel / LibreOffice Calc", f:"=MAX(B2:B11), =MIN(), =AVERAGE(), =SUM(); % = SUM(marks) / total marks × 100", viva:[["Difference between relative and absolute reference?","Relative shifts on copying (A1); absolute stays fixed ($A$1)."],["Which chart shows proportions?","Pie chart."]]},
 {t:"7 Experiments on MS Office Power Point/Open Office Impress: Make a simple presentation on your college, use 3D effects, animation on network topologies.", aim:"Create a slide presentation with 3D effects and animated network topology diagrams.", app:"MS PowerPoint / LibreOffice Impress", f:"Topologies: bus, star, ring, mesh, tree; Insert > Shapes; Animations tab", viva:[["Name network topologies.","Bus, star, ring, mesh and tree."],["Use of slide transitions?","To animate movement between slides."]]},
 {t:"8(a) Experiments on IoT: Basic Components of IOT, Interaction with the Internet, Major Components of IoT devices: Control Units, Sensors, Communication modules, Power Sources, Communication Technologies: RFID, Bluetooth, Zigbee, WiFi, RF Links, Mobile Internet, Wired Communication. Familiarization of Arduino/Raspberry Pi and perform necessary software installation.", aim:"Study IoT components and communication technologies; get familiar with Arduino/Raspberry Pi and install the required software.", app:"Arduino board / Raspberry Pi, USB cable, Arduino IDE / Raspberry Pi OS", f:"IoT stack: sensors → controller → communication module → cloud/internet", viva:[["Name IoT components.","Sensors, control unit, communication module and power source."],["Arduino vs Raspberry Pi?","Arduino is a microcontroller board; Raspberry Pi is a single-board computer running an OS."]]},
 {t:"8(b) To interface LED/Buzzer with Arduino / Raspberry Pi and write a program to turn on LED for 1 sec.", aim:"Connect an LED/buzzer to a digital pin and turn it on for 1 second.", app:"Arduino/Raspberry Pi, LED, 220 Ω resistor, breadboard, jumper wires", f:"Arduino: pinMode(13,OUTPUT); digitalWrite(13,HIGH); delay(1000); digitalWrite(13,LOW); series resistor R = (Vs − VLED)/I", viva:[["Why a resistor with the LED?","To limit current and avoid burning the LED."],["What does delay(1000) do?","Pauses for 1000 ms = 1 s."]]}
 ],
 text:[],
 ref:[]
});

sylAdd("AHP-006",{
 n:"English Language Lab", s:"English Lab", type:"lab", ltp:"0-0-2", cr:0, sem:"I or II (group-wise; alternative to Environmental Studies AHT-004)",
 marks:{sess:50,ext:25,total:75},
 obj:["Facilitate software based learning to provide the required English language proficiency to students.","Acquaint students with specific dimensions of communication skills i.e. Reading, Writing, Listening, Thinking and Speaking.","Train students to use correct and error-free writing by being well versed in rules of English grammar.","Cultivate relevant technical style of communication and presentation at the work place and for academic uses.","Enable students to apply it for practical and oral presentation purposes by being honed up in presentation skills and voice dynamics."],
 out:["CO1 Understand the basic objective of the course by being acquainted with specific dimensions of communication skills i.e. Reading, Writing, Listening, Thinking and Speaking.","CO2 Create a substantial base by the formation of strong professional vocabulary for application at different platforms and through numerous modes such as comprehension, reading, writing and speaking.","CO3 Apply it at the work place for writing purposes such as presentation / official drafting / administrative communication and use it for document / project / report / research paper writing.","CO4 Evaluate the correct and error-free writing by being well versed in rules of English grammar and cultivate relevant technical style of communication and presentation at the work place and for academic uses.","CO5 Apply it for practical and oral presentation purposes by being honed up in presentation skills and voice dynamics; apply techniques for developing interpersonal communication skills and positive attitude leading to professional competence."],
 note:"Credit 0 (L-T-P 0-0-2). Marks in the scheme table: sessional 50, practical exam 25, total 75.",
 exps:[
 {t:"1 Group Discussion: Practical based on Accurate and Current Grammatical Patterns.", aim:"Take part in group discussions using accurate, current grammar.", app:"Language lab, discussion topics", f:"GD flow: initiate → build points → respond to others → summarise", viva:[["Tips for a good GD?","Listen, be concise, be polite, support with facts, do not interrupt."],["Who summarises a GD?","Any participant, ideally toward the end."]]},
 {t:"2 Conversational Skills for Interviews under suitable Professional Communication Lab conditions with emphasis on Kinesics.", aim:"Practise interview conversation with attention to body language.", app:"Language lab, mock interview setup, video recorder", f:"Kinesics = body language: posture, eye contact, gesture, facial expression", viva:[["What is kinesics?","The study of body movements and gestures in communication."],["How to answer 'Tell me about yourself'?","Give a brief, relevant summary of education, skills and goals."]]},
 {t:"3 Communication Skills for Seminars / Conferences / Workshops with emphasis on Paralinguistic / Kinesics.", aim:"Practise communicating at seminars and workshops using voice and body cues.", app:"Language lab, audio-visual aids", f:"Paralanguage = pitch, pace, volume, tone, pauses", viva:[["What is paralanguage?","Vocal cues such as tone, pitch and pace that accompany speech."],["Why use pauses?","To emphasise points and let the audience absorb them."]]},
 {t:"4 Presentation Skills for Technical Paper / Project Reports / Professional Reports based on proper Stress and Intonation Mechanics.", aim:"Present technical papers and reports with correct stress and intonation.", app:"Projector, PowerPoint, language lab software", f:"Structure: introduction, body, conclusion; stress key words, falling tone for statements", viva:[["What is intonation?","The rise and fall of the voice in speech."],["What is word stress?","Emphasis on a particular syllable of a word."]]},
 {t:"5 Official / Public Speaking based on suitable Rhythmic Patterns.", aim:"Deliver official or public speeches with proper rhythm.", app:"Podium, microphone, language lab", f:"Rhythm in English: stress-timed pattern", viva:[["What is rhythm in speech?","The regular pattern of stressed and unstressed syllables."],["How to overcome stage fear?","Prepare, practise, breathe slowly and focus on the message."]]},
 {t:"6 Theme Presentation / Keynote Presentation based on correct methodologies argumentation.", aim:"Prepare and deliver a theme or keynote presentation with logical argument.", app:"Projector, slides", f:"Argument: claim → evidence → reasoning → conclusion", viva:[["What is a keynote address?","A main speech that sets the central theme of a conference."],["What makes an argument strong?","Clear claim supported by relevant evidence and logic."]]},
 {t:"7 Individual Speech Delivery / Conferencing with skills to defend Interjections / Quizzes.", aim:"Deliver an individual speech and handle interruptions and questions.", app:"Language lab, quiz material", f:"Handling questions: listen, pause, answer briefly, stay calm", viva:[["How to handle an interruption?","Acknowledge politely, respond briefly and return to the point."],["What is an interjection?","A word that expresses sudden emotion, e.g. oh, wow."]]},
 {t:"8 Argumentative Skills / Role Play Presentation with Stress and Intonation.", aim:"Practise arguing a point and role playing with proper stress and intonation.", app:"Language lab, role-play scripts", f:"Persuasion: stress key words and vary intonation", viva:[["What is role play?","Acting out a situation to practise communication."],["How to disagree politely?","Acknowledge the other view, then give your reasons."]]},
 {t:"9 Misplaced modifiers, Articles, Prepositions.", aim:"Correct sentences with misplaced modifiers and use articles and prepositions properly.", app:"Language lab software, worksheets", f:"Place the modifier next to the word it describes; a/an before a consonant/vowel sound; the for specific nouns", viva:[["What is a misplaced modifier?","A modifier placed away from the word it modifies, causing confusion."],["'an hour' or 'a hour'?","'An hour', because hour starts with a vowel sound."]]},
 {t:"10 Phonetic symbols.", aim:"Learn and use IPA symbols to read and write pronunciations.", app:"Language lab software, English pronouncing dictionary", f:"English has 44 sounds: 20 vowels (12 monophthongs, 8 diphthongs) and 24 consonants", viva:[["What does IPA stand for?","International Phonetic Alphabet."],["How many diphthongs does English have?","Eight."]]},
 {t:"11 Everyday conversation, Identifying Common Errors in Writing: Subject - verb agreement.", aim:"Practise everyday dialogues and correct subject-verb agreement errors.", app:"Language lab software, worksheets", f:"Singular subject takes singular verb; plural takes plural; 'each', 'every', 'neither' take singular", viva:[["Correct: 'The team is / are winning'?","'The team is winning' when the team acts as one unit."],["'Neither of the boys ___ present'?","'Is'."]]},
 {t:"12 Writing Practices: Comprehension, Précis Writing.", aim:"Practise answering comprehension passages and writing précis.", app:"Passages, worksheets", f:"Précis ≈ one-third of the original passage, in own words, with a title", viva:[["What is a précis?","A concise summary of a passage in your own words."],["Length of a précis?","About one-third of the original."]]}
 ],
 text:[],
 ref:["Word Power Made Easy by Norman Lewis, W.R. Goyal Pub. & Distributors, 2009, Delhi.","Manual of Practical Communication. L.U.B. Pandey; A.I.T.B.S. Publications India Ltd; Krishan Nagar, 2013, Delhi.","A Course in Phonetics and Spoken English, Sethi & Dhamija, Prentice Hall.","English Pronouncing Dictionary, Joans Daniel, Cambridge University Press, 2007.","English Grammar and Usage by R. P. Sinha, Oxford University Press, 2005, New Delhi.","English Grammar, Composition and Usage by N.K. Agrawal & F.T. Wood, Macmillan India Ltd., New Delhi.","Effective Communication Skill, Kulbhusan Kumar, RS Salaria, Khanna Publishing House.","English Grammar & Composition by Wren & Martin, S.Chand & Co. Ltd., New Delhi.","Communication Skills for Engineers and Scientists, Sangeeta Sharma et.al. PHI Learning Pvt. Ltd, 2011, New Delhi.","Personality Development, Harold R. Wallace & L. Ann Masters, Cengage Learning, New Delhi.","Personality Development & Soft Skills, Barun K. Mitra, Oxford University Press, 2012, New Delhi.","Business Correspondence and Report Writing by Prof. R.C. Sharma & Krishna Mohan, McGraw Hill & Co. Ltd., 2001, New Delhi.","Developing Communication Skills by Krishna Mohan, Meera Bannerji, Macmillan India Ltd. 1990, Delhi.","Spoken English - A Manual of Speech and Phonetics by R. K. Bansal & J.B. Harrison, Orient Blackswan, 2013, New Delhi.","Business English by Ken Taylor, Orient Blackswan, 2011, New Delhi."]
});
